/* Stage 4 (B2) — extra lessons for Unit 5 (Debat en abstracte onderwerpen) and Unit 6 (Valkuilen en examentraining): lessons 3 to 5 of each unit.
   Loaded after stage4-extra-b.js; lessons are appended to the existing units. */
(function () {
  'use strict';
  const NL = window.NL, A = NL.contentApi;
  const { N, VB, W, PH, h, p, tip, warn, table, ex, list, mc, fill, tr, build, conj, art, plural, dict, listen, speak, free, match, read, fix, write, auto, lesson } = A;
  const addTo = (unitId, l) => { const f = A.findUnit(unitId); if (f) f.unit.lessons.push(l); };
  const S = { stage: 4 };

  /* ================= Unit 5, lesson 3: ethics and dilemmas ================= */
  N('ethiek', 'de', null, 'ethics', 'Medische ethiek is een vak op zich.', 'Medical ethics is a subject in its own right.', { theme: 'abstract', ...S });
  N('geweten', 'het', null, 'conscience', 'Dat moet ieder met zijn eigen geweten uitmaken.', 'Everyone has to settle that with their own conscience.', { theme: 'abstract', ...S });
  N('beginsel', 'het', 'beginselen', 'principle', 'Het beginsel van zelfbeschikking weegt zwaar.', 'The principle of self-determination weighs heavily.', { theme: 'abstract', ...S });
  N('zelfbeschikking', 'de', null, 'self-determination', 'Zelfbeschikking is een kernwaarde in het Nederlandse debat.', 'Self-determination is a core value in the Dutch debate.', { theme: 'abstract', ...S });
  N('waarde', 'de', 'waarden', 'value', 'Hier botsen twee waarden: vrijheid en veiligheid.', 'Two values clash here: freedom and safety.', { theme: 'abstract', ...S });
  N('norm', 'de', 'normen', 'norm', 'Normen en waarden veranderen met de tijd.', 'Norms and values change with time.', { theme: 'abstract', ...S });
  N('plicht', 'de', 'plichten', 'duty', 'Tegenover rechten staan plichten.', 'Rights come with duties.', { theme: 'abstract', ...S });
  N('euthanasie', 'de', null, 'euthanasia', 'Euthanasie is in Nederland onder strikte voorwaarden toegestaan.', 'Euthanasia is permitted in the Netherlands under strict conditions.', { theme: 'abstract', ...S });
  N('orgaandonatie', 'de', null, 'organ donation', 'Bij orgaandonatie geldt sinds 2020 een "ja, tenzij"-systeem.', 'For organ donation a "yes, unless" system has applied since 2020.', { theme: 'abstract', ...S });
  N('gewetensbezwaar', 'het', 'gewetensbezwaren', 'conscientious objection', 'Een arts mag een gewetensbezwaar hebben.', 'A doctor may have a conscientious objection.', { theme: 'abstract', ...S });
  N('hellend vlak', 'het', null, 'slippery slope', 'Tegenstanders vrezen een hellend vlak.', 'Opponents fear a slippery slope.', { theme: 'abstract', ...S, id: 'hellend-vlak' });
  N('belangenafweging', 'de', 'belangenafwegingen', 'weighing of interests', 'Elke wet is het resultaat van een belangenafweging.', 'Every law is the result of a weighing of interests.', { theme: 'abstract', ...S });
  VB('botsen', 'to clash', 'bots|botst|botsen', 'botste|botsten', 'gebotst', 'hebben', 'Privacy en veiligheid botsen hier.', 'Privacy and safety clash here.', { theme: 'abstract', ...S });
  VB('rechtvaardigen', 'to justify', 'rechtvaardig|rechtvaardigt|rechtvaardigen', 'rechtvaardigde|rechtvaardigden', 'gerechtvaardigd', 'hebben', 'Rechtvaardigt het doel de middelen?', 'Does the end justify the means?', { theme: 'abstract', ...S });
  VB('prevaleren', 'to prevail', 'prevaleer|prevaleert|prevaleren', 'prevaleerde|prevaleerden', 'geprevaleerd', 'hebben', 'In dit geval prevaleert het algemeen belang.', 'In this case the public interest prevails.', { theme: 'abstract', ...S });
  VB('opwegen tegen', 'to outweigh', 'weeg op tegen|weegt op tegen|wegen op tegen', 'woog op tegen|wogen op tegen', 'opgewogen tegen', 'hebben', 'Wegen de voordelen op tegen de risico’s?', 'Do the benefits outweigh the risks?', { theme: 'abstract', ...S, id: 'opwegen-tegen' });
  VB('zich onthouden van', 'to refrain from', 'onthoud me van|onthoudt zich van|onthouden ons van', 'onthield me van|onthielden ons van', 'onthouden van', 'hebben', 'Ik onthoud me liever van een oordeel.', 'I would rather refrain from a judgement.', { theme: 'abstract', ...S, id: 'zich-onthouden-van' });
  W('principieel', 'on principle', 'adj', 'Ik ben er principieel tegen.', 'I am against it on principle.', { theme: 'abstract', ...S });
  W('pragmatisch', 'pragmatic', 'adj', 'De Nederlandse aanpak is pragmatisch.', 'The Dutch approach is pragmatic.', { theme: 'abstract', ...S });
  W('gerechtvaardigd', 'justified', 'adj', 'Is die inbreuk op de privacy gerechtvaardigd?', 'Is that infringement of privacy justified?', { theme: 'abstract', ...S });

  addTo('s4u5', lesson('s4u5l3', 'Ethics and dilemmas: when two values clash', 'You can discuss an ethical dilemma at B2 level: name the clashing values, weigh them, state a principled or pragmatic position, and respect the other side.', [
    h('The Dutch way of handling moral questions'),
    p('The Netherlands is known for regulating what other countries forbid: `euthanasie`, soft drugs (`gedogen`: officially illegal, tolerated in practice), prostitution. The reasoning is `pragmatisch`: it happens anyway, so make it safe and controllable. Opponents argue `principieel` and warn of a `hellend vlak`. Knowing both words lets you place almost any Dutch debate.'),
    h('The language of weighing'),
    table(['function', 'Dutch'], [['name the clash', '*Hier botsen twee waarden: … en …'], ['weigh', '*Wegen de voordelen op tegen de risico’s? / Het is een belangenafweging.'], ['prioritise', '*Voor mij prevaleert … / … weegt het zwaarst.'], ['principle', '*Ik ben er principieel voor / tegen, omdat …'], ['pragmatics', '*Het gebeurt toch; dan liever goed geregeld.'], ['limit', '*Dat is alleen gerechtvaardigd als … / mits …'], ['respect', '*Ik begrijp dat anderen daar anders over denken. / Dat moet ieder met zijn geweten uitmaken.'], ['abstain', '*Ik onthoud me liever van een oordeel.']]),
    h('Conditions carry the argument'),
    p('Ethical positions are almost always conditional: `mits` (provided), `tenzij` (unless), `alleen als`, `zolang`, `voor zover`. `Euthanasie is toegestaan, **mits** er sprake is van uitzichtloos en ondraaglijk lijden en de patiënt er vrijwillig om vraagt.` Hypotheticals test a principle: `Stel dat …, zou je dan nog steeds vinden dat …?`'),
    ex(['Hier botsen twee waarden: de zelfbeschikking van de patiënt en de plicht van de arts om leven te beschermen.', 'Two values clash here: the patient’s self-determination and the doctor’s duty to protect life.'], ['Ik ben niet principieel tegen, maar de inbreuk is alleen gerechtvaardigd als er geen minder ingrijpend middel is.', 'I am not against it on principle, but the infringement is only justified if there is no less intrusive means.'], ['Tegenstanders vrezen een hellend vlak; voorstanders wijzen erop dat de voorwaarden juist strenger zijn geworden.', 'Opponents fear a slippery slope; supporters point out that the conditions have actually become stricter.'], ['Stel dat het om je eigen kind ging, zou je er dan nog steeds zo over denken?', 'Suppose it concerned your own child, would you still think about it that way?']),
    tip('In a B2 speaking exam you do not have to be right. You have to name the dilemma, take a position with a condition, and acknowledge the other view in one sentence.'),
  ], ['g4-argument', 'g4-discourse', 'g4-past-tenses'], ['ethiek', 'geweten', 'beginsel', 'zelfbeschikking', 'waarde', 'norm', 'plicht', 'euthanasie', 'orgaandonatie', 'gewetensbezwaar', 'hellend-vlak', 'belangenafweging', 'botsen', 'rechtvaardigen', 'prevaleren', 'opwegen-tegen', 'zich-onthouden-van', 'principieel', 'pragmatisch', 'gerechtvaardigd'], [
    mc('"Gedogen" means', ['to forbid strictly', 'to tolerate what is officially not allowed', 'to legalise fully'], 1, 'The Dutch tolerance policy.'),
    mc('"Een hellend vlak" is', ['a slippery slope', 'a level playing field', 'a steep hill'], 0, 'Slippery-slope argument.'),
    mc('Someone who argues "het gebeurt toch, dan liever goed geregeld" argues', ['principieel', 'pragmatisch', 'emotioneel'], 1, 'Pragmatic.'),
    mc('Euthanasie is toegestaan, ___ aan strikte voorwaarden is voldaan.', ['tenzij', 'mits', 'hoewel'], 1, 'Provided that.'),
    mc('"Wegen de voordelen op tegen de risico’s?" asks whether the benefits', ['equal the risks', 'outweigh the risks', 'cause the risks'], 1, 'opwegen tegen.'),
    mc('Stel dat het om je eigen kind ___, zou je er dan zo over denken?', ['gaat', 'ging', 'gegaan'], 1, 'Hypothetical: past tense after stel dat.'),
    art('geweten', 'het', 'het geweten.'),
    art('beginsel', 'het', 'het beginsel.'),
    art('plicht', 'de', 'de plicht.'),
    fill('Hier ___ twee waarden: vrijheid en veiligheid. (clash)', ['botsen'], 'Two values clash here: freedom and safety.', 'Plural: botsen.'),
    fill('Rechtvaardigt het doel de ___?', ['middelen'], 'Does the end justify the means?', 'het doel heiligt de middelen.'),
    fill('In dit geval ___ het algemeen belang. (prevails)', ['prevaleert'], 'In this case the public interest prevails.', 'prevaleert.'),
    fill('Ik ___ me liever van een oordeel. (refrain)', ['onthoud'], 'I would rather refrain from a judgement.', 'zich onthouden van.'),
    build('I am against it on principle.', 'Ik ben er principieel tegen.', ['tegen het', 'principiële'], 'er … tegen.'),
    build('That is only justified if there is no other means.', 'Dat is alleen gerechtvaardigd als er geen ander middel is.', ['is er', 'andere'], 'als … is; het middel → geen ander middel.'),
    build('Everyone has to settle that with their own conscience.', 'Dat moet ieder met zijn eigen geweten uitmaken.', ['maakt uit', 'eigen zijn'], 'moet … uitmaken.'),
    tr('en-nl', 'Rights come with duties.', ['Tegenover rechten staan plichten.', 'Bij rechten horen plichten.'], 'tegenover … staan.'),
    tr('nl-en', 'Ik begrijp dat anderen daar anders over denken.', ['I understand that others think differently about that.'], 'daar … over.'),
    fix('Ik ben tegen het principieel.', ['Ik ben er principieel tegen.'], 'er … tegen; adverb in the middle.'),
    dict('Tegenstanders vrezen een hellend vlak, terwijl voorstanders op de strenge voorwaarden wijzen.', 'Opponents fear a slippery slope, while supporters point to the strict conditions.', 'wijzen op.'),
    listen('Voor mij prevaleert de zelfbeschikking van de patiënt, mits een tweede arts heeft meegekeken.', ['For me the patient’s self-determination prevails, provided a second doctor has reviewed the case.', 'For me the doctor’s opinion always prevails.', 'I refrain from any opinion.'], 0, 'prevaleert; mits.'),
    speak('Hier botsen twee waarden: de vrijheid van het individu en de plicht van de overheid om te beschermen.', 'Two values clash here: the freedom of the individual and the duty of the government to protect.'),
    read('Sinds 2020 is iedere volwassen inwoner van Nederland automatisch orgaandonor, tenzij hij of zij bezwaar heeft laten registreren. Voorstanders van dit "ja, tenzij"-systeem wijzen op de lange wachtlijsten: jaarlijks overlijden mensen die gered hadden kunnen worden. Tegenstanders vinden dat de overheid hiermee een grens overschrijdt. Het lichaam is volgens hen van de persoon zelf, en zwijgen mag niet als toestemming worden uitgelegd. De wetgever heeft geprobeerd beide bezwaren te wegen: wie niets registreert, wordt herhaaldelijk aangeschreven, en nabestaanden houden een stem. Of daarmee recht is gedaan aan het beginsel van zelfbeschikking, blijft omstreden. Opvallend is wel dat het aantal mensen dat bewust een keuze heeft vastgelegd sinds de wet sterk is gestegen, in beide richtingen.', [
      { q: 'Welke twee waarden botsen in deze kwestie?', options: ['gezondheid en geld', 'het redden van levens en de zelfbeschikking over het eigen lichaam', 'privacy en veiligheid'], answer: 1, explain: 'Waiting lists versus the body belonging to the person.' },
      { q: 'Wat is het principiële bezwaar van tegenstanders?', options: ['het systeem is te duur', 'zwijgen mag niet als toestemming gelden', 'artsen hebben te weinig tijd'], answer: 1, explain: '"zwijgen mag niet als toestemming worden uitgelegd".' },
      { q: 'Wat noemt de schrijver "opvallend"?', options: ['dat minder mensen doneren', 'dat meer mensen bewust een keuze hebben vastgelegd, voor én tegen', 'dat de wet is ingetrokken'], answer: 1, explain: '"sterk gestegen, in beide richtingen".' },
      { q: 'Wat is de houding van de schrijver?', options: ['duidelijk voor', 'duidelijk tegen', 'afwegend: de kwestie blijft omstreden'], answer: 2, explain: '"blijft omstreden": the writer weighs and does not decide.' },
    ], { en: 'Since 2020 every adult resident of the Netherlands is automatically an organ donor, unless he or she has had an objection registered. Supporters of this "yes, unless" system point to the long waiting lists: every year people die who could have been saved. Opponents think the government crosses a line with this. The body, according to them, belongs to the person, and silence may not be interpreted as consent. The legislator has tried to weigh both objections: whoever registers nothing is written to repeatedly, and relatives keep a say. Whether justice has thereby been done to the principle of self-determination remains disputed. What is striking is that the number of people who have consciously recorded a choice has risen sharply since the law, in both directions.' }),
    free('Exam-style long speaking task: "Mag de overheid burgers automatisch orgaandonor maken?" Name the clash, take a conditional position, acknowledge the other side.', 'Hier botsen twee waarden: het redden van levens en de zelfbeschikking over je eigen lichaam. Voor mij prevaleert in dit geval het eerste, omdat de inbreuk klein is: iedereen kan met één handeling bezwaar maken. Dat is wel alleen gerechtvaardigd mits mensen goed en herhaaldelijk worden geïnformeerd, ook in eenvoudige taal. Ik begrijp dat anderen er principieel anders over denken; zwijgen is inderdaad niet hetzelfde als instemmen. Al met al vind ik het systeem verdedigbaar, zolang de nabestaanden een stem houden.', 'Two values clash here: saving lives and self-determination over your own body. For me the first prevails in this case, because the infringement is small: anyone can object with a single act. That is only justified provided people are informed well and repeatedly, in plain language too. I understand that others think differently about it on principle; silence is indeed not the same as consent. All in all I find the system defensible, as long as relatives keep a say.', { hints: ['Hier botsen twee waarden: …', 'Voor mij prevaleert …, omdat …', '… alleen gerechtvaardigd mits …', 'Ik begrijp dat anderen …', 'Al met al …, zolang …'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('"Principieel" is the opposite of', ['pragmatisch', 'gerechtvaardigd'], 0, 'Principle versus practice.'),
    fill('De voordelen wegen niet op ___ de risico’s.', ['tegen'], 'The benefits do not outweigh the risks.', 'opwegen tegen.'),
    fill('Een arts mag een ___ hebben. (conscientious objection)', ['gewetensbezwaar'], 'A doctor may have a conscientious objection.', 'gewetensbezwaar.'),
    build('Does the end justify the means?', 'Rechtvaardigt het doel de middelen?', ['rechtvaardigen', 'het middel'], 'Verb first.'),
    tr('en-nl', 'Norms and values change with time.', ['Normen en waarden veranderen met de tijd.'], 'normen en waarden.'),
    speak('Ik ben er niet principieel tegen, maar het is alleen gerechtvaardigd als er geen ander middel is.', 'I am not against it on principle, but it is only justified if there is no other means.'),
  ]));

  /* ================= Unit 5, lesson 4: economy and inequality ================= */
  N('ongelijkheid', 'de', null, 'inequality', 'De vermogensongelijkheid is groter dan de inkomensongelijkheid.', 'Wealth inequality is greater than income inequality.', { theme: 'economy', ...S });
  N('kloof', 'de', 'kloven', 'gap', 'De kloof tussen huurders en huiseigenaren groeit.', 'The gap between tenants and homeowners is growing.', { theme: 'economy', ...S });
  N('bestaanszekerheid', 'de', null, 'security of livelihood', 'Bestaanszekerheid was het thema van de verkiezingen.', 'Security of livelihood was the theme of the elections.', { theme: 'economy', ...S });
  N('armoedegrens', 'de', null, 'poverty line', 'Eén op de twintig huishoudens leeft onder de armoedegrens.', 'One in twenty households lives below the poverty line.', { theme: 'economy', ...S });
  N('minimumloon', 'het', null, 'minimum wage', 'Het minimumloon is fors verhoogd.', 'The minimum wage has been raised substantially.', { theme: 'economy', ...S });
  N('uitkering', 'de', 'uitkeringen', 'benefit', 'Wie zijn baan verliest, heeft recht op een uitkering.', 'Whoever loses their job is entitled to a benefit.', { theme: 'economy', ...S });
  N('verzorgingsstaat', 'de', null, 'welfare state', 'De verzorgingsstaat staat onder druk door de vergrijzing.', 'The welfare state is under pressure from the ageing population.', { theme: 'economy', ...S });
  N('belastingdruk', 'de', null, 'tax burden', 'De belastingdruk op arbeid is hoog.', 'The tax burden on labour is high.', { theme: 'economy', ...S });
  N('herverdeling', 'de', null, 'redistribution', 'Herverdeling gebeurt via belastingen en toeslagen.', 'Redistribution happens via taxes and allowances.', { theme: 'economy', ...S });
  N('toeslagenstelsel', 'het', null, 'allowance system', 'Het toeslagenstelsel is te ingewikkeld geworden.', 'The allowance system has become too complicated.', { theme: 'economy', ...S });
  N('armoedeval', 'de', null, 'poverty trap', 'Door de armoedeval loont meer werken soms niet.', 'Because of the poverty trap working more sometimes does not pay.', { theme: 'economy', ...S });
  N('flexwerker', 'de', 'flexwerkers', 'flexible worker', 'Flexwerkers bouwen weinig pensioen op.', 'Flexible workers build up little pension.', { theme: 'economy', ...S });
  VB('toenemen', 'to increase', 'neem toe|neemt toe|nemen toe', 'nam toe|namen toe', 'toegenomen', 'zijn', 'De ongelijkheid is in tien jaar toegenomen.', 'Inequality has increased in ten years.', { theme: 'economy', ...S });
  VB('lonen', 'to pay / be worthwhile', 'loon|loont|lonen', 'loonde|loonden', 'geloond', 'hebben', 'Werken moet lonen.', 'Work must pay.', { theme: 'economy', ...S });
  VB('rondkomen', 'to make ends meet', 'kom rond|komt rond|komen rond', 'kwam rond|kwamen rond', 'rondgekomen', 'zijn', 'Steeds meer werkenden kunnen niet rondkomen.', 'More and more working people cannot make ends meet.', { theme: 'economy', ...S });
  VB('compenseren', 'to compensate', 'compenseer|compenseert|compenseren', 'compenseerde|compenseerden', 'gecompenseerd', 'hebben', 'De hogere energieprijzen werden deels gecompenseerd.', 'The higher energy prices were partly compensated.', { theme: 'economy', ...S });
  VB('afbouwen', 'to phase out', 'bouw af|bouwt af|bouwen af', 'bouwde af|bouwden af', 'afgebouwd', 'hebben', 'De toeslag wordt afgebouwd naarmate je meer verdient.', 'The allowance is phased out as you earn more.', { theme: 'economy', ...S });
  W('welvarend', 'prosperous', 'adj', 'Nederland is een welvarend land met een groeiende onderklasse.', 'The Netherlands is a prosperous country with a growing underclass.', { theme: 'economy', ...S });
  W('naar verhouding', 'proportionally', 'adv', 'Lage inkomens betalen naar verhouding meer aan energie.', 'Low incomes pay proportionally more for energy.', { theme: 'economy', ...S, id: 'naar-verhouding' });
  W('per saldo', 'on balance', 'adv', 'Per saldo gaan de meeste huishoudens erop vooruit.', 'On balance most households are better off.', { theme: 'economy', ...S, id: 'per-saldo' });

  addTo('s4u5', lesson('s4u5l4', 'Economy and inequality: arguing with figures', 'You can discuss inequality, benefits and taxes in Dutch, describe trends and proportions precisely, and use figures to support an argument.', [
    h('The Dutch debate in brief'),
    p('Income differences in the Netherlands are small by international standards; **wealth** differences (`vermogen`, above all home ownership) are large. `Bestaanszekerheid` became the central political word: can people `rondkomen`? The system redistributes through taxes and `toeslagen`, but the `toeslagenstelsel` is so complex that `werken` sometimes does not `lonen`: the `armoedeval`.'),
    h('Describing trends and proportions'),
    table(['Dutch', 'English'], [['*is met tien procent gestegen / gedaald', 'has risen / fallen by ten per cent'], ['*is verdubbeld / gehalveerd', 'has doubled / halved'], ['*één op de twintig huishoudens', 'one in twenty households'], ['*ruim / bijna / ongeveer een kwart', 'over / almost / about a quarter'], ['*naar verhouding meer', 'proportionally more'], ['*per saldo', 'on balance'], ['*gemiddeld, maar met grote verschillen', 'on average, but with big differences'], ['*ten opzichte van 2015', 'compared with 2015']]),
    h('Figures in an argument'),
    p('A figure needs a frame: what it is compared with, and what follows. `De huren zijn in tien jaar met 35 procent gestegen, **terwijl** de lonen met 20 procent stegen. **Dat betekent dat** huurders er per saldo op achteruit zijn gegaan.` Useful connectors: `terwijl` (whereas), `daarentegen`, `dat betekent dat`, `met als gevolg dat`, `wat erop wijst dat`.'),
    ex(['De inkomensverschillen zijn klein, terwijl het vermogen zeer ongelijk verdeeld is.', 'Income differences are small, whereas wealth is very unequally distributed.'], ['Lage inkomens besteden naar verhouding veel meer aan huur en energie.', 'Low incomes spend proportionally much more on rent and energy.'], ['De toeslag wordt afgebouwd naarmate je meer verdient, met als gevolg dat extra werken soms nauwelijks loont.', 'The allowance is phased out as you earn more, with the result that extra work sometimes hardly pays.'], ['Per saldo gaan de meeste huishoudens erop vooruit, maar dat gemiddelde verbergt grote verschillen.', 'On balance most households are better off, but that average hides big differences.']),
    tip('`erop vooruitgaan` and `erop achteruitgaan` (to be better or worse off) are the two verbs every Budget Day news report is built on.'),
  ], ['g4-discourse', 'g4-nominalisation'], ['ongelijkheid', 'kloof', 'bestaanszekerheid', 'armoedegrens', 'minimumloon', 'uitkering', 'verzorgingsstaat', 'belastingdruk', 'herverdeling', 'toeslagenstelsel', 'armoedeval', 'flexwerker', 'toenemen', 'lonen', 'rondkomen', 'compenseren', 'afbouwen', 'welvarend', 'naar-verhouding', 'per-saldo'], [
    mc('In the Netherlands, which is more unequally distributed?', ['income', 'wealth', 'both equally'], 1, 'Vermogen.'),
    mc('"De armoedeval" means that', ['poor people fall ill', 'working more hardly pays because allowances are phased out', 'poverty is falling'], 1, 'Poverty trap.'),
    mc('"Per saldo" means', ['per salary', 'on balance', 'for sale'], 1, 'On balance.'),
    mc('"Eén op de twintig" is', ['five per cent', 'twenty per cent', 'one per cent'], 0, '1/20 = 5%.'),
    mc('De huren stegen met 35 procent, ___ de lonen met 20 procent stegen.', ['terwijl', 'zodat', 'omdat'], 0, 'Contrast: whereas.'),
    mc('"Erop achteruitgaan" means', ['to walk backwards', 'to be worse off', 'to move house'], 1, 'Worse off.'),
    art('minimumloon', 'het', 'het loon.'),
    art('toeslagenstelsel', 'het', 'het stelsel.'),
    art('kloof', 'de', 'de kloof.'),
    fill('Steeds meer werkenden kunnen niet ___. (make ends meet)', ['rondkomen'], 'More and more working people cannot make ends meet.', 'rondkomen.'),
    fill('Werken moet ___. (pay)', ['lonen'], 'Work must pay.', 'lonen.'),
    fill('De ongelijkheid is in tien jaar ___. (toenemen)', ['toegenomen'], 'Inequality has increased in ten years.', 'toe + genomen, with zijn.'),
    fill('Lage inkomens betalen naar ___ meer aan energie.', ['verhouding'], 'Low incomes pay proportionally more for energy.', 'naar verhouding.'),
    build('The allowance is phased out as you earn more.', 'De toeslag wordt afgebouwd naarmate je meer verdient.', ['verdien je', 'omdat'], 'naarmate … verdient.'),
    build('That average hides big differences.', 'Dat gemiddelde verbergt grote verschillen.', ['die', 'groot'], 'het gemiddelde → dat.'),
    build('The minimum wage has been raised substantially.', 'Het minimumloon is fors verhoogd.', ['heeft', 'verhogen'], 'is … verhoogd.'),
    tr('en-nl', 'Whoever loses their job is entitled to a benefit.', ['Wie zijn baan verliest, heeft recht op een uitkering.'], 'wie …, heeft recht op.'),
    tr('nl-en', 'De verzorgingsstaat staat onder druk door de vergrijzing.', ['The welfare state is under pressure from the ageing population.', 'The welfare state is under pressure because of the ageing population.'], 'onder druk staan.'),
    fix('De huren zijn gestegen met 35 procent in tien jaar geworden.', ['De huren zijn in tien jaar met 35 procent gestegen.'], 'No geworden; participle last.'),
    dict('Per saldo gaan de meeste huishoudens erop vooruit, maar dat gemiddelde verbergt grote verschillen.', 'On balance most households are better off, but that average hides big differences.', 'erop vooruitgaan.'),
    listen('Flexwerkers bouwen weinig pensioen op, met als gevolg dat de ongelijkheid op latere leeftijd nog toeneemt.', ['Flexible workers build up little pension, with the result that inequality increases further in later life.', 'Flexible workers have the best pensions.', 'Inequality disappears at pension age.'], 0, 'met als gevolg dat.'),
    speak('De inkomensverschillen zijn klein, terwijl het vermogen zeer ongelijk verdeeld is; dat komt vooral door het eigen huis.', 'Income differences are small, whereas wealth is very unequally distributed; that is mainly due to home ownership.'),
    read('Nederland geldt als een egalitair land, en wat inkomens betreft klopt dat beeld: na belastingen en toeslagen zijn de verschillen kleiner dan in de meeste westerse landen. Bij het vermogen ligt dat anders. De rijkste tien procent van de huishoudens bezit ruim zestig procent van het totale vermogen, terwijl de onderste helft samen nauwelijks iets bezit. De belangrijkste oorzaak is de woningmarkt. Wie vóór 2015 een huis kocht, zag zijn vermogen verdubbelen zonder er iets voor te doen; wie huurt, betaalt elk jaar meer en bouwt niets op. Omdat ouders hun kinderen steeds vaker helpen bij de aankoop van een huis, wordt deze kloof bovendien erfelijk. Economen pleiten daarom voor een zwaardere belasting op vermogen en een lichtere op arbeid. Politiek is dat een gevoelig punt: huiseigenaren vormen de meerderheid van de kiezers.', [
      { q: 'Wat is de hoofdgedachte?', options: ['Nederland is in alle opzichten een gelijk land.', 'Inkomens zijn gelijk verdeeld, maar vermogen zeer ongelijk, vooral door de woningmarkt.', 'Huurders zijn rijker dan kopers.'], answer: 1, explain: 'The contrast introduced by "Bij het vermogen ligt dat anders".' },
      { q: 'Waarom wordt de kloof "erfelijk"?', options: ['door de erfbelasting', 'doordat ouders hun kinderen helpen een huis te kopen', 'door genetische verschillen'], answer: 1, explain: '"ouders hun kinderen steeds vaker helpen".' },
      { q: 'Waarom is de voorgestelde oplossing politiek gevoelig?', options: ['economen zijn het oneens', 'huiseigenaren zijn de meerderheid van de kiezers', 'de EU verbiedt het'], answer: 1, explain: 'Last sentence.' },
      { q: 'Wat betekent "zonder er iets voor te doen"?', options: ['door hard te werken', 'zonder inspanning', 'door te sparen'], answer: 1, explain: 'Without effort.' },
    ], { en: 'The Netherlands is regarded as an egalitarian country, and as far as incomes are concerned that picture is right: after taxes and allowances the differences are smaller than in most western countries. With wealth it is different. The richest ten per cent of households owns over sixty per cent of total wealth, whereas the bottom half together owns hardly anything. The main cause is the housing market. Whoever bought a house before 2015 saw their wealth double without doing anything for it; whoever rents pays more every year and builds up nothing. Because parents increasingly help their children buy a house, this gap is moreover becoming hereditary. Economists therefore argue for a heavier tax on wealth and a lighter one on labour. Politically that is a sensitive point: homeowners form the majority of voters.' }),
    free('Exam-style speaking task (60 seconds): describe one trend in inequality that you know, give a figure or proportion, and say what should be done.', 'In de grote steden is de kloof tussen huurders en kopers de laatste tien jaar sterk toegenomen. De huren zijn met ongeveer een derde gestegen, terwijl de lonen veel minder hard stegen. Dat betekent dat huurders naar verhouding steeds meer aan wonen kwijt zijn en niets kunnen sparen. Volgens mij zou de overheid daarom meer betaalbare huurwoningen moeten laten bouwen en vermogen zwaarder moeten belasten dan arbeid.', 'In the big cities the gap between tenants and buyers has increased sharply over the last ten years. Rents have risen by about a third, whereas wages rose much less fast. That means tenants spend proportionally more and more on housing and cannot save anything. In my view the government should therefore have more affordable rented homes built and tax wealth more heavily than labour.', { hints: ['… is de laatste tien jaar toegenomen', '… met ongeveer … gestegen, terwijl …', 'Dat betekent dat …', 'Volgens mij zou … moeten …'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('"Bestaanszekerheid" is about', ['whether people can make ends meet', 'national security'], 0, 'Security of livelihood.'),
    fill('Het aantal is ___ 2015 verdubbeld. (compared with)', ['ten opzichte van', 'sinds'], 'The number has doubled compared with 2015.', 'ten opzichte van / sinds.'),
    fill('De meeste huishoudens gaan erop ___. (better off)', ['vooruit'], 'Most households are better off.', 'erop vooruitgaan.'),
    build('One in twenty households lives below the poverty line.', 'Eén op de twintig huishoudens leeft onder de armoedegrens.', ['leven', 'van'], 'één op de … + singular verb.'),
    tr('en-nl', 'The tax burden on labour is high.', ['De belastingdruk op arbeid is hoog.'], 'belastingdruk.'),
    speak('Lage inkomens betalen naar verhouding meer, met als gevolg dat de kloof groter wordt.', 'Low incomes pay proportionally more, with the result that the gap widens.'),
  ]));

  /* ================= Unit 5, lesson 5: a timed debate with rebuttal ================= */
  N('openingsbeurt', 'de', 'openingsbeurten', 'opening speech', 'Je openingsbeurt duurt negentig seconden.', 'Your opening speech lasts ninety seconds.', { theme: 'debate', ...S });
  N('weerlegging', 'de', 'weerleggingen', 'rebuttal', 'In de weerlegging reageer je op het sterkste argument van de ander.', 'In the rebuttal you respond to the other side’s strongest argument.', { theme: 'debate', ...S });
  N('slotbeurt', 'de', 'slotbeurten', 'closing speech', 'In de slotbeurt breng je geen nieuwe argumenten in.', 'In the closing speech you introduce no new arguments.', { theme: 'debate', ...S });
  N('drogreden', 'de', 'drogredenen', 'fallacy', 'Een persoonlijke aanval is een drogreden.', 'A personal attack is a fallacy.', { theme: 'debate', ...S });
  N('stroman', 'de', 'stromannen', 'straw man', 'Dat is een stroman: dat heb ik nooit beweerd.', 'That is a straw man: I never claimed that.', { theme: 'debate', ...S });
  N('cirkelredenering', 'de', 'cirkelredeneringen', 'circular reasoning', 'Dat is een cirkelredenering.', 'That is circular reasoning.', { theme: 'debate', ...S });
  N('generalisatie', 'de', 'generalisaties', 'generalisation', 'Eén voorbeeld is nog geen bewijs; dat is een overhaaste generalisatie.', 'One example is not proof; that is a hasty generalisation.', { theme: 'debate', ...S });
  N('aanname', 'de', 'aannames', 'assumption', 'Uw betoog berust op een aanname die niet klopt.', 'Your argument rests on an assumption that is not correct.', { theme: 'debate', ...S });
  N('bewijslast', 'de', null, 'burden of proof', 'De bewijslast ligt bij degene die iets beweert.', 'The burden of proof lies with the one who makes a claim.', { theme: 'debate', ...S });
  VB('weerleggen', 'to refute', 'weerleg|weerlegt|weerleggen', 'weerlegde|weerlegden', 'weerlegd', 'hebben', 'Ik zal dat argument weerleggen.', 'I will refute that argument.', { theme: 'debate', ...S });
  VB('ondermijnen', 'to undermine', 'ondermijn|ondermijnt|ondermijnen', 'ondermijnde|ondermijnden', 'ondermijnd', 'hebben', 'Dat voorbeeld ondermijnt uw eigen stelling.', 'That example undermines your own proposition.', { theme: 'debate', ...S });
  VB('voorbijgaan aan', 'to ignore / pass over', 'ga voorbij aan|gaat voorbij aan|gaan voorbij aan', 'ging voorbij aan|gingen voorbij aan', 'voorbijgegaan aan', 'zijn', 'U gaat voorbij aan de kern van de zaak.', 'You are ignoring the heart of the matter.', { theme: 'debate', ...S, id: 'voorbijgaan-aan' });
  VB('staande houden', 'to maintain (a claim)', 'houd staande|houdt staande|houden staande', 'hield staande|hielden staande', 'staande gehouden', 'hebben', 'Ik houd staande dat het plan onbetaalbaar is.', 'I maintain that the plan is unaffordable.', { theme: 'debate', ...S, id: 'staande-houden' });
  PH('Mijn opponent stelt dat …', 'My opponent states that …', 'Mijn opponent stelt dat het plan banen kost.', 'My opponent states that the plan costs jobs.', { theme: 'debate', ...S, id: 'ph-mijn-opponent' });
  PH('Dat is een schijntegenstelling.', 'That is a false dichotomy.', 'Economie of klimaat? Dat is een schijntegenstelling.', 'Economy or climate? That is a false dichotomy.', { theme: 'debate', ...S, id: 'ph-schijntegenstelling' });
  PH('Daaruit volgt niet dat …', 'It does not follow that …', 'Daaruit volgt niet dat het beleid mislukt is.', 'It does not follow that the policy has failed.', { theme: 'debate', ...S, id: 'ph-daaruit-volgt-niet' });
  PH('Zelfs als dat waar is, …', 'Even if that is true, …', 'Zelfs als dat waar is, blijft mijn tweede argument overeind.', 'Even if that is true, my second argument still stands.', { theme: 'debate', ...S, id: 'ph-zelfs-als' });
  PH('overeind blijven', 'to remain standing', 'Van dat argument blijft weinig overeind.', 'Little remains of that argument.', { theme: 'debate', ...S, id: 'ph-overeind-blijven' });
  W('steekhoudend', 'sound / valid', 'adj', 'Dat is geen steekhoudend argument.', 'That is not a sound argument.', { theme: 'debate', ...S });

  addTo('s4u5', lesson('s4u5l5', 'A timed debate: opening, rebuttal, closing', 'You can take part in a formal timed debate: deliver a structured opening, rebut the strongest opposing argument, name a fallacy, and close without new points.', [
    h('Three turns'),
    table(['turn', 'time', 'job'], [['openingsbeurt', '90 s', 'standpoint, two arguments, each with evidence'], ['weerlegging', '60 s', 'restate their strongest argument fairly, then refute it'], ['slotbeurt', '45 s', 'what remains standing; no new arguments']]),
    h('The rebuttal formula'),
    list('1. **Restate**: `Mijn opponent stelt dat …` Fairly; a distorted version is a `stroman`.', '2. **Attack one thing**: the fact (`Die cijfers zijn verouderd`), the link (`Daaruit volgt niet dat …`), or the assumption (`Dat berust op de aanname dat …`).', '3. **Concede and hold**: `Zelfs als dat waar is, blijft mijn tweede argument overeind.`', '4. **Return** to your own case: `Ik houd dus staande dat …`'),
    h('Naming fallacies'),
    table(['drogreden', 'example', 'your reply'], [['*persoonlijke aanval', 'Jij hebt zelf een auto!', '*Dat is een aanval op de persoon, niet op het argument.'], ['*stroman', 'U wilt dus alle auto’s verbieden.', '*Dat heb ik niet beweerd.'], ['*overhaaste generalisatie', 'Mijn buurman deed het en ging failliet.', '*Eén voorbeeld is nog geen bewijs.'], ['*schijntegenstelling', 'Economie óf klimaat.', '*Dat is een schijntegenstelling.'], ['*cirkelredenering', 'Het is goed omdat het juist is.', '*Dat is een cirkelredenering.'], ['*hellend vlak', 'Straks mag niets meer.', '*Daaruit volgt dat niet.']]),
    ex(['Mijn opponent stelt dat een autovrije binnenstad winkels klanten kost. Die cijfers komen uit 2009 en uit veel grotere steden.', 'My opponent states that a car-free centre costs shops customers. Those figures come from 2009 and from much bigger cities.'], ['Zelfs als de omzet tijdelijk daalt, volgt daaruit niet dat het beleid mislukt is.', 'Even if turnover falls temporarily, it does not follow that the policy has failed.'], ['Economie of leefbaarheid? Dat is een schijntegenstelling: leefbare steden trekken juist bedrijven aan.', 'Economy or liveability? That is a false dichotomy: liveable cities actually attract businesses.'], ['Van de drie argumenten van de tegenpartij blijft er één overeind; ik houd daarom staande dat het plan moet doorgaan.', 'Of the three arguments of the other side one remains standing; I therefore maintain that the plan must go ahead.']),
    tip('Time yourself. At natural debate speed, ninety seconds is about 200 words: a standpoint, two arguments with one fact each, and a closing sentence. No more.'),
  ], ['g4-argument', 'g4-discourse'], ['openingsbeurt', 'weerlegging', 'slotbeurt', 'drogreden', 'stroman', 'cirkelredenering', 'generalisatie', 'aanname', 'bewijslast', 'weerleggen', 'ondermijnen', 'voorbijgaan-aan', 'staande-houden', 'ph-mijn-opponent', 'ph-schijntegenstelling', 'ph-daaruit-volgt-niet', 'ph-zelfs-als', 'ph-overeind-blijven', 'steekhoudend'], [
    mc('What may you not do in the slotbeurt?', ['summarise', 'introduce a new argument', 'thank the audience'], 1, 'No new arguments.'),
    mc('"U wilt dus alle auto’s verbieden" (when you said no such thing) is', ['a straw man', 'a sound argument', 'a concession'], 0, 'stroman.'),
    mc('"Jij hebt zelf een auto!" is', ['a personal attack', 'evidence', 'a conclusion'], 0, 'Attack on the person.'),
    mc('"Economie óf klimaat" as a forced choice is', ['een cirkelredenering', 'een schijntegenstelling', 'een aanname'], 1, 'False dichotomy.'),
    mc('The first step of a good rebuttal is to', ['attack the speaker', 'restate the opponent’s argument fairly', 'change the subject'], 1, 'Mijn opponent stelt dat …'),
    mc('"De bewijslast ligt bij u" means', ['you must prove your claim', 'you carry the costs', 'you are guilty'], 0, 'Burden of proof.'),
    art('drogreden', 'de', 'de reden.'),
    art('aanname', 'de', 'de aanname.'),
    fill('___ uit volgt niet dat het beleid mislukt is.', ['Daar'], 'It does not follow that the policy has failed.', 'daaruit volgt niet dat.'),
    fill('Zelfs ___ dat waar is, blijft mijn argument overeind.', ['als'], 'Even if that is true, my argument still stands.', 'zelfs als.'),
    fill('Ik houd ___ dat het plan onbetaalbaar is. (maintain)', ['staande'], 'I maintain that the plan is unaffordable.', 'staande houden.'),
    fill('Dat is geen ___ argument. (sound)', ['steekhoudend'], 'That is not a sound argument.', 'het argument + geen → no -e.'),
    fill('U gaat voorbij ___ de kern van de zaak.', ['aan'], 'You are ignoring the heart of the matter.', 'voorbijgaan aan.'),
    build('My opponent states that the plan costs jobs.', 'Mijn opponent stelt dat het plan banen kost.', ['kost banen', 'stellen'], 'stelt dat … kost.'),
    build('That example undermines your own proposition.', 'Dat voorbeeld ondermijnt uw eigen stelling.', ['die', 'ondermijnen'], 'het voorbeeld → dat.'),
    build('One example is not proof.', 'Eén voorbeeld is nog geen bewijs.', ['niet', 'een bewijs geen'], 'nog geen bewijs.'),
    tr('en-nl', 'Your argument rests on an assumption that is not correct.', ['Uw betoog berust op een aanname die niet klopt.'], 'berusten op; die … klopt.'),
    tr('nl-en', 'Van dat argument blijft weinig overeind.', ['Little remains of that argument.', 'Not much of that argument is left standing.'], 'overeind blijven.'),
    fix('Mijn opponent stelt dat kost het plan banen.', ['Mijn opponent stelt dat het plan banen kost.'], 'Verb at the end after dat.'),
    dict('Zelfs als de omzet tijdelijk daalt, volgt daaruit niet dat het beleid mislukt is.', 'Even if turnover falls temporarily, it does not follow that the policy has failed.', 'zelfs als …, volgt daaruit niet dat.'),
    listen('Mijn opponent gaat voorbij aan de kern: het gaat niet om de kosten van nu, maar om de kosten van niets doen.', ['The speaker says the opponent ignores the core: it is about the cost of doing nothing.', 'The speaker agrees that the plan is too expensive now.', 'The speaker has no counterargument.'], 0, 'voorbijgaan aan; niet om … maar om.'),
    speak('Mijn opponent stelt dat het plan banen kost. Zelfs als dat waar is, blijft mijn tweede argument overeind.', 'My opponent states that the plan costs jobs. Even if that is true, my second argument still stands.'),
    free('Openingsbeurt, 90 seconds, on: "Het collegegeld moet worden afgeschaft." Standpoint, two arguments with a fact each, closing sentence. Time yourself.', 'Voorzitter, ik ben voor de afschaffing van het collegegeld, en wel om twee redenen. Ten eerste is hoger onderwijs een investering waar de hele samenleving van profiteert: afgestudeerden betalen gedurende hun loopbaan gemiddeld veel meer belasting. Het is dus redelijk dat de samenleving meebetaalt. Ten tweede schrikt de studieschuld juist jongeren uit gezinnen met lage inkomens af, zo blijkt uit onderzoek onder scholieren. Talent gaat daardoor verloren. Tegenstanders zullen zeggen dat het onbetaalbaar is, maar Duitsland en Denemarken laten zien dat het kan. Ik pleit er daarom voor het collegegeld in vier jaar af te bouwen.', 'Chair, I am in favour of abolishing tuition fees, for two reasons. First, higher education is an investment from which the whole of society benefits: graduates pay much more tax on average during their careers. So it is reasonable that society contributes. Second, student debt deters precisely young people from low-income families, as research among school pupils shows. Talent is lost as a result. Opponents will say it is unaffordable, but Germany and Denmark show that it can be done. I therefore argue for phasing out tuition fees over four years.', { hints: ['Ik ben voor / tegen …, en wel om twee redenen', 'Ten eerste … Ten tweede …', 'Tegenstanders zullen zeggen dat …, maar …', 'Ik pleit er daarom voor …'] }),
    free('Weerlegging, 60 seconds: your opponent said "Gratis studeren betekent dat de bakker betaalt voor de advocaat." Restate, attack one thing, concede and hold.', 'Mijn opponent stelt dat mensen met een laag inkomen dan meebetalen aan de studie van latere veelverdieners. Dat klinkt rechtvaardig, maar het berust op de aanname dat belasting door iedereen in gelijke mate wordt betaald. Dat klopt niet: hoge inkomens betalen naar verhouding het meest, en afgestudeerden horen daar later zelf bij. Zelfs als een deel van het argument overeind blijft, volgt daaruit niet dat we de drempel voor arme studenten moeten handhaven. Ik houd dus staande dat afschaffing per saldo eerlijker is.', 'My opponent states that people on low incomes would then contribute to the studies of future high earners. That sounds fair, but it rests on the assumption that tax is paid by everyone in equal measure. That is not correct: high incomes pay proportionally the most, and graduates later belong to that group themselves. Even if part of the argument remains standing, it does not follow that we should maintain the barrier for poor students. So I maintain that abolition is on balance fairer.', { hints: ['Mijn opponent stelt dat …', 'Dat berust op de aanname dat …', 'Zelfs als …, volgt daaruit niet dat …', 'Ik houd dus staande dat …'] }),
    free('Slotbeurt, 45 seconds: say what remains standing on each side and end with one sentence. No new arguments.', 'Wat blijft er overeind? Mijn opponent heeft terecht gewezen op de kosten, en die ontken ik niet. Maar zijn belangrijkste punt, dat de bakker voor de advocaat betaalt, is weerlegd: de advocaat betaalt het later ruimschoots terug. Mijn twee argumenten, de maatschappelijke opbrengst en de drempel voor arme studenten, zijn niet bestreden. Kortom: wie talent wil benutten, moet de drempel weghalen.', 'What remains standing? My opponent rightly pointed to the costs, and I do not deny those. But his main point, that the baker pays for the lawyer, has been refuted: the lawyer pays it back amply later. My two arguments, the benefit to society and the barrier for poor students, have not been contested. In short: whoever wants to use talent must remove the barrier.', { hints: ['Wat blijft er overeind?', '… heeft terecht gewezen op …', '… is weerlegd', 'Kortom: …'] }),
    match([['de stroman', 'straw man'], ['de schijntegenstelling', 'false dichotomy'], ['de cirkelredenering', 'circular reasoning'], ['de bewijslast', 'burden of proof'], ['weerleggen', 'to refute'], ['staande houden', 'to maintain']]),
  ], [
    mc('"Steekhoudend" means', ['sound, valid', 'sharp, hurtful'], 0, 'A sound argument.'),
    fill('Dat is een ___: dat heb ik nooit beweerd. (straw man)', ['stroman'], 'That is a straw man: I never claimed that.', 'stroman.'),
    fill('De ___ ligt bij degene die iets beweert.', ['bewijslast'], 'The burden of proof lies with the one who makes a claim.', 'bewijslast.'),
    build('I will refute that argument.', 'Ik zal dat argument weerleggen.', ['die', 'weerlegt'], 'het argument → dat.'),
    tr('en-nl', 'That is a false dichotomy.', ['Dat is een schijntegenstelling.'], 'schijntegenstelling.'),
    speak('Daaruit volgt niet dat het beleid mislukt is; ik houd dus staande dat het plan moet doorgaan.', 'It does not follow that the policy has failed; so I maintain that the plan must go ahead.'),
  ]));

  /* ================= Unit 6, lesson 3: mock reading paper ================= */
  N('tekstsoort', 'de', 'tekstsoorten', 'text type', 'Bepaal eerst de tekstsoort.', 'Determine the text type first.', { theme: 'exam', ...S });
  N('tussenkop', 'de', 'tussenkoppen', 'subheading', 'De tussenkoppen geven de structuur.', 'The subheadings give the structure.', { theme: 'exam', ...S });
  N('verwijswoord', 'het', 'verwijswoorden', 'reference word', '"Dit", "deze" en "daarmee" zijn verwijswoorden.', '"Dit", "deze" and "daarmee" are reference words.', { theme: 'exam', ...S });
  N('bewering', 'de', 'beweringen', 'statement / claim', 'Welke bewering is juist volgens de tekst?', 'Which statement is correct according to the text?', { theme: 'exam', ...S });
  N('afleider', 'de', 'afleiders', 'distractor (wrong option)', 'Een afleider bevat vaak een woord uit de tekst, maar klopt net niet.', 'A distractor often contains a word from the text, but is just not right.', { theme: 'exam', ...S });
  N('tegenstelling', 'de', 'tegenstellingen', 'contrast', '"Echter" kondigt een tegenstelling aan.', '"Echter" announces a contrast.', { theme: 'exam', ...S });
  N('opsomming', 'de', 'opsommingen', 'enumeration', '"Ten eerste, ten tweede" vormen een opsomming.', '"Firstly, secondly" form an enumeration.', { theme: 'exam', ...S });
  VB('aankruisen', 'to tick', 'kruis aan|kruist aan|kruisen aan', 'kruiste aan|kruisten aan', 'aangekruist', 'hebben', 'Kruis het juiste antwoord aan.', 'Tick the right answer.', { theme: 'exam', ...S });
  VB('wegstrepen', 'to cross out', 'streep weg|streept weg|strepen weg', 'streepte weg|streepten weg', 'weggestreept', 'hebben', 'Streep eerst de antwoorden weg die zeker fout zijn.', 'First cross out the answers that are certainly wrong.', { theme: 'exam', ...S });
  VB('scannen', 'to scan', 'scan|scant|scannen', 'scande|scanden', 'gescand', 'hebben', 'Scan de tekst op het getal uit de vraag.', 'Scan the text for the number from the question.', { theme: 'exam', ...S });
  W('letterlijk', 'literally', 'adv', 'Het goede antwoord staat zelden letterlijk in de tekst.', 'The right answer is seldom literally in the text.', { theme: 'exam', ...S });
  W('impliciet', 'implicit', 'adj', 'De mening van de schrijver blijft impliciet.', 'The writer’s opinion remains implicit.', { theme: 'exam', ...S });

  addTo('s4u6', lesson('s4u6l3', 'Mock reading paper (Staatsexamen style)', 'You can work through a full reading paper under exam conditions: four text types, fourteen questions, and a strategy for distractors and time.', [
    h('How to take this paper'),
    list('Set a timer for **35 minutes**. Four texts, fourteen questions.', 'Per text: read the questions first, then the title and the first sentence of each paragraph, then scan for the answers.', 'Questions follow the order of the text.', 'The right option **paraphrases**; an option that repeats the text’s words exactly is often an `afleider`.', '`Streep weg` what is certainly wrong; choose between the two that remain by going back to the text.', 'Never leave a question open.'),
    h('Distractor types'),
    table(['type', 'how to spot it'], [['too strong', '*altijd, nooit, alle, bewijst* where the text hedges'], ['true but not in the text', 'you know it, the text does not say it'], ['right words, wrong relation', 'cause and effect swapped'], ['the other side’s view', 'the text reports it (`tegenstanders vinden`) but the writer does not hold it'], ['detail instead of main idea', 'correct, but answers a different question']]),
    h('After the paper'),
    p('Count your score: 10 or more of 14 is a comfortable pass level for practice. For each mistake, identify the distractor type; that is where the learning is.'),
    tip('If a text defeats you, move on and come back. Every question is worth the same.'),
  ], ['g4-reading', 'g4-staatsexamen'], ['tekstsoort', 'tussenkop', 'verwijswoord', 'bewering', 'afleider', 'tegenstelling', 'opsomming', 'aankruisen', 'wegstrepen', 'scannen', 'letterlijk', 'impliciet'], [
    read('Tekst 1 (mededeling). Aan alle medewerkers. Vanaf 1 maart wordt het kantoorpand aan de Wibautstraat gerenoveerd. De werkzaamheden duren naar verwachting tot eind september. Gedurende die periode is de derde verdieping gesloten; de afdelingen Finance en HR verhuizen tijdelijk naar de begane grond. Omdat er daardoor minder werkplekken beschikbaar zijn, vragen wij iedereen ten minste twee dagen per week thuis te werken. Wie thuis geen geschikte werkplek heeft, kan dat vóór 15 februari melden bij zijn leidinggevende; in dat geval wordt een vaste plek gereserveerd. De fietsenstalling blijft bereikbaar via de achteringang. Parkeren op het eigen terrein is tijdens de renovatie niet mogelijk.', [
      { q: 'Wat is het doel van deze tekst?', options: ['medewerkers informeren over de renovatie en de gevolgen', 'medewerkers overtuigen om te verhuizen', 'klachten over de renovatie verzamelen'], answer: 0, explain: 'A mededeling informs.' },
      { q: 'Waarom wordt iedereen gevraagd thuis te werken?', options: ['omdat het pand gesloten is', 'omdat er minder werkplekken zijn', 'omdat thuiswerken goedkoper is'], answer: 1, explain: '"Omdat er daardoor minder werkplekken beschikbaar zijn".' },
      { q: 'Wat moet iemand doen die thuis niet goed kan werken?', options: ['niets, er is plek genoeg', 'dat vóór 15 februari bij de leidinggevende melden', 'tijdelijk naar HR verhuizen'], answer: 1, explain: 'Then a fixed place is reserved.' },
    ], { en: 'Text 1 (notice). To all staff. From 1 March the office building on the Wibautstraat will be renovated. The work is expected to last until the end of September. During that period the third floor is closed; the Finance and HR departments move temporarily to the ground floor. Because fewer workplaces are available as a result, we ask everyone to work from home at least two days a week. Whoever has no suitable workplace at home can report that to their manager before 15 February; in that case a fixed place is reserved. The bike shed remains accessible via the back entrance. Parking on the premises is not possible during the renovation.' }),
    read('Tekst 2 (nieuwsbericht). Minder jongeren halen rijbewijs. Het aantal jongeren tussen 18 en 24 jaar met een rijbewijs is in tien jaar met bijna een vijfde gedaald, zo blijkt uit cijfers van het CBS. Vooral in de grote steden is de daling sterk. Onderzoekers noemen verschillende mogelijke oorzaken. De kosten van rijlessen en een examen zijn opgelopen tot gemiddeld drieduizend euro, terwijl studenten minder te besteden hebben sinds de invoering van het leenstelsel. Daarnaast is een auto in de stad vaak meer last dan gemak. Of jongeren het rijbewijs definitief links laten liggen, is volgens de onderzoekers nog niet te zeggen: het lijkt erop dat velen het halen van een rijbewijs uitstellen tot zij kinderen krijgen of buiten de stad gaan wonen.', [
      { q: 'Wat is de belangrijkste informatie uit dit bericht?', options: ['Rijlessen kosten drieduizend euro.', 'Minder jongeren hebben een rijbewijs, vooral in de steden.', 'Jongeren willen nooit meer autorijden.'], answer: 1, explain: 'Headline and first sentence.' },
      { q: 'Welke oorzaak wordt NIET genoemd?', options: ['de hoge kosten', 'het ongemak van een auto in de stad', 'strengere exameneisen'], answer: 2, explain: 'Exam requirements are not mentioned.' },
      { q: 'Wat zeggen de onderzoekers over de toekomst?', options: ['jongeren zullen nooit meer een rijbewijs halen', 'waarschijnlijk stellen veel jongeren het alleen uit', 'de daling is voorbij'], answer: 1, explain: '"het lijkt erop dat velen het … uitstellen". The first option is too strong.' },
      { q: 'Wat betekent "links laten liggen"?', options: ['links afslaan', 'negeren, niet doen', 'later ophalen'], answer: 1, explain: 'Idiom: to ignore.' },
    ], { en: 'Text 2 (news report). Fewer young people get driving licence. The number of young people between 18 and 24 with a driving licence has fallen by almost a fifth in ten years, figures from Statistics Netherlands show. The fall is particularly strong in the big cities. Researchers name several possible causes. The costs of driving lessons and a test have risen to an average of three thousand euros, while students have had less to spend since the introduction of the loan system. In addition a car in the city is often more burden than convenience. Whether young people are abandoning the licence for good cannot yet be said, according to the researchers: it seems that many postpone getting a licence until they have children or move out of the city.' }),
    read('Tekst 3 (opiniestuk). Laat de winkels op zondag dicht. Sinds gemeenten zelf mogen beslissen over de zondagsopenstelling, zijn in vrijwel alle grote steden de winkels zeven dagen per week open. Voorstanders spreken van vrijheid: de consument kan winkelen wanneer het hem uitkomt. Maar wiens vrijheid is dat eigenlijk? De caissière met een nulurencontract kan niet weigeren als zij op zondag wordt ingeroosterd. De kleine zelfstandige moet wel open, omdat de keten tegenover hem dat ook is, en staat daardoor zeven dagen in zijn zaak. Het argument dat er banen bij zouden komen, houdt evenmin stand: mensen geven hun geld maar één keer uit, of dat nu op zaterdag of op zondag is. Wat we ervoor terugkrijgen, is een week zonder rustpunt. Eén gezamenlijke vrije dag is geen ouderwets idee, maar een vorm van beschaving. Gemeenten zouden de moed moeten hebben dat besluit terug te draaien.', [
      { q: 'Wat is het standpunt van de schrijver?', options: ['winkels moeten zelf beslissen', 'winkels moeten op zondag dicht', 'de consument moet meer vrijheid krijgen'], answer: 1, explain: 'Title and last sentence.' },
      { q: 'Hoe gebruikt de schrijver het argument "vrijheid"?', options: ['hij neemt het over', 'hij keert het om: de vrijheid van de consument is de onvrijheid van de werknemer', 'hij negeert het'], answer: 1, explain: '"Maar wiens vrijheid is dat eigenlijk?"' },
      { q: 'Waarom komen er volgens de schrijver geen banen bij?', options: ['omdat winkels te duur zijn', 'omdat mensen hun geld maar één keer uitgeven', 'omdat er te weinig personeel is'], answer: 1, explain: '"mensen geven hun geld maar één keer uit".' },
      { q: 'Wat is het doel van de schrijver?', options: ['informeren', 'overtuigen en activeren', 'amuseren'], answer: 1, explain: 'He argues and calls on municipalities to act.' },
    ], { en: 'Text 3 (opinion piece). Keep the shops closed on Sundays. Since municipalities may decide on Sunday opening themselves, shops in almost all big cities are open seven days a week. Supporters speak of freedom: the consumer can shop when it suits him. But whose freedom is that really? The cashier on a zero-hours contract cannot refuse when she is scheduled on Sunday. The small independent shopkeeper has to open, because the chain opposite does too, and therefore stands in his shop seven days a week. The argument that jobs would be added does not hold either: people spend their money only once, whether on Saturday or on Sunday. What we get in return is a week without a resting point. One shared day off is not an old-fashioned idea, but a form of civilisation. Municipalities should have the courage to reverse that decision.' }),
    read('Tekst 4 (studietekst). Meertaligheid bij kinderen. Lange tijd werd gedacht dat kinderen die met twee talen opgroeien een achterstand oplopen. Die opvatting is inmiddels achterhaald. Uit onderzoek blijkt dat meertalige kinderen in elke afzonderlijke taal weliswaar iets later een grote woordenschat opbouwen, maar dat hun totale woordenschat, over beide talen samen, minstens even groot is als die van eentalige kinderen. Bovendien zijn er aanwijzingen dat zij beter zijn in taken waarbij zij hun aandacht moeten verdelen, al is de omvang van dat voordeel onder onderzoekers omstreden. Voor ouders is de belangrijkste conclusie praktisch: het helpt niet om thuis gebrekkig Nederlands te spreken in plaats van de eigen taal. Een rijke thuistaal vormt juist de basis waarop het Nederlands kan worden gebouwd, mits het kind buitenshuis voldoende Nederlands hoort.', [
      { q: 'Welke opvatting noemt de tekst "achterhaald"?', options: ['dat meertalige kinderen een achterstand oplopen', 'dat kinderen snel talen leren', 'dat ouders Nederlands moeten leren'], answer: 0, explain: 'First two sentences.' },
      { q: 'Wat blijkt over de woordenschat van meertalige kinderen?', options: ['die is in elke taal groter', 'in totaal is die minstens even groot als bij eentalige kinderen', 'die blijft altijd kleiner'], answer: 1, explain: '"hun totale woordenschat … minstens even groot".' },
      { q: 'Wat zegt de tekst over het aandachtsvoordeel?', options: ['het is bewezen en groot', 'er zijn aanwijzingen, maar de omvang is omstreden', 'het bestaat niet'], answer: 1, explain: 'Hedged: "aanwijzingen … omstreden". The first option is too strong.' },
      { q: 'Wat is het advies aan ouders?', options: ['spreek thuis altijd Nederlands, ook als je het slecht spreekt', 'spreek thuis je eigen taal goed, en zorg dat het kind buitenshuis genoeg Nederlands hoort', 'kies één taal en laat de andere vallen'], answer: 1, explain: 'Last two sentences, with the mits-condition.' },
    ], { en: 'Text 4 (study text). Multilingualism in children. For a long time it was thought that children who grow up with two languages fall behind. That view is now outdated. Research shows that multilingual children admittedly build up a large vocabulary somewhat later in each separate language, but that their total vocabulary, across both languages together, is at least as large as that of monolingual children. Moreover there are indications that they are better at tasks in which they have to divide their attention, although the size of that advantage is disputed among researchers. For parents the main conclusion is practical: it does not help to speak poor Dutch at home instead of your own language. A rich home language actually forms the basis on which Dutch can be built, provided the child hears enough Dutch outside the home.' }),
    mc('An option that uses "altijd" where the text says "vaak" is probably', ['correct', 'a distractor that is too strong', 'the main idea'], 1, 'Too strong.'),
    mc('"Tegenstanders vinden dat …" in a text tells you', ['the writer’s own view', 'a view the writer reports, maybe to refute it', 'a fact'], 1, 'Reported view.'),
    mc('The right answer in a reading exam usually', ['copies the text word for word', 'paraphrases the text', 'adds new information'], 1, 'Paraphrase.'),
    fill('Streep eerst de antwoorden ___ die zeker fout zijn.', ['weg'], 'First cross out the answers that are certainly wrong.', 'wegstrepen.'),
    fill('"Dit" en "daarmee" zijn ___. (reference words)', ['verwijswoorden'], '"Dit" and "daarmee" are reference words.', 'verwijswoorden.'),
    build('Determine the text type first.', 'Bepaal eerst de tekstsoort.', ['bepaalt', 'het'], 'Imperative; de tekstsoort.'),
    tr('nl-en', 'Het goede antwoord staat zelden letterlijk in de tekst.', ['The right answer is seldom literally in the text.'], 'letterlijk.'),
  ], [
    mc('What do you read first in the exam?', ['the whole text', 'the questions', 'the last paragraph'], 1, 'Questions first.'),
    mc('"Een afleider" is', ['a wrong option designed to look right', 'the correct answer'], 0, 'Distractor.'),
    fill('"Echter" kondigt een ___ aan.', ['tegenstelling'], '"Echter" announces a contrast.', 'tegenstelling.'),
    build('Tick the right answer.', 'Kruis het juiste antwoord aan.', ['aankruis', 'de'], 'kruis … aan.'),
    tr('en-nl', 'Which statement is correct according to the text?', ['Welke bewering is juist volgens de tekst?'], 'bewering.'),
    speak('Ik lees eerst de vragen, dan de eerste zin van elke alinea, en daarna zoek ik de antwoorden.', 'I read the questions first, then the first sentence of each paragraph, and after that I look for the answers.'),
  ]));

  /* ================= Unit 6, lesson 4: mock writing paper ================= */
  N('schrijfopdracht', 'de', 'schrijfopdrachten', 'writing task', 'Lees de schrijfopdracht twee keer.', 'Read the writing task twice.', { theme: 'exam', ...S });
  N('aandachtspunt', 'het', 'aandachtspunten', 'point to cover', 'Verwerk alle aandachtspunten in je tekst.', 'Cover all the points in your text.', { theme: 'exam', ...S });
  N('aanhef', 'de', null, 'salutation', 'Kies de aanhef die bij de lezer past.', 'Choose the salutation that fits the reader.', { theme: 'exam', ...S });
  N('slotzin', 'de', 'slotzinnen', 'closing sentence', 'Een goede slotzin zegt wat je van de lezer verwacht.', 'A good closing sentence says what you expect from the reader.', { theme: 'exam', ...S });
  N('samenhang', 'de', null, 'coherence', 'Signaalwoorden zorgen voor samenhang.', 'Signal words provide coherence.', { theme: 'exam', ...S });
  N('woordkeuze', 'de', null, 'word choice', 'Let op je woordkeuze: formeel of informeel?', 'Watch your word choice: formal or informal?', { theme: 'exam', ...S });
  N('kladversie', 'de', 'kladversies', 'rough draft', 'Voor een kladversie is geen tijd; maak een kort plan.', 'There is no time for a rough draft; make a short plan.', { theme: 'exam', ...S });
  VB('verwerken', 'to work in / process', 'verwerk|verwerkt|verwerken', 'verwerkte|verwerkten', 'verwerkt', 'hebben', 'Heb je alle punten verwerkt?', 'Have you worked in all the points?', { theme: 'exam', ...S });
  VB('nalezen', 'to read through / proofread', 'lees na|leest na|lezen na', 'las na|lazen na', 'nagelezen', 'hebben', 'Lees je tekst na op je vaste fouten.', 'Proofread your text for your recurring mistakes.', { theme: 'exam', ...S });
  VB('formuleren', 'to formulate', 'formuleer|formuleert|formuleren', 'formuleerde|formuleerden', 'geformuleerd', 'hebben', 'Formuleer je verzoek in één zin.', 'Formulate your request in one sentence.', { theme: 'exam', ...S });
  W('volledig', 'complete', 'adj', 'Een volledige tekst scoort beter dan een mooie halve.', 'A complete text scores better than a beautiful half.', { theme: 'exam', ...S });
  W('passend', 'appropriate', 'adj', 'Gebruik een passende aanhef en afsluiting.', 'Use an appropriate salutation and closing.', { theme: 'exam', ...S });

  addTo('s4u6', lesson('s4u6l4', 'Mock writing paper (Staatsexamen style)', 'You can complete a full writing paper under exam conditions: sentence completion, two short messages and two longer texts, each planned, written and checked.', [
    h('How to take this paper'),
    list('Set a timer for **60 minutes**: about 10 for the short tasks, 20 for each long task, 10 to check.', 'Per task: underline the **reader**, the **purpose**, and every **aandachtspunt**. Decide `u` or `je` before the first word.', 'Plan in key words: one line per paragraph.', 'Write `volledig` before you write beautifully: a missing point costs more than a clumsy sentence.', 'Check with your error log: verb position after `dat / omdat / als`, inversion, `dt`, `de / het`, register.'),
    h('What examiners score'),
    table(['criterion', 'question they ask'], [['inhoud', 'Are all the points there? Is the purpose clear?'], ['opbouw en samenhang', 'Paragraphs? Signal words? A logical order?'], ['grammatica', 'Word order, verb forms, agreement'], ['woordkeuze en register', 'Varied, precise, and fitting the reader?'], ['spelling', 'Does it hinder reading?']]),
    h('Frames that always work'),
    p('Formal email: `Geachte … / Naar aanleiding van … / Graag verneem ik … / Bij voorbaat dank. / Met vriendelijke groet,` Argument: `Naar mijn mening … In de eerste plaats … Daarnaast … Tegenstanders … Dat mag zo zijn, maar … Al met al …` Complaint: facts with dates, the problem, what you want, a deadline.'),
    tip('Use the model answers below only **after** you have written your own. Then compare against the checklist, not sentence by sentence.'),
  ], ['g4-staatsexamen', 'g4-argument', 'g4-register-switching'], ['schrijfopdracht', 'aandachtspunt', 'aanhef', 'slotzin', 'samenhang', 'woordkeuze', 'kladversie', 'verwerken', 'nalezen', 'formuleren', 'volledig', 'passend'], [
    fill('Opdracht 1a. Maak de zin af: "Hoewel ik al drie jaar in Nederland woon, ___ ik nog steeds moeite met de woordvolgorde." (hebben)', ['heb'], 'Although I have lived in the Netherlands for three years, I still have trouble with word order.', 'After a fronted hoewel-clause the main verb comes first: heb ik.'),
    fill('Opdracht 1b. Maak de zin af: "Ik zou graag willen weten ___ de cursus ook online wordt aangeboden." (whether)', ['of'], 'I would like to know whether the course is also offered online.', 'Indirect yes/no question: of.'),
    fill('Opdracht 1c. Maak de zin af: "De vergadering is uitgesteld ___ de voorzitter ziek is." (because)', ['omdat', 'doordat', 'aangezien'], 'The meeting has been postponed because the chair is ill.', 'omdat / doordat / aangezien + verb at the end.'),
    fill('Opdracht 1d. Maak de zin af: "Als ik dat eerder had geweten, ___ ik me wel hebben aangemeld." (zullen, past)', ['zou'], 'If I had known that earlier, I would have registered.', 'Unreal past: zou … hebben aangemeld.'),
    fix('Opdracht 1e. Verbeter de zin: "Ik wil u vragen of kunt u mij een bevestiging sturen."', ['Ik wil u vragen of u mij een bevestiging kunt sturen.', 'Ik wil u vragen of u mij een bevestiging kan sturen.'], 'After of the verbs go to the end: … of u mij een bevestiging kunt sturen.'),
    fix('Opdracht 1f. Verbeter de zin: "De informatie die u heeft gestuurd zijn niet compleet."', ['De informatie die u heeft gestuurd is niet compleet.', 'De informatie die u heeft gestuurd, is niet compleet.'], 'de informatie is singular: is.'),
    write('Opdracht 2 (kort, ongeveer 50 woorden). U heeft een afspraak bij de tandarts op donderdag om 9.00 uur, maar u moet die ochtend onverwacht werken. Schrijf een e-mail aan de praktijk: zeg de afspraak af, geef de reden en vraag om een nieuwe afspraak, liefst in de middag.', ['Passende aanhef (Geachte heer, mevrouw, / Beste assistent,)', 'Welke afspraak (dag en tijd)', 'Reden in één zin', 'Verzoek om een nieuwe afspraak, liefst ’s middags', 'u, zou / graag, afsluiting met naam'], 'Geachte heer, mevrouw, Helaas moet ik mijn afspraak van donderdag 12 juni om 9.00 uur afzeggen, omdat ik die ochtend onverwacht moet werken. Zou ik een nieuwe afspraak kunnen maken, bij voorkeur op een middag in dezelfde of de volgende week? Alvast bedankt voor de moeite. Met vriendelijke groet, Sam Taylor'),
    write('Opdracht 3 (kort, ongeveer 60 woorden). Uw buurvrouw, mevrouw Visser, heeft de afgelopen twee weken uw planten water gegeven en uw post bewaard. Schrijf een kaartje: bedank haar, vertel iets over uw vakantie en nodig haar uit voor koffie.', ['Informele maar beleefde toon (Beste mevrouw Visser / Lieve …)', 'Bedanken met concrete reden', 'Eén of twee zinnen over de vakantie', 'Uitnodiging met een voorstel voor dag of tijd', 'Warme afsluiting'], 'Beste mevrouw Visser, Heel hartelijk bedankt dat u op onze planten en de post heeft gepast; alles zag er prachtig uit toen we thuiskwamen. We hebben een heerlijke vakantie gehad in Portugal, met veel zon en lekker eten. Heeft u zin om zaterdagochtend een kopje koffie te komen drinken? Dan laten we wat foto’s zien. Hartelijke groet, Sam en Anna'),
    write('Opdracht 4 (lang, ongeveer 150 woorden). U volgt een avondopleiding. De school heeft besloten alle lessen voortaan alleen online te geven. Schrijf een brief aan de directie waarin u uitlegt waarom u het daar niet mee eens bent. Noem twee bezwaren, toon begrip voor het standpunt van de school en doe een voorstel.', ['Formele aanhef en doel in de eerste alinea', 'Bezwaar 1 met toelichting of voorbeeld', 'Bezwaar 2', 'Begrip voor de school (Ik begrijp dat … / Dat mag zo zijn, maar …)', 'Een concreet voorstel', 'Slotzin met verwachting + Met vriendelijke groet', 'Signaalwoorden; u; werkwoord achteraan na dat / omdat'], 'Geachte directie, Naar aanleiding van uw bericht dat alle lessen voortaan online worden gegeven, wil ik u vragen dat besluit te heroverwegen. In de eerste plaats leer ik in de avondopleiding vooral door te oefenen met medestudenten. Online is dat veel moeilijker: gesprekken in kleine groepjes lopen stroef en je durft minder snel een vraag te stellen. Daarnaast zit ik overdag al acht uur achter een scherm. Na nog drie uur online les kan ik me nauwelijks meer concentreren. Ik begrijp dat online lesgeven voor de school goedkoper is en dat sommige studenten het prettig vinden. Dat mag zo zijn, maar het gaat ten koste van de kwaliteit. Ik stel daarom voor de theorielessen online te houden en de praktijklessen op school. Graag verneem ik of dat mogelijk is. Met vriendelijke groet, Sam Taylor'),
    write('Opdracht 5 (lang, ongeveer 200 woorden). In uw gemeente wordt gesproken over een verbod op vuurwerk met oud en nieuw. De lokale krant vraagt lezers om hun mening. Schrijf een betoog. Neem een duidelijk standpunt in, geef twee argumenten, weerleg één tegenargument en sluit af met een conclusie.', ['Titel en inleiding met standpunt', 'Argument 1 met onderbouwing (In de eerste plaats …)', 'Argument 2 (Daarnaast / Bovendien …)', 'Tegenargument genoemd en weerlegd (Tegenstanders … Dat mag zo zijn, maar …)', 'Conclusie zonder nieuwe argumenten (Al met al / Kortom …)', 'Alinea’s, signaalwoorden, gevarieerde woordkeuze', 'Nalezen: woordvolgorde, dt, de / het'], 'Tijd voor een vuurwerkverbod. Elk jaar laait de discussie over vuurwerk weer op. Naar mijn mening is het tijd dat onze gemeente het afsteken door particulieren verbiedt. In de eerste plaats is vuurwerk gevaarlijk. Elke jaarwisseling belanden honderden mensen op de spoedeisende hulp, onder wie veel kinderen en omstanders die zelf niets hebben afgestoken. Hulpverleners worden bovendien steeds vaker met vuurwerk bekogeld. Daarnaast is de overlast groot. Al weken voor oud en nieuw klinken er knallen, waar ouderen, huisdieren en mensen met een oorlogstrauma onder lijden, en op 1 januari ligt de straat vol afval. Tegenstanders zeggen dat vuurwerk een traditie is die je niet mag afpakken. Dat mag zo zijn, maar tradities veranderen. Een grote vuurwerkshow van de gemeente, zoals in andere steden, houdt het feest in stand zonder de gevaren. Wie dat ziet, mist het eigen vuurwerk nauwelijks. Al met al wegen veiligheid en rust zwaarder dan het plezier van een kleine groep. De gemeenteraad zou daarom moeten kiezen voor een verbod, in combinatie met één mooie centrale show.'),
    mc('What costs the most points in the writing exam?', ['a small spelling mistake', 'leaving out one of the required points', 'a short sentence'], 1, 'Task completion comes first.'),
    mc('When do you decide on u or je?', ['halfway through', 'before the first word', 'it does not matter'], 1, 'Before you start, and keep it.'),
    mc('What do you check last?', ['your recurring mistakes from your error log', 'the examiner’s name', 'the word count only'], 0, 'Verb position, dt, de / het, register.'),
    build('Have you worked in all the points?', 'Heb je alle aandachtspunten verwerkt?', ['verwerken', 'alle je'], 'heb je … verwerkt.'),
    tr('en-nl', 'Proofread your text.', ['Lees je tekst na.', 'Lees uw tekst na.'], 'nalezen: lees … na.'),
  ], [
    mc('"De aanhef" of a letter is', ['the salutation', 'the signature'], 0, 'Geachte …,'),
    fill('Signaalwoorden zorgen voor ___. (coherence)', ['samenhang'], 'Signal words provide coherence.', 'samenhang.'),
    fix('Ik schrijf u omdat ik ben het niet eens met uw besluit.', ['Ik schrijf u omdat ik het niet eens ben met uw besluit.'], 'omdat: verb to the end.'),
    build('Formulate your request in one sentence.', 'Formuleer je verzoek in één zin.', ['formuleert', 'de verzoek'], 'Imperative; het verzoek.'),
    tr('en-nl', 'A complete text scores better than a beautiful half.', ['Een volledige tekst scoort beter dan een mooie halve.'], 'volledige; beter dan.'),
    speak('Ik onderstreep eerst de lezer, het doel en alle aandachtspunten, en daarna maak ik een kort plan.', 'First I underline the reader, the purpose and all the points to cover, and then I make a short plan.'),
  ]));

  /* ================= Unit 6, lesson 5: mock speaking paper ================= */
  N('spreekopdracht', 'de', 'spreekopdrachten', 'speaking task', 'Bij elke spreekopdracht staat hoeveel tijd je hebt.', 'Each speaking task states how much time you have.', { theme: 'exam', ...S });
  N('trefwoord', 'het', 'trefwoorden', 'key word', 'Schrijf in de voorbereidingstijd alleen trefwoorden op.', 'In the preparation time only write down key words.', { theme: 'exam', ...S });
  N('spreektijd', 'de', null, 'speaking time', 'Gebruik de volle spreektijd.', 'Use the full speaking time.', { theme: 'exam', ...S });
  N('gesprekspartner', 'de', 'gesprekspartners', 'conversation partner', 'Let op wie je gesprekspartner is: je of u?', 'Note who your conversation partner is: je or u?', { theme: 'exam', ...S });
  N('verstaanbaarheid', 'de', null, 'intelligibility', 'Verstaanbaarheid is belangrijker dan een perfect accent.', 'Intelligibility is more important than a perfect accent.', { theme: 'exam', ...S });
  N('vloeiendheid', 'de', null, 'fluency', 'Vloeiendheid betekent doorpraten, ook na een fout.', 'Fluency means carrying on, even after a mistake.', { theme: 'exam', ...S });
  VB('doorpraten', 'to keep talking', 'praat door|praat door|praten door', 'praatte door|praatten door', 'doorgepraat', 'hebben', 'Maak je een fout? Praat gewoon door.', 'Do you make a mistake? Just keep talking.', { theme: 'exam', ...S });
  VB('zich herstellen', 'to correct oneself / recover', 'herstel me|herstelt zich|herstellen ons', 'herstelde me|herstelden ons', 'hersteld', 'hebben', 'Je mag jezelf herstellen: "ik bedoel …".', 'You may correct yourself: "I mean …".', { theme: 'exam', ...S, id: 'zich-herstellen' });
  VB('omschrijven', 'to paraphrase / describe', 'omschrijf|omschrijft|omschrijven', 'omschreef|omschreven', 'omschreven', 'hebben', 'Weet je een woord niet? Omschrijf het.', 'Do you not know a word? Describe it.', { theme: 'exam', ...S });
  PH('Ik bedoel …', 'I mean …', 'Hij heeft, ik bedoel, hij is gisteren gekomen.', 'He has, I mean, he came yesterday.', { theme: 'exam', ...S, id: 'ph-ik-bedoel' });
  PH('Hoe zeg je dat … een soort …', 'How do you say … a kind of …', 'Het is, hoe zeg je dat, een soort vergunning.', 'It is, how do you say, a kind of permit.', { theme: 'exam', ...S, id: 'ph-hoe-zeg-je-dat' });
  PH('Samengevat: …', 'In summary: …', 'Samengevat: ik ben voor, mits het goed geregeld wordt.', 'In summary: I am in favour, provided it is well arranged.', { theme: 'exam', ...S, id: 'ph-samengevat' });

  addTo('s4u6', lesson('s4u6l5', 'Mock speaking paper (Staatsexamen style)', 'You can complete a full speaking paper: short reactions in everyday and formal situations and long tasks with an opinion, advice or a description, each within its time.', [
    h('How to take this paper'),
    list('Use a timer. Short tasks: **20 seconds** to prepare, **30 seconds** to speak. Long tasks: **1 minute** to prepare, **2 minutes** to speak.', 'In the preparation time write **trefwoorden**, never sentences.', 'Identify the `gesprekspartner`: a friend or colleague (`je`), or an official, client or stranger (`u`).', 'Speak **out loud** and record yourself if you can. Then compare with the model answer and the checklist.', 'Fill the time. Stopping early loses more than a grammar mistake.'),
    h('Structure for every long task'),
    table(['step', 'frame'], [['point', '*Volgens mij … / Ik zou u aanraden om …'], ['reason 1', '*Ten eerste …'], ['reason 2', '*Ten tweede … / Daarnaast …'], ['example', '*Een voorbeeld daarvan is … / Zo …'], ['other side', '*Natuurlijk kun je zeggen dat …, maar …'], ['close', '*Samengevat: … / Kortom, …']]),
    h('When it goes wrong mid-sentence'),
    p('Correct yourself briefly and go on: `… ik bedoel …`. Missing a word: `hoe zeg je dat … een soort …` and describe it. Lost the thread: `Wat ik wil zeggen, is …`. Examiners score `vloeiendheid` and `verstaanbaarheid`; a repaired sentence counts as fluent.'),
    tip('Record one long task today and the same task in a week. Hearing your own progress is the best exam preparation there is.'),
  ], ['g4-staatsexamen', 'g4-register-switching', 'g4-argument'], ['spreekopdracht', 'trefwoord', 'spreektijd', 'gesprekspartner', 'verstaanbaarheid', 'vloeiendheid', 'doorpraten', 'zich-herstellen', 'omschrijven', 'ph-ik-bedoel', 'ph-hoe-zeg-je-dat', 'ph-samengevat'], [
    free('Kort 1 (je). Een collega vraagt of u vrijdag zijn dienst kunt overnemen. U kunt niet. Reageer: zeg nee, geef een reden en doe een ander voorstel.', 'Wat vervelend dat je iemand zoekt. Vrijdag lukt me helaas niet, want ik heb een afspraak in het ziekenhuis die ik niet kan verzetten. Zaterdag zou ik wel kunnen. Is dat misschien een optie, of zal ik aan Tom vragen of hij vrijdag kan?', 'How annoying that you are looking for someone. Friday unfortunately does not work for me, because I have a hospital appointment I cannot move. I could do Saturday, though. Is that maybe an option, or shall I ask Tom whether he can do Friday?', { hints: ['… lukt me helaas niet, want …', '… zou ik wel kunnen', 'Is dat een optie?'] }),
    free('Kort 2 (u). U staat aan de balie van de gemeente. Uw nieuwe identiteitskaart had gisteren klaar moeten zijn, maar is er niet. Reageer.', 'Goedemorgen. Ik heb drie weken geleden een identiteitskaart aangevraagd, en volgens de brief zou die gisteren klaarliggen. Nu hoor ik dat hij er nog niet is. Dat is vervelend, want ik ga volgende week op reis. Kunt u voor mij uitzoeken wanneer hij wel klaar is, en of het eventueel met spoed kan?', 'Good morning. I applied for an ID card three weeks ago, and according to the letter it would be ready yesterday. Now I hear it is not there yet. That is annoying, because I am travelling next week. Could you find out for me when it will be ready, and whether it could possibly be done urgently?', { hints: ['Ik heb … aangevraagd', 'volgens de brief zou …', 'Kunt u voor mij uitzoeken …?'] }),
    free('Kort 3 (je). Een vriend wil een tweedehands auto kopen van iemand via internet en het hele bedrag vooraf overmaken. Geef advies.', 'Dat zou ik niet doen als ik jou was. Je weet niet of de verkoper betrouwbaar is, en als je vooraf betaalt, ben je je geld misschien kwijt. Ik zou eerst gaan kijken, een proefrit maken en pas betalen als de auto op jouw naam staat. Zal ik anders met je meegaan?', 'I would not do that if I were you. You do not know whether the seller is reliable, and if you pay in advance, you may lose your money. I would first go and look, take a test drive and only pay when the car is in your name. Shall I come with you otherwise?', { hints: ['Dat zou ik niet doen als ik jou was', 'Ik zou eerst …', 'pas betalen als …'] }),
    free('Kort 4 (u). U belt uw verhuurder: de verwarming doet het al drie dagen niet en het is winter. Leg het probleem uit en zeg wat u wilt.', 'Goedemiddag, met Sam Taylor van de Javastraat 12. Ik bel omdat de verwarming het al drie dagen niet doet. Het is nu veertien graden in huis, en ik heb een klein kind. Ik heb zaterdag al een bericht ingesproken, maar niets gehoord. Zou u vandaag nog een monteur kunnen sturen? Ik ben de hele dag thuis.', 'Good afternoon, Sam Taylor from Javastraat 12 speaking. I am calling because the heating has not been working for three days. It is now fourteen degrees in the house, and I have a small child. I already left a message on Saturday, but heard nothing. Could you send a mechanic today? I am at home all day.', { hints: ['Ik bel omdat …', 'Ik heb al …, maar …', 'Zou u vandaag nog … kunnen …?'] }),
    free('Lang 1 (mening, 2 minuten). "Werkgevers zouden hun personeel moeten verplichten om Nederlands te leren." Geef uw mening met twee argumenten, een tegenargument en een conclusie.', 'Volgens mij is een verplichting niet de goede weg, maar moeten werkgevers het leren van Nederlands wel actief mogelijk maken. Ten eerste werkt dwang slecht bij volwassenen. Wie moe uit zijn werk komt en verplicht naar een les moet, leert weinig; wie zelf het nut ziet, leert veel sneller. Ten tweede is de situatie per bedrijf heel verschillend. In een internationaal bedrijf waar iedereen Engels spreekt, is Nederlands voor het werk niet nodig, terwijl het in de zorg of de bouw om veiligheid gaat. Daar vind ik een taaleis wél redelijk. Natuurlijk kun je zeggen dat mensen zonder Nederlands buiten de samenleving blijven staan. Dat is een terecht punt, maar juist daarom zou ik kiezen voor lessen onder werktijd, betaald door de werkgever. Dan is de drempel weg en is een verplichting niet meer nodig. Samengevat: geen algemene plicht, maar wel een recht op taalles in werktijd, en een taaleis waar de veiligheid dat vraagt.', 'In my view an obligation is not the right way, but employers must actively make learning Dutch possible. First, compulsion works badly with adults. Second, the situation differs greatly per company. Of course you can say that people without Dutch stay outside society. That is a fair point, but precisely for that reason I would choose lessons during working hours, paid for by the employer. In summary: no general duty, but a right to language lessons in working time, and a language requirement where safety demands it.', { hints: ['Volgens mij …', 'Ten eerste … Ten tweede …', 'Natuurlijk kun je zeggen dat …, maar …', 'Samengevat: …'] }),
    free('Lang 2 (advies, 2 minuten). Een kennis uit het buitenland komt in Nederland werken en vraagt u hoe hij snel een woning, een huisarts en een bankrekening regelt. Geef een duidelijk advies in de goede volgorde.', 'Ik zou je aanraden om het in deze volgorde te doen. Begin met de inschrijving bij de gemeente, want zonder BSN kun je bijna niets regelen. Maak daarvoor online een afspraak en neem je paspoort en je huurcontract mee. Daarna kun je een bankrekening openen; bij de meeste banken gaat dat via een app, maar je hebt wel je BSN nodig. Schrijf je vervolgens in bij een huisarts in je eigen wijk. Doe dat meteen, ook als je niet ziek bent, want veel praktijken zitten vol. Vergeet ook de zorgverzekering niet: die moet je binnen vier maanden afsluiten. De woning is het moeilijkst. Reken op een paar maanden zoeken, reageer snel op advertenties en betaal nooit vooraf zonder het huis te hebben gezien. Een voorbeeld: een collega van mij vond pas iets via een oproep op zijn werk. Samengevat: eerst de gemeente, dan de bank, de huisarts en de verzekering, en neem voor de woning de tijd.', 'I would advise you to do it in this order. Start with registration at the municipality, because without a BSN you can arrange almost nothing. Then you can open a bank account. Next register with a GP in your own district. Do not forget health insurance either. The home is the hardest. In summary: first the municipality, then the bank, the GP and the insurance, and take your time for the home.', { hints: ['Ik zou je aanraden om …', 'Begin met …, want …', 'Daarna … Vervolgens …', 'Samengevat: …'] }),
    free('Lang 3 (beschrijven en verklaren, 2 minuten). Beschrijf een ontwikkeling die u in uw eigen vakgebied of woonplaats ziet, leg de oorzaken uit en zeg wat u ervan verwacht.', 'Een ontwikkeling die ik in mijn buurt zie, is dat steeds meer kleine winkels verdwijnen. Vijf jaar geleden waren er in mijn straat een bakker, een groenteboer en een fietsenmaker; nu zitten er twee koffiezaken en een makelaar. Dat heeft volgens mij twee oorzaken. Ten eerste zijn de huren sterk gestegen, waardoor alleen zaken met hoge marges kunnen overleven. Ten tweede bestellen mensen steeds meer online, zodat een gewone winkel minder klanten krijgt. Het gevolg is dat de buurt er mooier uitziet, maar minder praktisch is geworden, vooral voor ouderen. Ik verwacht dat deze ontwikkeling doorgaat, tenzij de gemeente ingrijpt, bijvoorbeeld door in bepaalde straten alleen winkels voor dagelijkse boodschappen toe te staan. Samengevat: de buurt wordt duurder en minder divers, en zonder beleid zal dat niet veranderen.', 'A development I see in my neighbourhood is that more and more small shops are disappearing. That has two causes in my view. First, rents have risen sharply. Second, people order more and more online. The result is that the neighbourhood looks nicer but has become less practical. I expect this development to continue, unless the municipality intervenes. In summary: the neighbourhood is becoming more expensive and less diverse, and without policy that will not change.', { hints: ['Een ontwikkeling die ik zie, is dat …', 'Dat heeft twee oorzaken', 'Het gevolg is dat …', 'Ik verwacht dat …, tenzij …'] }),
    speak('Volgens mij is dat een goed plan, en wel om twee redenen. Ten eerste bespaart het tijd, ten tweede is het eerlijker.', 'In my view that is a good plan, for two reasons. First it saves time, second it is fairer.'),
    speak('Hij heeft, ik bedoel, hij is gisteren aangekomen, en hij zoekt, hoe zeg je dat, een soort tijdelijke woning.', 'He has, I mean, he arrived yesterday, and he is looking for, how do you say, a kind of temporary home.'),
    mc('What do you write down in the preparation time?', ['full sentences', 'key words', 'nothing'], 1, 'Trefwoorden.'),
    mc('You make a grammar mistake halfway through a sentence. You', ['stop and start the task again', 'correct it briefly with "ik bedoel" and go on', 'apologise at length'], 1, 'Repair and continue.'),
    mc('You do not know the Dutch word for "permit". You say', ['nothing', '"een soort officiële toestemming van de gemeente"', 'the English word three times'], 1, 'Describe it: omschrijven.'),
    mc('A task says: "U belt met de gemeente." You use', ['je', 'u', 'jullie'], 1, 'Official: u.'),
    fill('Maak je een fout? Praat gewoon ___.', ['door'], 'Do you make a mistake? Just keep talking.', 'doorpraten.'),
    fill('___: ik ben voor, mits het goed geregeld wordt. (in summary)', ['Samengevat'], 'In summary: I am in favour, provided it is well arranged.', 'samengevat.'),
    build('Use the full speaking time.', 'Gebruik de volle spreektijd.', ['gebruikt', 'vol'], 'Imperative; de spreektijd → volle.'),
    tr('en-nl', 'Do you not know a word? Describe it.', ['Weet je een woord niet? Omschrijf het.'], 'omschrijven.'),
  ], [
    mc('"Vloeiendheid" means', ['speaking without any mistakes', 'carrying on smoothly, also after a mistake'], 1, 'Fluency.'),
    fill('Schrijf alleen ___ op, geen zinnen. (key words)', ['trefwoorden'], 'Only write down key words, not sentences.', 'trefwoorden.'),
    fill('Hij heeft, ik ___, hij is gisteren gekomen.', ['bedoel'], 'He has, I mean, he came yesterday.', 'ik bedoel.'),
    build('Intelligibility is more important than a perfect accent.', 'Verstaanbaarheid is belangrijker dan een perfect accent.', ['als', 'perfecte'], 'belangrijker dan; het accent + een → no -e.'),
    tr('en-nl', 'I would advise you to start with the municipality.', ['Ik zou u aanraden om met de gemeente te beginnen.', 'Ik zou je aanraden om met de gemeente te beginnen.'], 'zou … aanraden om … te beginnen.'),
    speak('Samengevat: eerst de gemeente, dan de bank en de huisarts, en neem voor de woning de tijd.', 'In summary: first the municipality, then the bank and the GP, and take your time for the home.'),
  ]));
})();
