/* Stage 4 (B2) — extra lessons for Unit 1 (Politiek en samenleving) and Unit 2 (Wetenschap en technologie): lessons 3 to 5 of each unit.
   Loaded after stage4-u4-6.js; lessons are appended to the existing units. */
(function () {
  'use strict';
  const NL = window.NL, A = NL.contentApi;
  const { N, VB, W, PH, h, p, tip, warn, table, ex, list, mc, fill, tr, build, conj, art, plural, dict, listen, speak, free, match, read, fix, write, auto, lesson } = A;
  const addTo = (unitId, l) => { const f = A.findUnit(unitId); if (f) f.unit.lessons.push(l); };
  const S = { stage: 4 };

  /* ================= Unit 1, lesson 3: the EU and international relations ================= */
  N('lidstaat', 'de', 'lidstaten', 'member state', 'De EU telt zevenentwintig lidstaten.', 'The EU has twenty-seven member states.', { theme: 'politics', ...S });
  N('verdrag', 'het', 'verdragen', 'treaty', 'Het verdrag werd in 1992 in Maastricht getekend.', 'The treaty was signed in Maastricht in 1992.', { theme: 'politics', ...S });
  N('richtlijn', 'de', 'richtlijnen', 'directive / guideline', 'De richtlijn moet binnen twee jaar in nationale wetgeving zijn omgezet.', 'The directive must be transposed into national law within two years.', { theme: 'politics', ...S });
  N('wetgeving', 'de', null, 'legislation', 'Veel milieuwetgeving komt uit Brussel.', 'Much environmental legislation comes from Brussels.', { theme: 'politics', ...S });
  N('soevereiniteit', 'de', null, 'sovereignty', 'Critici vrezen verlies van soevereiniteit.', 'Critics fear a loss of sovereignty.', { theme: 'politics', ...S });
  N('interne markt', 'de', null, 'single market', 'Nederland profiteert sterk van de interne markt.', 'The Netherlands benefits greatly from the single market.', { theme: 'politics', ...S, id: 'interne-markt' });
  N('vetorecht', 'het', null, 'right of veto', 'Bij buitenlands beleid heeft elke lidstaat vetorecht.', 'On foreign policy every member state has a veto.', { theme: 'politics', ...S });
  N('bondgenoot', 'de', 'bondgenoten', 'ally', 'De NAVO-bondgenoten verhogen hun defensie-uitgaven.', 'The NATO allies are raising their defence spending.', { theme: 'politics', ...S });
  N('sanctie', 'de', 'sancties', 'sanction', 'De sancties zijn opnieuw verlengd.', 'The sanctions have been extended again.', { theme: 'politics', ...S });
  N('onderhandeling', 'de', 'onderhandelingen', 'negotiation', 'De onderhandelingen verliepen moeizaam.', 'The negotiations went with difficulty.', { theme: 'politics', ...S });
  N('nettobetaler', 'de', 'nettobetalers', 'net contributor', 'Nederland is een nettobetaler aan de EU.', 'The Netherlands is a net contributor to the EU.', { theme: 'politics', ...S });
  VB('ratificeren', 'to ratify', 'ratificeer|ratificeert|ratificeren', 'ratificeerde|ratificeerden', 'geratificeerd', 'hebben', 'Het verdrag moet door alle lidstaten worden geratificeerd.', 'The treaty must be ratified by all member states.', { theme: 'politics', ...S });
  VB('toetreden', 'to join / accede', 'treed toe|treedt toe|treden toe', 'trad toe|traden toe', 'toegetreden', 'zijn', 'Kroatië is in 2013 tot de EU toegetreden.', 'Croatia joined the EU in 2013.', { theme: 'politics', ...S });
  VB('uittreden', 'to leave / withdraw', 'treed uit|treedt uit|treden uit', 'trad uit|traden uit', 'uitgetreden', 'zijn', 'Het Verenigd Koninkrijk is in 2020 uitgetreden.', 'The United Kingdom withdrew in 2020.', { theme: 'politics', ...S });
  VB('overdragen', 'to transfer / hand over', 'draag over|draagt over|dragen over', 'droeg over|droegen over', 'overgedragen', 'hebben', 'Lidstaten hebben bevoegdheden aan Brussel overgedragen.', 'Member states have transferred powers to Brussels.', { theme: 'politics', ...S });
  VB('handhaven', 'to enforce / maintain', 'handhaaf|handhaaft|handhaven', 'handhaafde|handhaafden', 'gehandhaafd', 'hebben', 'Regels die niet worden gehandhaafd, hebben weinig zin.', 'Rules that are not enforced make little sense.', { theme: 'politics', ...S });
  W('grensoverschrijdend', 'cross-border', 'adj', 'Klimaat is een grensoverschrijdend probleem.', 'Climate is a cross-border problem.', { theme: 'politics', ...S });
  W('unaniem', 'unanimous(ly)', 'adj', 'Het besluit moet unaniem worden genomen.', 'The decision must be taken unanimously.', { theme: 'politics', ...S });
  W('ten koste van', 'at the expense of', 'prep', 'Samenwerking gaat soms ten koste van snelheid.', 'Cooperation sometimes comes at the expense of speed.', { theme: 'politics', ...S, id: 'ten-koste-van' });

  addTo('s4u1', lesson('s4u1l3', 'The Netherlands in Europe: long sentences about treaties and power', 'You can read and discuss texts about the EU and international cooperation, and handle their long, clause-rich sentences with confidence.', [
    h('Why EU texts are hard'),
    p('They combine everything difficult at once: **stacked relative clauses**, **passives with modals**, **nominalisations** and **long compounds**. `De richtlijn, die in 2019 werd aangenomen en die binnen twee jaar in nationale wetgeving had moeten worden omgezet, is door drie lidstaten nog altijd niet geïmplementeerd.` Strategy: find the main clause first (`De richtlijn … is … niet geïmplementeerd`), then open the brackets one by one.'),
    h('The debate in one paragraph'),
    p('Supporters point to the `interne markt`, peace, and problems that are `grensoverschrijdend` (climate, migration, security). Critics stress `soevereiniteit`, the cost to a `nettobetaler`, and distance from voters. The Dutch position is pragmatic: strongly pro-market, cautious about transferring more powers.'),
    h('Useful structures'),
    table(['structure', 'example'], [['passive + modal + perfect', '*Het verdrag had door alle lidstaten moeten worden geratificeerd.'], ['relative clause with preposition', '*De onderwerpen waarover unaniem moet worden besloten, zijn gevoelig.'], ['nominal style', '*De overdracht van bevoegdheden leidt tot verlies van zeggenschap.'], ['concession', '*Hoewel Nederland nettobetaler is, profiteert het sterk van de interne markt.'], ['ten koste van', '*Meer samenwerking gaat ten koste van nationale vrijheid.']]),
    ex(['De onderwerpen waarover unaniem moet worden besloten, zoals buitenlands beleid, leiden vaak tot vertraging.', 'The subjects on which decisions must be taken unanimously, such as foreign policy, often lead to delay.'], ['Hoewel Nederland nettobetaler is, verdient het een veelvoud daarvan terug via de interne markt.', 'Although the Netherlands is a net contributor, it earns a multiple of that back via the single market.'], ['Critici stellen dat er te veel bevoegdheden zijn overgedragen zonder dat de kiezer daarover is geraadpleegd.', 'Critics argue that too many powers have been transferred without the voter having been consulted about it.'], ['Regels die niet worden gehandhaafd, ondermijnen het vertrouwen in de hele Unie.', 'Rules that are not enforced undermine trust in the whole Union.']),
    tip('In a long sentence, underline the finite verb of the main clause and its partner at the end. Everything between commas is extra.'),
  ], ['g4-long-sentences', 'g4-passive-all', 'g4-nominalisation'], ['lidstaat', 'verdrag', 'richtlijn', 'wetgeving', 'soevereiniteit', 'interne-markt', 'vetorecht', 'bondgenoot', 'sanctie', 'onderhandeling', 'nettobetaler', 'ratificeren', 'toetreden', 'uittreden', 'overdragen', 'handhaven', 'grensoverschrijdend', 'unaniem', 'ten-koste-van'], [
    mc('"De richtlijn, die in 2019 werd aangenomen, is nog niet geïmplementeerd." What is the main clause?', ['die in 2019 werd aangenomen', 'De richtlijn is nog niet geïmplementeerd', 'in 2019 werd aangenomen'], 1, 'Remove the relative clause between the commas.'),
    mc('Het verdrag had door alle lidstaten ___.', ['moeten worden geratificeerd', 'gemoeten geratificeerd worden', 'worden moeten geratificeerd'], 0, 'had + moeten + worden + participle.'),
    mc('De onderwerpen ___ unaniem moet worden besloten, zijn gevoelig.', ['waarover', 'over die', 'dat over'], 0, 'besluiten over → waarover.'),
    mc('"Ten koste van" means', ['thanks to', 'at the expense of', 'at the cost price'], 1, 'At the expense of.'),
    mc('"Grensoverschrijdend" describes a problem that', ['stops at the border', 'crosses borders', 'concerns border guards'], 1, 'grens + overschrijdend.'),
    mc('Kroatië ___ in 2013 tot de EU toegetreden.', ['is', 'heeft', 'werd'], 0, 'toetreden takes zijn.'),
    art('verdrag', 'het', 'het verdrag.'),
    art('richtlijn', 'de', 'de lijn → de richtlijn.'),
    art('vetorecht', 'het', 'het recht.'),
    fill('Lidstaten hebben bevoegdheden aan Brussel ___. (overdragen)', ['overgedragen'], 'Member states have transferred powers to Brussels.', 'over + gedragen.'),
    fill('Regels die niet worden ___, hebben weinig zin. (handhaven)', ['gehandhaafd'], 'Rules that are not enforced make little sense.', 'gehandhaafd.'),
    fill('Het besluit moet ___ worden genomen. (unanimously)', ['unaniem'], 'The decision must be taken unanimously.', 'unaniem.'),
    fill('___ Nederland nettobetaler is, profiteert het van de interne markt.', ['Hoewel'], 'Although the Netherlands is a net contributor, it benefits from the single market.', 'hoewel + verb at the end, then inversion.'),
    build('The treaty must be ratified by all member states.', 'Het verdrag moet door alle lidstaten worden geratificeerd.', ['ratificeren', 'van'], 'moet door … worden geratificeerd.'),
    build('Climate is a cross-border problem.', 'Klimaat is een grensoverschrijdend probleem.', ['grensoverschrijdende', 'de'], 'het probleem + een → no -e.'),
    build('The negotiations went with difficulty.', 'De onderhandelingen verliepen moeizaam.', ['verliep', 'moeizame'], 'Plural past: verliepen.'),
    tr('en-nl', 'The United Kingdom left the EU in 2020.', ['Het Verenigd Koninkrijk is in 2020 uit de EU getreden.', 'Het Verenigd Koninkrijk is in 2020 uitgetreden.', 'Het Verenigd Koninkrijk heeft de EU in 2020 verlaten.'], 'uittreden / verlaten.'),
    tr('nl-en', 'Critici vrezen dat verdere samenwerking ten koste gaat van de nationale soevereiniteit.', ['Critics fear that further cooperation comes at the expense of national sovereignty.'], 'ten koste gaan van.'),
    fix('De richtlijn is nog niet geïmplementeerd geworden.', ['De richtlijn is nog niet geïmplementeerd.'], 'No geworden in the perfect passive.'),
    dict('Hoewel Nederland nettobetaler is, profiteert het sterk van de interne markt.', 'Although the Netherlands is a net contributor, it benefits greatly from the single market.', 'hoewel … is, profiteert het.'),
    listen('De sancties, waarover de lidstaten het gisteren eens zijn geworden, gaan volgende maand in.', ['The sanctions, on which the member states agreed yesterday, take effect next month.', 'The member states disagreed about the sanctions.', 'The sanctions ended last month.'], 0, 'waarover … eens geworden; gaan … in.'),
    speak('Hoewel Nederland nettobetaler is, verdient het een veelvoud daarvan terug via de interne markt.', 'Although the Netherlands is a net contributor, it earns a multiple of that back via the single market.'),
    read('De Europese Unie wordt vaak voorgesteld als een machtig blok dat vanuit Brussel regels oplegt. In werkelijkheid is de besluitvorming traag en sterk afhankelijk van de lidstaten zelf. Een voorstel van de Europese Commissie moet niet alleen door het Europees Parlement, maar ook door de regeringen van de lidstaten worden goedgekeurd, en voor gevoelige onderwerpen, zoals belastingen en buitenlands beleid, geldt nog altijd het vetorecht. Dat beschermt kleine landen tegen de grote, maar het betekent ook dat één land een besluit kan blokkeren waarmee zesentwintig andere hebben ingestemd. Voorstanders van hervorming willen het vetorecht daarom afschaffen; tegenstanders wijzen erop dat juist Nederland daarmee zijn sterkste onderhandelingsmiddel zou verliezen.', [
      { q: 'Wat is de hoofdgedachte?', options: ['Brussel legt snel en eenzijdig regels op.', 'De besluitvorming in de EU is traag en afhankelijk van de lidstaten, mede door het vetorecht.', 'Nederland wil uit de EU.'], answer: 1, explain: '"In werkelijkheid" introduces the correction of the common image.' },
      { q: 'Waar verwijst "daarmee" naar in de laatste zin?', options: ['met het afschaffen van het vetorecht', 'met de Europese Commissie', 'met de belastingen'], answer: 0, explain: 'Abolishing the veto would cost the Netherlands its bargaining tool.' },
      { q: 'Welk nadeel van het vetorecht noemt de tekst?', options: ['kleine landen worden beschermd', 'één land kan een besluit van alle andere blokkeren', 'het Parlement heeft te veel macht'], answer: 1, explain: '"één land een besluit kan blokkeren".' },
    ], { en: 'The European Union is often presented as a powerful bloc that imposes rules from Brussels. In reality decision-making is slow and strongly dependent on the member states themselves. A proposal by the European Commission must be approved not only by the European Parliament but also by the governments of the member states, and for sensitive subjects, such as taxes and foreign policy, the veto still applies. That protects small countries against the large ones, but it also means that one country can block a decision with which twenty-six others have agreed. Supporters of reform therefore want to abolish the veto; opponents point out that the Netherlands of all countries would thereby lose its strongest bargaining tool.' }),
    free('Give a balanced one-minute view on the statement "Nederland moet meer bevoegdheden aan de EU overdragen": one argument for, one against, your conclusion.', 'Enerzijds zijn problemen als klimaat en migratie grensoverschrijdend; die kan geen enkel land alleen oplossen. Anderzijds gaat elke overdracht van bevoegdheden ten koste van de invloed van de kiezer. Ik ben daarom voor meer samenwerking op die twee terreinen, mits het Europees Parlement meer controle krijgt.', 'On the one hand problems such as climate and migration cross borders; no country can solve them alone. On the other hand every transfer of powers comes at the expense of the voter’s influence. I am therefore in favour of more cooperation in those two areas, provided the European Parliament gets more control.', { hints: ['Enerzijds … anderzijds …', 'ten koste van', 'Ik ben daarom voor …, mits …'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('"Een lidstaat" is', ['a member state', 'a treaty', 'a veto'], 0, 'lid + staat.'),
    fill('Het verdrag werd in Maastricht ___. (tekenen)', ['getekend'], 'The treaty was signed in Maastricht.', 'getekend.'),
    fill('De onderwerpen ___ we spraken, zijn gevoelig. (about which)', ['waarover'], 'The subjects we talked about are sensitive.', 'waarover.'),
    build('The sanctions have been extended again.', 'De sancties zijn opnieuw verlengd.', ['hebben', 'verlengen'], 'zijn … verlengd.'),
    tr('en-nl', 'Critics fear a loss of sovereignty.', ['Critici vrezen verlies van soevereiniteit.', 'Critici vrezen een verlies van soevereiniteit.'], 'verlies van.'),
    speak('Regels die niet worden gehandhaafd, ondermijnen het vertrouwen in de hele Unie.', 'Rules that are not enforced undermine trust in the whole Union.'),
  ]));

  /* ================= Unit 1, lesson 4: the migration and integration debate ================= */
  N('migratie', 'de', null, 'migration', 'Migratie is al jaren het belangrijkste verkiezingsthema.', 'Migration has been the main election issue for years.', { theme: 'society', ...S });
  N('asielzoeker', 'de', 'asielzoekers', 'asylum seeker', 'De opvang van asielzoekers is ongelijk verdeeld over gemeenten.', 'The reception of asylum seekers is unevenly spread across municipalities.', { theme: 'society', ...S });
  N('arbeidsmigrant', 'de', 'arbeidsmigranten', 'labour migrant', 'Veel arbeidsmigranten werken in de kassen en distributiecentra.', 'Many labour migrants work in greenhouses and distribution centres.', { theme: 'society', ...S });
  N('kennismigrant', 'de', 'kennismigranten', 'highly skilled migrant', 'Kennismigranten komen vooral naar de Randstad en Eindhoven.', 'Highly skilled migrants mainly come to the Randstad and Eindhoven.', { theme: 'society', ...S });
  N('vluchteling', 'de', 'vluchtelingen', 'refugee', 'Vluchtelingen hebben recht op bescherming.', 'Refugees have a right to protection.', { theme: 'society', ...S });
  N('opvang', 'de', null, 'reception / shelter', 'Er is een tekort aan opvangplekken.', 'There is a shortage of reception places.', { theme: 'society', ...S });
  N('integratie', 'de', null, 'integration', 'Taal is de sleutel tot integratie.', 'Language is the key to integration.', { theme: 'society', ...S });
  N('arbeidsmarkt', 'de', null, 'labour market', 'De krapte op de arbeidsmarkt houdt aan.', 'The tightness on the labour market continues.', { theme: 'society', ...S });
  N('vergrijzing', 'de', null, 'ageing of the population', 'Door de vergrijzing neemt de vraag naar zorgpersoneel toe.', 'Because of the ageing population the demand for care staff is increasing.', { theme: 'society', ...S });
  N('voorziening', 'de', 'voorzieningen', 'facility / service', 'De druk op voorzieningen als huisvesting en onderwijs neemt toe.', 'The pressure on services such as housing and education is increasing.', { theme: 'society', ...S });
  N('draagvlak', 'het', null, 'public support', 'Zonder draagvlak in de wijk mislukt elk opvangplan.', 'Without support in the neighbourhood every reception plan fails.', { theme: 'society', ...S });
  N('nuance', 'de', 'nuances', 'nuance', 'In het debat ontbreekt vaak de nuance.', 'Nuance is often missing from the debate.', { theme: 'society', ...S });
  VB('beperken', 'to limit', 'beperk|beperkt|beperken', 'beperkte|beperkten', 'beperkt', 'hebben', 'De regering wil de instroom beperken.', 'The government wants to limit the inflow.', { theme: 'society', ...S });
  VB('bijdragen aan', 'to contribute to', 'draag bij aan|draagt bij aan|dragen bij aan', 'droeg bij aan|droegen bij aan', 'bijgedragen aan', 'hebben', 'Migranten dragen bij aan de economie.', 'Migrants contribute to the economy.', { theme: 'society', ...S, id: 'bijdragen-aan' });
  VB('onderscheiden', 'to distinguish', 'onderscheid|onderscheidt|onderscheiden', 'onderscheidde|onderscheidden', 'onderscheiden', 'hebben', 'Je moet asiel, arbeid en studie van elkaar onderscheiden.', 'You have to distinguish asylum, work and study from each other.', { theme: 'society', ...S });
  VB('generaliseren', 'to generalise', 'generaliseer|generaliseert|generaliseren', 'generaliseerde|generaliseerden', 'gegeneraliseerd', 'hebben', 'Laten we niet generaliseren.', 'Let us not generalise.', { theme: 'society', ...S });
  W('daarentegen', 'by contrast', 'adv', 'Kennismigranten, daarentegen, vinden snel werk.', 'Highly skilled migrants, by contrast, find work quickly.', { theme: 'discourse', ...S });
  W('weliswaar', 'admittedly / it is true that', 'adv', 'De instroom is weliswaar gestegen, maar minder dan vaak wordt beweerd.', 'The inflow has admittedly risen, but less than is often claimed.', { theme: 'discourse', ...S });
  W('niettemin', 'nevertheless', 'adv', 'Niettemin blijft de druk op de woningmarkt groot.', 'Nevertheless the pressure on the housing market remains high.', { theme: 'discourse', ...S });

  addTo('s4u1', lesson('s4u1l4', 'A heated debate, handled with nuance', 'You can follow and take part in a polarised public debate: distinguish the categories, concede with weliswaar, contrast with daarentegen and niettemin, and avoid generalising.', [
    h('First, distinguish'),
    p('The Dutch debate mixes four very different groups. Naming them precisely is already a contribution: `asielzoekers` and `vluchtelingen` (protection), `arbeidsmigranten` (mostly EU, free movement), `kennismigranten` (recruited by employers), and `studenten` and `gezinsmigranten`. Each has different rules, numbers and effects.'),
    h('Markers for a nuanced position'),
    table(['marker', 'job', 'example'], [['*weliswaar … maar', 'concede, then turn', '*De instroom is weliswaar gestegen, maar minder dan wordt beweerd.'], ['*daarentegen', 'contrast two groups', '*Asielzoekers mogen vaak niet werken; kennismigranten, daarentegen, beginnen meteen.'], ['*niettemin / desondanks', 'despite that', '*Niettemin blijft de druk op de woningmarkt groot.'], ['*in tegenstelling tot', 'unlike', '*In tegenstelling tot wat vaak wordt gedacht, …'], ['*dat neemt niet weg dat', 'that does not alter the fact that', '*Dat neemt niet weg dat gemeenten overvraagd worden.'], ['*laten we niet generaliseren', 'against sweeping claims', '']]),
    p('`weliswaar` stands in the middle of its clause and **needs** a `maar` to follow. `daarentegen` comes after the element it contrasts.'),
    h('Arguments you will hear'),
    list('Economic: `vergrijzing`, `krapte op de arbeidsmarkt`, `migranten dragen bij aan de economie`.', 'Capacity: `druk op voorzieningen`, `woningnood`, `tekort aan opvangplekken`.', 'Social: `integratie`, `taal`, `draagvlak in de wijk`.', 'Legal and moral: `recht op bescherming`, international treaties.'),
    ex(['De instroom is weliswaar gestegen, maar het grootste deel bestaat uit arbeids- en studiemigratie, niet uit asiel.', 'The inflow has admittedly risen, but the largest part consists of labour and study migration, not asylum.'], ['In tegenstelling tot wat vaak wordt gedacht, komen de meeste migranten uit andere EU-landen.', 'Contrary to what is often thought, most migrants come from other EU countries.'], ['Door de vergrijzing is er personeel nodig; dat neemt niet weg dat de druk op de woningmarkt reëel is.', 'Because of the ageing population staff are needed; that does not alter the fact that the pressure on the housing market is real.'], ['Laten we niet generaliseren: een asielzoeker en een kennismigrant hebben weinig met elkaar gemeen.', 'Let us not generalise: an asylum seeker and a highly skilled migrant have little in common.']),
    tip('In an exam speaking task on a sensitive topic, precision is what scores: name the group, give a figure or example, concede one point, conclude.'),
  ], ['g4-discourse', 'g4-argument'], ['migratie', 'asielzoeker', 'arbeidsmigrant', 'kennismigrant', 'vluchteling', 'opvang', 'integratie', 'arbeidsmarkt', 'vergrijzing', 'voorziening', 'draagvlak', 'nuance', 'beperken', 'bijdragen-aan', 'onderscheiden', 'generaliseren', 'daarentegen', 'weliswaar', 'niettemin'], [
    mc('"Weliswaar" must be followed by', ['dus', 'maar', 'omdat'], 1, 'weliswaar … maar.'),
    mc('Which sentence is correct?', ['Weliswaar de instroom is gestegen, maar …', 'De instroom is weliswaar gestegen, maar …', 'De instroom weliswaar is gestegen, maar …'], 1, 'weliswaar in the middle field.'),
    mc('"Dat neemt niet weg dat …" means', ['that does not alter the fact that', 'that takes nothing away', 'nobody denies that'], 0, 'Concession formula.'),
    mc('Which group is recruited by employers for specialist work?', ['asielzoekers', 'kennismigranten', 'vluchtelingen'], 1, 'kennismigranten.'),
    mc('"Vergrijzing" means', ['air pollution', 'ageing of the population', 'grey weather'], 1, 'grijs → vergrijzing.'),
    mc('"In tegenstelling tot wat vaak wordt gedacht" introduces', ['a common belief the writer confirms', 'a correction of a common belief', 'an example'], 1, 'Contrary to what is often thought.'),
    art('draagvlak', 'het', 'het vlak.'),
    art('arbeidsmarkt', 'de', 'de markt.'),
    art('voorziening', 'de', '-ing → de.'),
    fill('Kennismigranten, ___, vinden meestal snel werk. (by contrast)', ['daarentegen'], 'Highly skilled migrants, by contrast, usually find work quickly.', 'daarentegen after the contrasted element.'),
    fill('___ blijft de druk op de woningmarkt groot. (nevertheless)', ['Niettemin', 'Desondanks', 'Toch'], 'Nevertheless the pressure on the housing market remains high.', 'niettemin + inversion.'),
    fill('Migranten dragen bij ___ de economie.', ['aan'], 'Migrants contribute to the economy.', 'bijdragen aan.'),
    fill('Laten we niet ___. (generalise)', ['generaliseren'], 'Let us not generalise.', 'generaliseren.'),
    build('The inflow has admittedly risen, but less than is claimed.', 'De instroom is weliswaar gestegen, maar minder dan wordt beweerd.', ['Weliswaar de', 'als'], 'weliswaar … maar; minder dan.'),
    build('That does not alter the fact that the pressure is real.', 'Dat neemt niet weg dat de druk reëel is.', ['is reëel', 'neem'], 'dat … is at the end.'),
    build('You have to distinguish asylum and labour migration.', 'Je moet asiel en arbeidsmigratie onderscheiden.', ['onderscheidt', 'van'], 'moet … onderscheiden.'),
    tr('en-nl', 'Without public support every plan fails.', ['Zonder draagvlak mislukt elk plan.'], 'zonder + inversion; het plan → elk.'),
    tr('nl-en', 'In tegenstelling tot wat vaak wordt gedacht, komen de meeste migranten uit andere EU-landen.', ['Contrary to what is often thought, most migrants come from other EU countries.'], 'in tegenstelling tot.'),
    fix('De instroom is weliswaar gestegen, dus de cijfers vallen mee.', ['De instroom is weliswaar gestegen, maar de cijfers vallen mee.'], 'weliswaar needs maar.'),
    dict('Door de vergrijzing neemt de vraag naar zorgpersoneel de komende jaren sterk toe.', 'Because of the ageing population the demand for care staff will increase sharply in the coming years.', 'neemt … toe.'),
    listen('Er is weliswaar een tekort aan opvangplekken, maar dat komt vooral doordat erkende vluchtelingen geen woning kunnen vinden.', ['There is admittedly a shortage of reception places, but that is mainly because recognised refugees cannot find a home.', 'There are too many reception places.', 'Refugees find homes easily.'], 0, 'weliswaar … maar; doordat.'),
    speak('De instroom is weliswaar gestegen, maar laten we niet generaliseren: asiel en arbeidsmigratie zijn verschillende dingen.', 'The inflow has admittedly risen, but let us not generalise: asylum and labour migration are different things.'),
    free('Exam-style long speaking task (90 seconds): "Moet Nederland arbeidsmigratie beperken?" Distinguish, give an argument on each side, concede one point, conclude.', 'Eerst wil ik een onderscheid maken: ik heb het over arbeidsmigratie, niet over asiel. Enerzijds is er door de vergrijzing een groot tekort aan personeel, bijvoorbeeld in de zorg en de bouw. Anderzijds neemt de druk op de woningmarkt toe, en worden arbeidsmigranten niet altijd goed gehuisvest. Dat probleem is weliswaar reëel, maar het ligt vooral bij werkgevers en uitzendbureaus. Ik pleit er daarom niet voor om de migratie te beperken, maar om werkgevers verantwoordelijk te maken voor huisvesting en taallessen.', 'First I want to make a distinction: I am talking about labour migration, not asylum. On the one hand the ageing population means a great shortage of staff, for example in care and construction. On the other hand the pressure on the housing market is rising, and labour migrants are not always housed properly. That problem is admittedly real, but it lies mainly with employers and agencies. I therefore do not argue for limiting migration, but for making employers responsible for housing and language lessons.', { hints: ['Eerst wil ik een onderscheid maken: …', 'Enerzijds … Anderzijds …', '… is weliswaar …, maar …', 'Ik pleit er daarom voor om …'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('"Niettemin" means', ['nevertheless', 'not at all'], 0, 'nevertheless.'),
    fill('De druk op ___ als huisvesting neemt toe. (services)', ['voorzieningen'], 'The pressure on services such as housing is increasing.', 'voorzieningen.'),
    fill('Het aantal is ___ gestegen, maar minder dan verwacht. (admittedly)', ['weliswaar'], 'The number has admittedly risen, but less than expected.', 'weliswaar.'),
    build('Language is the key to integration.', 'Taal is de sleutel tot integratie.', ['voor', 'het'], 'de sleutel tot.'),
    tr('en-nl', 'Let us not generalise.', ['Laten we niet generaliseren.'], 'generaliseren.'),
    speak('Dat neemt niet weg dat gemeenten overvraagd worden; niettemin is de nuance in dit debat nodig.', 'That does not alter the fact that municipalities are overstretched; nevertheless nuance is needed in this debate.'),
  ]));

  /* ================= Unit 1, lesson 5: a radio debate in exam format ================= */
  N('presentator', 'de', 'presentatoren', 'presenter / host', 'De presentator vat het debat samen.', 'The presenter summarises the debate.', { theme: 'media', ...S });
  N('gast', 'de', 'gasten', 'guest', 'Onze gasten zijn een econoom en een wethouder.', 'Our guests are an economist and an alderman.', { theme: 'media', ...S });
  N('stelling', 'de', 'stellingen', 'proposition', 'De stelling van vandaag: de binnenstad moet autovrij.', 'Today’s proposition: the city centre must be car-free.', { theme: 'media', ...S });
  N('luisteraar', 'de', 'luisteraars', 'listener', 'Luisteraars kunnen reageren via de app.', 'Listeners can respond via the app.', { theme: 'media', ...S });
  N('deskundige', 'de', 'deskundigen', 'expert', 'De deskundige nuanceert het beeld.', 'The expert adds nuance to the picture.', { theme: 'media', ...S });
  N('standpunt', 'het', 'standpunten', 'position', 'Beide gasten lichten hun standpunt toe.', 'Both guests explain their position.', { theme: 'media', ...S });
  VB('nuanceren', 'to qualify / add nuance', 'nuanceer|nuanceert|nuanceren', 'nuanceerde|nuanceerden', 'genuanceerd', 'hebben', 'Ik wil dat beeld graag nuanceren.', 'I would like to qualify that picture.', { theme: 'media', ...S });
  VB('bestrijden', 'to dispute / combat', 'bestrijd|bestrijdt|bestrijden', 'bestreed|bestreden', 'bestreden', 'hebben', 'De wethouder bestrijdt die cijfers.', 'The alderman disputes those figures.', { theme: 'media', ...S });
  VB('onderschrijven', 'to endorse', 'onderschrijf|onderschrijft|onderschrijven', 'onderschreef|onderschreven', 'onderschreven', 'hebben', 'Dat standpunt onderschrijf ik volledig.', 'I fully endorse that position.', { theme: 'media', ...S });
  VB('in de rede vallen', 'to interrupt', 'val in de rede|valt in de rede|vallen in de rede', 'viel in de rede|vielen in de rede', 'in de rede gevallen', 'zijn', 'Sorry dat ik u in de rede val.', 'Sorry to interrupt you.', { theme: 'media', ...S, id: 'in-de-rede-vallen' });
  PH('Als ik daar even op mag inhaken', 'If I may pick up on that', 'Als ik daar even op mag inhaken: die cijfers zijn verouderd.', 'If I may pick up on that: those figures are outdated.', { theme: 'media', ...S, id: 'ph-inhaken' });
  PH('Daar ben ik het maar ten dele mee eens.', 'I only partly agree with that.', 'Daar ben ik het maar ten dele mee eens.', 'I only partly agree with that.', { theme: 'media', ...S, id: 'ph-ten-dele' });
  PH('U gaat voorbij aan …', 'You are ignoring …', 'U gaat voorbij aan de kosten voor ondernemers.', 'You are ignoring the costs for business owners.', { theme: 'media', ...S, id: 'ph-voorbijgaan-aan' });
  PH('Om kort te gaan', 'To cut a long story short', 'Om kort te gaan: het plan is onbetaalbaar.', 'To cut a long story short: the plan is unaffordable.', { theme: 'media', ...S, id: 'ph-om-kort-te-gaan' });
  W('ten dele', 'partly', 'adv', 'Dat klopt maar ten dele.', 'That is only partly true.', { theme: 'discourse', ...S, id: 'ten-dele' });
  W('verouderd', 'outdated', 'adj', 'Die cijfers zijn verouderd.', 'Those figures are outdated.', { theme: 'media', ...S });

  addTo('s4u1', lesson('s4u1l5', 'Listening: a radio debate (exam format)', 'You can follow a fast two-sided radio debate: identify each speaker’s position, catch concessions and disagreements, and answer exam-style questions about it.', [
    h('How a radio debate is built'),
    list('The `presentator` gives the `stelling` and introduces the `gasten`.', 'Each guest states a `standpunt`; listen for `voor` or `tegen` in the first sentence.', 'Then come the clashes: interruption, concession, rebuttal.', 'The presenter closes with a summary. If you lost the thread, this is your second chance.'),
    h('Signals to listen for'),
    table(['signal', 'tells you'], [['*Dat onderschrijf ik. / Precies.', 'agreement'], ['*Daar ben ik het maar ten dele mee eens.', 'partial agreement, a "but" follows'], ['*Dat bestrijd ik. / Dat klopt niet.', 'disagreement'], ['*Ik wil dat graag nuanceren.', 'a softer correction follows'], ['*U gaat voorbij aan …', 'accusation of ignoring something'], ['*Als ik daar even op mag inhaken …', 'polite interruption'], ['*Om kort te gaan … / Kortom …', 'the speaker’s conclusion']]),
    h('Exam strategy'),
    p('Read the questions first. They are asked in the order of the fragment and are **paraphrased**: the text says `onbetaalbaar`, the answer says `te duur`. Questions ask who holds which view, what a speaker concedes, and what the relation between the speakers is (`zijn het eens`, `oneens`, `deels eens`). Reductions are normal: `da’s`, `’t`, `eigenlijk` → "eigelijk".'),
    ex(['De stelling van vandaag: de binnenstad moet binnen vijf jaar autovrij zijn.', 'Today’s proposition: the city centre must be car-free within five years.'], ['Dat onderschrijf ik volledig, maar u gaat voorbij aan de bezorgers en de ouderen.', 'I fully endorse that, but you are ignoring delivery drivers and the elderly.'], ['Als ik daar even op mag inhaken: die cijfers over omzetverlies zijn verouderd.', 'If I may pick up on that: those figures about lost turnover are outdated.'], ['Om kort te gaan: we zijn het eens over het doel, maar niet over het tempo.', 'To cut a long story short: we agree on the goal, but not on the pace.']),
    tip('Play each dialogue below with the play button first, without reading. Then read the question. That is exactly the exam order.'),
  ], ['g4-listening', 'g4-discourse'], ['presentator', 'gast', 'stelling', 'luisteraar', 'deskundige', 'standpunt', 'nuanceren', 'bestrijden', 'onderschrijven', 'in-de-rede-vallen', 'ph-inhaken', 'ph-ten-dele', 'ph-voorbijgaan-aan', 'ph-om-kort-te-gaan', 'ten-dele', 'verouderd'], [
    listen('Welkom bij het debat. De stelling van vandaag: de binnenstad moet binnen vijf jaar autovrij zijn. Mijn gasten zijn wethouder De Boer en winkelier Van Dam.', ['The proposition is that the city centre must be car-free within five years; the guests are an alderman and a shopkeeper.', 'The guests are two shopkeepers who want more cars.', 'The debate is about public transport prices.'], 0, 'stelling; gasten.'),
    listen('Ik ben vóór. Minder auto’s betekent schonere lucht en meer ruimte, en uit onderzoek blijkt dat winkels daar juist van profiteren.', ['The speaker is in favour: cleaner air, more space, and research shows shops benefit.', 'The speaker is against because shops lose customers.', 'The speaker has no opinion.'], 0, 'Ik ben vóór; profiteren.'),
    listen('Daar ben ik het maar ten dele mee eens. Het doel onderschrijf ik, maar u gaat voorbij aan de bezorgers en aan klanten die slecht ter been zijn.', ['The speaker partly agrees: he endorses the goal but says delivery drivers and customers with reduced mobility are being ignored.', 'The speaker fully disagrees with the goal.', 'The speaker fully agrees and has nothing to add.'], 0, 'ten dele; onderschrijf; gaat voorbij aan.'),
    listen('Als ik daar even op mag inhaken: voor bezorgers komen er venstertijden, en voor mensen met een beperking blijft de binnenstad gewoon bereikbaar.', ['The alderman interrupts politely: there will be delivery time windows and access remains for people with a disability.', 'The alderman refuses any exceptions.', 'The alderman says delivery will be banned.'], 0, 'inhaken; venstertijden; bereikbaar.'),
    listen('Dat wil ik graag nuanceren. Venstertijden klinken mooi, maar die cijfers over omzet zijn verouderd en komen uit veel grotere steden.', ['The shopkeeper qualifies the claim: the turnover figures are outdated and come from much bigger cities.', 'The shopkeeper confirms the figures are recent.', 'The shopkeeper says time windows are illegal.'], 0, 'nuanceren; verouderd.'),
    listen('Om kort te gaan: u bent het eens over het doel, maar niet over het tempo en de uitzonderingen. Dank u beiden.', ['The presenter concludes: they agree on the goal but not on the pace and the exceptions.', 'The presenter concludes that they disagree on everything.', 'The presenter announces a vote.'], 0, 'Om kort te gaan; eens over het doel.'),
    mc('What is the relation between the two guests?', ['zij zijn het volledig eens', 'zij zijn het deels eens', 'zij zijn het volledig oneens'], 1, 'Agreed on the goal, not on pace and exceptions.'),
    mc('"Dat onderschrijf ik" signals', ['agreement', 'doubt', 'a question'], 0, 'onderschrijven = endorse.'),
    mc('"U gaat voorbij aan …" is', ['a compliment', 'an accusation of ignoring something', 'a request to leave'], 1, 'voorbijgaan aan.'),
    mc('The text says "onbetaalbaar". Which answer paraphrases it?', ['te duur', 'gratis', 'te langzaam'], 0, 'Exam answers paraphrase.'),
    fill('Daar ben ik het maar ten ___ mee eens.', ['dele'], 'I only partly agree with that.', 'ten dele.'),
    fill('Sorry dat ik u in de ___ val.', ['rede'], 'Sorry to interrupt you.', 'in de rede vallen.'),
    fill('Die cijfers zijn ___. (outdated)', ['verouderd'], 'Those figures are outdated.', 'verouderd.'),
    fill('Als ik daar even op mag ___: dat klopt niet.', ['inhaken'], 'If I may pick up on that: that is not right.', 'inhaken op.'),
    build('I would like to qualify that picture.', 'Ik wil dat beeld graag nuanceren.', ['nuanceert', 'die'], 'het beeld → dat; wil … nuanceren.'),
    build('The alderman disputes those figures.', 'De wethouder bestrijdt die cijfers.', ['bestrijd', 'dat'], 'stem + t; plural → die.'),
    tr('en-nl', 'I fully endorse that position.', ['Dat standpunt onderschrijf ik volledig.', 'Ik onderschrijf dat standpunt volledig.'], 'onderschrijven.'),
    tr('nl-en', 'We zijn het eens over het doel, maar niet over het tempo.', ['We agree on the goal, but not on the pace.'], 'het eens zijn over.'),
    dict('Het doel onderschrijf ik, maar u gaat voorbij aan de kosten voor ondernemers.', 'I endorse the goal, but you are ignoring the costs for business owners.', 'onderschrijf ik; gaat voorbij aan.'),
    speak('Daar ben ik het maar ten dele mee eens. Het doel onderschrijf ik, maar het tempo is te hoog.', 'I only partly agree with that. I endorse the goal, but the pace is too high.'),
    free('You are the third guest. React to both speakers in 45 seconds: endorse one point, qualify another, conclude.', 'Als ik daar even op mag inhaken. Wat de wethouder zegt over schonere lucht, onderschrijf ik volledig. De zorg van meneer Van Dam wil ik wel nuanceren: in vergelijkbare steden bleek het omzetverlies tijdelijk. Niettemin vind ik dat er een overgangsperiode moet komen. Om kort te gaan: ik ben voor, mits de uitzonderingen goed geregeld zijn.', 'If I may pick up on that. What the alderman says about cleaner air, I fully endorse. I do want to qualify Mr Van Dam’s concern: in comparable cities the loss of turnover proved temporary. Nevertheless I think there should be a transition period. To cut a long story short: I am in favour, provided the exceptions are well arranged.', { hints: ['Als ik daar even op mag inhaken', '… onderschrijf ik', '… wil ik nuanceren', 'Om kort te gaan: …'] }),
  ], [
    listen('Dat bestrijd ik. Uit de laatste cijfers blijkt juist dat het aantal bezoekers is toegenomen.', ['The speaker disputes it: the latest figures show that visitor numbers have increased.', 'The speaker agrees that visitor numbers fell.', 'The speaker has no figures.'], 0, 'bestrijd; toegenomen.'),
    listen('Luisteraars kunnen reageren via de app; na het nieuws gaan we verder met uw reacties.', ['Listeners can respond via the app; after the news they continue with the reactions.', 'The programme ends after the news.', 'Listeners cannot respond.'], 0, 'reageren via de app.'),
    mc('"Ik wil dat graag nuanceren" announces', ['full agreement', 'a softer correction', 'an insult'], 1, 'nuanceren.'),
    fill('Om ___ te gaan: het plan is onbetaalbaar.', ['kort'], 'To cut a long story short: the plan is unaffordable.', 'om kort te gaan.'),
    tr('en-nl', 'That is only partly true.', ['Dat klopt maar ten dele.', 'Dat is maar ten dele waar.'], 'ten dele.'),
    speak('Dat wil ik graag nuanceren: die cijfers zijn verouderd en komen uit veel grotere steden.', 'I would like to qualify that: those figures are outdated and come from much bigger cities.'),
  ]));

  /* ================= Unit 2, lesson 3: AI and ethics ================= */
  N('taalmodel', 'het', 'taalmodellen', 'language model', 'Een taalmodel voorspelt het volgende woord.', 'A language model predicts the next word.', { theme: 'technology', ...S });
  N('trainingsdata', 'de', 'trainingsdata', 'training data', 'De kwaliteit hangt af van de trainingsdata.', 'The quality depends on the training data.', { theme: 'technology', ...S, note: 'Plural.' });
  N('vooroordeel', 'het', 'vooroordelen', 'bias / prejudice', 'Vooroordelen in de data komen terug in de uitkomsten.', 'Biases in the data come back in the results.', { theme: 'technology', ...S });
  N('transparantie', 'de', null, 'transparency', 'Burgers hebben recht op transparantie over algoritmes.', 'Citizens have a right to transparency about algorithms.', { theme: 'technology', ...S });
  N('aansprakelijkheid', 'de', null, 'liability', 'Wie draagt de aansprakelijkheid als een algoritme een fout maakt?', 'Who bears liability when an algorithm makes a mistake?', { theme: 'technology', ...S });
  N('toezichthouder', 'de', 'toezichthouders', 'regulator', 'De toezichthouder legde een boete op.', 'The regulator imposed a fine.', { theme: 'technology', ...S });
  N('besluitvorming', 'de', null, 'decision-making', 'Geautomatiseerde besluitvorming raakt miljoenen mensen.', 'Automated decision-making affects millions of people.', { theme: 'technology', ...S });
  N('risico', 'het', "risico's", 'risk', 'De risico’s zijn onvoldoende in kaart gebracht.', 'The risks have been insufficiently mapped.', { theme: 'technology', ...S });
  N('afweging', 'de', 'afwegingen', 'trade-off / weighing up', 'Het is een afweging tussen gemak en privacy.', 'It is a trade-off between convenience and privacy.', { theme: 'technology', ...S });
  N('dilemma', 'het', "dilemma's", 'dilemma', 'Dat is een klassiek ethisch dilemma.', 'That is a classic ethical dilemma.', { theme: 'technology', ...S });
  VB('voorspellen', 'to predict', 'voorspel|voorspelt|voorspellen', 'voorspelde|voorspelden', 'voorspeld', 'hebben', 'Het systeem voorspelt wie fraude pleegt.', 'The system predicts who commits fraud.', { theme: 'technology', ...S });
  VB('discrimineren', 'to discriminate', 'discrimineer|discrimineert|discrimineren', 'discrimineerde|discrimineerden', 'gediscrimineerd', 'hebben', 'Het algoritme bleek te discrimineren op nationaliteit.', 'The algorithm turned out to discriminate on nationality.', { theme: 'technology', ...S });
  VB('reguleren', 'to regulate', 'reguleer|reguleert|reguleren', 'reguleerde|reguleerden', 'gereguleerd', 'hebben', 'De EU wil kunstmatige intelligentie reguleren.', 'The EU wants to regulate artificial intelligence.', { theme: 'technology', ...S });
  VB('verantwoorden', 'to account for / justify', 'verantwoord|verantwoordt|verantwoorden', 'verantwoordde|verantwoordden', 'verantwoord', 'hebben', 'Een overheid moet haar besluiten kunnen verantwoorden.', 'A government must be able to account for its decisions.', { theme: 'technology', ...S });
  VB('in kaart brengen', 'to map out', 'breng in kaart|brengt in kaart|brengen in kaart', 'bracht in kaart|brachten in kaart', 'in kaart gebracht', 'hebben', 'De risico’s moeten eerst in kaart worden gebracht.', 'The risks must first be mapped out.', { theme: 'technology', ...S, id: 'in-kaart-brengen' });
  W('ethisch', 'ethical', 'adj', 'Is dat ethisch verantwoord?', 'Is that ethically responsible?', { theme: 'technology', ...S });
  W('onvermijdelijk', 'inevitable', 'adj', 'Fouten zijn onvermijdelijk.', 'Mistakes are inevitable.', { theme: 'technology', ...S });
  W('in hoeverre', 'to what extent', 'adv', 'In hoeverre mag een computer over mensen beslissen?', 'To what extent may a computer decide about people?', { theme: 'discourse', ...S, id: 'in-hoeverre' });

  addTo('s4u2', lesson('s4u2l3', 'AI and ethics: weighing risks in formal Dutch', 'You can discuss the ethics of algorithms and AI in formal Dutch: risks, liability, transparency and regulation, using nominal style and hedged claims.', [
    h('Why this is a Dutch topic'),
    p('In the `toeslagenaffaire` thousands of parents were wrongly labelled as fraudsters, partly by a risk model that used nationality. It made `algoritmes`, `transparantie` and `aansprakelijkheid` household words, and it is a likely exam topic.'),
    h('The vocabulary of weighing up'),
    table(['Dutch', 'English'], [['*een afweging maken tussen … en …', 'to weigh … against …'], ['*de risico’s in kaart brengen', 'to map out the risks'], ['*In hoeverre …?', 'To what extent …?'], ['*Het is de vraag of …', 'It is questionable whether …'], ['*verantwoording afleggen over', 'to be accountable for'], ['*menselijke tussenkomst', 'human intervention'], ['*onvermijdelijk / wenselijk / verantwoord', 'inevitable / desirable / responsible']]),
    h('Hedging your claims'),
    p('Formal argument avoids absolutes: `Het lijkt erop dat …`, `Het is aannemelijk dat …` (it is plausible that), `Dat hoeft niet te betekenen dat …`, `vermoedelijk`, `in veel gevallen`, `tot op zekere hoogte` (to a certain extent). A claim with a hedge is harder to refute.'),
    h('Nominal style in action'),
    p('`Geautomatiseerde **besluitvorming** zonder menselijke **tussenkomst** vergroot het **risico** op **discriminatie**.` Unpacked: if computers decide without a human checking, people are more likely to be discriminated against.'),
    ex(['In hoeverre mag een overheid beslissingen over burgers aan een algoritme overlaten?', 'To what extent may a government leave decisions about citizens to an algorithm?'], ['Vooroordelen in de trainingsdata komen onvermijdelijk terug in de uitkomsten.', 'Biases in the training data inevitably come back in the results.'], ['Het is de vraag of transparantie alleen voldoende is; iemand moet ook aansprakelijk zijn.', 'It is questionable whether transparency alone is sufficient; someone must also be liable.'], ['De toezichthouder eist dat de risico’s vooraf in kaart worden gebracht.', 'The regulator requires that the risks be mapped out in advance.']),
    tip('`In hoeverre` is the most useful opening for a B2 discussion question. It forces a nuanced answer instead of yes or no.'),
  ], ['g4-nominalisation', 'g4-argument'], ['taalmodel', 'trainingsdata', 'vooroordeel', 'transparantie', 'aansprakelijkheid', 'toezichthouder', 'besluitvorming', 'risico', 'afweging', 'dilemma', 'voorspellen', 'discrimineren', 'reguleren', 'verantwoorden', 'in-kaart-brengen', 'ethisch', 'onvermijdelijk', 'in-hoeverre'], [
    mc('"In hoeverre" asks for', ['a yes or no', 'a degree: to what extent', 'a place'], 1, 'To what extent.'),
    mc('"De risico’s in kaart brengen" means', ['to draw a map', 'to map out the risks', 'to hide the risks'], 1, 'in kaart brengen.'),
    mc('"Het is aannemelijk dat …" means', ['it is certain that', 'it is plausible that', 'it is impossible that'], 1, 'Hedge.'),
    mc('Which noun hides the verb "besluiten"?', ['besluitvorming', 'aansprakelijkheid', 'transparantie'], 0, 'besluit + vorming.'),
    mc('In the toeslagenaffaire, the risk model wrongly used', ['income', 'nationality', 'age'], 1, 'Nationality as a risk factor.'),
    art('risico', 'het', 'het risico.'),
    art('dilemma', 'het', 'het dilemma.'),
    art('aansprakelijkheid', 'de', '-heid → de.'),
    art('taalmodel', 'het', 'het model.'),
    fill('Het is een ___ tussen gemak en privacy. (trade-off)', ['afweging'], 'It is a trade-off between convenience and privacy.', 'afweging.'),
    fill('De risico’s moeten eerst in ___ worden gebracht.', ['kaart'], 'The risks must first be mapped out.', 'in kaart brengen.'),
    fill('Fouten zijn ___. (inevitable)', ['onvermijdelijk'], 'Mistakes are inevitable.', 'on + vermijd + elijk.'),
    fill('Een overheid moet haar besluiten kunnen ___. (account for)', ['verantwoorden'], 'A government must be able to account for its decisions.', 'verantwoorden.'),
    build('Who bears liability when an algorithm makes a mistake?', 'Wie draagt de aansprakelijkheid als een algoritme een fout maakt?', ['maakt een fout', 'dragen'], 'als … maakt at the end.'),
    build('The EU wants to regulate artificial intelligence.', 'De EU wil kunstmatige intelligentie reguleren.', ['reguleert', 'kunstmatig'], 'wil … reguleren.'),
    build('The algorithm turned out to discriminate.', 'Het algoritme bleek te discrimineren.', ['discrimineert', 'blijkt te'], 'blijken + te; past: bleek.'),
    tr('en-nl', 'Is that ethically responsible?', ['Is dat ethisch verantwoord?'], 'ethisch verantwoord.'),
    tr('nl-en', 'Het is de vraag of transparantie alleen voldoende is.', ['It is questionable whether transparency alone is sufficient.', 'The question is whether transparency alone is enough.'], 'het is de vraag of.'),
    fix('De risico’s zijn onvoldoende in kaart gebrengd.', ['De risico’s zijn onvoldoende in kaart gebracht.'], 'brengen → gebracht.'),
    dict('Vooroordelen in de trainingsdata komen onvermijdelijk terug in de uitkomsten.', 'Biases in the training data inevitably come back in the results.', 'komen … terug.'),
    listen('De toezichthouder eist dat er altijd een mens meekijkt voordat een besluit over een burger wordt genomen.', ['The regulator requires that a human always checks before a decision about a citizen is taken.', 'The regulator bans all algorithms.', 'Citizens must check the algorithm themselves.'], 0, 'eist dat … meekijkt; voordat … wordt genomen.'),
    speak('In hoeverre mag een overheid beslissingen over burgers aan een algoritme overlaten?', 'To what extent may a government leave decisions about citizens to an algorithm?'),
    read('Algoritmes worden door overheden steeds vaker ingezet om fraude op te sporen. Dat is begrijpelijk: ze zijn snel, goedkoop en worden niet moe. Het probleem is dat een model leert van gegevens uit het verleden, en dat daarin bestaande vooroordelen zitten. Wie vaker werd gecontroleerd, werd vaker betrapt, en wordt dus door het model opnieuw als risico aangemerkt. Zo ontstaat een cirkel die van buitenaf nauwelijks te doorbreken is, zeker als niet duidelijk is op grond waarvan iemand is geselecteerd. Transparantie is daarom een noodzakelijke, maar geen voldoende voorwaarde: er moet ook iemand zijn die het besluit kan uitleggen en die erop kan worden aangesproken.', [
      { q: 'Waarom zetten overheden algoritmes in?', options: ['ze zijn snel en goedkoop', 'ze zijn altijd eerlijk', 'de wet verplicht het'], answer: 0, explain: '"snel, goedkoop en worden niet moe".' },
      { q: 'Welke "cirkel" beschrijft de tekst?', options: ['wie vaker gecontroleerd werd, wordt opnieuw als risico aangemerkt', 'fraudeurs worden steeds slimmer', 'algoritmes worden steeds duurder'], answer: 0, explain: 'Past checks produce the data that trigger new checks.' },
      { q: 'Wat bedoelt de schrijver met "een noodzakelijke, maar geen voldoende voorwaarde"?', options: ['transparantie is overbodig', 'transparantie is nodig, maar niet genoeg', 'transparantie lost alles op'], answer: 1, explain: 'Necessary but not sufficient: accountability is needed too.' },
    ], { en: 'Algorithms are increasingly used by governments to detect fraud. That is understandable: they are fast, cheap and do not get tired. The problem is that a model learns from past data, and that existing biases are in it. Whoever was checked more often was caught more often, and is therefore flagged as a risk again by the model. Thus a circle arises that can hardly be broken from outside, certainly when it is unclear on what grounds someone was selected. Transparency is therefore a necessary, but not a sufficient condition: there must also be someone who can explain the decision and who can be held to account for it.' }),
    free('Exam-style speaking task (60 seconds): "Mag een gemeente een algoritme gebruiken om bijstandsfraude op te sporen?" Weigh up and conclude with a condition.', 'Het is een afweging tussen efficiëntie en rechtsbescherming. Enerzijds kan een algoritme veel sneller patronen herkennen dan een ambtenaar. Anderzijds zitten er in de trainingsdata vaak vooroordelen, waardoor bepaalde groepen onterecht als risico worden aangemerkt. Ik vind dat het mag, mits de risico’s vooraf in kaart zijn gebracht, de selectiecriteria openbaar zijn, en een mens elk besluit controleert en kan verantwoorden.', 'It is a trade-off between efficiency and legal protection. On the one hand an algorithm can recognise patterns much faster than an official. On the other hand there are often biases in the training data, as a result of which certain groups are wrongly flagged as a risk. I think it is allowed, provided the risks have been mapped out beforehand, the selection criteria are public, and a human checks and can account for every decision.', { hints: ['Het is een afweging tussen … en …', 'Enerzijds … Anderzijds …', 'Ik vind dat het mag, mits …'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('"Tot op zekere hoogte" means', ['up to a certain height', 'to a certain extent'], 1, 'Hedge.'),
    fill('Wie draagt de ___ als het misgaat? (liability)', ['aansprakelijkheid'], 'Who bears liability when it goes wrong?', 'aansprakelijkheid.'),
    fill('___ hoeverre is dat wenselijk?', ['In'], 'To what extent is that desirable?', 'in hoeverre.'),
    build('That is a classic ethical dilemma.', 'Dat is een klassiek ethisch dilemma.', ['klassieke', 'ethische'], 'het dilemma + een → no -e.'),
    tr('en-nl', 'The regulator imposed a fine.', ['De toezichthouder legde een boete op.', 'De toezichthouder heeft een boete opgelegd.'], 'een boete opleggen.'),
    speak('Transparantie is een noodzakelijke, maar geen voldoende voorwaarde; iemand moet het besluit ook kunnen verantwoorden.', 'Transparency is a necessary but not a sufficient condition; someone must also be able to account for the decision.'),
  ]));

  /* ================= Unit 2, lesson 4: health research in the news ================= */
  N('studie', 'de', 'studies', 'study', 'De studie werd gepubliceerd in een medisch tijdschrift.', 'The study was published in a medical journal.', { theme: 'science', ...S });
  N('deelnemer', 'de', 'deelnemers', 'participant', 'Er deden achtduizend deelnemers mee.', 'Eight thousand participants took part.', { theme: 'science', ...S });
  N('controlegroep', 'de', 'controlegroepen', 'control group', 'De controlegroep kreeg een placebo.', 'The control group received a placebo.', { theme: 'science', ...S });
  N('oorzakelijk verband', 'het', null, 'causal link', 'Een oorzakelijk verband is niet aangetoond.', 'A causal link has not been demonstrated.', { theme: 'science', ...S, id: 'oorzakelijk-verband' });
  N('samenhang', 'de', null, 'correlation / association', 'Er is een samenhang tussen slaap en gewicht.', 'There is an association between sleep and weight.', { theme: 'science', ...S });
  N('risicofactor', 'de', 'risicofactoren', 'risk factor', 'Roken is de belangrijkste risicofactor.', 'Smoking is the most important risk factor.', { theme: 'science', ...S });
  N('kans', 'de', 'kansen', 'chance / probability', 'De kans op hartziekten neemt met een kwart af.', 'The chance of heart disease decreases by a quarter.', { theme: 'science', ...S });
  N('bevinding', 'de', 'bevindingen', 'finding', 'De bevindingen moeten nog worden bevestigd.', 'The findings still have to be confirmed.', { theme: 'science', ...S });
  N('kanttekening', 'de', 'kanttekeningen', 'caveat', 'De onderzoekers plaatsen zelf een kanttekening.', 'The researchers themselves add a caveat.', { theme: 'science', ...S });
  N('belangenverstrengeling', 'de', null, 'conflict of interest', 'Het onderzoek werd betaald door de industrie; er is dus mogelijk belangenverstrengeling.', 'The research was paid for by industry; so there is possibly a conflict of interest.', { theme: 'science', ...S });
  VB('samenhangen met', 'to be associated with', 'hang samen met|hangt samen met|hangen samen met', 'hing samen met|hingen samen met', 'samengehangen met', 'hebben', 'Weinig slaap hangt samen met overgewicht.', 'Little sleep is associated with being overweight.', { theme: 'science', ...S, id: 'samenhangen-met' });
  VB('verlagen', 'to lower', 'verlaag|verlaagt|verlagen', 'verlaagde|verlaagden', 'verlaagd', 'hebben', 'Bewegen verlaagt de kans op diabetes.', 'Exercise lowers the chance of diabetes.', { theme: 'science', ...S });
  VB('verhogen', 'to raise', 'verhoog|verhoogt|verhogen', 'verhoogde|verhoogden', 'verhoogd', 'hebben', 'Bewerkt vlees verhoogt het risico op darmkanker.', 'Processed meat raises the risk of bowel cancer.', { theme: 'science', ...S });
  VB('suggereren', 'to suggest', 'suggereer|suggereert|suggereren', 'suggereerde|suggereerden', 'gesuggereerd', 'hebben', 'De kop suggereert meer dan het onderzoek aantoont.', 'The headline suggests more than the research demonstrates.', { theme: 'science', ...S });
  VB('overschatten', 'to overestimate', 'overschat|overschat|overschatten', 'overschatte|overschatten', 'overschat', 'hebben', 'Het effect wordt in de media vaak overschat.', 'The effect is often overestimated in the media.', { theme: 'science', ...S });
  W('observationeel', 'observational', 'adj', 'Het ging om een observationele studie.', 'It was an observational study.', { theme: 'science', ...S });
  W('relatief', 'relative', 'adj', 'Een relatieve daling van 25 procent klinkt groter dan ze is.', 'A relative fall of 25 per cent sounds bigger than it is.', { theme: 'science', ...S });
  W('absoluut', 'absolute', 'adj', 'In absolute cijfers gaat het om één op de duizend.', 'In absolute figures it concerns one in a thousand.', { theme: 'science', ...S });
  W('voorzichtig', 'cautious', 'adj', 'De onderzoekers zijn voorzichtig met conclusies.', 'The researchers are cautious with conclusions.', { theme: 'science', ...S });

  addTo('s4u2', lesson('s4u2l4', 'Health research in the news: reading between the hedges', 'You can read a news report about a medical study critically: tell association from cause, relative from absolute risk, and headline from finding.', [
    h('Five questions for every health headline'),
    list('**Wie?** How many `deelnemers`, and who were they?', '**Hoe?** `Observationeel` (people were only observed) or with a `controlegroep`? Only the second can show cause.', '**Samenhang of oorzaak?** `hangt samen met` is not `veroorzaakt`.', '**Relatief of absoluut?** "25 procent minder kans" may mean from 4 to 3 in a thousand.', '**Wie betaalde?** Possible `belangenverstrengeling`.'),
    h('The hedges journalists use'),
    table(['Dutch', 'strength'], [['*toont aan dat', 'demonstrates (strong)'], ['*wijst erop dat', 'indicates'], ['*suggereert dat', 'suggests'], ['*hangt samen met', 'is associated with (no cause)'], ['*zou kunnen', 'could'], ['*mogelijk / vermoedelijk', 'possibly / presumably'], ['*de onderzoekers plaatsen een kanttekening', 'the researchers add a caveat']]),
    h('Passive in all tenses, again'),
    p('`De studie **werd uitgevoerd** onder 8.000 deelnemers.` `De bevindingen **moeten** nog **worden bevestigd**.` `Er **kon** geen oorzakelijk verband **worden aangetoond**.` `Het effect **wordt** vaak **overschat**.`'),
    ex(['Koffiedrinkers leven langer, kopte de krant, maar de studie toont alleen een samenhang aan.', 'Coffee drinkers live longer, the newspaper headlined, but the study only demonstrates an association.'], ['Omdat het een observationele studie was, kon geen oorzakelijk verband worden aangetoond.', 'Because it was an observational study, no causal link could be demonstrated.'], ['De kans daalt met een kwart, maar in absolute cijfers gaat het om één op de duizend mensen.', 'The chance falls by a quarter, but in absolute figures it concerns one in a thousand people.'], ['De onderzoekers plaatsen zelf een kanttekening: de deelnemers waren gemiddeld hoogopgeleid.', 'The researchers themselves add a caveat: the participants were on average highly educated.']),
    tip('Exam questions about such texts almost always test the hedge: "Welke bewering volgt uit de tekst?" The answer with `veroorzaakt` is usually the wrong one.'),
  ], ['g4-reading', 'g4-passive-all'], ['studie', 'deelnemer', 'controlegroep', 'oorzakelijk-verband', 'samenhang', 'risicofactor', 'kans', 'bevinding', 'kanttekening', 'belangenverstrengeling', 'samenhangen-met', 'verlagen', 'verhogen', 'suggereren', 'overschatten', 'observationeel', 'relatief', 'absoluut', 'voorzichtig'], [
    mc('"Weinig slaap hangt samen met overgewicht" means', ['little sleep causes overweight', 'little sleep and overweight occur together', 'overweight people sleep more'], 1, 'Association, not cause.'),
    mc('Which study design can show cause?', ['an observational study', 'a study with a control group', 'a survey'], 1, 'Controlegroep.'),
    mc('"25 procent minder kans" is a', ['relative figure', 'absolute figure', 'caveat'], 0, 'Relative.'),
    mc('Which verb makes the strongest claim?', ['suggereert', 'wijst erop', 'toont aan'], 2, 'aantonen = demonstrate.'),
    mc('"Belangenverstrengeling" means', ['shared interests', 'conflict of interest', 'a complicated study'], 1, 'Conflict of interest.'),
    mc('Er kon geen oorzakelijk verband ___.', ['worden aangetoond', 'aantonen worden', 'aangetoond hebben'], 0, 'kon … worden aangetoond.'),
    art('oorzakelijk verband', 'het', 'het verband.'),
    art('kans', 'de', 'de kans.'),
    art('bevinding', 'de', '-ing → de.'),
    fill('De bevindingen moeten nog worden ___. (bevestigen)', ['bevestigd'], 'The findings still have to be confirmed.', 'be- verb: bevestigd.'),
    fill('Bewegen ___ de kans op diabetes. (lowers)', ['verlaagt'], 'Exercise lowers the chance of diabetes.', 'verlaagt.'),
    fill('Het effect wordt in de media vaak ___. (overestimated)', ['overschat'], 'The effect is often overestimated in the media.', 'overschat.'),
    fill('De onderzoekers plaatsen zelf een ___. (caveat)', ['kanttekening'], 'The researchers themselves add a caveat.', 'kanttekening.'),
    build('The study only demonstrates an association.', 'De studie toont alleen een samenhang aan.', ['aantoont', 'de samenhang een'], 'toont … aan.'),
    build('In absolute figures it concerns one in a thousand.', 'In absolute cijfers gaat het om één op de duizend.', ['het gaat', 'van'], 'Inversion; gaan om; één op de duizend.'),
    build('The headline suggests more than the research demonstrates.', 'De kop suggereert meer dan het onderzoek aantoont.', ['toont aan', 'als'], 'dan … aantoont (verb at the end, one word).'),
    tr('en-nl', 'Smoking is the most important risk factor.', ['Roken is de belangrijkste risicofactor.'], 'risicofactor.'),
    tr('nl-en', 'Omdat het een observationele studie was, kon geen oorzakelijk verband worden aangetoond.', ['Because it was an observational study, no causal link could be demonstrated.'], 'kon … worden aangetoond.'),
    fix('Uit de studie blijkt dat koffie langer leven veroorzaakt; er is namelijk een samenhang.', ['Uit de studie blijkt alleen een samenhang tussen koffie en langer leven.', 'De studie toont alleen een samenhang aan, geen oorzakelijk verband.'], 'Association is not cause.'),
    dict('De kans daalt met een kwart, maar in absolute cijfers is het effect klein.', 'The chance falls by a quarter, but in absolute figures the effect is small.', 'daalt met; absolute cijfers.'),
    listen('De onderzoekers zijn voorzichtig: het zou kunnen dat gezonde mensen simpelweg vaker wandelen.', ['The researchers are cautious: it could be that healthy people simply walk more often.', 'The researchers are certain that walking makes you healthy.', 'Healthy people never walk.'], 0, 'voorzichtig; zou kunnen.'),
    speak('De studie toont alleen een samenhang aan; een oorzakelijk verband kon niet worden aangetoond.', 'The study only demonstrates an association; a causal link could not be demonstrated.'),
    read('"Dagelijks handje noten verlaagt kans op hartziekten met 20 procent", kopte een nieuwssite vorige week. Het bericht was gebaseerd op een studie waarin ruim 80.000 mensen twaalf jaar lang werden gevolgd. Wie dagelijks noten at, kreeg inderdaad minder vaak een hartziekte. De onderzoekers plaatsen daar echter zelf een kanttekening bij: notenliefhebbers rookten minder, bewogen meer en waren gemiddeld hoger opgeleid. Hoewel voor die factoren is gecorrigeerd, kan niet worden uitgesloten dat andere, niet gemeten verschillen een rol spelen. Bovendien gaat het om een relatieve daling: in absolute cijfers daalde het risico van vijf naar vier op de honderd. Ten slotte werd het onderzoek deels gefinancierd door een brancheorganisatie van notentelers, wat de onafhankelijkheid niet ten goede komt.', [
      { q: 'Welke bewering volgt uit de tekst?', options: ['Noten eten voorkomt hartziekten.', 'Notenliefhebbers kregen minder vaak een hartziekte, maar de oorzaak staat niet vast.', 'Noten zijn ongezond.'], answer: 1, explain: 'Association with several caveats.' },
      { q: 'Wat betekent de daling in absolute cijfers?', options: ['van 20 naar 0 procent', 'van vijf naar vier op de honderd', 'van 80.000 naar 60.000'], answer: 1, explain: '"van vijf naar vier op de honderd".' },
      { q: 'Waarom noemt de schrijver de financiering?', options: ['om het onderzoek te prijzen', 'omdat er mogelijk belangenverstrengeling is', 'omdat noten duur zijn'], answer: 1, explain: '"wat de onafhankelijkheid niet ten goede komt".' },
      { q: 'Wat is het doel van de schrijver?', options: ['lezers aansporen meer noten te eten', 'laten zien hoe je zo’n bericht kritisch leest', 'de onderzoekers beschuldigen van fraude'], answer: 1, explain: 'The text models critical reading.' },
    ], { en: '"A daily handful of nuts lowers the chance of heart disease by 20 per cent", a news site headlined last week. The report was based on a study in which over 80,000 people were followed for twelve years. Those who ate nuts daily did indeed get heart disease less often. The researchers themselves, however, add a caveat: nut lovers smoked less, exercised more and were on average more highly educated. Although those factors were corrected for, it cannot be ruled out that other, unmeasured differences play a role. Moreover it is a relative fall: in absolute figures the risk fell from five to four in a hundred. Finally the research was partly funded by a trade organisation of nut growers, which does not benefit its independence.' }),
    free('Explain to a friend in everyday Dutch why a headline like "Koffiedrinkers leven langer" does not prove that coffee is healthy.', 'Zo’n onderzoek kijkt alleen naar mensen die zelf al koffie drinken. Misschien hebben koffiedrinkers gewoon vaker een baan of meer vrienden, en leven ze daardoor langer. Er is dus een samenhang, maar geen bewijs dat koffie de oorzaak is. Daarvoor heb je een controlegroep nodig.', 'Such a study only looks at people who already drink coffee themselves. Maybe coffee drinkers simply more often have a job or more friends, and live longer because of that. So there is an association, but no proof that coffee is the cause. For that you need a control group.', { hints: ['Zo’n onderzoek kijkt alleen naar …', 'Er is een samenhang, maar geen bewijs dat …', 'Daarvoor heb je … nodig'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('"Een observationele studie" can show', ['cause', 'association only'], 1, 'Association only.'),
    fill('Weinig slaap hangt ___ met overgewicht.', ['samen'], 'Little sleep is associated with being overweight.', 'samenhangen met.'),
    fill('De controlegroep ___ een placebo. (krijgen, past)', ['kreeg'], 'The control group received a placebo.', 'krijgen → kreeg.'),
    build('The researchers are cautious with conclusions.', 'De onderzoekers zijn voorzichtig met conclusies.', ['voorzichtige', 'over'], 'voorzichtig met.'),
    tr('en-nl', 'The findings still have to be confirmed.', ['De bevindingen moeten nog worden bevestigd.', 'De bevindingen moeten nog bevestigd worden.'], 'moeten worden bevestigd.'),
    speak('Het gaat om een relatieve daling; in absolute cijfers is het effect veel kleiner.', 'It is a relative fall; in absolute figures the effect is much smaller.'),
  ]));

  /* ================= Unit 2, lesson 5: summarising an academic text ================= */
  N('onderzoeksvraag', 'de', 'onderzoeksvragen', 'research question', 'De onderzoeksvraag staat in de inleiding.', 'The research question is in the introduction.', { theme: 'academic', ...S });
  N('methode', 'de', 'methoden', 'method', 'De methode wordt in hoofdstuk twee beschreven.', 'The method is described in chapter two.', { theme: 'academic', ...S });
  N('aanleiding', 'de', 'aanleidingen', 'reason / occasion', 'De aanleiding voor het onderzoek was de stijging van het ziekteverzuim.', 'The reason for the research was the rise in sick leave.', { theme: 'academic', ...S });
  N('beperking', 'de', 'beperkingen', 'limitation', 'Een beperking is de kleine steekproef.', 'A limitation is the small sample.', { theme: 'academic', ...S });
  N('vervolgonderzoek', 'het', null, 'follow-up research', 'De auteurs bevelen vervolgonderzoek aan.', 'The authors recommend follow-up research.', { theme: 'academic', ...S });
  N('verklaring', 'de', 'verklaringen', 'explanation', 'Een mogelijke verklaring is de hogere werkdruk.', 'A possible explanation is the higher workload.', { theme: 'academic', ...S });
  N('begrip', 'het', 'begrippen', 'concept / term', 'De auteurs definiëren eerst het begrip werkdruk.', 'The authors first define the concept of workload.', { theme: 'academic', ...S });
  N('literatuur', 'de', null, 'literature', 'Dit sluit aan bij eerdere literatuur.', 'This is in line with earlier literature.', { theme: 'academic', ...S });
  VB('concluderen', 'to conclude', 'concludeer|concludeert|concluderen', 'concludeerde|concludeerden', 'geconcludeerd', 'hebben', 'De auteurs concluderen dat thuiswerken het verzuim verlaagt.', 'The authors conclude that working from home lowers absence.', { theme: 'academic', ...S });
  VB('aanbevelen', 'to recommend', 'beveel aan|beveelt aan|bevelen aan', 'beval aan|bevalen aan', 'aanbevolen', 'hebben', 'Zij bevelen aan het beleid aan te passen.', 'They recommend adjusting the policy.', { theme: 'academic', ...S });
  VB('definiëren', 'to define', 'definieer|definieert|definiëren', 'definieerde|definieerden', 'gedefinieerd', 'hebben', 'Hoe wordt "werkdruk" gedefinieerd?', 'How is "workload" defined?', { theme: 'academic', ...S, id: 'definieren' });
  VB('verklaren', 'to explain / account for', 'verklaar|verklaart|verklaren', 'verklaarde|verklaarden', 'verklaard', 'hebben', 'Dit verschil kan niet door toeval worden verklaard.', 'This difference cannot be explained by chance.', { theme: 'academic', ...S });
  VB('aansluiten bij', 'to be in line with', 'sluit aan bij|sluit aan bij|sluiten aan bij', 'sloot aan bij|sloten aan bij', 'aangesloten bij', 'hebben', 'De resultaten sluiten aan bij eerder onderzoek.', 'The results are in line with earlier research.', { theme: 'academic', ...S, id: 'aansluiten-bij' });
  VB('parafraseren', 'to paraphrase', 'parafraseer|parafraseert|parafraseren', 'parafraseerde|parafraseerden', 'geparafraseerd', 'hebben', 'Parafraseer; kopieer geen zinnen.', 'Paraphrase; do not copy sentences.', { theme: 'academic', ...S });
  PH('De auteurs gaan na of …', 'The authors examine whether …', 'De auteurs gaan na of thuiswerken samenhangt met minder verzuim.', 'The authors examine whether working from home is associated with less absence.', { theme: 'academic', ...S, id: 'ph-gaan-na-of' });
  PH('Uit de resultaten komt naar voren dat …', 'The results show that …', 'Uit de resultaten komt naar voren dat het verzuim met een derde daalde.', 'The results show that absence fell by a third.', { theme: 'academic', ...S, id: 'ph-komt-naar-voren' });
  PH('Als beperking noemen zij …', 'As a limitation they mention …', 'Als beperking noemen zij de korte looptijd.', 'As a limitation they mention the short duration.', { theme: 'academic', ...S, id: 'ph-als-beperking' });
  W('beknopt', 'concise', 'adj', 'Een samenvatting moet beknopt en neutraal zijn.', 'A summary must be concise and neutral.', { theme: 'academic', ...S });

  addTo('s4u2', lesson('s4u2l5', 'Writing a summary of an academic text', 'You can summarise a research article or report in about 120 words: question, method, results, conclusion and limitations, neutrally and in your own words.', [
    h('The fixed skeleton'),
    table(['part', 'frame'], [['aanleiding', '*Aanleiding voor het onderzoek was …'], ['vraag', '*De auteurs gaan na of … / De onderzoeksvraag luidt: …'], ['methode', '*Daartoe werden … ondervraagd / gevolgd / vergeleken.'], ['resultaten', '*Uit de resultaten komt naar voren dat … / Het blijkt dat …'], ['verklaring', '*Een mogelijke verklaring is dat …'], ['conclusie', '*De auteurs concluderen dat …'], ['beperkingen', '*Als beperking noemen zij … / Vervolgonderzoek wordt aanbevolen.']]),
    h('Rules of the genre'),
    list('**Neutral**: `de auteurs`, never `ik vind`.', '**Present tense** for what the text says (`de auteurs concluderen`), **past** for what was done (`werden ondervraagd`).', '**Paraphrase**: change the structure, not just the words. Nominal → verbal is the easiest move.', '**Keep the hedges**: if the text says `wijst erop`, do not write `bewijst`.', '**Beknopt**: no examples, no figures beyond the one key number.'),
    h('Paraphrasing by unpacking nouns'),
    p('Source: `De invoering van hybride werken ging gepaard met een afname van het kortdurend verzuim.` Summary: `Nadat hybride werken was ingevoerd, meldden werknemers zich minder vaak kort ziek.` Same content, different structure: that is paraphrase.'),
    ex(['Aanleiding voor het onderzoek was de sterke stijging van het ziekteverzuim na 2020.', 'The reason for the research was the sharp rise in sick leave after 2020.'], ['De auteurs gaan na of thuiswerken samenhangt met minder kortdurend verzuim; daartoe werden gegevens van veertig bedrijven vergeleken.', 'The authors examine whether working from home is associated with less short-term absence; for that purpose data from forty companies were compared.'], ['Uit de resultaten komt naar voren dat het verzuim met een derde daalde, al verschilt het effect sterk per sector.', 'The results show that absence fell by a third, although the effect differs strongly per sector.'], ['Als beperking noemen zij de korte looptijd; vervolgonderzoek wordt aanbevolen.', 'As a limitation they mention the short duration; follow-up research is recommended.']),
    tip('Write the skeleton words first (Aanleiding … De auteurs gaan na of … Daartoe … Uit de resultaten … De auteurs concluderen … Als beperking …), then fill each with one sentence.'),
  ], ['g4-nominalisation', 'g4-reading'], ['onderzoeksvraag', 'methode', 'aanleiding', 'beperking', 'vervolgonderzoek', 'verklaring', 'begrip', 'literatuur', 'concluderen', 'aanbevelen', 'definieren', 'verklaren', 'aansluiten-bij', 'parafraseren', 'ph-gaan-na-of', 'ph-komt-naar-voren', 'ph-als-beperking', 'beknopt'], [
    mc('Which tense reports what the authors say?', ['present: de auteurs concluderen', 'pluperfect', 'future'], 0, 'Present for the text, past for what was done.'),
    mc('The source says "wijst erop dat". Your summary should say', ['bewijst dat', 'wijst erop dat / suggereert dat', 'ontkent dat'], 1, 'Keep the hedge.'),
    mc('Which belongs in an academic summary?', ['your opinion of the study', 'the research question and the main result', 'all the figures'], 1, 'Question, method, result, conclusion, limitation.'),
    mc('"Daartoe werden veertig bedrijven vergeleken." "Daartoe" means', ['because of that', 'for that purpose', 'after that'], 1, 'daartoe = to that end.'),
    mc('Good paraphrase changes', ['only a few words', 'the structure of the sentence', 'the meaning'], 1, 'Structure, not meaning.'),
    art('begrip', 'het', 'het begrip.'),
    art('vervolgonderzoek', 'het', 'het onderzoek.'),
    art('methode', 'de', 'de methode.'),
    fill('De auteurs gaan ___ of thuiswerken samenhangt met minder verzuim.', ['na'], 'The authors examine whether working from home is associated with less absence.', 'nagaan of.'),
    fill('Uit de resultaten komt naar ___ dat het verzuim daalde.', ['voren'], 'The results show that absence fell.', 'naar voren komen.'),
    fill('Als ___ noemen zij de kleine steekproef. (limitation)', ['beperking'], 'As a limitation they mention the small sample.', 'beperking.'),
    fill('Vervolgonderzoek wordt ___. (aanbevelen)', ['aanbevolen'], 'Follow-up research is recommended.', 'aanbevelen → aanbevolen.'),
    fill('Een samenvatting moet ___ en neutraal zijn. (concise)', ['beknopt'], 'A summary must be concise and neutral.', 'beknopt.'),
    build('The authors conclude that working from home lowers absence.', 'De auteurs concluderen dat thuiswerken het verzuim verlaagt.', ['verlaagt het verzuim', 'concludeert'], 'dat … verlaagt.'),
    build('A possible explanation is the higher workload.', 'Een mogelijke verklaring is de hogere werkdruk.', ['mogelijk', 'hoger'], 'de verklaring → mogelijke; de werkdruk → hogere.'),
    build('The results are in line with earlier research.', 'De resultaten sluiten aan bij eerder onderzoek.', ['aansluiten', 'met'], 'sluiten aan bij.'),
    tr('en-nl', 'How is "workload" defined?', ['Hoe wordt "werkdruk" gedefinieerd?', 'Hoe wordt werkdruk gedefinieerd?'], 'wordt gedefinieerd.'),
    tr('nl-en', 'Dit verschil kan niet door toeval worden verklaard.', ['This difference cannot be explained by chance.'], 'kan niet worden verklaard.'),
    fix('Ik vind dat de auteurs gelijk hebben dat thuiswerken goed is.', ['De auteurs concluderen dat thuiswerken het verzuim verlaagt.'], 'Neutral: report, do not judge.'),
    dict('De auteurs gaan na of thuiswerken samenhangt met minder kortdurend verzuim.', 'The authors examine whether working from home is associated with less short-term absence.', 'gaan na of … samenhangt.'),
    read('Hybride werken en ziekteverzuim. Sinds 2020 werkt ruim een derde van de Nederlandse werknemers deels thuis. In dit onderzoek is nagegaan of die verandering samenhangt met het kortdurend ziekteverzuim. Daartoe zijn verzuimgegevens van veertig middelgrote organisaties over de periode 2018–2023 met elkaar vergeleken. Het kortdurend verzuim blijkt in organisaties met een hybride regeling gemiddeld een derde lager te liggen dan in organisaties zonder zo’n regeling. De onderzoekers wijzen op twee mogelijke verklaringen: werknemers met lichte klachten werken thuis door, en de besmettingskans op kantoor neemt af. Tegelijk waarschuwen zij dat doorwerken bij ziekte op termijn juist tot langdurig verzuim kan leiden. Het onderzoek beslaat bovendien slechts vijf jaar en bevat geen gegevens over de zorg en het onderwijs, waar thuiswerken nauwelijks mogelijk is. Vervolgonderzoek naar langdurig verzuim wordt dan ook aanbevolen.', [
      { q: 'Wat is de onderzoeksvraag?', options: ['Of thuiswerken samenhangt met kortdurend verzuim.', 'Hoeveel mensen thuiswerken.', 'Of kantoren moeten sluiten.'], answer: 0, explain: '"nagegaan of die verandering samenhangt met het kortdurend ziekteverzuim".' },
      { q: 'Wat is het belangrijkste resultaat?', options: ['het verzuim is verdubbeld', 'het kortdurend verzuim ligt een derde lager bij hybride werken', 'er is geen verschil'], answer: 1, explain: '"gemiddeld een derde lager".' },
      { q: 'Welke waarschuwing geven de onderzoekers?', options: ['thuiswerken is duur', 'doorwerken bij ziekte kan later tot langdurig verzuim leiden', 'kantoren zijn ongezond'], answer: 1, explain: '"op termijn juist tot langdurig verzuim kan leiden".' },
      { q: 'Welke beperking noemt de tekst?', options: ['te veel deelnemers', 'slechts vijf jaar en geen gegevens over zorg en onderwijs', 'de gegevens zijn geheim'], answer: 1, explain: 'Short period and missing sectors.' },
    ], { en: 'Hybrid working and sick leave. Since 2020 over a third of Dutch employees have worked partly from home. This study examined whether that change is associated with short-term sick leave. To that end absence data from forty medium-sized organisations over the period 2018–2023 were compared. Short-term absence turns out to be on average a third lower in organisations with a hybrid arrangement than in organisations without one. The researchers point to two possible explanations: employees with mild complaints carry on working at home, and the chance of infection at the office decreases. At the same time they warn that working through illness can in the long run actually lead to long-term absence. The study moreover covers only five years and contains no data on care and education, where working from home is hardly possible. Follow-up research into long-term absence is therefore recommended.' }),
    write('Exam-style writing task: summarise the text above in 100 to 130 words, using the fixed skeleton.', ['Aanleiding in one sentence', 'De auteurs / onderzoekers gaan na of …', 'Method in one sentence with a past passive (werden vergeleken)', 'Main result with the one key figure', 'Explanations and the warning, hedged as in the source', 'Beperkingen + vervolgonderzoek', 'Neutral, own words, no ik'], 'Aanleiding voor het onderzoek is dat sinds 2020 veel werknemers deels thuiswerken. De onderzoekers gaan na of dat samenhangt met het kortdurend ziekteverzuim. Daartoe werden de verzuimcijfers van veertig organisaties over vijf jaar vergeleken. Uit de resultaten komt naar voren dat het kortdurend verzuim bij hybride werken ongeveer een derde lager ligt. Mogelijke verklaringen zijn dat mensen met lichte klachten thuis doorwerken en dat ze elkaar op kantoor minder besmetten. De auteurs waarschuwen wel dat doorwerken bij ziekte later tot langdurig verzuim kan leiden. Als beperkingen noemen zij de korte onderzoeksperiode en het ontbreken van sectoren als zorg en onderwijs. Zij bevelen daarom vervolgonderzoek aan.'),
    speak('De auteurs concluderen dat het kortdurend verzuim daalt, maar waarschuwen dat doorwerken bij ziekte risico’s heeft.', 'The authors conclude that short-term absence falls, but warn that working through illness has risks.'),
  ], [
    mc('"Beknopt" means', ['concise', 'complete'], 0, 'Concise.'),
    fill('De auteurs ___ dat het effect per sector verschilt. (conclude)', ['concluderen'], 'The authors conclude that the effect differs per sector.', 'concluderen.'),
    fill('Een mogelijke ___ is de lagere besmettingskans. (explanation)', ['verklaring'], 'A possible explanation is the lower chance of infection.', 'verklaring.'),
    build('Follow-up research is recommended.', 'Vervolgonderzoek wordt aanbevolen.', ['aanbevelen', 'is'], 'wordt aanbevolen.'),
    tr('en-nl', 'Paraphrase; do not copy sentences.', ['Parafraseer; kopieer geen zinnen.', 'Parafraseer en kopieer geen zinnen.'], 'Imperatives.'),
    speak('Als beperking noemen zij de korte looptijd; vervolgonderzoek wordt dan ook aanbevolen.', 'As a limitation they mention the short duration; follow-up research is therefore recommended.'),
  ]));
})();
