/* Stage 4 — B2: grammar and skills reference. Vocabulary and lessons live in stage4-u*.js */
(function () {
  'use strict';
  const NL = window.NL, A = NL.contentApi;
  const { G, h, p, tip, warn, table, ex, list } = A;

  G('g4-long-sentences', 'Advanced word order and long sentences', 4, ['word order', 'reading', 'writing'], [
    p('B2 Dutch is less about new rules than about keeping the known rules under control in long sentences. Three things make Dutch sentences long: stacked subordinate clauses, the distance between the two verb positions (the **tangconstructie**, or pincer), and material placed after the final verb.'),
    h('The pincer and how to read it'),
    p('The finite verb and the rest of the verb group can be far apart: `De minister **heeft** gisteren tijdens een debat in de Tweede Kamer over de nieuwe woningwet, waarover al maanden wordt gesproken, een opvallende uitspraak **gedaan**.` Reading strategy: find the finite verb, jump to the end of the clause for its partner, then fill in the middle.'),
    h('Verb clusters at the end'),
    table(['cluster', 'example'], [['two verbs', '*… dat hij het rapport heeft gelezen / gelezen heeft.'], ['modal + infinitive', '*… dat ze morgen moet werken.'], ['three verbs', '*… dat het besluit had moeten worden genomen.'], ['with te', '*… dat hij zit te wachten.']]),
    p('In clusters of three or more the Netherlands prefers the order **finite verb, then modals, then the main verb**: `zou kunnen hebben gezegd`. The participle may also come first: `gezegd zou kunnen hebben`. Do not split the cluster with other words.'),
    h('Extraposition: what may follow the final verb'),
    p('Prepositional phrases and long clauses can be moved **after** the verb group to lighten the middle: `Ik heb lang gewacht **op een antwoord**.` `Hij heeft gezegd **dat hij niet komt**.` Relative clauses can be moved too: `Ik heb de man gesproken **die je zocht**.`'),
    h('Writing long sentences that stay readable'),
    list('Put the subject and the finite verb early.', 'Limit each sentence to one subordinate clause inside another.', 'Prefer two sentences joined by a discourse marker over one sentence with three clauses.', 'Keep the verb cluster together and close to its objects.'),
    ex(['Hoewel de partij had beloofd de belastingen te verlagen, heeft ze, nu ze eenmaal in de regering zit, besloten dat plan voorlopig uit te stellen.', 'Although the party had promised to lower taxes, it has decided, now that it is in government, to postpone that plan for the time being.'], ['Het is de vraag of de maatregel, die pas volgend jaar ingaat, het gewenste effect zal hebben.', 'The question is whether the measure, which only takes effect next year, will have the desired effect.'], ['Dat had eerder moeten worden besproken.', 'That should have been discussed earlier.']),
    tip('When a sentence loses you, bracket the clauses. Every `dat, omdat, die, waarover, hoewel` opens a bracket that closes at its verb.'),
  ]);

  G('g4-past-tenses', 'All the past tenses: pluperfect and future perfect', 4, ['verbs', 'past'], [
    table(['tense', 'Dutch name', 'form', 'example'], [['perfect', 'vtt', 'heb / ben + participle', '*Ik heb het gelezen.'], ['simple past', 'ovt', 'stem + te/de or strong form', '*Ik las het.'], ['pluperfect', 'vvt', 'had / was + participle', '*Ik had het al gelezen.'], ['future', 'ott + zullen', 'zal + infinitive', '*Ik zal het lezen.'], ['future perfect', 'vttt', 'zal + participle + hebben / zijn', '*Ik zal het morgen gelezen hebben.'], ['conditional perfect', 'vvtt', 'zou + participle + hebben / zijn', '*Ik zou het gelezen hebben.']]),
    h('Pluperfect: the past before the past'),
    p('Use it for what had already happened before another past moment, typically with `nadat`, `toen`, `al`, `nog niet`: `Nadat ze was afgestudeerd, vond ze meteen werk.` `Toen ik aankwam, was de trein al vertrokken.` Auxiliary choice is the same as in the perfect: `had gewerkt`, `was gegaan`.'),
    h('Unreal past: regret and hypothesis'),
    p('`Als ik dat had geweten, was ik niet gekomen.` / `… zou ik niet gekomen zijn.` `Had ik maar beter geluisterd!` (If only I had listened better.) `Je had het me moeten zeggen.` (You should have told me.) `Dat had ik niet verwacht.`'),
    h('Future perfect: completed by a future point, or a guess'),
    p('`Tegen vrijdag zal ik het rapport afgerond hebben.` In practice Dutch often uses the plain perfect with a time expression: `Vrijdag heb ik het af.` The future perfect is also used for assumptions about the past: `Hij zal het wel vergeten zijn.` (He has probably forgotten.)'),
    ex(['Toen de brandweer arriveerde, was het vuur al gedoofd.', 'When the fire brigade arrived, the fire had already gone out.'], ['Had ik dat maar eerder geweten!', 'If only I had known that earlier!'], ['Over een jaar zullen we hopelijk verhuisd zijn.', 'In a year we will hopefully have moved.'], ['Ze zal de trein wel gemist hebben.', 'She has probably missed the train.']),
    warn('`moeten`, `kunnen`, `willen` in the pluperfect keep the double infinitive: `Je had het moeten zeggen`, never "gemoeten".'),
  ]);

  G('g4-passive-all', 'The passive in all tenses and its alternatives', 4, ['passive', 'formal'], [
    table(['tense', 'passive', 'English'], [['present', '*Het plan wordt besproken.', 'is being discussed'], ['simple past', '*Het plan werd besproken.', 'was discussed'], ['perfect', '*Het plan is besproken.', 'has been discussed'], ['pluperfect', '*Het plan was al besproken.', 'had been discussed'], ['future', '*Het plan zal worden besproken.', 'will be discussed'], ['future perfect', '*Het plan zal zijn besproken.', 'will have been discussed'], ['conditional', '*Het plan zou worden besproken.', 'would be discussed'], ['conditional perfect', '*Het plan zou zijn besproken.', 'would have been discussed'], ['modal', '*Het plan moet worden besproken.', 'must be discussed'], ['modal perfect', '*Het plan had moeten worden besproken.', 'should have been discussed']]),
    h('Indirect object as subject? Not in Dutch'),
    p('English "I was given a book" has no direct Dutch equivalent. Keep the indirect object as it is: `Mij werd een boek gegeven` or, far more natural, `Ik kreeg een boek.` The `krijgen`-passive is common in speech: `Ik kreeg het toegestuurd.`'),
    h('Alternatives to the passive'),
    list('`men` (formal, one): `Men neemt aan dat …`', '`je` (general you): `Dat zie je vaak.`', '`ze` (they): `Ze hebben de straat afgesloten.`', '`er` + passive: `Er wordt aan gewerkt.`', '`zijn te` + infinitive (can / must be): `Dat is niet te doen.` `Het formulier is online in te vullen.`', '`laten` + infinitive: `Ik laat het nakijken.`', '`-baar`: `Het is niet haalbaar.`'),
    ex(['De resultaten zullen in het najaar worden gepubliceerd.', 'The results will be published in the autumn.'], ['Dat had veel eerder moeten worden aangepakt.', 'That should have been tackled much earlier.'], ['De schade is niet te overzien.', 'The damage cannot be overseen.'], ['Men gaat ervan uit dat de rente zal dalen.', 'It is assumed that interest rates will fall.']),
    tip('In formal writing the passive hides the doer; in argumentative writing, name the doer when responsibility matters.'),
  ]);

  G('g4-subjunctive', 'Subjunctive remnants and fixed expressions', 4, ['formal', 'fixed expressions'], [
    p('Modern Dutch has no living subjunctive, but the old form (stem + **-e**) survives in wishes, formulas and formal texts. You need to recognise them, and use a handful.'),
    table(['expression', 'meaning', 'where'], [['*Leve de koning!', 'long live the king', 'celebrations'], ['*Het ga je goed.', 'may it go well with you', 'farewell'], ['*God zij dank.', 'thank God', 'speech'], ['*Dank zij / dankzij', 'thanks to', 'now one word, a preposition'], ['*als het ware', 'as it were', 'speech and writing'], ['*wat er ook gebeure', 'whatever may happen', 'formal'], ['*koste wat het kost', 'at all costs', 'speech'], ['*het zij zo', 'so be it', 'resignation'], ['*men neme …', 'take … (recipes)', 'old cookbooks'], ['*moge', 'may', '*Moge het nieuwe jaar u veel geluk brengen.'], ['*ware', 'were', '*Als het ware; *ware het niet dat … (were it not that)'], ['*bij wijze van spreken', 'so to speak', 'speech']]),
    h('Other frozen forms'),
    p('Old case endings live on in fixed phrases: `ter plaatse` (on the spot), `ten slotte` (finally), `te allen tijde` (at all times), `in naam der wet` (in the name of the law), `heden ten dage` (nowadays), `van harte` (heartily), `des te beter` (all the better), `’s ochtends` (from "des ochtends"). Learn them as vocabulary; never build new ones.'),
    ex(['Koste wat het kost moet die deadline gehaald worden.', 'That deadline must be met at all costs.'], ['Het was, als het ware, een tweede thuis voor me.', 'It was, as it were, a second home for me.'], ['Ware het niet dat ik moest werken, dan was ik gekomen.', 'Were it not that I had to work, I would have come.'], ['Hoe meer je leest, des te groter wordt je woordenschat.', 'The more you read, the bigger your vocabulary becomes.']),
    tip('`hoe …, des te / hoe …`: `Hoe eerder, hoe beter.` `Hoe langer ik hier woon, des te meer ik ervan hou.`'),
  ]);

  G('g4-nominalisation', 'Nominalisation and formal written Dutch', 4, ['formal', 'writing'], [
    p('Formal and academic Dutch packs actions into **nouns**. Recognising the verb inside the noun is the key to reading such texts; unpacking nouns back into verbs is the key to writing clearly.'),
    table(['verb', 'noun', 'pattern'], [['onderzoeken', '*het onderzoek', 'stem'], ['ontwikkelen', '*de ontwikkeling', '-ing'], ['toenemen', '*de toename', 'strong stem'], ['afnemen', '*de afname', 'strong stem'], ['groeien', '*de groei', 'stem'], ['besluiten', '*het besluit / de besluitvorming', 'stem / compound'], ['invoeren', '*de invoering', '-ing'], ['verminderen', '*de vermindering', '-ing'], ['lezen', '*het lezen', 'het + infinitive'], ['aanwezig zijn', '*de aanwezigheid', '-heid']]),
    h('het + infinitive'),
    p('Any infinitive becomes a het-noun: `Het schrijven van een scriptie kost tijd.` `Door het invoeren van de maatregel …` Objects follow with `van`.'),
    h('Formal prepositional phrases'),
    p('`met betrekking tot` (regarding), `ten aanzien van` (with respect to), `als gevolg van` (as a result of), `op grond van` (on the basis of), `ten behoeve van` (for the benefit of), `in het kader van` (within the framework of), `naar aanleiding van` (further to), `door middel van` (by means of), `ondanks`, `wegens` (because of), `gezien` (in view of).'),
    h('From formal to clear'),
    table(['nominal style', 'verbal style'], [['*De invoering van de maatregel leidde tot een afname van het aantal ongelukken.', '*Toen de maatregel werd ingevoerd, gebeurden er minder ongelukken.'], ['*Wegens de toename van de vraag …', '*Omdat de vraag toeneemt …']]),
    ex(['Uit het onderzoek blijkt een sterke toename van het aantal thuiswerkers.', 'The study shows a strong increase in the number of people working from home.'], ['Op grond van deze gegevens is besloten tot uitstel van de invoering.', 'On the basis of these data it has been decided to postpone the introduction.'], ['Het verminderen van de uitstoot heeft prioriteit.', 'Reducing emissions has priority.']),
    tip('Reading tip: for every -ing, -heid or het + infinitive, ask "who does what?". Writing tip: use at most one nominalisation per clause.'),
  ]);

  G('g4-argument', 'Argumentative writing: structuring a betoog', 4, ['writing', 'exam'], [
    p('A Dutch argumentative text (`betoog`) is direct: the position comes early, the arguments are numbered or clearly marked, a counterargument is named and answered, and the conclusion repeats the position. The Staatsexamen writing tasks reward exactly this.'),
    table(['part', 'what it does', 'useful language'], [['inleiding', 'topic, why it matters, your standpunt', '*Steeds vaker … / De vraag is of … / Naar mijn mening …'], ['argument 1', 'strongest reason + example', '*In de eerste plaats … / Ten eerste … / Zo blijkt uit …'], ['argument 2', 'second reason', '*Daarnaast … / Bovendien … / Een tweede argument is dat …'], ['tegenargument', 'name it, then refute it', '*Tegenstanders beweren dat … / Dat mag zo zijn, maar … / Daar staat tegenover dat …'], ['conclusie', 'restate, no new points', '*Kortom … / Concluderend … / Al met al … / Daarom pleit ik voor …']]),
    h('Signal words by function'),
    table(['function', 'signal words'], [['adding', '*bovendien, daarnaast, ook, verder, tevens'], ['contrast', '*maar, echter, toch, daarentegen, desondanks, enerzijds … anderzijds'], ['cause', '*omdat, doordat, aangezien, immers, namelijk, want'], ['effect', '*daardoor, daarom, dus, zodat, waardoor, als gevolg daarvan'], ['condition', '*als, indien, mits, tenzij'], ['example', '*bijvoorbeeld, zo, neem nou, ter illustratie'], ['conclusion', '*kortom, dus, al met al, concluderend, samenvattend']]),
    h('doordat vs omdat'),
    p('`omdat` gives a **reason** (someone’s motive); `doordat` gives a **cause** (no intention): `Hij bleef thuis omdat hij moe was.` `De trein viel uit doordat er een storing was.`'),
    ex(['Naar mijn mening zou de binnenstad autovrij moeten worden. In de eerste plaats verbetert dat de luchtkwaliteit.', 'In my opinion the city centre should become car-free. In the first place it improves air quality.'], ['Tegenstanders beweren dat winkels klanten verliezen. Dat mag zo zijn, maar onderzoek in andere steden laat het tegendeel zien.', 'Opponents claim that shops lose customers. That may be so, but research in other cities shows the opposite.'], ['Kortom, een autovrije binnenstad is gezonder, veiliger en uiteindelijk ook beter voor de economie.', 'In short, a car-free city centre is healthier, safer and ultimately also better for the economy.']),
    tip('`mits` = provided that; `tenzij` = unless. Both send the verb to the end: `Ik kom, tenzij het regent.`'),
  ]);

  G('g4-reading', 'Reading strategies for newspaper and academic texts', 4, ['reading', 'exam'], [
    h('Before you read'),
    list('Read the **title, lead and subheadings** first; predict the standpoint.', 'Identify the text type: `nieuwsbericht` (facts, who-what-where), `achtergrondartikel` (context), `opiniestuk` / `column` (one view), `betoog` (argued position), `wetenschappelijk artikel` (question, method, results, discussion).'),
    h('While you read'),
    list('Read the **first and last sentence** of each paragraph; Dutch paragraphs usually open with the topic sentence.', 'Follow the **signal words**: `echter` flips the direction, `kortom` announces the conclusion, `zo` and `bijvoorbeeld` mark an example you may skim.', 'Unpack long sentences: finite verb first, then its partner at the end.', 'Unpack **nominalisations** and **compounds** from the right.', 'Track reference words: `deze`, `dit`, `daarvan`, `hiermee`, `de laatste`, `eerstgenoemde`. Ask what each points to.'),
    h('Newspaper conventions'),
    p('Headlines drop articles and use the present: `Kabinet verlaagt belasting op arbeid`. Hedging marks uncertainty: `zou` (`De minister zou aftreden` = is reported to be resigning), `naar verluidt`, `volgens bronnen`, `mogelijk`, `vermoedelijk`.'),
    h('Exam questions'),
    p('Typical question types: main idea (`hoofdgedachte`), the function of a paragraph, the writer’s aim (`informeren, overtuigen, amuseren, activeren`), what a word refers to, and whether a statement follows from the text. Answer from the text, not from what you know.'),
    ex(['De minister zou volgende week een besluit nemen.', 'The minister is reported to be taking a decision next week.'], ['Hiermee doelt de auteur op de eerder genoemde bezuinigingen.', 'With this the author refers to the cuts mentioned earlier.'], ['Uit het bovenstaande volgt dat de maatregel weinig effect heeft gehad.', 'It follows from the above that the measure has had little effect.']),
    tip('Newspaper `zou` is not politeness; it means "according to unconfirmed reports".'),
  ]);

  G('g4-listening', 'Listening to fast natural speech', 4, ['listening', 'spoken Dutch'], [
    p('Spoken Dutch drops and merges sounds in predictable ways. Knowing the patterns turns noise into words.'),
    table(['written', 'spoken', 'pattern'], [['*het', "'t, ut", 'unstressed het'], ['*een', "'n, un", 'unstressed een'], ['*ik heb het', "'k heb 't", 'clitic pronouns'], ['*dat is', 'da’s', 'contraction'], ['*als het', "as 't", 'l dropped'], ['*niet', 'nie', 'final t dropped'], ['*eigenlijk', 'eigelijk, eik', 'syllables swallowed'], ['*natuurlijk', 'tuurlijk', 'first syllable dropped'], ['*even', 'effe', 'v → f, n dropped'], ['*weet je wel', 'weetjewel', 'filler, run together'], ['*lopen, werken', 'lope, werke', 'final -n silent'], ['*heb je', 'hebbie, hejje', 'assimilation']]),
    h('Fillers and hedges'),
    p('`eh`, `nou`, `zeg maar` (kind of), `weet je`, `dus`, `ja`, `of zo` (or something), `en zo` (and stuff), `gewoon`, `best wel`, `een beetje`, `zo’n beetje` (roughly), `volgens mij`, `ik bedoel`. They carry no content; let them pass.'),
    h('Strategies'),
    list('Listen for **stressed words**; Dutch stresses the new information.', 'Predict from context; the verb at the end confirms the guess.', 'Use the **signal words** as you do in reading.', 'In exams, read the questions first and listen for the paraphrase, not the exact words.', 'Train with the radio (NPO Radio 1), the news in normal speed (NOS), and podcasts; slow your player to 0.8 at first.'),
    ex(["'k Heb 't eigenlijk nooit zo bekeken.", 'I have actually never looked at it that way.'], ["Da's best wel duur, zeg maar.", 'That is, like, pretty expensive.'], ['Hebbie effe tijd?', 'Do you have a moment?']),
    tip('You do not have to speak like this; you have to understand it. Pronounce final -n or not, both are accepted.'),
  ]);

  G('g4-discourse', 'Discourse markers: steering a text or a conversation', 4, ['writing', 'speaking', 'cohesion'], [
    table(['marker', 'meaning', 'register', 'position'], [['*echter', 'however', 'written', 'after the first element'], ['*desondanks / niettemin', 'nevertheless', 'written', 'first or middle'], ['*daarentegen', 'by contrast', 'neutral', 'after the contrasted element'], ['*immers', 'after all (shared reason)', 'written', 'middle'], ['*namelijk', 'you see, namely (new reason)', 'neutral', 'middle, never first'], ['*overigens / trouwens', 'by the way', 'neutral / spoken', 'first or middle'], ['*kortom', 'in short', 'neutral', 'first'], ['*oftewel', 'in other words', 'neutral', 'between the two wordings'], ['*met andere woorden', 'in other words', 'neutral', 'first'], ['*enerzijds … anderzijds', 'on the one hand … on the other', 'written', 'first in each half'], ['*zowel … als', 'both … and', 'neutral', ''], ['*niet alleen … maar ook', 'not only … but also', 'neutral', ''], ['*laat staan', 'let alone', 'neutral', 'before the stronger case'], ['*sterker nog', 'what is more', 'spoken and written', 'first']]),
    h('namelijk and immers'),
    p('Both explain the previous sentence. `namelijk` gives a reason the reader does **not** know yet: `Ik kom niet. Ik ben namelijk ziek.` `immers` reminds the reader of something they **do** know: `We moeten opschieten. De trein wacht immers niet.` Neither can start the sentence.'),
    h('In conversation'),
    p('`Trouwens, …` (by the way), `Hoe dan ook, …` (anyhow), `Waar was ik?`, `Om kort te gaan …`, `Wat ik bedoel is …`, `Dat gezegd hebbende …` (that said), `Eerlijk is eerlijk …` (fair is fair).'),
    ex(['De plannen zijn ambitieus. De financiering is echter nog niet rond.', 'The plans are ambitious. The financing, however, is not yet settled.'], ['Hij spreekt geen Duits, laat staan Fries.', 'He does not speak German, let alone Frisian.'], ['Het onderzoek was duur en, sterker nog, het leverde niets op.', 'The research was expensive and, what is more, it yielded nothing.']),
    tip('One marker per sentence is enough. A text where every sentence starts with a marker reads like a checklist.'),
  ]);

  G('g4-register-switching', 'Register switching: one message, three voices', 4, ['register', 'speaking', 'writing'], [
    table(['', 'informal', 'neutral', 'formal'], [['ask', '*Kun je ff helpen?', '*Kun je me even helpen?', '*Zou u mij kunnen helpen?'], ['refuse', '*Nee joh, geen tijd.', '*Dat lukt me helaas niet.', '*Helaas kan ik niet aan uw verzoek voldoen.'], ['disagree', '*Onzin.', '*Daar ben ik het niet mee eens.', '*Ik deel die opvatting niet.'], ['because', '*want, omdat', '*omdat, doordat', '*aangezien, wegens, gezien'], ['but', '*maar', '*maar, toch', '*echter, niettemin'], ['get', '*krijgen', '*krijgen', '*ontvangen, verkrijgen'], ['say', '*zeggen', '*zeggen, vertellen', '*mededelen, verklaren, stellen'], ['think', '*vinden', '*vinden, denken', '*van mening zijn, achten']]),
    h('What changes with register'),
    list('**Address**: je ↔ u, first name ↔ title and surname.', '**Verbs**: everyday ↔ Latinate or compound (`regelen` ↔ `bewerkstelligen`).', '**Syntax**: short main clauses ↔ passives, nominalisations, long clauses.', '**Particles**: many (`even, maar, hoor`) ↔ almost none.', '**Contractions and fillers**: present ↔ absent.'),
    h('Choosing'),
    p('Dutch professional life is flatter than most: colleagues and managers are `je`, clients and officials start as `u`. Match the other person and move down when invited (`Zeg maar je, hoor`). Too formal sounds distant; too informal in a complaint or application sounds careless. At the Staatsexamen, speaking tasks name the listener: adapt to them.'),
    ex(['Hé Tom, heb je ff tijd? Ik kom er niet uit met dat rapport.', 'Hey Tom, got a sec? I cannot figure out that report.'], ['Beste Tom, zou je vandaag even naar het rapport kunnen kijken? Ik loop vast bij hoofdstuk 3.', 'Dear Tom, could you have a look at the report today? I am stuck at chapter 3.'], ['Geachte heer Bakker, graag verneem ik of u bereid bent het rapport van commentaar te voorzien.', 'Dear Mr Bakker, I would like to hear whether you are willing to comment on the report.']),
    tip('Practise by rewriting one message three ways. It trains vocabulary and tone at the same time.'),
  ]);

  G('g4-regional', 'Regional variation and Belgian Dutch', 4, ['variation', 'listening'], [
    p('Dutch is one standard language with two national varieties (Netherlands and Belgium, plus Suriname) and many regional accents. You do not need to produce them; you need to recognise them and avoid misunderstandings.'),
    table(['Netherlands', 'Flanders', 'meaning'], [['*jij / je, u (formal only)', '*gij / ge (informal, spoken), u (common)', 'you'], ['*pinnen', '*met de kaart betalen', 'to pay by card'], ['*de pinautomaat', '*de bankautomaat', 'cash machine'], ['*de magnetron', '*de microgolf(oven)', 'microwave'], ['*het mobieltje', '*de gsm', 'mobile phone'], ['*de patat / friet', '*de frieten', 'chips'], ['*leuk', '*plezant, tof', 'nice, fun'], ['*lopen', '*lopen = to run', 'careful: NL lopen = walk'], ['*straks', '*seffens, direct', 'in a moment'], ['*goedendag', '*goeiedag, dag', 'hello'], ['*de afspraak', '*het rendez-vous (older)', 'appointment'], ['*solliciteren', '*solliciteren', 'same']]),
    h('Sound'),
    p('Northern Dutch: hard `g`, diphthongised long vowels, final `-n` dropped. Southern (Brabant, Limburg, Flanders): **soft g**, purer vowels, clearer final `-n`, a more melodic intonation. Amsterdam: `z` → `s`, `v` → `f` (`de son`, `feel`). Randstad `r` often like English r at the end of a syllable (`Gooise r`).'),
    h('Grammar and politeness'),
    p('Flemish speakers use `u` far more widely, prefer the participle-first order in verb clusters (`gezien heb`), keep a three-gender feel for nouns (`de tafel … ze`), and use diminutives in `-ke` (`een huizeke`) in dialect. In formal Belgian Dutch, French loanwords are often avoided where the Netherlands keeps them (`stortbad` vs `douche`).'),
    h('Also Dutch'),
    p('**Surinamese Dutch** has its own vocabulary and rhythm; **Frisian** is a separate official language in Friesland; **Afrikaans** is a daughter language and largely readable for Dutch speakers.'),
    ex(['Ge moogt gerust binnenkomen.', 'You may certainly come in. (Flemish)'], ['Ik ga seffens naar de winkel.', 'I am going to the shop in a moment. (Flemish)'], ['Dat is een toffe film.', 'That is a great film. (Flemish, also informal NL)']),
    tip('If a Flemish speaker says `lopen`, check whether they mean run. If they say `u`, they are not being distant.'),
  ]);

  G('g4-proverbs', 'Advanced idioms and proverbs', 4, ['idioms', 'vocabulary'], [
    p('Dutch is rich in proverbs (`spreekwoorden`) and sayings (`gezegden`), many from sailing, farming and water. Journalists play with them constantly, so recognising the original unlocks headlines.'),
    table(['expression', 'meaning'], [['*De appel valt niet ver van de boom.', 'like parent, like child'], ['*Wie A zegt, moet ook B zeggen.', 'finish what you start'], ['*Beter één vogel in de hand dan tien in de lucht.', 'a bird in the hand'], ['*Oost west, thuis best.', 'there is no place like home'], ['*Hoge bomen vangen veel wind.', 'prominent people get much criticism'], ['*De druppel die de emmer doet overlopen.', 'the last straw'], ['*Water bij de wijn doen.', 'to compromise'], ['*Het roer omgooien.', 'to change course radically'], ['*Tegen de stroom in roeien.', 'to go against the tide'], ['*Schoon schip maken.', 'to make a clean sweep'], ['*Een oogje in het zeil houden.', 'to keep an eye on things'], ['*De koe bij de horens vatten.', 'to take the bull by the horns'], ['*Over koetjes en kalfjes praten.', 'to make small talk'], ['*Iets onder de knie hebben.', 'to have mastered something'], ['*Door de mand vallen.', 'to be exposed'], ['*Het Spaans benauwd krijgen.', 'to get very anxious'], ['*Van een mug een olifant maken.', 'to make a mountain out of a molehill'], ['*Wie het kleine niet eert, is het grote niet weerd.', 'value the small things'], ['*Zoals het klokje thuis tikt, tikt het nergens.', 'home is unique'], ['*Na regen komt zonneschijn.', 'after rain comes sunshine']]),
    h('Using them'),
    p('Sayings with a verb conjugate normally: `We hebben water bij de wijn moeten doen.` `Ze gooide het roer om.` Proverbs are quoted whole, often with `zoals ze zeggen` or `je weet wel`. Do not translate English idioms literally: "it rains cats and dogs" is `het regent pijpenstelen`.'),
    ex(['Na drie jaar studie heb ik de Nederlandse grammatica eindelijk onder de knie.', 'After three years of study I have finally mastered Dutch grammar.'], ['De nieuwe belasting was de druppel die de emmer deed overlopen.', 'The new tax was the last straw.'], ['Beide partijen moesten water bij de wijn doen.', 'Both parties had to compromise.']),
    tip('Headline decoder: "Kabinet gooit roer om" = the cabinet changes course; "Minister valt door de mand" = the minister is exposed.'),
  ]);

  G('g4-false-friends', 'False friends with English and German', 4, ['vocabulary', 'errors'], [
    h('English'),
    table(['Dutch', 'means', 'not', 'that is'], [['*eventueel', 'possibly, if need be', 'eventually', '*uiteindelijk'], ['*actueel', 'current, topical', 'actual', '*werkelijk, eigenlijk'], ['*de controle', 'check, inspection', 'control (power)', '*de macht, de beheersing'], ['*de fabriek', 'factory', 'fabric', '*de stof'], ['*de kritiek', 'criticism', 'critic', '*de criticus'], ['*de novelle', 'novella', 'novel', '*de roman'], ['*brutaal', 'cheeky, rude', 'brutal', '*wreed, bruut'], ['*braaf', 'well-behaved', 'brave', '*dapper, moedig'], ['*de chef', 'boss', 'chef', '*de kok'], ['*ordinair', 'vulgar', 'ordinary', '*gewoon'], ['*sympathiek', 'likeable', 'sympathetic', '*meelevend'], ['*consequent', 'consistent', 'consequent(ly)', '*daardoor, dus'], ['*de mening', 'opinion', 'meaning', '*de betekenis'], ['*overzien', 'to survey, oversee the whole', 'to overlook (miss)', '*over het hoofd zien'], ['*solliciteren', 'to apply for a job', 'to solicit', '*werven'], ['*het recept', 'recipe / prescription', 'receipt', '*de bon'], ['*de map', 'folder', 'map', '*de kaart'], ['*slim', 'clever', 'slim', '*slank']]),
    h('German'),
    table(['Dutch', 'means', 'German look-alike', 'which means'], [['*bellen', 'to phone / ring', 'bellen', 'to bark'], ['*het meer', 'lake', 'das Meer', 'sea'], ['*de zee', 'sea', 'der See', 'lake'], ['*doof', 'deaf', 'doof', 'stupid'], ['*klaar', 'ready, finished', 'klar', 'clear'], ['*durven', 'to dare', 'dürfen', 'to be allowed'], ['*mogen', 'to be allowed', 'mögen', 'to like'], ['*de winkel', 'shop', 'der Winkel', 'angle, corner'], ['*aandacht', 'attention', 'Andacht', 'devotion'], ['*verzoeken', 'to request', 'versuchen', 'to try']]),
    ex(['Eventueel kunnen we de vergadering verzetten.', 'If need be, we can move the meeting.'], ['Dat is een actueel onderwerp.', 'That is a topical subject.'], ['Wat een brutale opmerking!', 'What a cheeky remark!'], ['Je bent consequent te laat.', 'You are consistently late.']),
    warn('`Ik wil een bier` sounds blunt; `Ik wil graag een biertje`. And `willen` is "want", not "will": "I will do it" = `Ik zal het doen`.'),
  ]);

  G('g4-common-errors', 'Common errors of advanced learners', 4, ['errors', 'exam'], [
    table(['error', 'wrong', 'right', 'rule'], [['verb not at the end', '*… omdat ik ben moe.', '*… omdat ik moe ben.', 'subordinate clause'], ['no inversion', '*Gisteren ik ging …', '*Gisteren ging ik …', 'verb second'], ['no inversion after a clause', '*Als het regent, ik blijf thuis.', '*Als het regent, blijf ik thuis.', 'clause = first element'], ['de / het', '*de huis, het auto', '*het huis, de auto', 'learn with the noun'], ['adjective ending', '*een mooie huis', '*een mooi huis', 'een + het-word: no -e'], ['die / dat', '*het boek die', '*het boek dat', 'het-word → dat'], ['hebben / zijn', '*ik heb gegaan', '*ik ben gegaan', 'movement / change → zijn'], ['als / dan', '*groter als', '*groter dan', 'comparison → dan'], ['als / toen', '*als ik jong was', '*toen ik jong was', 'past period → toen'], ['omdat / doordat', '*doordat ik moe was, ging ik slapen', '*omdat ik moe was …', 'motive → omdat'], ['hun / hen / ze', '*hun hebben', '*zij / ze hebben', 'hun is never a subject'], ['er missing', '*Ik heb twee.', '*Ik heb er twee.', 'number needs er'], ['preposition + het', '*met het', '*ermee', 'things → er + preposition'], ['te after modal', '*ik moet te werken', '*ik moet werken', 'no te'], ['dt', '*hij word, het gebeurd', '*hij wordt, het gebeurt', 'stem + t'], ['compound spacing', '*lange termijn planning', '*langetermijnplanning', 'one word'], ['word order of niet', '*Ik niet weet het.', '*Ik weet het niet.', 'niet late'], ['English calques', '*Het maakt geen zin.', '*Het heeft geen zin. / Dat slaat nergens op.', 'zin hebben']]),
    h('dt in thirty seconds'),
    p('Present tense: stem + t for jij (before the verb), hij, zij, het, u: `hij wordt`, `zij vindt`, `het gebeurt`. No t when jij follows: `word je`. Past participle: ’t kofschip on the stem: `gebeurd`, `verhuisd`, `gewerkt`. So: `Het gebeurt vaak.` (present) but `Het is gebeurd.` (participle).'),
    h('More English calques to unlearn'),
    list('"I am agree" → `Ik ben het ermee eens.`', '"It depends of" → `Het hangt af van …`', '"I look forward to" → `Ik kijk uit naar …` / `Ik verheug me op …`', '"I am 30 years" → `Ik ben dertig (jaar).`', '"I have it cold" is correct Dutch: `Ik heb het koud.`', '"to make a photo" is correct Dutch: `een foto maken`.', '"That makes sense" → `Dat klinkt logisch.` / `Dat snap ik.`'),
    ex(['Het gebeurt vaak dat de trein vertraagd is; gisteren is het weer gebeurd.', 'It often happens that the train is delayed; yesterday it happened again.'], ['Ik weet niet of hij komt, omdat hij niets van zich heeft laten horen.', 'I do not know whether he is coming, because he has not been in touch.'], ['De langetermijnplanning wordt volgende week besproken.', 'The long-term planning will be discussed next week.']),
    tip('Keep a personal error log with your five most frequent mistakes. Check every text you write against that list before sending it.'),
  ]);

  G('g4-staatsexamen', 'Staatsexamen NT2 Programma II: what to expect', 4, ['exam'], [
    p('The Staatsexamen NT2 Programma II tests **B2** in four separate parts: `lezen`, `luisteren`, `schrijven`, `spreken`. You can take the parts separately and you pass each one on its own. The diploma gives access to higher education (hbo, university) and to many professions. Details change; always check the current information from the exam board before you register.'),
    table(['part', 'what you do', 'what is assessed'], [['Lezen', 'several longer texts (news, opinion, study and work texts) with multiple-choice questions', 'main idea, detail, structure, the writer’s aim, reference words'], ['Luisteren', 'audio fragments (interviews, lectures, discussions) with multiple-choice questions', 'gist, detail, opinion, relation between speakers'], ['Schrijven', 'short tasks (finish sentences, short messages) and longer tasks (email, letter, short report or argument)', 'task completion, grammar, vocabulary, cohesion, register'], ['Spreken', 'short and longer speaking tasks recorded on a computer: react, describe, give and defend an opinion, advise', 'content, fluency, grammar, vocabulary, pronunciation, register']]),
    h('Strategy'),
    list('**Lezen**: questions follow the order of the text. Read the question, find the paragraph, answer from the text.', '**Luisteren**: read the questions in the pause before the fragment; listen for paraphrase.', '**Schrijven**: do exactly what the task says (every bullet), name the reader, choose `u` or `je`, plan for two minutes, leave time to check your error log (verb position, dt, de / het).', '**Spreken**: use the preparation time to note key words, not sentences; start with your point, give two reasons and an example, and finish with a conclusion. Keep talking until the time is nearly up.'),
    h('Useful frames for speaking tasks'),
    p('`Volgens mij …, en wel om twee redenen.` `Ten eerste … Ten tweede …` `Een voorbeeld daarvan is …` `Ik zou u daarom aanraden om …` `Kortom, …` `Als ik het goed begrijp, vraagt u …`'),
    ex(['Ik zou u aanraden om eerst contact op te nemen met uw leidinggevende.', 'I would advise you to contact your manager first.'], ['Volgens mij is thuiswerken een goede ontwikkeling, en wel om twee redenen.', 'In my view working from home is a good development, for two reasons.'], ['Kortom, ik ben voor, mits er duidelijke afspraken worden gemaakt.', 'In short, I am in favour, provided that clear agreements are made.']),
    tip('Every lesson in this stage ends with tasks in exam format. Do the speaking ones aloud and against the clock.'),
  ]);
})();
