/* Stage 5 — speaking topics, part 2: fifteen more Free-talk topics with model answers (A1 to B2).
   Same shape as the topics in stage5.js; appended to NL.content.talk. */
(function () {
  'use strict';
  const NL = window.NL;
  const talk = (NL.content.talk = NL.content.talk || []);
  const topic = (id, title, level, icon, prompts) => talk.push({ id, title, level, icon, prompts: prompts.map(([prompt, model, modelEn, hints]) => ({ prompt, model, modelEn, hints })) });

  topic('t-tijd', 'Time, dates and appointments', 'A1', '\u{1F552}', [
    ['Say what time it is now and what time you get up and go to bed.', 'Het is nu kwart over acht. Ik sta om zeven uur op en ik ga om elf uur naar bed.', 'It is now a quarter past eight. I get up at seven and I go to bed at eleven.', ['Het is nu …', 'Ik sta om … op', 'Ik ga om … naar bed']],
    ['Say your birthday and today’s date.', 'Ik ben jarig op twaalf maart. Vandaag is het dinsdag drieëntwintig september.', 'My birthday is on 12 March. Today is Tuesday 23 September.', ['Ik ben jarig op …', 'Vandaag is het …']],
    ['Make an appointment with a friend for next week.', 'Zullen we volgende week afspreken? Woensdag om zeven uur? Of komt donderdag beter uit?', 'Shall we meet next week? Wednesday at seven? Or does Thursday suit you better?', ['Zullen we … afspreken?', 'Komt … uit?']],
    ['Say what you do on which day of the week.', 'Op maandag sport ik. Op woensdag werk ik thuis. In het weekend ga ik naar de markt.', 'On Mondays I exercise. On Wednesdays I work from home. At the weekend I go to the market.', ['Op maandag …', 'In het weekend …']],
  ]);
  topic('t-kleding-weer', 'Clothes and weather', 'A1', '\u{1F9E5}', [
    ['What is the weather like today, and what are you wearing?', 'Het regent en het is koud. Ik draag een jas, een sjaal en laarzen.', 'It is raining and it is cold. I am wearing a coat, a scarf and boots.', ['Het regent / Het is …', 'Ik draag …']],
    ['What do you wear to work and at the weekend?', 'Op mijn werk draag ik een overhemd en een nette broek. In het weekend draag ik een spijkerbroek en een trui.', 'At work I wear a shirt and smart trousers. At the weekend I wear jeans and a jumper.', ['Op mijn werk draag ik …', 'In het weekend …']],
    ['Buy a jacket in a shop: size, colour, price.', 'Ik zoek een jas. Maat medium, in het blauw. Wat kost deze? Mag ik hem passen?', 'I am looking for a jacket. Size medium, in blue. How much is this one? May I try it on?', ['Ik zoek …', 'Wat kost …?', 'Mag ik … passen?']],
    ['Which season do you like best and why?', 'Ik hou het meest van de lente. Het is niet te warm en de bloemen bloeien. De winter vind ik te donker.', 'I like spring most. It is not too warm and the flowers are blooming. I find winter too dark.', ['Ik hou het meest van …', '… vind ik te …']],
  ]);
  topic('t-vrije-tijd-a1', 'Hobbies and free time', 'A1', '\u{1F3AE}', [
    ['What do you do in your free time?', 'In mijn vrije tijd lees ik en ik fiets. Op zondag kook ik voor vrienden.', 'In my free time I read and I cycle. On Sundays I cook for friends.', ['In mijn vrije tijd …', 'Op zondag …']],
    ['Do you play a sport? How often?', 'Ja, ik voetbal op dinsdag en ik zwem één keer per week.', 'Yes, I play football on Tuesdays and I swim once a week.', ['Ik … op …', '… keer per week']],
    ['Invite someone to the cinema.', 'Heb je zin om zaterdag naar de bioscoop te gaan? De film begint om acht uur.', 'Do you feel like going to the cinema on Saturday? The film starts at eight.', ['Heb je zin om … te …?', 'De film begint om …']],
    ['What did you do yesterday evening?', 'Gisteravond heb ik een serie gekeken en met mijn zus gebeld. Daarna ben ik vroeg naar bed gegaan.', 'Yesterday evening I watched a series and phoned my sister. Then I went to bed early.', ['Gisteravond heb ik …', 'Daarna ben ik …']],
  ]);
  topic('t-getallen', 'Numbers, prices and forms', 'A1', '\u{1F522}', [
    ['Say your phone number and your postcode.', 'Mijn telefoonnummer is nul zes, twaalf, vierendertig, zesenvijftig, achtenzeventig. Mijn postcode is tien twaalf AB.', 'My phone number is 06 12 34 56 78. My postcode is 1012 AB.', ['Mijn telefoonnummer is …', 'Mijn postcode is …']],
    ['Ask the price of three things at the market and say the total.', 'Wat kosten de appels? En de kaas? Twee euro vijftig plus zes euro is acht euro vijftig.', 'How much are the apples? And the cheese? Two fifty plus six euros is eight fifty.', ['Wat kosten …?', '… plus … is …']],
    ['Fill in a form out loud: name, address, date of birth.', 'Mijn naam is Sam Taylor. Ik woon op de Javastraat twaalf in Amsterdam. Ik ben geboren op vier juni negentienhonderdnegentig.', 'My name is Sam Taylor. I live at Javastraat 12 in Amsterdam. I was born on 4 June 1990.', ['Mijn naam is …', 'Ik woon op …', 'Ik ben geboren op …']],
    ['Say how many people live in your house and how old they are.', 'We wonen met drie mensen. Mijn partner is vijfendertig, ik ben drieëndertig en onze dochter is twee.', 'Three of us live here. My partner is thirty-five, I am thirty-three and our daughter is two.', ['We wonen met … mensen', '… is … jaar']],
  ]);

  topic('t-winkelen-a2', 'Shopping and returning things', 'A2', '\u{1F6CD}️', [
    ['Bring back a jumper that does not fit.', 'Ik heb deze trui gisteren gekocht, maar hij is te klein. Ik heb de bon nog. Kan ik hem ruilen voor een maat groter?', 'I bought this jumper yesterday, but it is too small. I still have the receipt. Can I exchange it for one size bigger?', ['Ik heb … gekocht, maar …', 'Ik heb de bon nog', 'Kan ik … ruilen?']],
    ['Phone about an order that has not arrived.', 'Ik bel over mijn bestelling van vorige week. Het pakket is nog niet aangekomen. Kunt u kijken waar het is?', 'I am calling about my order from last week. The parcel has not arrived yet. Could you check where it is?', ['Ik bel over …', '… is nog niet aangekomen', 'Kunt u …?']],
    ['Compare shopping online with shopping in a shop.', 'Online is makkelijker en vaak goedkoper, maar in de winkel kun je dingen passen en meteen meenemen. Ik koop kleren liever in de winkel.', 'Online is easier and often cheaper, but in a shop you can try things on and take them straight away. I prefer to buy clothes in a shop.', ['… is makkelijker / goedkoper, maar …', 'Ik koop liever …']],
    ['Tell about the last thing you bought and whether you are happy with it.', 'Ik heb vorige week een tweedehands fiets gekocht voor honderd euro. Ik ben er heel blij mee, alleen de rem moet nog gerepareerd worden.', 'I bought a second-hand bike last week for a hundred euros. I am very happy with it, only the brake still needs repairing.', ['Ik heb … gekocht', 'Ik ben er … mee', 'alleen …']],
  ]);
  topic('t-eten-uit', 'Eating out and cooking', 'A2', '\u{1F37D}️', [
    ['Book a table by phone.', 'Goedemiddag, ik wil graag een tafel reserveren voor vrijdag om zeven uur, voor vier personen. Op naam van Taylor.', 'Good afternoon, I would like to book a table for Friday at seven, for four people. In the name of Taylor.', ['Ik wil graag een tafel reserveren voor …', 'voor … personen', 'Op naam van …']],
    ['Explain a simple recipe.', 'Eerst snijd je een ui en bak je die in olie. Dan doe je de tomaten erbij. Laat het twintig minuten koken en eet het met pasta.', 'First you cut an onion and fry it in oil. Then you add the tomatoes. Let it cook for twenty minutes and eat it with pasta.', ['Eerst …', 'Dan …', 'Laat het … koken']],
    ['Complain politely about a cold dish in a restaurant.', 'Sorry, mag ik u even storen? De soep is koud. Zou u hem even kunnen opwarmen?', 'Sorry, may I disturb you a moment? The soup is cold. Could you warm it up?', ['Sorry, mag ik u even storen?', 'Zou u … kunnen …?']],
    ['What is typically Dutch food, and what do you think of it?', 'Typisch Nederlands is stamppot met worst, en haring natuurlijk. Stamppot vind ik lekker in de winter; haring heb ik één keer geprobeerd en dat was genoeg.', 'Typically Dutch is stamppot with sausage, and herring of course. I find stamppot tasty in winter; I tried herring once and that was enough.', ['Typisch Nederlands is …', '… vind ik …', '… heb ik één keer geprobeerd']],
  ]);
  topic('t-verleden', 'Childhood and the past', 'A2', '\u{1F9F8}', [
    ['Where did you grow up, and what was it like?', 'Ik ben opgegroeid in een dorp bij Manchester. Het was rustig en groen. We speelden altijd buiten.', 'I grew up in a village near Manchester. It was quiet and green. We always played outside.', ['Ik ben opgegroeid in …', 'Het was …', 'We … altijd …']],
    ['Tell about your school when you were young.', 'Mijn school was klein. Ik had een strenge juf, maar ik vond rekenen leuk. Na school fietste ik met vrienden naar het park.', 'My school was small. I had a strict teacher, but I liked arithmetic. After school I cycled to the park with friends.', ['Mijn school was …', 'Ik had …', 'Na school …']],
    ['What has changed most since you were a child?', 'Vroeger had niemand een mobiele telefoon. We belden thuis of we spraken gewoon af. Nu is iedereen altijd bereikbaar.', 'In the past nobody had a mobile phone. We phoned at home or simply arranged to meet. Now everyone is always reachable.', ['Vroeger …', 'Nu …']],
    ['Describe a person who was important to you as a child.', 'Mijn oma was heel belangrijk voor mij. Ze woonde bij ons in de straat en ze kookte elke zondag voor de hele familie. Ze was lief maar ook streng.', 'My grandma was very important to me. She lived in our street and cooked for the whole family every Sunday. She was kind but also strict.', ['… was heel belangrijk voor mij', 'Ze woonde …', 'Ze was … maar …']],
  ]);
  topic('t-mail-telefoon', 'Phone and email', 'A2', '\u{1F4DE}', [
    ['Answer the phone at work and take a message.', 'Goedemorgen, met Sam Taylor. Mevrouw De Vries is er niet. Kan ik iets doorgeven? Wat is uw nummer?', 'Good morning, Sam Taylor speaking. Ms De Vries is not here. Can I pass something on? What is your number?', ['Met …', 'Kan ik iets doorgeven?', 'Wat is uw nummer?']],
    ['Leave a voicemail to cancel an appointment.', 'Goedemiddag, met Sam Taylor. Ik heb morgen om tien uur een afspraak, maar ik kan helaas niet komen. Kunt u mij terugbellen voor een nieuwe afspraak? Mijn nummer is 06 12 34 56 78.', 'Good afternoon, Sam Taylor speaking. I have an appointment tomorrow at ten, but unfortunately I cannot come. Could you call me back for a new appointment? My number is 06 12 34 56 78.', ['Ik heb … een afspraak, maar …', 'Kunt u mij terugbellen?']],
    ['Spell your name and email address.', 'Mijn achternaam is Taylor: T van Theodoor, A, Y, L, O, R. Mijn e-mailadres is sam punt taylor apenstaartje mail punt com.', 'My surname is Taylor: T for Theodoor, A, Y, L, O, R. My email address is sam dot taylor at mail dot com.', ['… van …', 'punt', 'apenstaartje']],
    ['Say what you would write in a short email to a colleague who is ill.', 'Ik zou schrijven: Hoi Anna, ik hoorde dat je ziek bent. Beterschap! Maak je geen zorgen over het werk, dat regelen wij. Groetjes, Sam.', 'I would write: Hi Anna, I heard you are ill. Get well soon! Do not worry about work, we will take care of that. Regards, Sam.', ['Ik hoorde dat …', 'Beterschap!', 'Maak je geen zorgen over …']],
  ]);

  topic('t-milieu-b1', 'Environment and sustainability', 'B1', '\u{1F333}', [
    ['What do you do to live more sustainably?', 'Ik scheid mijn afval, ik fiets bijna overal naartoe en ik koop veel tweedehands. Vlees eet ik nog wel, maar minder dan vroeger.', 'I separate my waste, I cycle almost everywhere and I buy a lot second-hand. I do still eat meat, but less than before.', ['Ik scheid …', 'Ik koop …', '… nog wel, maar minder']],
    ['Is a flight tax a good idea? Give your opinion.', 'Volgens mij wel. Vliegen is nu goedkoper dan de trein, terwijl het veel schadelijker is. Als de prijs eerlijk wordt, kiezen mensen vanzelf vaker de trein.', 'In my view yes. Flying is now cheaper than the train, whereas it is much more harmful. If the price becomes fair, people will automatically choose the train more often.', ['Volgens mij …', '… terwijl …', 'Als …, … vanzelf …']],
    ['Describe what is being done about energy in your building or street.', 'Onze flat wordt volgend jaar geïsoleerd en er komen zonnepanelen op het dak. Dat wordt betaald door de woningcorporatie, maar de huur gaat wel iets omhoog.', 'Our block is being insulated next year and solar panels are coming on the roof. That is paid for by the housing association, but the rent does go up a little.', ['… wordt … geïsoleerd', 'Er komen …', 'Dat wordt betaald door …']],
    ['Who should pay for the energy transition: citizens, companies or the government?', 'Ik vind dat bedrijven en de overheid het grootste deel moeten betalen. Ze hebben het meest vervuild en ze kunnen het beter dragen dan een gezin met een laag inkomen.', 'I think companies and the government should pay the largest part. They have polluted most and they can bear it better than a family on a low income.', ['Ik vind dat … moeten betalen', 'Ze hebben …', '… beter dan …']],
  ]);
  topic('t-geld-b1', 'Money and bureaucracy', 'B1', '\u{1F4B6}', [
    ['Explain to a newcomer what toeslagen are and how you apply.', 'Toeslagen zijn bijdragen van de overheid voor mensen met een lager inkomen, bijvoorbeeld voor de huur of de zorgverzekering. Je vraagt ze aan bij de Belastingdienst, met je DigiD.', 'Allowances are contributions from the government for people on a lower income, for example for rent or health insurance. You apply for them at the tax office, with your DigiD.', ['Toeslagen zijn …', 'Je vraagt ze aan bij …']],
    ['Phone your bank: your card has been stolen.', 'Goedemiddag, mijn pinpas is gestolen. Kunt u hem meteen blokkeren? Mijn rekeningnummer is … Kan ik een nieuwe pas aanvragen?', 'Good afternoon, my debit card has been stolen. Could you block it immediately? My account number is … Can I apply for a new card?', ['Mijn pinpas is gestolen', 'Kunt u hem blokkeren?', 'Kan ik een nieuwe … aanvragen?']],
    ['You received a letter from the gemeente you do not understand. Ask a colleague for help.', 'Heb je even? Ik heb een brief van de gemeente over een parkeervergunning, maar ik snap niet wat ik moet doen. Er staat iets over "uiterlijk 1 juli". Kun je even meelezen?', 'Do you have a moment? I have a letter from the municipality about a parking permit, but I do not understand what I have to do. It says something about "by 1 July". Could you read along with me?', ['Ik heb een brief van …, maar …', 'Er staat iets over …', 'Kun je even meelezen?']],
    ['Are Dutch prices high? Compare with your own country.', 'Wonen is hier veel duurder dan in mijn land, vooral de huur. Boodschappen zijn ongeveer even duur, maar uit eten is duurder. Het openbaar vervoer vind ik echt duur.', 'Housing is much more expensive here than in my country, especially rent. Groceries are about as expensive, but eating out costs more. I find public transport really expensive.', ['… is veel duurder dan …', '… ongeveer even duur', '… vind ik echt …']],
  ]);
  topic('t-onderwijs-b1', 'Education and learning', 'B1', '\u{1F3EB}', [
    ['Explain the Dutch school system in a few sentences.', 'Kinderen gaan van vier tot twaalf naar de basisschool. Daarna krijgen ze een advies voor vmbo, havo of vwo. Na het vwo kun je naar de universiteit, na de havo naar het hbo.', 'Children go to primary school from four to twelve. Then they get a recommendation for vmbo, havo or vwo. After vwo you can go to university, after havo to a university of applied sciences.', ['Kinderen gaan van … tot … naar …', 'Daarna krijgen ze …', 'Na … kun je naar …']],
    ['Talk to a teacher about your child at a parents’ evening.', 'Hoe gaat het met Noor in de klas? Ik maak me een beetje zorgen over haar spelling, want thuis spreken we geen Nederlands. Wat kunnen wij thuis doen?', 'How is Noor doing in class? I am a little worried about her spelling, because we do not speak Dutch at home. What can we do at home?', ['Hoe gaat het met …?', 'Ik maak me zorgen over …', 'Wat kunnen wij thuis doen?']],
    ['How do you learn Dutch best? Give advice to a beginner.', 'Ik leer het beste door elke dag een kwartier te oefenen en veel te luisteren. Mijn advies: stel het niet uit, praat met je buren, en maak je niet druk over fouten.', 'I learn best by practising a quarter of an hour every day and listening a lot. My advice: do not put it off, talk to your neighbours, and do not worry about mistakes.', ['Ik leer het beste door … te …', 'Mijn advies: …']],
    ['Should Dutch lessons be free for all newcomers?', 'Ja, volgens mij wel. Wie de taal spreekt, vindt sneller werk en heeft minder hulp nodig. Op de lange termijn verdient de overheid dat geld dus terug.', 'Yes, in my view. Whoever speaks the language finds work faster and needs less help. In the long term the government therefore earns that money back.', ['Volgens mij wel / niet', 'Wie …, …', 'Op de lange termijn …']],
  ]);
  topic('t-relaties', 'Neighbours, friends and small talk', 'B1', '\u{1F91D}', [
    ['You have new neighbours. Introduce yourself and say something about the street.', 'Hoi, ik ben Sam, ik woon op nummer twaalf. Welkom in de straat! Het is hier rustig, en op zaterdag is er een markt om de hoek. Als je iets nodig hebt, bel gewoon aan.', 'Hi, I am Sam, I live at number twelve. Welcome to the street! It is quiet here, and on Saturdays there is a market around the corner. If you need anything, just ring the bell.', ['Ik ben …, ik woon op …', 'Welkom …', 'Als je iets nodig hebt, …']],
    ['Complain politely to a neighbour about noise at night.', 'Sorry dat ik stoor. Gisteravond was de muziek tot twee uur erg hard, en ik moest vroeg op. Zou het na elf uur wat zachter kunnen? Alvast bedankt.', 'Sorry to disturb you. Last night the music was very loud until two, and I had to get up early. Could it be a bit quieter after eleven? Thanks in advance.', ['Sorry dat ik stoor', 'Gisteravond …', 'Zou het … kunnen?']],
    ['Make small talk at the coffee machine about the weekend.', 'Hé, hoe was je weekend? Bij mij was het lekker rustig, hoor. We zijn naar Haarlem gefietst en het weer viel wel mee. En jij, nog iets leuks gedaan?', 'Hey, how was your weekend? Mine was nice and quiet. We cycled to Haarlem and the weather was not so bad. And you, did you do anything fun?', ['Hoe was je weekend?', '… lekker rustig, hoor', 'En jij?']],
    ['Is it hard to make Dutch friends? Give your experience.', 'In het begin vond ik het moeilijk. Nederlanders zijn vriendelijk, maar ze plannen alles weken van tevoren. Sinds ik bij een sportclub zit, gaat het veel beter; daar zie je dezelfde mensen elke week.', 'At first I found it hard. Dutch people are friendly, but they plan everything weeks ahead. Since I joined a sports club it has gone much better; there you see the same people every week.', ['In het begin vond ik het …', 'Nederlanders zijn …, maar …', 'Sinds ik …, gaat het …']],
  ]);

  topic('t-wonen-b2', 'Housing and the city', 'B2', '\u{1F3D9}️', [
    ['Analyse the housing shortage: causes and one possible solution.', 'De woningnood heeft meerdere oorzaken: er is jarenlang te weinig gebouwd, de bevolking groeit, en huizen zijn een beleggingsobject geworden. Eén oplossing zou zijn om bouwgrond sneller vrij te geven, mits er vooral betaalbare woningen worden gebouwd en niet alleen dure appartementen.', 'The housing shortage has several causes: too little has been built for years, the population is growing, and houses have become an investment object. One solution would be to release building land faster, provided mainly affordable homes are built and not only expensive flats.', ['… heeft meerdere oorzaken: …', 'Eén oplossing zou zijn om …', 'mits …']],
    ['Should the city centre become car-free? Argue with two reasons and a counterargument.', 'Ik ben daar voorstander van. Ten eerste wordt de lucht schoner en de straat veiliger. Ten tweede laten steden als Gent zien dat winkels er per saldo van profiteren. Tegenstanders wijzen op ouderen en bezorgers; dat mag zo zijn, maar daarvoor kun je uitzonderingen en venstertijden regelen.', 'I am in favour. First, the air becomes cleaner and the street safer. Second, cities like Ghent show that shops benefit on balance. Opponents point to the elderly and delivery drivers; that may be so, but for them you can arrange exceptions and time windows.', ['Ten eerste … Ten tweede …', 'Tegenstanders wijzen op …', 'Dat mag zo zijn, maar …']],
    ['Describe how your neighbourhood has changed and what you expect.', 'Toen ik hier kwam wonen, waren er nog een bakker en een groenteboer; die zijn vervangen door koffiezaken. De huren zijn sterk gestegen. Ik verwacht dat de buurt nog duurder wordt, tenzij de gemeente ingrijpt.', 'When I came to live here there were still a baker and a greengrocer; they have been replaced by coffee bars. Rents have risen sharply. I expect the neighbourhood to become even more expensive, unless the municipality intervenes.', ['Toen ik hier kwam wonen, …', '… zijn vervangen door …', 'Ik verwacht dat …, tenzij …']],
    ['Write to the council in your head: one request about your street, with facts.', 'Geachte heer, mevrouw. Namens de bewoners van de Javastraat vraag ik uw aandacht voor de kapotte straatverlichting. Sinds februari zijn drie lantaarnpalen defect; hiervan is op 3 en 20 februari een melding gedaan. Wij verzoeken u de verlichting binnen twee weken te herstellen.', 'Dear Sir or Madam. On behalf of the residents of the Javastraat I ask your attention for the broken street lighting. Since February three lampposts have been out of order; this was reported on 3 and 20 February. We request you to repair the lighting within two weeks.', ['Namens … vraag ik uw aandacht voor …', 'Sinds … ; hiervan is … een melding gedaan', 'Wij verzoeken u … te …']],
  ]);
  topic('t-gezondheid-b2', 'Health care and choices', 'B2', '\u{1FA7A}', [
    ['Explain the Dutch health system and give one point of criticism.', 'Iedereen is verplicht verzekerd bij een private verzekeraar, met een eigen risico; de huisarts is de poortwachter voor de specialist. Het systeem is goed georganiseerd, maar de wachttijden in de geestelijke gezondheidszorg zijn onaanvaardbaar lang.', 'Everyone is obliged to be insured with a private insurer, with an excess; the GP is the gatekeeper for the specialist. The system is well organised, but the waiting times in mental health care are unacceptably long.', ['Iedereen is verplicht …', '… is de poortwachter voor …', '… maar … onaanvaardbaar …']],
    ['Should unhealthy food be taxed more heavily? Weigh up and conclude.', 'Enerzijds zou een suikertaks het verbruik verlagen; in landen die het invoerden, daalde de verkoop van frisdrank. Anderzijds treft zo’n belasting vooral lage inkomens. Ik ben voor, mits de opbrengst wordt gebruikt om gezond eten goedkoper te maken.', 'On the one hand a sugar tax would lower consumption; in countries that introduced it, sales of soft drinks fell. On the other hand such a tax mainly hits low incomes. I am in favour, provided the proceeds are used to make healthy food cheaper.', ['Enerzijds …, anderzijds …', 'Ik ben voor, mits …']],
    ['A friend hesitates to see a psychologist. Advise them.', 'Ik zou je aanraden om er niet mee te wachten. Je huisarts kan je doorverwijzen, en het is niets om je voor te schamen; één op de vier mensen krijgt er ooit mee te maken. Als de wachtlijst lang is, kan de praktijkondersteuner je vaak al helpen.', 'I would advise you not to wait with it. Your GP can refer you, and it is nothing to be ashamed of; one in four people has to deal with it at some point. If the waiting list is long, the practice nurse can often already help you.', ['Ik zou je aanraden om …', '… is niets om je voor te schamen', 'Als …, kan …']],
    ['Explain to a doctor that you want a second opinion, politely but firmly.', 'Ik waardeer uw uitleg, maar ik twijfel nog over de operatie. Ik zou graag een second opinion willen vragen voordat ik een besluit neem. Kunt u mij daarvoor doorverwijzen, of moet ik dat via de huisarts regelen?', 'I appreciate your explanation, but I still have doubts about the operation. I would like to ask for a second opinion before I take a decision. Can you refer me for that, or do I have to arrange it through my GP?', ['Ik waardeer …, maar …', 'Ik zou graag … willen …', 'Kunt u …, of moet ik …?']],
  ]);
  topic('t-actualiteit', 'Current affairs: reacting to the news', 'B2', '\u{1F4E1}', [
    ['Summarise a news story of this week and give your view in one sentence.', 'Deze week besloot de gemeente de parkeertarieven in het centrum te verdubbelen. Voorstanders zeggen dat het de drukte vermindert; ondernemers vrezen omzetverlies. Ik vind het verdedigbaar, mits de opbrengst naar beter openbaar vervoer gaat.', 'This week the municipality decided to double parking rates in the centre. Supporters say it reduces congestion; business owners fear a loss of turnover. I find it defensible, provided the proceeds go to better public transport.', ['Deze week besloot …', 'Voorstanders …; … vrezen …', 'Ik vind het …, mits …']],
    ['React to a statement in a talk show: "Jongeren willen niet meer werken."', 'Dat is een overhaaste generalisatie. Uit cijfers blijkt dat jongeren juist meer bijbanen hebben dan tien jaar geleden. Wat wel is veranderd, is dat ze meer waarde hechten aan vrije tijd. Dat is iets anders dan niet willen werken.', 'That is a hasty generalisation. Figures show that young people actually have more side jobs than ten years ago. What has changed is that they attach more value to free time. That is something different from not wanting to work.', ['Dat is een overhaaste generalisatie', 'Uit cijfers blijkt dat …', 'Wat wel is veranderd, is …']],
    ['Explain a graph: unemployment fell, then rose slightly. What could be the cause?', 'De werkloosheid daalde tussen 2015 en 2022 tot ruim drie procent, het laagste niveau in decennia. Sindsdien stijgt ze licht. Een mogelijke verklaring is de hogere rente, waardoor bedrijven minder investeren en voorzichtiger aannemen.', 'Unemployment fell between 2015 and 2022 to just over three per cent, the lowest level in decades. Since then it has risen slightly. A possible explanation is the higher interest rate, as a result of which companies invest less and hire more cautiously.', ['… daalde tussen … en … tot …', 'Sindsdien …', 'Een mogelijke verklaring is …, waardoor …']],
    ['Is the news too negative? Give a nuanced answer.', 'Ten dele. Nieuws gaat per definitie over wat afwijkt, en dat is vaak slecht nieuws. Toch zie ik ook een verandering: steeds meer redacties brengen bewust oplossingen in beeld. Wie alleen de koppen leest, krijgt een somber beeld; wie doorleest, meestal een genuanceerder.', 'Partly. News by definition is about what deviates, and that is often bad news. Still I also see a change: more and more editorial teams consciously show solutions. Whoever only reads the headlines gets a gloomy picture; whoever reads on, usually a more nuanced one.', ['Ten dele', '… per definitie …', 'Toch zie ik ook …', 'Wie …, …; wie …, …']],
  ]);
})();
