/* Stage 5 — Fluency and maintenance: speaking topics with model answers, weekly challenges, vocabulary-bank themes.
   The bank's extra words live in stage5-bank.js. The engine for all of this is js/engine/fluency.js. */
(function () {
  'use strict';
  const NL = window.NL, A = NL.contentApi;
  const C = NL.content;

  /* ------------------------------------------------------------ speaking topics
     topic: { id, title, level:'A1'|'A2'|'B1'|'B2', icon, prompts:[{ prompt, model, modelEn, hints? }] } */
  const talk = (C.talk = []);
  const topic = (id, title, level, icon, prompts) => talk.push({ id, title, level, icon, prompts: prompts.map(([prompt, model, modelEn, hints]) => ({ prompt, model, modelEn, hints })) });

  topic('t-mezelf', 'Myself', 'A1', '\u{1F44B}', [
    ['Introduce yourself: name, where you come from, where you live.', 'Ik ben Sam. Ik kom uit Engeland en ik woon sinds twee jaar in Amsterdam.', 'I am Sam. I come from England and I have lived in Amsterdam for two years.', ['Ik ben …', 'Ik kom uit …', 'Ik woon in …']],
    ['Talk about your family.', 'Ik heb een broer en een zus. Mijn ouders wonen in Leeds. Mijn zus is getrouwd en heeft twee kinderen.', 'I have a brother and a sister. My parents live in Leeds. My sister is married and has two children.', ['Ik heb …', 'Mijn … woont in …']],
    ['What do you do on a normal day?', 'Ik sta om zeven uur op. Ik fiets naar mijn werk. ’s Avonds kook ik en kijk ik een serie.', 'I get up at seven. I cycle to work. In the evening I cook and watch a series.', ['Ik sta om … op', '’s Avonds …']],
    ['What do you like and not like?', 'Ik hou van koffie en van fietsen. Ik vind regen niet leuk, maar ik vind Amsterdam wel mooi.', 'I love coffee and cycling. I do not like rain, but I do find Amsterdam beautiful.', ['Ik hou van …', 'Ik vind … (niet) leuk']],
  ]);
  topic('t-eten', 'Food and shopping', 'A1', '\u{1F9C0}', [
    ['What do you eat for breakfast and lunch?', 'Ik ontbijt met brood en kaas en ik drink koffie. Tussen de middag eet ik meestal een broodje.', 'I have bread and cheese for breakfast and I drink coffee. At midday I usually eat a sandwich.', ['Ik ontbijt met …', 'Tussen de middag …']],
    ['Order something in a café.', 'Goedemiddag. Mag ik een cappuccino en een stuk appeltaart, alstublieft? En mag ik daarna de rekening?', 'Good afternoon. May I have a cappuccino and a piece of apple pie, please? And may I have the bill afterwards?', ['Mag ik …, alstublieft?', 'de rekening']],
    ['Where do you do your shopping, and what do you buy?', 'Ik doe boodschappen bij de supermarkt op de hoek. Op zaterdag ga ik naar de markt voor groente, fruit en kaas.', 'I do my shopping at the supermarket on the corner. On Saturdays I go to the market for vegetables, fruit and cheese.', ['Ik doe boodschappen bij …', 'Op zaterdag …']],
    ['What is your favourite dish? Describe it.', 'Mijn lievelingseten is pasta met tomatensaus. Het is makkelijk en lekker. Ik eet het vaak op vrijdag.', 'My favourite food is pasta with tomato sauce. It is easy and tasty. I often eat it on Fridays.', ['Mijn lievelingseten is …', 'Het is …']],
  ]);
  topic('t-stad', 'My neighbourhood', 'A1', '\u{1F6B2}', [
    ['Describe the street or neighbourhood where you live.', 'Ik woon in een rustige straat in Oost. Er is een bakker, een park en een tramhalte. De buren zijn aardig.', 'I live in a quiet street in East. There is a bakery, a park and a tram stop. The neighbours are nice.', ['Ik woon in …', 'Er is / er zijn …']],
    ['How do you get to work or school?', 'Ik ga met de fiets naar mijn werk. Het is twintig minuten. Als het regent, neem ik de tram.', 'I go to work by bike. It is twenty minutes. When it rains, I take the tram.', ['Ik ga met de … naar …', 'Als het regent …']],
    ['Give directions from your house to the nearest supermarket.', 'Je gaat de straat uit en dan linksaf. Bij het stoplicht ga je rechtdoor. De supermarkt is aan de rechterkant.', 'You go out of the street and then turn left. At the traffic light you go straight on. The supermarket is on the right.', ['linksaf, rechtsaf, rechtdoor', 'aan de rechterkant']],
    ['What do you like about your city?', 'Ik vind de grachten mooi en ik hou van de markten. Alles is dichtbij en je kunt overal fietsen.', 'I find the canals beautiful and I love the markets. Everything is close and you can cycle everywhere.', ['Ik vind … mooi', 'Je kunt …']],
  ]);

  topic('t-weekend', 'Last weekend', 'A2', '\u{1F4C5}', [
    ['What did you do last weekend?', 'Zaterdag heb ik boodschappen gedaan en ’s avonds ben ik met vrienden uit eten gegaan. Zondag heb ik lang geslapen en een wandeling gemaakt.', 'On Saturday I did the shopping and in the evening I went out for dinner with friends. On Sunday I slept in and went for a walk.', ['Zaterdag heb ik …', 'Zondag ben ik …']],
    ['Tell about a trip you made.', 'Vorig jaar ben ik naar Lissabon gevlogen. Ik heb de stad bekeken, veel vis gegeten en in zee gezwommen. Het was prachtig weer.', 'Last year I flew to Lisbon. I looked around the city, ate a lot of fish and swam in the sea. The weather was wonderful.', ['Ik ben naar … gegaan', 'Ik heb … gezien']],
    ['Tell about something that went wrong recently.', 'Vorige week heb ik mijn trein gemist. Ik stond op het verkeerde perron. Gelukkig kwam er na een half uur een nieuwe trein.', 'Last week I missed my train. I was on the wrong platform. Luckily there was a new train after half an hour.', ['Vorige week …', 'Gelukkig …']],
    ['What are your plans for next weekend?', 'Volgend weekend ga ik naar Utrecht. Ik ga een vriendin bezoeken en we gaan samen naar een concert.', 'Next weekend I am going to Utrecht. I am going to visit a friend and we are going to a concert together.', ['Volgend weekend ga ik …', 'We gaan …']],
  ]);
  topic('t-dokter', 'At the doctor', 'A2', '\u{1FA7A}', [
    ['Phone the practice and make an appointment.', 'Goedemorgen, met Sam Taylor. Ik wil graag een afspraak maken met de huisarts. Ik heb al een week keelpijn en sinds gisteren koorts.', 'Good morning, Sam Taylor speaking. I would like to make an appointment with the GP. I have had a sore throat for a week and a fever since yesterday.', ['Ik wil graag …', 'Ik heb al …']],
    ['Describe your symptoms to the doctor.', 'Ik voel me al vier dagen niet goed. Ik heb hoofdpijn, ik ben moe en ’s ochtends ben ik misselijk. Het wordt niet beter.', 'I have not felt well for four days. I have a headache, I am tired and in the morning I am nauseous. It is not getting better.', ['Ik voel me …', 'Ik heb … pijn']],
    ['Ask questions about a medicine.', 'Hoe vaak moet ik de tabletten innemen? Heeft het medicijn bijwerkingen? En mag ik erbij autorijden?', 'How often do I have to take the tablets? Does the medicine have side effects? And may I drive while taking it?', ['Hoe vaak …?', 'Heeft het … bijwerkingen?']],
    ['Call in sick at work.', 'Goedemorgen, met Sam. Ik meld me vandaag ziek. Ik heb griep en ik verwacht dat ik donderdag weer kom.', 'Good morning, Sam here. I am calling in sick today. I have the flu and I expect to be back on Thursday.', ['Ik meld me ziek', 'Ik verwacht dat …']],
  ]);
  topic('t-wonen', 'Housing and the gemeente', 'A2', '\u{1F3E0}', [
    ['Describe your home.', 'Ik woon in een appartement op de tweede verdieping. Er zijn drie kamers en een klein balkon. Er is geen lift, maar het is wel licht.', 'I live in a flat on the second floor. There are three rooms and a small balcony. There is no lift, but it is bright.', ['Er zijn …', 'Er is geen …']],
    ['Ask a neighbour for a favour.', 'Hoi, ik ben Sam van nummer 12. Zou je morgen een pakketje voor mij kunnen aannemen? Ik ben de hele dag weg.', 'Hi, I am Sam from number 12. Could you take in a parcel for me tomorrow? I am away all day.', ['Zou je … kunnen …?', 'voor mij']],
    ['Explain at the gemeente why you have come.', 'Goedemorgen. Ik ben hier om me in te schrijven. Ik ben vorige week verhuisd en ik heb mijn paspoort en mijn huurcontract bij me.', 'Good morning. I am here to register. I moved last week and I have my passport and my rental contract with me.', ['Ik ben hier om … te …', 'Ik heb … bij me']],
    ['Complain politely about noise.', 'Sorry dat ik stoor. Gisteravond was de muziek erg hard en ik kon niet slapen. Zou het na elf uur wat zachter kunnen?', 'Sorry to disturb you. Last night the music was very loud and I could not sleep. Could it be a bit quieter after eleven?', ['Sorry dat ik stoor', 'Zou het … kunnen?']],
  ]);
  topic('t-werk', 'My work', 'A2', '\u{1F4BC}', [
    ['What kind of work do you do, and why do you like it or not?', 'Ik werk als ontwerper bij een klein bureau. Ik vind het leuk omdat ik creatief kan zijn, maar de deadlines zijn soms te krap.', 'I work as a designer at a small agency. I like it because I can be creative, but the deadlines are sometimes too tight.', ['Ik werk als … bij …', 'omdat …']],
    ['Describe your working day tomorrow.', 'Morgen heb ik om negen uur overleg. Daarna moet ik een verslag afmaken. ’s Middags geef ik een presentatie en om vijf uur ga ik naar huis.', 'Tomorrow I have a meeting at nine. After that I have to finish a report. In the afternoon I am giving a presentation and at five I am going home.', ['Morgen heb ik …', 'Daarna moet ik …']],
    ['Tell about your career so far.', 'Eerst heb ik in Manchester gestudeerd. Daarna heb ik drie jaar bij een krant gewerkt. Toen ben ik naar Nederland verhuisd. Sinds 2024 werk ik hier.', 'First I studied in Manchester. After that I worked at a newspaper for three years. Then I moved to the Netherlands. Since 2024 I have worked here.', ['Eerst …', 'Daarna …', 'Sinds …']],
    ['Ask your manager for a day off.', 'Heb je even tijd? Ik wil graag volgende week vrijdag een dag vrij nemen, omdat mijn ouders op bezoek komen. Komt dat uit?', 'Do you have a moment? I would like to take next Friday off, because my parents are visiting. Is that convenient?', ['Ik wil graag …', 'Komt dat uit?']],
  ]);

  topic('t-nieuws', 'In the news', 'B1', '\u{1F4F0}', [
    ['Summarise a news item you saw this week.', 'Ik las een artikel over de woningnood. De maatregelen die de gemeente neemt, zijn volgens veel mensen niet genoeg. De huren, die al jaren stijgen, blijven een probleem.', 'I read an article about the housing shortage. The measures the municipality is taking are, according to many people, not enough. Rents, which have been rising for years, remain a problem.', ['Ik las een artikel over …', 'Volgens …']],
    ['What is the biggest problem in your city, in your opinion?', 'Volgens mij is de woningmarkt het grootste probleem. Jonge mensen kunnen bijna geen betaalbare woning vinden. Er wordt te weinig gebouwd.', 'In my view the housing market is the biggest problem. Young people can hardly find an affordable home. Too little is being built.', ['Volgens mij …', 'Er wordt …']],
    ['How do you follow the news, and which sources do you trust?', 'Ik lees elke ochtend het nieuws op mijn telefoon en ik luister naar de radio. Ik vertrouw vooral de publieke omroep, omdat die bronnen noemt.', 'Every morning I read the news on my phone and I listen to the radio. I mainly trust the public broadcaster, because it names its sources.', ['Ik lees …', 'Ik vertrouw … omdat …']],
    ['Should voting be compulsory? Give your opinion.', 'Ik vind dat stemmen niet verplicht moet zijn. Aan de ene kant is het belangrijk dat iedereen meedoet, aan de andere kant heeft een gedwongen stem weinig waarde.', 'I think voting should not be compulsory. On the one hand it is important that everyone takes part, on the other hand a forced vote has little value.', ['Ik vind dat …', 'Aan de ene kant …, aan de andere kant …']],
  ]);
  topic('t-gezond', 'Health and lifestyle', 'B1', '\u{1F957}', [
    ['A friend is always tired. Give advice.', 'Als ik jou was, zou ik eerder naar bed gaan. Je zou ook minder koffie moeten drinken. En je zou eens kunnen proberen om elke dag te wandelen.', 'If I were you, I would go to bed earlier. You should also drink less coffee. And you could try walking every day.', ['Als ik jou was, zou ik …', 'Je zou … moeten …']],
    ['Tell about a habit you changed.', 'Ik eet geen vlees meer. Ik ben nog niet helemaal vegetariër, want ik eet wel eens vis. Ik ontbijt nooit, dat moet ik nog veranderen.', 'I no longer eat meat. I am not fully vegetarian yet, because I sometimes eat fish. I never have breakfast, I still have to change that.', ['Ik … niet meer', 'Ik … nog niet']],
    ['What would you do if you had one extra free day every week?', 'Als ik een extra vrije dag had, zou ik meer sporten en een cursus volgen. Ik zou ook vaker mijn familie bezoeken.', 'If I had an extra day off, I would exercise more and take a course. I would also visit my family more often.', ['Als ik … had, zou ik …']],
    ['Is the Dutch healthcare system good? Compare it with your country.', 'Ik vind het systeem goed geregeld, hoewel het duur is. In mijn land hoef je geen verzekering af te sluiten, maar de wachttijden zijn er langer.', 'I think the system is well organised, although it is expensive. In my country you do not have to take out insurance, but the waiting times are longer there.', ['hoewel …', 'In mijn land …']],
  ]);
  topic('t-cultuur', 'Dutch habits', 'B1', '\u{1F9E1}', [
    ['Which Dutch custom surprised you most?', 'Ik was verbaasd dat je op je verjaardag zelf moet trakteren. Ook de directheid vond ik in het begin moeilijk, maar het valt wel mee.', 'I was surprised that on your birthday you have to bring the treats yourself. I also found the directness hard at first, but it is not so bad.', ['Ik was verbaasd dat …', 'het valt wel mee']],
    ['Explain a tradition from your own country.', 'In mijn land vieren we in november Bonfire Night. Er wordt vuurwerk afgestoken en er worden grote vuren gemaakt. Het herinnert aan een gebeurtenis uit 1605.', 'In my country we celebrate Bonfire Night in November. Fireworks are set off and big fires are made. It commemorates an event from 1605.', ['We vieren …', 'Er wordt / worden …']],
    ['What happens on 4 and 5 May, and why?', 'Op 4 mei worden de doden herdacht; om acht uur is het twee minuten stil. Op 5 mei vieren we de bevrijding van 1945.', 'On 4 May the dead are commemorated; at eight o’clock there are two minutes of silence. On 5 May we celebrate the liberation of 1945.', ['worden … herdacht', 'vieren']],
    ['Do you feel at home in the Netherlands? Why or why not?', 'Ik voel me hier steeds meer thuis. Sinds ik Nederlands spreek, heb ik meer contact met mijn buren. Wat ik nog mis, is de spontaniteit.', 'I feel more and more at home here. Since I have spoken Dutch, I have had more contact with my neighbours. What I still miss is spontaneity.', ['Ik voel me …', 'Sinds ik …']],
  ]);
  topic('t-vergadering', 'Meetings and work talk', 'B1', '\u{1F5C2}️', [
    ['Make a proposal in a meeting and give one reason.', 'Ik stel voor dat we de lancering een kwartaal uitstellen. Dit kwartaal is dat niet haalbaar, want de begroting is te krap. Zijn we het daarover eens?', 'I propose that we postpone the launch by a quarter. This quarter that is not feasible, because the budget is too tight. Are we agreed on that?', ['Ik stel voor dat …', 'Zijn we het daarover eens?']],
    ['Disagree politely with a colleague.', 'Mag ik daar even op reageren? Ik begrijp je punt, maar ik zie het anders. Volgens mij kost het meer tijd dan je denkt.', 'May I respond to that? I understand your point, but I see it differently. In my view it takes more time than you think.', ['Mag ik daar even op reageren?', 'Ik zie het anders']],
    ['Summarise a meeting and divide the tasks.', 'Even samenvatten: we verzetten de deadline naar 22 mei. Anna maakt de planning en Tom vraagt de offerte aan. Ik stuur vanmiddag de notulen.', 'To summarise: we are moving the deadline to 22 May. Anna makes the planning and Tom requests the quotation. I will send the minutes this afternoon.', ['Even samenvatten: …', 'Ik stuur …']],
    ['Leave a voicemail for a client.', 'Goedemiddag, met Sam Taylor van bureau Noord. Ik bel over de offerte die ik u dinsdag heb gestuurd. Zou u mij kunnen terugbellen op 06 12 34 56 78?', 'Good afternoon, Sam Taylor from Noord agency. I am calling about the quotation I sent you on Tuesday. Could you call me back on 06 12 34 56 78?', ['Ik bel over …', 'Zou u mij kunnen terugbellen?']],
  ]);

  topic('t-stelling-werk', 'Debate: the four-day week', 'B2', '\u{2696}️', [
    ['Give your opinion on a four-day working week, with two arguments.', 'Volgens mij zou een vierdaagse werkweek de norm moeten worden, en wel om twee redenen. Ten eerste blijft de productiviteit gelijk, zo blijkt uit proeven. Ten tweede hebben mensen meer tijd voor zorg en scholing.', 'In my view a four-day working week should become the norm, for two reasons. First, productivity stays the same, as trials show. Second, people have more time for care and training.', ['en wel om twee redenen', 'Ten eerste … Ten tweede …']],
    ['Name the strongest counterargument and refute it.', 'Tegenstanders wijzen erop dat niet elk beroep zich ervoor leent. Dat mag zo zijn, maar een kortere werkweek betekent niet dat de organisatie sluit, wel dat het werk anders wordt verdeeld.', 'Opponents point out that not every profession lends itself to it. That may be so, but a shorter working week does not mean the organisation closes, only that the work is divided differently.', ['Tegenstanders …', 'Dat mag zo zijn, maar …']],
    ['Conclude your argument in two sentences.', 'Al met al wegen de voordelen ruimschoots op tegen de praktische bezwaren. Daarom pleit ik ervoor dat de overheid de vierdaagse werkweek actief stimuleert.', 'All in all the advantages amply outweigh the practical objections. That is why I argue that the government should actively encourage the four-day working week.', ['Al met al …', 'Daarom pleit ik ervoor dat …']],
    ['Advise a manager who doubts the idea.', 'Ik zou u aanraden om met één afdeling een proef van een halfjaar te doen. Als de resultaten gelijk blijven, kunt u de regeling uitbreiden; zo niet, dan is er weinig verloren.', 'I would advise you to run a six-month trial with one department. If the results stay the same, you can extend the scheme; if not, little is lost.', ['Ik zou u aanraden om …', 'Als …, kunt u …']],
  ]);
  topic('t-technologie', 'Technology and society', 'B2', '\u{1F916}', [
    ['How is artificial intelligence changing your field?', 'In mijn vak wordt steeds meer routinewerk door software overgenomen. Dat bespaart tijd, maar het betekent ook dat je je voortdurend moet bijscholen.', 'In my field more and more routine work is being taken over by software. That saves time, but it also means you constantly have to retrain.', ['wordt … overgenomen', 'Dat betekent dat …']],
    ['Should social media be banned for children under 15?', 'Enerzijds begrijp ik de zorgen over slaap en concentratie. Anderzijds is een verbod moeilijk te handhaven. Ik pleit daarom voor strengere regels voor de bedrijven zelf.', 'On the one hand I understand the worries about sleep and concentration. On the other hand a ban is hard to enforce. I therefore argue for stricter rules for the companies themselves.', ['Enerzijds … anderzijds …', 'Ik pleit voor …']],
    ['Summarise a study you read about, including its limits.', 'Uit het onderzoek blijkt dat mensen die hun telefoon in bed gebruiken later in slaap vallen. Een oorzakelijk verband kon echter niet worden aangetoond, dus we moeten voorzichtig zijn met conclusies.', 'The study shows that people who use their phone in bed fall asleep later. A causal link could, however, not be demonstrated, so we have to be careful with conclusions.', ['Uit het onderzoek blijkt dat …', 'echter']],
    ['What should the government do about privacy?', 'Naar mijn mening moet het toezicht op techbedrijven worden versterkt. Gegevensbescherming is wettelijk geregeld, maar zolang de controle tekortschiet, heeft de wet weinig effect.', 'In my opinion oversight of tech companies must be strengthened. Data protection is regulated by law, but as long as enforcement falls short, the law has little effect.', ['Naar mijn mening …', 'zolang …']],
  ]);
  topic('t-loopbaan', 'Career and regrets', 'B2', '\u{1F9ED}', [
    ['Tell your career story with its turning points.', 'Toen ik naar Nederland kwam, had ik al zes jaar als ontwerper gewerkt. Na de reorganisatie heb ik het roer omgegooid en me laten omscholen. Achteraf had ik dat eerder moeten doen.', 'When I came to the Netherlands, I had already worked as a designer for six years. After the reorganisation I changed course and retrained. In retrospect I should have done that earlier.', ['Toen ik …, had ik al …', 'Achteraf had ik … moeten …']],
    ['What would you have done differently?', 'Als ik eerder Nederlands had geleerd, was ik waarschijnlijk sneller doorgegroeid. Had ik maar meteen een cursus gevolgd! Toch heb ik er geen spijt van dat ik gekomen ben.', 'If I had learned Dutch earlier, I would probably have progressed faster. If only I had taken a course straight away! Still I do not regret coming.', ['Als ik … had …, was ik …', 'Had ik maar …']],
    ['Answer the interview question: what are your strengths and weaknesses?', 'Een sterk punt van mij is dat ik goed kan plannen. Mijn valkuil is dat ik soms te veel hooi op mijn vork neem, maar ik heb geleerd taken te verdelen.', 'One of my strengths is that I plan well. My weakness is that I sometimes take on too much, but I have learned to delegate.', ['Een sterk punt van mij is …', 'Mijn valkuil is …']],
    ['Where will you be in five years?', 'Over vijf jaar zal ik hopelijk zijn doorgegroeid tot teamleider. Tegen die tijd wil ik ook het staatsexamen hebben gehaald en een huis hebben gekocht.', 'In five years I will hopefully have progressed to team leader. By then I also want to have passed the state exam and bought a house.', ['Over vijf jaar zal ik …', 'Tegen die tijd …']],
  ]);
  topic('t-examen', 'Exam-style speaking tasks', 'B2', '\u{1F393}', [
    ['Short task: a colleague wants to stop his Dutch course because he is too busy. Advise him.', 'Ik begrijp dat je het druk hebt, maar ik zou je aanraden om niet te stoppen. Misschien kun je tijdelijk één avond per week doen in plaats van twee. Dan blijf je vooruitgaan zonder dat het te zwaar wordt.', 'I understand that you are busy, but I would advise you not to stop. Maybe you can temporarily do one evening a week instead of two. Then you keep progressing without it becoming too heavy.', ['Ik begrijp dat …, maar …', 'Ik zou je aanraden om …']],
    ['Short task: you are late for an appointment at the gemeente. Phone and explain.', 'Goedemorgen, met Sam Taylor. Ik heb om tien uur een afspraak, maar door een storing bij de NS kom ik een kwartier later. Kan de afspraak doorgaan, of moet ik een nieuwe maken?', 'Good morning, Sam Taylor speaking. I have an appointment at ten, but because of a disruption on the railways I will be a quarter of an hour late. Can the appointment go ahead, or do I have to make a new one?', ['Ik heb om … een afspraak', 'door een storing']],
    ['Long task: should all children learn programming at primary school?', 'Volgens mij is dat een goed idee, en wel om twee redenen. Ten eerste wordt technologie steeds belangrijker op de arbeidsmarkt. Ten tweede leer je door programmeren logisch denken. Tegenstanders zeggen dat er te weinig tijd is voor lezen en rekenen. Dat mag zo zijn, maar programmeren kan juist in die vakken worden geïntegreerd. Kortom, ik ben voor, mits leraren goed worden opgeleid.', 'In my view that is a good idea, for two reasons. First, technology is becoming ever more important on the labour market. Second, programming teaches logical thinking. Opponents say there is too little time for reading and arithmetic. That may be so, but programming can be integrated into those subjects. In short, I am in favour, provided teachers are trained well.', ['Volgens mij …, en wel om twee redenen', 'Dat mag zo zijn, maar …', 'Kortom, …']],
    ['Long task: describe a graph or trend you know and explain the cause.', 'Het aantal mensen dat thuiswerkt is de laatste jaren sterk toegenomen. Dat komt doordat bedrijven tijdens de pandemie hebben ontdekt dat het kan. Als gevolg daarvan staan veel kantoren half leeg, terwijl de vraag naar grotere woningen juist is gestegen.', 'The number of people working from home has risen sharply in recent years. That is because companies discovered during the pandemic that it is possible. As a result many offices stand half empty, while demand for bigger homes has actually risen.', ['is … toegenomen', 'Dat komt doordat …', 'Als gevolg daarvan …']],
  ]);

  /* ---------------------------------------------------------- weekly challenges
     challenge: { id, title, icon, desc, xp, goals:[{ kind, n, min? }], tip?, links? }
     goal kinds: xp, answers, days, voice, lessons, reviews, perfect, bank, accuracy (n = percent, min = minimum answers) */
  C.challenges = [
    { id: 'c-ritme', title: 'Vijf dagen ritme', icon: '\u{1F4C6}', desc: 'Little and often beats one long session. Practise on five different days this week.', xp: 150, goals: [{ kind: 'days', n: 5 }, { kind: 'xp', n: 300 }], tip: 'Ten minutes a day is enough. Put it next to something you already do every day, like your morning coffee.' },
    { id: 'c-herhalen', title: 'Herhaalweek', icon: '\u{1F501}', desc: 'Clear your review queue and keep it clear.', xp: 150, goals: [{ kind: 'reviews', n: 80 }, { kind: 'days', n: 4 }], links: [['Review', '#/review/go'], ['Vocabulary bank', '#/bank']] },
    { id: 'c-spreken', title: 'Praatweek', icon: '\u{1F399}️', desc: 'Say it out loud. Speaking exercises, free talk and speaking mode all count.', xp: 200, goals: [{ kind: 'voice', n: 25 }, { kind: 'days', n: 3 }], tip: 'Chrome or Edge gives you scored speech recognition. In other browsers you grade yourself, which counts too.', links: [['Free talk', '#/mode/freetalk'], ['Speaking only', '#/mode/speaking']] },
    { id: 'c-woorden', title: 'Woordenweek', icon: '\u{1F5C2}️', desc: 'Pick two themes in the vocabulary bank and work through them.', xp: 200, goals: [{ kind: 'bank', n: 60 }, { kind: 'reviews', n: 30 }], links: [['Vocabulary bank', '#/bank'], ['Review', '#/review/go']] },
    { id: 'c-lessen', title: 'Drie lessen', icon: '\u{1F4D8}', desc: 'Move forward on your path: three lessons, and at least one of them perfect.', xp: 200, goals: [{ kind: 'lessons', n: 3 }, { kind: 'perfect', n: 1 }], links: [['Home', '#/home']] },
    { id: 'c-precisie', title: 'Precisie', icon: '\u{1F3AF}', desc: 'Slow down and get it right: 85% accuracy over at least 80 answers.', xp: 200, goals: [{ kind: 'accuracy', n: 85, min: 80 }, { kind: 'days', n: 3 }], tip: 'Read the explanation after every mistake. The same errors come back in review until they are gone.' },
    { id: 'c-marathon', title: 'Kleine marathon', icon: '\u{1F3C3}', desc: 'A big week: 600 XP spread over at least four days.', xp: 250, goals: [{ kind: 'xp', n: 600 }, { kind: 'days', n: 4 }] },
    { id: 'c-allround', title: 'Allrounder', icon: '\u{1F31F}', desc: 'A bit of everything: a lesson, reviews, speaking and the vocabulary bank.', xp: 250, goals: [{ kind: 'lessons', n: 1 }, { kind: 'reviews', n: 30 }, { kind: 'voice', n: 10 }, { kind: 'bank', n: 20 }] },
    { id: 'c-elke-dag', title: 'Elke dag', icon: '\u{1F525}', desc: 'Seven days out of seven. Any amount counts.', xp: 250, goals: [{ kind: 'days', n: 7 }], tip: 'One review session of two minutes keeps the streak and the challenge alive.' },
    { id: 'c-luisteren', title: 'Antwoordweek', icon: '\u{270D}️', desc: 'Volume week: answer 250 exercises of any kind.', xp: 200, goals: [{ kind: 'answers', n: 250 }, { kind: 'days', n: 4 }], links: [['Listening only', '#/mode/listening'], ['Speed round', '#/mode/speed']] },
    { id: 'c-diep', title: 'Diepgang', icon: '\u{1F9E0}', desc: 'Two lessons, both done carefully, plus your reviews.', xp: 200, goals: [{ kind: 'lessons', n: 2 }, { kind: 'accuracy', n: 80, min: 60 }, { kind: 'reviews', n: 40 }] },
    { id: 'c-stem', title: 'Stem en woorden', icon: '\u{1F5E3}️', desc: 'Combine speaking with new vocabulary.', xp: 200, goals: [{ kind: 'voice', n: 15 }, { kind: 'bank', n: 40 }], links: [['Free talk', '#/mode/freetalk'], ['Vocabulary bank', '#/bank']] },
  ];

  /* ------------------------------------------------------- vocabulary bank groups
     group: { id, title, nl, icon, themes:[vocabulary theme keys] }. Every dictionary word whose `theme` is listed lands in
     the group; words with an unlisted theme go to "Everything else". */
  C.bank = [
    { id: 'kern', title: 'Core and grammar words', nl: 'Kernwoorden', icon: '\u{1F511}', themes: ['basics', 'grammar', 'modals', 'verbs', 'misc', 'particles', 'negation', 'comparison', 'prepositions', 'numbers', 'colours', 'adjectives', 'adverbs', 'materials'] },
    { id: 'tijd', title: 'Time and calendar', nl: 'Tijd en kalender', icon: '\u{1F552}', themes: ['time'] },
    { id: 'mensen', title: 'People, family and feelings', nl: 'Mensen, familie en gevoelens', icon: '\u{1F46A}', themes: ['people', 'family', 'social', 'greetings', 'politeness', 'feelings', 'life', 'regret', 'advice', 'character'] },
    { id: 'thuis', title: 'Home and daily life', nl: 'Thuis en dagelijks leven', icon: '\u{1F3E0}', themes: ['home', 'housing', 'daily', 'furniture', 'kitchen'] },
    { id: 'eten', title: 'Food and drink', nl: 'Eten en drinken', icon: '\u{1F9C0}', themes: ['food', 'cafe'] },
    { id: 'winkelen', title: 'Shopping, clothes and money', nl: 'Winkelen, kleding en geld', icon: '\u{1F6CD}️', themes: ['shopping', 'complaints', 'clothes', 'money', 'economy'] },
    { id: 'stad', title: 'City, transport and travel', nl: 'Stad, vervoer en reizen', icon: '\u{1F6B2}', themes: ['city', 'directions', 'places', 'regions', 'transport', 'travel', 'countries', 'accidents'] },
    { id: 'gezondheid', title: 'Health and body', nl: 'Gezondheid en lichaam', icon: '\u{1FA7A}', themes: ['health', 'body', 'appointments'] },
    { id: 'werk', title: 'Work and communication', nl: 'Werk en communicatie', icon: '\u{1F4BC}', themes: ['work', 'career', 'meetings', 'email', 'phone', 'communication', 'letters', 'professions'] },
    { id: 'studie', title: 'Study, science and technology', nl: 'Studie, wetenschap en techniek', icon: '\u{1F52C}', themes: ['education', 'study', 'exam', 'science', 'technology', 'academic'] },
    { id: 'vrije-tijd', title: 'Free time, sport and culture', nl: 'Vrije tijd, sport en cultuur', icon: '\u{1F3AD}', themes: ['hobbies', 'leisure', 'sport', 'culture', 'media', 'story', 'arts'] },
    { id: 'natuur', title: 'Nature, weather and environment', nl: 'Natuur, weer en milieu', icon: '\u{1F333}', themes: ['nature', 'weather', 'environment', 'animals'] },
    { id: 'samenleving', title: 'Society, politics and bureaucracy', nl: 'Samenleving, politiek en bureaucratie', icon: '\u{1F3DB}️', themes: ['news', 'politics', 'society', 'neighbourhood', 'history', 'bureaucracy', 'formal', 'law'] },
    { id: 'debat', title: 'Opinions, debate and the language itself', nl: 'Meningen, debat en taal', icon: '\u{1F4AC}', themes: ['opinions', 'argument', 'debate', 'writing', 'abstract', 'discourse', 'fixed', 'register', 'informal', 'spoken', 'listening', 'variation', 'errors', 'false friends'] },
    { id: 'uitdrukkingen', title: 'Idioms and proverbs', nl: 'Uitdrukkingen en spreekwoorden', icon: '\u{1F408}', themes: ['idioms', 'proverbs'] },
  ];

  /* Stage 5 is a hub, not a list of lessons: it is always open and links to review, challenges, talk topics and the bank. */
  A.stage('s5', '5', 'B2+', 'Fluency and maintenance', 'Keep it alive: daily spaced-repetition review, a new challenge every Monday, speaking topics with model answers from A1 to B2, and a themed vocabulary bank of every word in the course.', [], [], { hub: true });
})();
