/* Stage 5 — vocabulary bank: frequent words that the lessons do not teach, grouped by theme.
   Each word is a full dictionary entry (audio, example, SRS card once practised). Words that already exist keep their first definition.
   Compact helpers: n(nl, gender, plural, en, exNl, exEn) · v(nl, en, pres, past, part, aux, exNl, exEn) · w(nl, pos, en, exNl, exEn) */
(function () {
  'use strict';
  const NL = window.NL, A = NL.contentApi;
  let O = { theme: 'misc', stage: 5 };
  const theme = (t, stage) => { O = { theme: t, stage: stage || 5, bank: true }; };
  const n = (nl, g, pl, en, a, b) => A.N(nl, g, pl, en, a, b, Object.assign({}, O));
  const v = (nl, en, pres, past, part, aux, a, b) => A.VB(nl, en, pres, past, part, aux, a, b, Object.assign({}, O));
  const w = (nl, pos, en, a, b) => A.W(nl, en, pos, a, b, Object.assign({}, O));

  theme('food', 1);
  n('appel', 'de', 'appels', 'apple', 'Ik eet elke dag een appel.', 'I eat an apple every day.');
  n('banaan', 'de', 'bananen', 'banana', 'De bananen zijn nog groen.', 'The bananas are still green.');
  n('sinaasappel', 'de', 'sinaasappels', 'orange', 'Ik pers een sinaasappel.', 'I squeeze an orange.');
  n('druif', 'de', 'druiven', 'grape', 'Deze druiven zijn zoet.', 'These grapes are sweet.');
  n('aardbei', 'de', 'aardbeien', 'strawberry', 'In juni zijn er Hollandse aardbeien.', 'In June there are Dutch strawberries.');
  n('citroen', 'de', 'citroenen', 'lemon', 'Wil je citroen in je thee?', 'Do you want lemon in your tea?');
  n('peer', 'de', 'peren', 'pear', 'De peer is rijp.', 'The pear is ripe.');
  n('tomaat', 'de', 'tomaten', 'tomato', 'Ik snijd de tomaten.', 'I cut the tomatoes.');
  n('komkommer', 'de', 'komkommers', 'cucumber', 'Een halve komkommer, graag.', 'Half a cucumber, please.');
  n('wortel', 'de', 'wortels', 'carrot', 'Konijnen eten graag wortels.', 'Rabbits like eating carrots.');
  n('ui', 'de', 'uien', 'onion', 'Snijd de ui in stukjes.', 'Cut the onion into pieces.');
  n('knoflook', 'de', null, 'garlic', 'Ik doe veel knoflook in de saus.', 'I put a lot of garlic in the sauce.');
  n('sla', 'de', null, 'lettuce / salad', 'We eten sla bij de pasta.', 'We eat salad with the pasta.');
  n('paprika', 'de', "paprika's", 'bell pepper', 'Ik koop een rode paprika.', 'I buy a red pepper.');
  n('champignon', 'de', 'champignons', 'mushroom', 'Ik bak de champignons in boter.', 'I fry the mushrooms in butter.');
  n('bloemkool', 'de', 'bloemkolen', 'cauliflower', 'Bloemkool met kaassaus is lekker.', 'Cauliflower with cheese sauce is tasty.');
  n('boon', 'de', 'bonen', 'bean', 'We eten bruine bonen.', 'We are eating brown beans.');
  n('erwt', 'de', 'erwten', 'pea', 'Erwtensoep eet je in de winter.', 'You eat pea soup in winter.');
  n('rijst', 'de', null, 'rice', 'Ik kook rijst voor vier personen.', 'I am cooking rice for four people.');
  n('ei', 'het', 'eieren', 'egg', 'Ik wil een gekookt ei.', 'I want a boiled egg.');
  n('boter', 'de', null, 'butter', 'Er zit boter op het brood.', 'There is butter on the bread.');
  n('suiker', 'de', null, 'sugar', 'Koffie zonder suiker, graag.', 'Coffee without sugar, please.');
  n('zout', 'het', null, 'salt', 'Er zit te veel zout in.', 'There is too much salt in it.');
  n('peper', 'de', null, 'pepper', 'Mag ik de peper?', 'May I have the pepper?');
  n('olie', 'de', null, 'oil', 'Ik bak in olijfolie.', 'I fry in olive oil.');
  n('meel', 'het', null, 'flour', 'Voor pannenkoeken heb je meel nodig.', 'For pancakes you need flour.');
  n('kip', 'de', 'kippen', 'chicken', 'We eten kip met rijst.', 'We are eating chicken with rice.');
  n('rundvlees', 'het', null, 'beef', 'Rundvlees is duur geworden.', 'Beef has become expensive.');
  n('varkensvlees', 'het', null, 'pork', 'Ik eet geen varkensvlees.', 'I do not eat pork.');
  n('worst', 'de', 'worsten', 'sausage', 'Stamppot met worst is echt Hollands.', 'Stamppot with sausage is really Dutch.');
  n('ham', 'de', null, 'ham', 'Een broodje ham en kaas.', 'A ham and cheese roll.');
  n('zalm', 'de', 'zalmen', 'salmon', 'Ik heb zalm uit de oven gemaakt.', 'I made salmon from the oven.');
  n('haring', 'de', 'haringen', 'herring', 'Heb je ooit een haring gegeten?', 'Have you ever eaten a herring?');
  n('garnaal', 'de', 'garnalen', 'shrimp', 'Hollandse garnalen zijn klein.', 'Dutch shrimps are small.');
  n('yoghurt', 'de', null, 'yoghurt', 'Ik ontbijt met yoghurt en fruit.', 'I have yoghurt and fruit for breakfast.');
  n('room', 'de', null, 'cream', 'Wil je room in de soep?', 'Do you want cream in the soup?');
  n('honing', 'de', null, 'honey', 'Thee met honing helpt tegen keelpijn.', 'Tea with honey helps against a sore throat.');
  n('jam', 'de', null, 'jam', 'Aardbeienjam op toast.', 'Strawberry jam on toast.');
  n('pindakaas', 'de', null, 'peanut butter', 'Nederlanders eten veel pindakaas.', 'Dutch people eat a lot of peanut butter.');
  n('hagelslag', 'de', null, 'chocolate sprinkles', 'Kinderen eten hagelslag op brood.', 'Children eat chocolate sprinkles on bread.');
  n('stroopwafel', 'de', 'stroopwafels', 'syrup waffle', 'Een verse stroopwafel van de markt.', 'A fresh syrup waffle from the market.');
  n('soep', 'de', 'soepen', 'soup', 'De soep is nog te heet.', 'The soup is still too hot.');
  n('saus', 'de', 'sauzen', 'sauce', 'Welke saus wil je bij de friet?', 'Which sauce do you want with the chips?');
  n('toetje', 'het', 'toetjes', 'dessert', 'Wat is het toetje?', 'What is the dessert?');
  n('snoep', 'het', null, 'sweets', 'Te veel snoep is slecht voor je tanden.', 'Too many sweets are bad for your teeth.');
  n('noot', 'de', 'noten', 'nut', 'Ik ben allergisch voor noten.', 'I am allergic to nuts.');
  n('sap', 'het', 'sappen', 'juice', 'Een glas sap, alsjeblieft.', 'A glass of juice, please.');
  n('frisdrank', 'de', 'frisdranken', 'soft drink', 'Frisdrank bevat veel suiker.', 'Soft drinks contain a lot of sugar.');

  theme('kitchen', 2);
  n('pan', 'de', 'pannen', 'pan', 'De pan staat op het vuur.', 'The pan is on the stove.');
  n('koekenpan', 'de', 'koekenpannen', 'frying pan', 'Bak het ei in de koekenpan.', 'Fry the egg in the frying pan.');
  n('mes', 'het', 'messen', 'knife', 'Dit mes is niet scherp.', 'This knife is not sharp.');
  n('vork', 'de', 'vorken', 'fork', 'Mag ik een schone vork?', 'May I have a clean fork?');
  n('lepel', 'de', 'lepels', 'spoon', 'Roer met een houten lepel.', 'Stir with a wooden spoon.');
  n('bord', 'het', 'borden', 'plate', 'Zet de borden op tafel.', 'Put the plates on the table.');
  n('kom', 'de', 'kommen', 'bowl', 'Een kom soep.', 'A bowl of soup.');
  n('beker', 'de', 'bekers', 'mug / cup', 'Mijn beker is leeg.', 'My mug is empty.');
  n('oven', 'de', 'ovens', 'oven', 'Verwarm de oven voor op 200 graden.', 'Preheat the oven to 200 degrees.');
  n('koelkast', 'de', 'koelkasten', 'fridge', 'De melk staat in de koelkast.', 'The milk is in the fridge.');
  n('vriezer', 'de', 'vriezers', 'freezer', 'Er ligt brood in de vriezer.', 'There is bread in the freezer.');
  n('vaatwasser', 'de', 'vaatwassers', 'dishwasher', 'Wie ruimt de vaatwasser uit?', 'Who is emptying the dishwasher?');
  n('waterkoker', 'de', 'waterkokers', 'kettle', 'Zet de waterkoker even aan.', 'Just switch the kettle on.');
  n('snijplank', 'de', 'snijplanken', 'chopping board', 'Gebruik een aparte snijplank voor vlees.', 'Use a separate chopping board for meat.');
  n('schaal', 'de', 'schalen', 'dish / bowl', 'Doe de sla in een grote schaal.', 'Put the salad in a big bowl.');
  n('deksel', 'het', 'deksels', 'lid', 'Doe het deksel op de pan.', 'Put the lid on the pan.');
  n('afwas', 'de', null, 'washing-up', 'Wie doet de afwas?', 'Who is doing the washing-up?');
  v('snijden', 'to cut', 'snijd|snijdt|snijden', 'sneed|sneden', 'gesneden', 'hebben', 'Snijd de groente in kleine stukjes.', 'Cut the vegetables into small pieces.');
  v('roeren', 'to stir', 'roer|roert|roeren', 'roerde|roerden', 'geroerd', 'hebben', 'Blijf roeren tot de saus dik wordt.', 'Keep stirring until the sauce thickens.');
  v('braden', 'to roast / fry (meat)', 'braad|braadt|braden', 'braadde|braadden', 'gebraden', 'hebben', 'Braad het vlees tien minuten.', 'Roast the meat for ten minutes.');
  v('schillen', 'to peel', 'schil|schilt|schillen', 'schilde|schilden', 'geschild', 'hebben', 'Ik schil de aardappels.', 'I am peeling the potatoes.');
  v('proeven', 'to taste', 'proef|proeft|proeven', 'proefde|proefden', 'geproefd', 'hebben', 'Proef eens, is er genoeg zout?', 'Have a taste, is there enough salt?');
  v('afwassen', 'to wash up', 'was af|wast af|wassen af', 'waste af|wasten af', 'afgewassen', 'hebben', 'Ik was af en jij droogt af.', 'I wash up and you dry.');
  v('opwarmen', 'to heat up', 'warm op|warmt op|warmen op', 'warmde op|warmden op', 'opgewarmd', 'hebben', 'Ik warm de soep even op.', 'I will just heat up the soup.');
  v('mengen', 'to mix', 'meng|mengt|mengen', 'mengde|mengden', 'gemengd', 'hebben', 'Meng het meel met de melk.', 'Mix the flour with the milk.');

  theme('furniture', 1);
  n('stoel', 'de', 'stoelen', 'chair', 'Pak maar een stoel.', 'Grab a chair.');
  n('tafel', 'de', 'tafels', 'table', 'Het eten staat op tafel.', 'The food is on the table.');
  n('kast', 'de', 'kasten', 'cupboard / wardrobe', 'Mijn jas hangt in de kast.', 'My coat is hanging in the wardrobe.');
  n('bed', 'het', 'bedden', 'bed', 'Ik lig om elf uur in bed.', 'I am in bed at eleven.');
  n('lamp', 'de', 'lampen', 'lamp', 'Doe de lamp uit, alsjeblieft.', 'Turn the lamp off, please.');
  n('spiegel', 'de', 'spiegels', 'mirror', 'Er hangt een spiegel in de gang.', 'There is a mirror in the hall.');
  n('gordijn', 'het', 'gordijnen', 'curtain', 'Doe de gordijnen dicht.', 'Close the curtains.');
  n('vloerkleed', 'het', 'vloerkleden', 'rug', 'Het vloerkleed ligt voor de bank.', 'The rug is in front of the sofa.');
  n('plank', 'de', 'planken', 'shelf / plank', 'De boeken staan op de plank.', 'The books are on the shelf.');
  n('bureau', 'het', 'bureaus', 'desk', 'Mijn laptop staat op mijn bureau.', 'My laptop is on my desk.');
  n('kussen', 'het', 'kussens', 'cushion / pillow', 'Ik slaap met twee kussens.', 'I sleep with two pillows.');
  n('deken', 'de', 'dekens', 'blanket', 'Wil je een extra deken?', 'Do you want an extra blanket?');
  n('matras', 'het', 'matrassen', 'mattress', 'Het matras is te zacht.', 'The mattress is too soft.');
  n('wasmachine', 'de', 'wasmachines', 'washing machine', 'De wasmachine is kapot.', 'The washing machine is broken.');
  n('stofzuiger', 'de', 'stofzuigers', 'vacuum cleaner', 'Waar staat de stofzuiger?', 'Where is the vacuum cleaner?');
  n('vuilnisbak', 'de', 'vuilnisbakken', 'rubbish bin', 'De vuilnisbak is vol.', 'The bin is full.');
  n('stopcontact', 'het', 'stopcontacten', 'power socket', 'Is er een stopcontact bij het bed?', 'Is there a socket near the bed?');
  n('kraan', 'de', 'kranen', 'tap', 'De kraan lekt.', 'The tap is leaking.');
  n('plafond', 'het', 'plafonds', 'ceiling', 'Het plafond is drie meter hoog.', 'The ceiling is three metres high.');
  n('vloer', 'de', 'vloeren', 'floor', 'De vloer is nat.', 'The floor is wet.');
  n('muur', 'de', 'muren', 'wall', 'We schilderen de muur wit.', 'We are painting the wall white.');
  n('dak', 'het', 'daken', 'roof', 'Het dak lekt als het hard regent.', 'The roof leaks when it rains hard.');

  theme('clothes', 1);
  n('sok', 'de', 'sokken', 'sock', 'Ik zoek mijn andere sok.', 'I am looking for my other sock.');
  n('riem', 'de', 'riemen', 'belt', 'Deze broek heeft een riem nodig.', 'These trousers need a belt.');
  n('handschoen', 'de', 'handschoenen', 'glove', 'Neem handschoenen mee, het vriest.', 'Take gloves, it is freezing.');
  n('sjaal', 'de', 'sjaals', 'scarf', 'Ze draagt een rode sjaal.', 'She is wearing a red scarf.');
  n('muts', 'de', 'mutsen', 'woolly hat', 'Zet je muts op.', 'Put your hat on.');
  n('pet', 'de', 'petten', 'cap', 'Hij draagt altijd een pet.', 'He always wears a cap.');
  n('rok', 'de', 'rokken', 'skirt', 'Ze heeft een nieuwe rok gekocht.', 'She has bought a new skirt.');
  n('jurk', 'de', 'jurken', 'dress', 'Wat een mooie jurk!', 'What a beautiful dress!');
  n('pak', 'het', 'pakken', 'suit', 'Hij draagt een pak naar zijn werk.', 'He wears a suit to work.');
  n('stropdas', 'de', 'stropdassen', 'tie', 'Een stropdas is hier niet nodig.', 'A tie is not needed here.');
  n('ondergoed', 'het', null, 'underwear', 'Ik moet nieuw ondergoed kopen.', 'I have to buy new underwear.');
  n('pyjama', 'de', "pyjama's", 'pyjamas', 'De kinderen hebben hun pyjama al aan.', 'The children already have their pyjamas on.');
  n('laars', 'de', 'laarzen', 'boot', 'Doe je laarzen aan, het is nat.', 'Put your boots on, it is wet.');
  n('sandaal', 'de', 'sandalen', 'sandal', 'In de zomer draag ik sandalen.', 'In summer I wear sandals.');
  n('regenjas', 'de', 'regenjassen', 'raincoat', 'Zonder regenjas overleef je hier niet.', 'Without a raincoat you will not survive here.');
  n('knoop', 'de', 'knopen', 'button', 'Er is een knoop van mijn jas af.', 'A button has come off my coat.');
  n('rits', 'de', 'ritsen', 'zip', 'De rits zit vast.', 'The zip is stuck.');
  n('mouw', 'de', 'mouwen', 'sleeve', 'De mouwen zijn te lang.', 'The sleeves are too long.');

  theme('body', 1);
  n('schouder', 'de', 'schouders', 'shoulder', 'Mijn schouder doet pijn.', 'My shoulder hurts.');
  n('elleboog', 'de', 'ellebogen', 'elbow', 'Ik heb mijn elleboog gestoten.', 'I bumped my elbow.');
  n('pols', 'de', 'polsen', 'wrist', 'Ze heeft haar pols gebroken.', 'She broke her wrist.');
  n('vinger', 'de', 'vingers', 'finger', 'Ik heb in mijn vinger gesneden.', 'I cut my finger.');
  n('duim', 'de', 'duimen', 'thumb', 'Ik duim voor je!', 'I am keeping my fingers crossed for you!');
  n('knie', 'de', 'knieën', 'knee', 'Mijn knie is dik.', 'My knee is swollen.');
  n('enkel', 'de', 'enkels', 'ankle', 'Ik heb mijn enkel verzwikt.', 'I sprained my ankle.');
  n('teen', 'de', 'tenen', 'toe', 'Au, mijn teen!', 'Ouch, my toe!');
  n('borst', 'de', 'borsten', 'chest / breast', 'Ik heb pijn op de borst.', 'I have chest pain.');
  n('heup', 'de', 'heupen', 'hip', 'Oma heeft een nieuwe heup.', 'Grandma has a new hip.');
  n('nek', 'de', 'nekken', 'neck', 'Ik heb een stijve nek.', 'I have a stiff neck.');
  n('kin', 'de', 'kinnen', 'chin', 'Hij heeft een litteken op zijn kin.', 'He has a scar on his chin.');
  n('wang', 'de', 'wangen', 'cheek', 'Drie kussen op de wang.', 'Three kisses on the cheek.');
  n('voorhoofd', 'het', 'voorhoofden', 'forehead', 'Je voorhoofd is warm.', 'Your forehead is warm.');
  n('lip', 'de', 'lippen', 'lip', 'Mijn lippen zijn droog.', 'My lips are dry.');
  n('tong', 'de', 'tongen', 'tongue', 'Steek je tong eens uit.', 'Stick your tongue out.');
  n('huid', 'de', null, 'skin', 'Ik heb een gevoelige huid.', 'I have sensitive skin.');
  n('bot', 'het', 'botten', 'bone', 'Het bot is niet gebroken.', 'The bone is not broken.');
  n('spier', 'de', 'spieren', 'muscle', 'Ik heb spierpijn in mijn benen.', 'My leg muscles ache.');
  n('hart', 'het', 'harten', 'heart', 'Mijn hart klopt snel.', 'My heart is beating fast.');
  n('long', 'de', 'longen', 'lung', 'Roken is slecht voor je longen.', 'Smoking is bad for your lungs.');
  n('maag', 'de', 'magen', 'stomach', 'Ik heb last van mijn maag.', 'I have stomach trouble.');
  n('bloed', 'het', null, 'blood', 'Er wordt bloed geprikt.', 'Blood is being taken.');
  n('hersenen', 'de', 'hersenen', 'brain', 'Slaap is goed voor je hersenen.', 'Sleep is good for your brain.');

  theme('animals', 1);
  n('koe', 'de', 'koeien', 'cow', 'De koeien staan in de wei.', 'The cows are in the meadow.');
  n('paard', 'het', 'paarden', 'horse', 'Ze rijdt elke week paard.', 'She rides a horse every week.');
  n('schaap', 'het', 'schapen', 'sheep', 'Op Texel zijn meer schapen dan mensen.', 'On Texel there are more sheep than people.');
  n('varken', 'het', 'varkens', 'pig', 'Het varken ligt in de modder.', 'The pig is lying in the mud.');
  n('eend', 'de', 'eenden', 'duck', 'De kinderen voeren de eenden.', 'The children are feeding the ducks.');
  n('gans', 'de', 'ganzen', 'goose', 'In de winter zie je veel ganzen.', 'In winter you see many geese.');
  n('konijn', 'het', 'konijnen', 'rabbit', 'We hebben een konijn in de tuin.', 'We have a rabbit in the garden.');
  n('muis', 'de', 'muizen', 'mouse', 'Er zit een muis in de keuken.', 'There is a mouse in the kitchen.');
  n('vogel', 'de', 'vogels', 'bird', 'De vogels zingen al vroeg.', 'The birds sing early.');
  n('vis', 'de', 'vissen', 'fish', 'Er zwemmen vissen in de gracht.', 'There are fish swimming in the canal.');
  n('duif', 'de', 'duiven', 'pigeon', 'Op de Dam lopen veel duiven.', 'There are many pigeons on the Dam.');
  n('meeuw', 'de', 'meeuwen', 'seagull', 'De meeuw pikte mijn patat.', 'The seagull stole my chips.');
  n('zwaan', 'de', 'zwanen', 'swan', 'Er zwemt een zwaan in de gracht.', 'A swan is swimming in the canal.');
  n('reiger', 'de', 'reigers', 'heron', 'Op de markt wacht altijd een reiger.', 'There is always a heron waiting at the market.');
  n('egel', 'de', 'egels', 'hedgehog', 'Er woont een egel in onze tuin.', 'A hedgehog lives in our garden.');
  n('vos', 'de', 'vossen', 'fox', 'In de duinen leven vossen.', 'Foxes live in the dunes.');
  n('hert', 'het', 'herten', 'deer', 'Op de Veluwe kun je herten zien.', 'You can see deer on the Veluwe.');
  n('kikker', 'de', 'kikkers', 'frog', 'Ik hoor kikkers in de sloot.', 'I hear frogs in the ditch.');
  n('spin', 'de', 'spinnen', 'spider', 'Ik ben bang voor spinnen.', 'I am afraid of spiders.');
  n('vlieg', 'de', 'vliegen', 'fly', 'Er zit een vlieg in mijn soep.', 'There is a fly in my soup.');
  n('mug', 'de', 'muggen', 'mosquito', 'Ik ben gestoken door een mug.', 'I was bitten by a mosquito.');
  A.N('bij', 'de', 'bijen', 'bee', 'Bijen zijn belangrijk voor de natuur.', 'Bees are important for nature.', { theme: 'animals', stage: 1, bank: true, id: 'bij-insect' });
  n('vlinder', 'de', 'vlinders', 'butterfly', 'Er zit een vlinder op de bloem.', 'There is a butterfly on the flower.');
  n('mier', 'de', 'mieren', 'ant', 'Er lopen mieren in de keuken.', 'There are ants in the kitchen.');

  theme('nature', 2);
  n('boom', 'de', 'bomen', 'tree', 'Voor ons huis staat een oude boom.', 'There is an old tree in front of our house.');
  n('bloem', 'de', 'bloemen', 'flower', 'Ik koop elke week bloemen.', 'I buy flowers every week.');
  n('gras', 'het', null, 'grass', 'We zitten in het gras.', 'We are sitting on the grass.');
  n('blad', 'het', 'bladeren', 'leaf', 'In de herfst vallen de bladeren.', 'In autumn the leaves fall.');
  n('tak', 'de', 'takken', 'branch', 'Er ligt een tak op de weg.', 'There is a branch on the road.');
  n('bos', 'het', 'bossen', 'forest', 'We wandelen in het bos.', 'We are walking in the forest.');
  n('heide', 'de', null, 'heath', 'In augustus bloeit de heide.', 'In August the heath is in bloom.');
  n('duin', 'het', 'duinen', 'dune', 'Achter de duinen ligt de zee.', 'Behind the dunes lies the sea.');
  n('rivier', 'de', 'rivieren', 'river', 'De Amstel is een rivier.', 'The Amstel is a river.');
  n('sloot', 'de', 'sloten', 'ditch', 'De koe staat bij de sloot.', 'The cow is standing by the ditch.');
  n('kust', 'de', 'kusten', 'coast', 'We rijden langs de kust.', 'We are driving along the coast.');
  n('golf', 'de', 'golven', 'wave', 'De golven zijn vandaag hoog.', 'The waves are high today.');
  n('zand', 'het', null, 'sand', 'Er zit zand in mijn schoenen.', 'There is sand in my shoes.');
  n('steen', 'de', 'stenen', 'stone', 'Het huis is van steen.', 'The house is made of stone.');
  n('berg', 'de', 'bergen', 'mountain', 'Nederland heeft geen echte bergen.', 'The Netherlands has no real mountains.');
  n('heuvel', 'de', 'heuvels', 'hill', 'In Limburg zijn heuvels.', 'There are hills in Limburg.');
  n('veld', 'het', 'velden', 'field', 'De bollenvelden bloeien in april.', 'The bulb fields bloom in April.');
  n('weiland', 'het', 'weilanden', 'meadow', 'Vanuit de trein zie je weilanden.', 'From the train you see meadows.');
  n('hemel', 'de', null, 'sky / heaven', 'De hemel is grijs.', 'The sky is grey.');
  n('ster', 'de', 'sterren', 'star', 'In de stad zie je weinig sterren.', 'In the city you see few stars.');
  n('maan', 'de', 'manen', 'moon', 'Het is volle maan.', 'It is a full moon.');
  n('aarde', 'de', null, 'earth / soil', 'De aarde warmt op.', 'The earth is warming up.');
  n('regenboog', 'de', 'regenbogen', 'rainbow', 'Kijk, een regenboog!', 'Look, a rainbow!');
  n('onweer', 'het', null, 'thunderstorm', 'Er komt onweer aan.', 'A thunderstorm is coming.');
  n('bliksem', 'de', null, 'lightning', 'De bliksem sloeg in de toren.', 'Lightning struck the tower.');
  n('mist', 'de', null, 'fog', 'Door de mist zie ik niets.', 'Because of the fog I see nothing.');
  n('hagel', 'de', null, 'hail', 'Eerst regen, toen hagel.', 'First rain, then hail.');
  n('ijs', 'het', null, 'ice / ice cream', 'Er ligt ijs op de grachten.', 'There is ice on the canals.');

  theme('city', 2);
  n('gebouw', 'het', 'gebouwen', 'building', 'Dat gebouw is een oud pakhuis.', 'That building is an old warehouse.');
  n('toren', 'de', 'torens', 'tower', 'Vanaf de toren zie je de hele stad.', 'From the tower you see the whole city.');
  n('brug', 'de', 'bruggen', 'bridge', 'De brug is open, we moeten wachten.', 'The bridge is open, we have to wait.');
  n('plein', 'het', 'pleinen', 'square', 'We spreken af op het plein.', 'We are meeting on the square.');
  n('steeg', 'de', 'stegen', 'alley', 'De steeg is te smal voor auto’s.', 'The alley is too narrow for cars.');
  n('stoep', 'de', 'stoepen', 'pavement', 'Fiets niet op de stoep.', 'Do not cycle on the pavement.');
  n('zebrapad', 'het', 'zebrapaden', 'zebra crossing', 'Steek over bij het zebrapad.', 'Cross at the zebra crossing.');
  n('stoplicht', 'het', 'stoplichten', 'traffic light', 'Het stoplicht staat op rood.', 'The traffic light is red.');
  n('rotonde', 'de', 'rotondes', 'roundabout', 'Op de rotonde neem je de tweede afslag.', 'At the roundabout you take the second exit.');
  n('kruispunt', 'het', 'kruispunten', 'crossroads', 'Bij het kruispunt ga je linksaf.', 'At the crossroads you turn left.');
  n('fietspad', 'het', 'fietspaden', 'cycle path', 'Blijf op het fietspad.', 'Stay on the cycle path.');
  n('parkeerplaats', 'de', 'parkeerplaatsen', 'parking space', 'Er is geen parkeerplaats vrij.', 'There is no parking space free.');
  n('bibliotheek', 'de', 'bibliotheken', 'library', 'Ik studeer in de bibliotheek.', 'I study in the library.');
  n('stadhuis', 'het', 'stadhuizen', 'town hall', 'Ze trouwen in het stadhuis.', 'They are getting married in the town hall.');
  n('kerk', 'de', 'kerken', 'church', 'De kerk is uit de vijftiende eeuw.', 'The church is from the fifteenth century.');
  n('moskee', 'de', 'moskeeën', 'mosque', 'De moskee staat om de hoek.', 'The mosque is around the corner.');
  n('politiebureau', 'het', 'politiebureaus', 'police station', 'Aangifte doe je op het politiebureau.', 'You report a crime at the police station.');
  n('zwembad', 'het', 'zwembaden', 'swimming pool', 'Het zwembad is op zondag druk.', 'The swimming pool is busy on Sundays.');
  n('haven', 'de', 'havens', 'harbour', 'Rotterdam heeft de grootste haven van Europa.', 'Rotterdam has the biggest harbour in Europe.');
  n('pont', 'de', 'ponten', 'ferry', 'De pont naar Noord is gratis.', 'The ferry to Noord is free.');
  n('sluis', 'de', 'sluizen', 'lock (canal)', 'De boot wacht voor de sluis.', 'The boat is waiting at the lock.');
  n('molen', 'de', 'molens', 'mill / windmill', 'Bij Kinderdijk staan negentien molens.', 'There are nineteen windmills at Kinderdijk.');

  theme('professions', 2);
  n('bakker', 'de', 'bakkers', 'baker', 'De bakker is om zeven uur open.', 'The baker opens at seven.');
  n('slager', 'de', 'slagers', 'butcher', 'Ik haal het vlees bij de slager.', 'I get the meat from the butcher.');
  n('kapper', 'de', 'kappers', 'hairdresser', 'Ik moet naar de kapper.', 'I need to go to the hairdresser.');
  n('loodgieter', 'de', 'loodgieters', 'plumber', 'De loodgieter komt morgen.', 'The plumber is coming tomorrow.');
  n('elektricien', 'de', 'elektriciens', 'electrician', 'We hebben een elektricien nodig.', 'We need an electrician.');
  n('timmerman', 'de', 'timmerlieden', 'carpenter', 'De timmerman maakt een nieuwe kast.', 'The carpenter is making a new cupboard.');
  n('schilder', 'de', 'schilders', 'painter', 'De schilder begint maandag.', 'The painter starts on Monday.');
  n('schoonmaker', 'de', 'schoonmakers', 'cleaner', 'De schoonmaker komt op vrijdag.', 'The cleaner comes on Fridays.');
  n('monteur', 'de', 'monteurs', 'mechanic', 'De monteur repareert de cv-ketel.', 'The mechanic is repairing the boiler.');
  n('chauffeur', 'de', 'chauffeurs', 'driver', 'De chauffeur hielp met de kinderwagen.', 'The driver helped with the pram.');
  n('postbode', 'de', 'postbodes', 'postman', 'De postbode is al geweest.', 'The postman has already been.');
  n('politieagent', 'de', 'politieagenten', 'police officer', 'De politieagent wees ons de weg.', 'The police officer showed us the way.');
  n('advocaat', 'de', 'advocaten', 'lawyer', 'Ik heb een advocaat ingeschakeld.', 'I have engaged a lawyer.');
  n('rechter', 'de', 'rechters', 'judge', 'De rechter doet volgende week uitspraak.', 'The judge will give a ruling next week.');
  n('boekhouder', 'de', 'boekhouders', 'bookkeeper / accountant', 'Mijn boekhouder doet mijn aangifte.', 'My accountant does my tax return.');
  n('ingenieur', 'de', 'ingenieurs', 'engineer', 'Ze werkt als ingenieur bij de TU.', 'She works as an engineer at the technical university.');
  n('architect', 'de', 'architecten', 'architect', 'De architect heeft het station ontworpen.', 'The architect designed the station.');
  n('apotheker', 'de', 'apothekers', 'pharmacist', 'Vraag het aan de apotheker.', 'Ask the pharmacist.');
  n('kok', 'de', 'koks', 'cook / chef', 'De kok komt uit Italië.', 'The chef comes from Italy.');
  n('ober', 'de', 'obers', 'waiter', 'De ober bracht de verkeerde bestelling.', 'The waiter brought the wrong order.');
  n('verkoper', 'de', 'verkopers', 'salesperson', 'De verkoper was erg behulpzaam.', 'The salesperson was very helpful.');
  n('ambtenaar', 'de', 'ambtenaren', 'civil servant', 'Mijn buurman is ambtenaar bij de gemeente.', 'My neighbour is a civil servant at the municipality.');
  n('ondernemer', 'de', 'ondernemers', 'entrepreneur', 'Ze is ondernemer en heeft drie winkels.', 'She is an entrepreneur and has three shops.');
  n('zzp’er', 'de', 'zzp’ers', 'freelancer (self-employed without staff)', 'Als zzp’er regel je je eigen pensioen.', 'As a freelancer you arrange your own pension.');
  n('vrijwilliger', 'de', 'vrijwilligers', 'volunteer', 'De voedselbank zoekt vrijwilligers.', 'The food bank is looking for volunteers.');

  theme('character', 3);
  w('eerlijk', 'adj', 'honest / fair', 'Wees eerlijk tegen me.', 'Be honest with me.');
  w('geduldig', 'adj', 'patient', 'De docent is heel geduldig.', 'The teacher is very patient.');
  w('ongeduldig', 'adj', 'impatient', 'Ik word ongeduldig van wachten.', 'Waiting makes me impatient.');
  w('verlegen', 'adj', 'shy', 'Hij is verlegen bij nieuwe mensen.', 'He is shy with new people.');
  w('beleefd', 'adj', 'polite', 'Ze is altijd beleefd.', 'She is always polite.');
  w('grappig', 'adj', 'funny', 'Dat was een grappige film.', 'That was a funny film.');
  w('serieus', 'adj', 'serious', 'Meen je dat serieus?', 'Are you serious?');
  w('dom', 'adj', 'stupid', 'Dat was een domme fout.', 'That was a stupid mistake.');
  w('koppig', 'adj', 'stubborn', 'Mijn vader is erg koppig.', 'My father is very stubborn.');
  w('gul', 'adj', 'generous', 'Ze is gul met complimenten.', 'She is generous with compliments.');
  w('gierig', 'adj', 'stingy', 'Zuinig is niet hetzelfde als gierig.', 'Thrifty is not the same as stingy.');
  w('nieuwsgierig', 'adj', 'curious', 'Ik ben nieuwsgierig naar je nieuwe huis.', 'I am curious about your new house.');
  w('zelfverzekerd', 'adj', 'self-confident', 'Ze kwam zelfverzekerd over.', 'She came across as confident.');
  w('onzeker', 'adj', 'insecure / uncertain', 'Ik ben onzeker over mijn uitspraak.', 'I am insecure about my pronunciation.');
  w('bescheiden', 'adj', 'modest', 'Hij is te bescheiden.', 'He is too modest.');
  w('arrogant', 'adj', 'arrogant', 'Directheid is niet hetzelfde als arrogant zijn.', 'Directness is not the same as being arrogant.');
  w('ijverig', 'adj', 'diligent', 'Het is een ijverige student.', 'He is a diligent student.');
  w('gevoelig', 'adj', 'sensitive', 'Dat is een gevoelig onderwerp.', 'That is a sensitive subject.');
  w('eigenwijs', 'adj', 'headstrong / know-it-all', 'Kinderen van twee zijn eigenwijs.', 'Two-year-olds are headstrong.');
  w('betrokken', 'adj', 'involved / committed', 'Het is een betrokken collega.', 'She is a committed colleague.');

  theme('feelings', 3);
  w('opgelucht', 'adj', 'relieved', 'Ik ben opgelucht dat het voorbij is.', 'I am relieved that it is over.');
  w('jaloers', 'adj', 'jealous', 'Ik ben jaloers op je balkon.', 'I am jealous of your balcony.');
  w('eenzaam', 'adj', 'lonely', 'In het begin voelde ik me eenzaam.', 'At first I felt lonely.');
  w('bezorgd', 'adj', 'worried', 'Ik ben bezorgd over mijn moeder.', 'I am worried about my mother.');
  w('geïrriteerd', 'adj', 'irritated', 'Hij reageerde geïrriteerd.', 'He reacted irritably.');
  w('verbaasd', 'adj', 'surprised', 'Ik was verbaasd over de prijs.', 'I was surprised at the price.');
  w('enthousiast', 'adj', 'enthusiastic', 'Iedereen was enthousiast over het plan.', 'Everyone was enthusiastic about the plan.');
  w('dankbaar', 'adj', 'grateful', 'Ik ben je erg dankbaar.', 'I am very grateful to you.');
  w('gespannen', 'adj', 'tense', 'Voor het examen was ik gespannen.', 'Before the exam I was tense.');
  n('heimwee', 'het', null, 'homesickness', 'Soms heb ik heimwee naar Engeland.', 'Sometimes I am homesick for England.');
  n('verdriet', 'het', null, 'grief / sorrow', 'Ze heeft veel verdriet van het afscheid.', 'The goodbye is causing her a lot of sorrow.');
  n('vreugde', 'de', null, 'joy', 'Er was grote vreugde na de uitslag.', 'There was great joy after the result.');
  n('woede', 'de', null, 'anger', 'De woede over de maatregel is groot.', 'There is great anger about the measure.');
  n('angst', 'de', 'angsten', 'fear', 'Ik heb angst voor hoogtes.', 'I have a fear of heights.');
  n('hoop', 'de', null, 'hope', 'Er is nog hoop.', 'There is still hope.');

  theme('sport', 2);
  n('doelpunt', 'het', 'doelpunten', 'goal (scored)', 'Ajax maakte drie doelpunten.', 'Ajax scored three goals.');
  n('scheidsrechter', 'de', 'scheidsrechters', 'referee', 'De scheidsrechter floot voor een penalty.', 'The referee blew for a penalty.');
  n('speler', 'de', 'spelers', 'player', 'Elk team heeft elf spelers.', 'Each team has eleven players.');
  n('toernooi', 'het', 'toernooien', 'tournament', 'Het toernooi duurt twee dagen.', 'The tournament lasts two days.');
  n('kampioen', 'de', 'kampioenen', 'champion', 'PSV is kampioen geworden.', 'PSV have become champions.');
  n('stadion', 'het', 'stadions', 'stadium', 'Het stadion was uitverkocht.', 'The stadium was sold out.');
  n('supporter', 'de', 'supporters', 'supporter', 'De supporters zongen de hele wedstrijd.', 'The supporters sang the whole match.');
  n('gelijkspel', 'het', null, 'draw', 'Het werd een gelijkspel.', 'It ended in a draw.');
  n('fietstocht', 'de', 'fietstochten', 'bike ride', 'We maken zondag een fietstocht.', 'We are going on a bike ride on Sunday.');
  n('hockey', 'het', null, 'hockey', 'Hockey is populair in Nederland.', 'Hockey is popular in the Netherlands.');
  n('wielrennen', 'het', null, 'cycle racing', 'Wielrennen is zwaar in de wind.', 'Cycle racing is hard in the wind.');
  v('schaatsen', 'to ice skate', 'schaats|schaatst|schaatsen', 'schaatste|schaatsten', 'geschaatst', 'hebben', 'Als het vriest, schaatsen we op de sloot.', 'When it freezes, we skate on the ditch.');
  v('zeilen', 'to sail', 'zeil|zeilt|zeilen', 'zeilde|zeilden', 'gezeild', 'hebben', 'We gaan zeilen op het IJsselmeer.', 'We are going sailing on the IJsselmeer.');
  v('roeien', 'to row', 'roei|roeit|roeien', 'roeide|roeiden', 'geroeid', 'hebben', 'Ze roeit elke ochtend op de Amstel.', 'She rows on the Amstel every morning.');
  v('schaken', 'to play chess', 'schaak|schaakt|schaken', 'schaakte|schaakten', 'geschaakt', 'hebben', 'Opa schaakt met de buurman.', 'Grandpa plays chess with the neighbour.');
  v('trainen', 'to train', 'train|traint|trainen', 'trainde|trainden', 'getraind', 'hebben', 'We trainen twee keer per week.', 'We train twice a week.');
  v('scoren', 'to score', 'scoor|scoort|scoren', 'scoorde|scoorden', 'gescoord', 'hebben', 'Ze scoorde in de laatste minuut.', 'She scored in the last minute.');

  theme('arts', 3);
  n('schilderij', 'het', 'schilderijen', 'painting', 'De Nachtwacht is een beroemd schilderij.', 'The Night Watch is a famous painting.');
  n('beeld', 'het', 'beelden', 'statue / image', 'Op het plein staat een beeld van Rembrandt.', 'On the square there is a statue of Rembrandt.');
  n('kunstenaar', 'de', 'kunstenaars', 'artist', 'De kunstenaar woont in Noord.', 'The artist lives in Noord.');
  n('tekening', 'de', 'tekeningen', 'drawing', 'De tekening hangt aan de muur.', 'The drawing is hanging on the wall.');
  n('galerie', 'de', 'galerieën', 'gallery', 'De galerie opent een nieuwe expositie.', 'The gallery is opening a new exhibition.');
  n('roman', 'de', 'romans', 'novel', 'Ik lees een Nederlandse roman.', 'I am reading a Dutch novel.');
  n('dichter', 'de', 'dichters', 'poet', 'De dichter las voor uit eigen werk.', 'The poet read from his own work.');
  n('toneelstuk', 'het', 'toneelstukken', 'play', 'Het toneelstuk duurt twee uur.', 'The play lasts two hours.');
  n('acteur', 'de', 'acteurs', 'actor', 'De acteur speelt de hoofdrol.', 'The actor plays the lead.');
  n('regisseur', 'de', 'regisseurs', 'director', 'De regisseur won een prijs.', 'The director won a prize.');
  n('orkest', 'het', 'orkesten', 'orchestra', 'Het orkest speelt in het Concertgebouw.', 'The orchestra plays at the Concertgebouw.');
  n('zanger', 'de', 'zangers', 'singer', 'De zanger komt uit Volendam.', 'The singer comes from Volendam.');
  n('lied', 'het', 'liederen', 'song', 'Iedereen kent dat lied.', 'Everyone knows that song.');
  n('melodie', 'de', 'melodieën', 'melody', 'Ik krijg die melodie niet uit mijn hoofd.', 'I cannot get that melody out of my head.');
  n('instrument', 'het', 'instrumenten', 'instrument', 'Speel je een instrument?', 'Do you play an instrument?');
  n('viool', 'de', 'violen', 'violin', 'Ze speelt viool in een orkest.', 'She plays the violin in an orchestra.');
  n('podium', 'het', 'podia', 'stage', 'De band staat op het podium.', 'The band is on stage.');
  n('applaus', 'het', null, 'applause', 'Er klonk een lang applaus.', 'There was long applause.');

  theme('technology', 2);
  n('computer', 'de', 'computers', 'computer', 'Mijn computer start niet op.', 'My computer will not start.');
  n('laptop', 'de', 'laptops', 'laptop', 'Ik neem mijn laptop mee.', 'I am taking my laptop.');
  n('scherm', 'het', 'schermen', 'screen', 'Het scherm is gebarsten.', 'The screen is cracked.');
  n('toetsenbord', 'het', 'toetsenborden', 'keyboard', 'Dit toetsenbord heeft geen Nederlandse indeling.', 'This keyboard has no Dutch layout.');
  n('oplader', 'de', 'opladers', 'charger', 'Mag ik je oplader lenen?', 'May I borrow your charger?');
  n('batterij', 'de', 'batterijen', 'battery', 'De batterij is bijna leeg.', 'The battery is nearly empty.');
  n('kabel', 'de', 'kabels', 'cable', 'Ik zoek de kabel van de printer.', 'I am looking for the printer cable.');
  n('printer', 'de', 'printers', 'printer', 'De printer heeft geen papier meer.', 'The printer is out of paper.');
  n('app', 'de', 'apps', 'app', 'Betalen kan via de app.', 'You can pay via the app.');
  n('website', 'de', 'websites', 'website', 'Kijk op de website van de gemeente.', 'Look on the municipality’s website.');
  n('internet', 'het', null, 'internet', 'Het internet ligt eruit.', 'The internet is down.');
  n('zoekmachine', 'de', 'zoekmachines', 'search engine', 'Gebruik een zoekmachine.', 'Use a search engine.');
  n('update', 'de', 'updates', 'update', 'Er staat een update klaar.', 'An update is ready.');
  n('virus', 'het', 'virussen', 'virus', 'Mijn laptop heeft een virus.', 'My laptop has a virus.');
  v('downloaden', 'to download', 'download|downloadt|downloaden', 'downloadde|downloadden', 'gedownload', 'hebben', 'Je kunt het formulier downloaden.', 'You can download the form.');
  v('opslaan', 'to save', 'sla op|slaat op|slaan op', 'sloeg op|sloegen op', 'opgeslagen', 'hebben', 'Sla het bestand eerst op.', 'Save the file first.');
  v('verwijderen', 'to delete / remove', 'verwijder|verwijdert|verwijderen', 'verwijderde|verwijderden', 'verwijderd', 'hebben', 'Ik heb de mail per ongeluk verwijderd.', 'I deleted the email by accident.');
  v('installeren', 'to install', 'installeer|installeert|installeren', 'installeerde|installeerden', 'geïnstalleerd', 'hebben', 'Ik moet de app opnieuw installeren.', 'I have to reinstall the app.');
  v('klikken', 'to click', 'klik|klikt|klikken', 'klikte|klikten', 'geklikt', 'hebben', 'Klik op de groene knop.', 'Click the green button.');
  v('typen', 'to type', 'typ|typt|typen', 'typte|typten', 'getypt', 'hebben', 'Ze typt heel snel.', 'She types very fast.');

  theme('law', 4);
  n('wet', 'de', 'wetten', 'law / act', 'De wet is vorig jaar veranderd.', 'The law changed last year.');
  n('recht', 'het', 'rechten', 'right / law', 'Je hebt recht op een advocaat.', 'You have the right to a lawyer.');
  n('rechtbank', 'de', 'rechtbanken', 'court', 'De zaak komt voor de rechtbank.', 'The case is going to court.');
  n('misdaad', 'de', 'misdaden', 'crime', 'De misdaad is nooit opgelost.', 'The crime was never solved.');
  n('diefstal', 'de', 'diefstallen', 'theft', 'Fietsendiefstal is een groot probleem.', 'Bike theft is a big problem.');
  n('inbraak', 'de', 'inbraken', 'burglary', 'Er was een inbraak bij de buren.', 'There was a burglary at the neighbours’.');
  n('fraude', 'de', null, 'fraud', 'Hij wordt verdacht van fraude.', 'He is suspected of fraud.');
  n('straf', 'de', 'straffen', 'punishment / sentence', 'De straf was twee jaar.', 'The sentence was two years.');
  n('gevangenis', 'de', 'gevangenissen', 'prison', 'Hij zit in de gevangenis.', 'He is in prison.');
  n('getuige', 'de', 'getuigen', 'witness', 'De politie zoekt getuigen.', 'The police are looking for witnesses.');
  n('vonnis', 'het', 'vonnissen', 'verdict', 'Het vonnis volgt over twee weken.', 'The verdict follows in two weeks.');
  n('aangifte', 'de', 'aangiftes', 'report (to the police) / declaration', 'Ik heb aangifte gedaan van diefstal.', 'I reported the theft.');
  w('onschuldig', 'adj', 'innocent', 'Hij zegt dat hij onschuldig is.', 'He says he is innocent.');
  w('strafbaar', 'adj', 'punishable', 'Appen op de fiets is strafbaar.', 'Texting on a bike is a punishable offence.');
  v('verbieden', 'to forbid', 'verbied|verbiedt|verbieden', 'verbood|verboden', 'verboden', 'hebben', 'Roken is hier verboden.', 'Smoking is forbidden here.');
  v('toestaan', 'to allow', 'sta toe|staat toe|staan toe', 'stond toe|stonden toe', 'toegestaan', 'hebben', 'Honden zijn niet toegestaan.', 'Dogs are not allowed.');
  v('overtreden', 'to break (a rule)', 'overtreed|overtreedt|overtreden', 'overtrad|overtraden', 'overtreden', 'hebben', 'Hij heeft de regels overtreden.', 'He broke the rules.');
  v('arresteren', 'to arrest', 'arresteer|arresteert|arresteren', 'arresteerde|arresteerden', 'gearresteerd', 'hebben', 'De verdachte is gearresteerd.', 'The suspect has been arrested.');
  v('veroordelen', 'to convict / condemn', 'veroordeel|veroordeelt|veroordelen', 'veroordeelde|veroordeelden', 'veroordeeld', 'hebben', 'Hij werd veroordeeld tot een boete.', 'He was sentenced to a fine.');

  theme('economy', 4);
  n('economie', 'de', 'economieën', 'economy', 'De economie groeit langzaam.', 'The economy is growing slowly.');
  n('inflatie', 'de', null, 'inflation', 'Door de inflatie wordt alles duurder.', 'Because of inflation everything gets more expensive.');
  n('loon', 'het', 'lonen', 'wage', 'De lonen stijgen minder hard dan de prijzen.', 'Wages are rising less fast than prices.');
  n('winst', 'de', 'winsten', 'profit', 'Het bedrijf maakte vorig jaar winst.', 'The company made a profit last year.');
  n('verlies', 'het', 'verliezen', 'loss', 'Het verlies was groter dan verwacht.', 'The loss was bigger than expected.');
  n('omzet', 'de', null, 'turnover', 'De omzet is met tien procent gestegen.', 'Turnover rose by ten per cent.');
  A.N('kosten', 'de', 'kosten', 'costs', 'De kosten zijn te hoog.', 'The costs are too high.', { theme: 'economy', stage: 4, bank: true, id: 'kosten-noun', note: 'Plural only.' });
  n('investering', 'de', 'investeringen', 'investment', 'Zonnepanelen zijn een goede investering.', 'Solar panels are a good investment.');
  n('aandeel', 'het', 'aandelen', 'share', 'De aandelen zijn in waarde gedaald.', 'The shares have fallen in value.');
  n('beurs', 'de', 'beurzen', 'stock exchange / trade fair / grant', 'De beurs sloot hoger.', 'The stock exchange closed higher.');
  n('werkloosheid', 'de', null, 'unemployment', 'De werkloosheid is laag.', 'Unemployment is low.');
  n('groei', 'de', null, 'growth', 'De groei valt tegen.', 'Growth is disappointing.');
  n('crisis', 'de', 'crises', 'crisis', 'Na de crisis stegen de huizenprijzen snel.', 'After the crisis house prices rose fast.');
  n('koopkracht', 'de', null, 'purchasing power', 'De koopkracht daalt dit jaar.', 'Purchasing power is falling this year.');
  n('consument', 'de', 'consumenten', 'consumer', 'De consument betaalt de rekening.', 'The consumer pays the bill.');
  n('concurrentie', 'de', null, 'competition', 'Er is veel concurrentie tussen supermarkten.', 'There is a lot of competition between supermarkets.');
  n('stijging', 'de', 'stijgingen', 'rise', 'Een stijging van drie procent.', 'A rise of three per cent.');
  n('daling', 'de', 'dalingen', 'fall', 'Een lichte daling van de rente.', 'A slight fall in interest rates.');

  theme('verbs', 3);
  v('lukken', 'to succeed / work out', 'luk|lukt|lukken', 'lukte|lukten', 'gelukt', 'zijn', 'Het is gelukt!', 'It worked!');
  v('mislukken', 'to fail', 'misluk|mislukt|mislukken', 'mislukte|mislukten', 'mislukt', 'zijn', 'De taart is mislukt.', 'The cake was a failure.');
  v('beslissen', 'to decide', 'beslis|beslist|beslissen', 'besliste|beslisten', 'beslist', 'hebben', 'Je moet vandaag beslissen.', 'You have to decide today.');
  v('kiezen', 'to choose', 'kies|kiest|kiezen', 'koos|kozen', 'gekozen', 'hebben', 'Ik kan niet kiezen.', 'I cannot choose.');
  v('vergelijken', 'to compare', 'vergelijk|vergelijkt|vergelijken', 'vergeleek|vergeleken', 'vergeleken', 'hebben', 'Vergelijk eerst de prijzen.', 'Compare the prices first.');
  v('verwachten', 'to expect', 'verwacht|verwacht|verwachten', 'verwachtte|verwachtten', 'verwacht', 'hebben', 'Dat had ik niet verwacht.', 'I had not expected that.');
  v('beloven', 'to promise', 'beloof|belooft|beloven', 'beloofde|beloofden', 'beloofd', 'hebben', 'Ik beloof dat ik op tijd ben.', 'I promise that I will be on time.');
  v('voorkomen', 'to prevent', 'voorkom|voorkomt|voorkomen', 'voorkwam|voorkwamen', 'voorkomen', 'hebben', 'Voorkomen is beter dan genezen.', 'Prevention is better than cure.');
  v('veroorzaken', 'to cause', 'veroorzaak|veroorzaakt|veroorzaken', 'veroorzaakte|veroorzaakten', 'veroorzaakt', 'hebben', 'De storm veroorzaakte veel schade.', 'The storm caused a lot of damage.');
  v('verbeteren', 'to improve / correct', 'verbeter|verbetert|verbeteren', 'verbeterde|verbeterden', 'verbeterd', 'hebben', 'Ik wil mijn uitspraak verbeteren.', 'I want to improve my pronunciation.');
  v('ontwikkelen', 'to develop', 'ontwikkel|ontwikkelt|ontwikkelen', 'ontwikkelde|ontwikkelden', 'ontwikkeld', 'hebben', 'Het bedrijf ontwikkelt software.', 'The company develops software.');
  v('verschijnen', 'to appear', 'verschijn|verschijnt|verschijnen', 'verscheen|verschenen', 'verschenen', 'zijn', 'Het boek verschijnt in mei.', 'The book comes out in May.');
  v('ontstaan', 'to arise / come into being', 'ontsta|ontstaat|ontstaan', 'ontstond|ontstonden', 'ontstaan', 'zijn', 'Hoe is dat probleem ontstaan?', 'How did that problem arise?');
  v('bestaan', 'to exist', 'besta|bestaat|bestaan', 'bestond|bestonden', 'bestaan', 'hebben', 'Die winkel bestaat niet meer.', 'That shop no longer exists.');
  v('bevatten', 'to contain', 'bevat|bevat|bevatten', 'bevatte|bevatten', 'bevat', 'hebben', 'Dit product bevat noten.', 'This product contains nuts.');
  v('betekenen', 'to mean', 'beteken|betekent|betekenen', 'betekende|betekenden', 'betekend', 'hebben', 'Wat betekent dit woord?', 'What does this word mean?');
  v('bedoelen', 'to mean (intend)', 'bedoel|bedoelt|bedoelen', 'bedoelde|bedoelden', 'bedoeld', 'hebben', 'Wat bedoel je precies?', 'What exactly do you mean?');
  v('herkennen', 'to recognise', 'herken|herkent|herkennen', 'herkende|herkenden', 'herkend', 'hebben', 'Ik herkende je niet met die bril.', 'I did not recognise you with those glasses.');
  v('onthouden', 'to remember (keep in mind)', 'onthoud|onthoudt|onthouden', 'onthield|onthielden', 'onthouden', 'hebben', 'Ik kan namen slecht onthouden.', 'I am bad at remembering names.');
  v('controleren', 'to check', 'controleer|controleert|controleren', 'controleerde|controleerden', 'gecontroleerd', 'hebben', 'Controleer je antwoorden.', 'Check your answers.');
  v('organiseren', 'to organise', 'organiseer|organiseert|organiseren', 'organiseerde|organiseerden', 'georganiseerd', 'hebben', 'Wie organiseert het buurtfeest?', 'Who is organising the street party?');
  v('deelnemen', 'to take part', 'neem deel|neemt deel|nemen deel', 'nam deel|namen deel', 'deelgenomen', 'hebben', 'Ik neem deel aan het onderzoek.', 'I am taking part in the study.');
  v('samenwerken', 'to work together', 'werk samen|werkt samen|werken samen', 'werkte samen|werkten samen', 'samengewerkt', 'hebben', 'We werken samen met een bureau in Gent.', 'We work together with an agency in Ghent.');
  v('ondersteunen', 'to support', 'ondersteun|ondersteunt|ondersteunen', 'ondersteunde|ondersteunden', 'ondersteund', 'hebben', 'De gemeente ondersteunt het project.', 'The municipality supports the project.');
  v('aanbieden', 'to offer', 'bied aan|biedt aan|bieden aan', 'bood aan|boden aan', 'aangeboden', 'hebben', 'Ze boden me een vaste baan aan.', 'They offered me a permanent job.');
  v('accepteren', 'to accept', 'accepteer|accepteert|accepteren', 'accepteerde|accepteerden', 'geaccepteerd', 'hebben', 'Ik heb het aanbod geaccepteerd.', 'I accepted the offer.');
  v('afwijzen', 'to reject', 'wijs af|wijst af|wijzen af', 'wees af|wezen af', 'afgewezen', 'hebben', 'Mijn aanvraag is afgewezen.', 'My application was rejected.');
  v('waarderen', 'to appreciate', 'waardeer|waardeert|waarderen', 'waardeerde|waardeerden', 'gewaardeerd', 'hebben', 'Ik waardeer je hulp enorm.', 'I really appreciate your help.');
  v('vertrouwen', 'to trust', 'vertrouw|vertrouwt|vertrouwen', 'vertrouwde|vertrouwden', 'vertrouwd', 'hebben', 'Ik vertrouw hem volledig.', 'I trust him completely.');
  v('overwegen', 'to consider', 'overweeg|overweegt|overwegen', 'overwoog|overwogen', 'overwogen', 'hebben', 'Ik overweeg om te verhuizen.', 'I am considering moving.');
  v('opvallen', 'to stand out / be noticeable', 'val op|valt op|vallen op', 'viel op|vielen op', 'opgevallen', 'zijn', 'Het viel me op dat hij stil was.', 'I noticed that he was quiet.');
  v('meemaken', 'to experience / go through', 'maak mee|maakt mee|maken mee', 'maakte mee|maakten mee', 'meegemaakt', 'hebben', 'Zoiets heb ik nog nooit meegemaakt.', 'I have never experienced anything like it.');

  theme('adjectives', 3);
  w('belangrijk', 'adj', 'important', 'Dat is een belangrijk punt.', 'That is an important point.');
  w('noodzakelijk', 'adj', 'necessary', 'Een afspraak is noodzakelijk.', 'An appointment is necessary.');
  w('mogelijk', 'adj', 'possible', 'Is het mogelijk om later te betalen?', 'Is it possible to pay later?');
  w('onmogelijk', 'adj', 'impossible', 'Dat is onmogelijk in één dag.', 'That is impossible in one day.');
  w('duidelijk', 'adj', 'clear', 'De uitleg was heel duidelijk.', 'The explanation was very clear.');
  w('eenvoudig', 'adj', 'simple', 'Het is een eenvoudig recept.', 'It is a simple recipe.');
  w('bekend', 'adj', 'well-known / familiar', 'Dat komt me bekend voor.', 'That seems familiar to me.');
  w('bijzonder', 'adj', 'special', 'Het was een bijzondere avond.', 'It was a special evening.');
  w('normaal', 'adj', 'normal', 'Is dat normaal in Nederland?', 'Is that normal in the Netherlands?');
  w('algemeen', 'adj', 'general', 'In het algemeen ben ik tevreden.', 'In general I am satisfied.');
  w('definitief', 'adj', 'final / definitive', 'Het besluit is nog niet definitief.', 'The decision is not final yet.');
  w('officieel', 'adj', 'official', 'Je krijgt nog een officiële brief.', 'You will get an official letter.');
  w('persoonlijk', 'adj', 'personal', 'Dat is een persoonlijke vraag.', 'That is a personal question.');
  w('openbaar', 'adj', 'public', 'Het openbaar vervoer staakt morgen.', 'Public transport is on strike tomorrow.');
  w('gezamenlijk', 'adj', 'joint / shared', 'We hebben een gezamenlijke tuin.', 'We have a shared garden.');
  w('voldoende', 'adj', 'sufficient', 'Is er voldoende tijd?', 'Is there enough time?');
  w('geschikt', 'adj', 'suitable', 'Deze woning is geschikt voor een gezin.', 'This home is suitable for a family.');
  w('nuttig', 'adj', 'useful', 'Dat was een nuttige tip.', 'That was a useful tip.');
  w('zinloos', 'adj', 'pointless', 'Het is zinloos om te wachten.', 'It is pointless to wait.');
  w('veilig', 'adj', 'safe', 'Is het hier ’s nachts veilig?', 'Is it safe here at night?');
  w('gevaarlijk', 'adj', 'dangerous', 'Dat kruispunt is gevaarlijk.', 'That crossroads is dangerous.');
  w('breed', 'adj', 'wide', 'De gracht is hier heel breed.', 'The canal is very wide here.');
  w('smal', 'adj', 'narrow', 'De trap is smal en steil.', 'The stairs are narrow and steep.');
  w('diep', 'adj', 'deep', 'Het water is hier diep.', 'The water is deep here.');
  w('scherp', 'adj', 'sharp', 'Pas op, dat mes is scherp.', 'Careful, that knife is sharp.');
  w('zacht', 'adj', 'soft / mild', 'Het is zacht weer voor januari.', 'It is mild weather for January.');
  w('glad', 'adj', 'slippery / smooth', 'De weg is glad door de vorst.', 'The road is slippery because of the frost.');
  w('nat', 'adj', 'wet', 'Ik ben helemaal nat geworden.', 'I got completely wet.');
  w('droog', 'adj', 'dry', 'Morgen blijft het droog.', 'Tomorrow it will stay dry.');
  w('vol', 'adj', 'full', 'De tram zit vol.', 'The tram is full.');
  w('leeg', 'adj', 'empty', 'Mijn telefoon is leeg.', 'My phone is dead.');
  w('schoon', 'adj', 'clean', 'De keuken is weer schoon.', 'The kitchen is clean again.');
  w('vies', 'adj', 'dirty', 'Mijn schoenen zijn vies.', 'My shoes are dirty.');

  theme('adverbs', 3);
  w('bijna', 'adv', 'almost', 'Ik ben bijna klaar.', 'I am almost done.');
  w('ongeveer', 'adv', 'approximately', 'Het duurt ongeveer een uur.', 'It takes about an hour.');
  w('vooral', 'adv', 'especially', 'Ik hou vooral van de lente.', 'I especially love spring.');
  w('zelfs', 'adv', 'even', 'Zelfs mijn baas was te laat.', 'Even my boss was late.');
  w('tenminste', 'adv', 'at least (in any case)', 'Het regent niet, tenminste nu niet.', 'It is not raining, at least not now.');
  w('minstens', 'adv', 'at least (quantity)', 'Je hebt minstens een uur nodig.', 'You need at least an hour.');
  w('hoogstens', 'adv', 'at most', 'Het kost hoogstens tien euro.', 'It costs ten euros at most.');
  w('ergens', 'adv', 'somewhere', 'Ik heb mijn sleutels ergens neergelegd.', 'I put my keys down somewhere.');
  w('overal', 'adv', 'everywhere', 'Overal staan fietsen.', 'There are bikes everywhere.');
  w('plotseling', 'adv', 'suddenly', 'Plotseling ging het licht uit.', 'Suddenly the light went out.');
  w('langzamerhand', 'adv', 'gradually', 'Langzamerhand begrijp ik meer.', 'Gradually I understand more.');
  w('voortdurend', 'adv', 'constantly', 'De telefoon gaat voortdurend.', 'The phone rings constantly.');
  w('af en toe', 'adv', 'now and then', 'Af en toe ga ik naar de film.', 'Now and then I go to the cinema.');
  w('tegelijk', 'adv', 'at the same time', 'We kwamen tegelijk aan.', 'We arrived at the same time.');
  w('vooraf', 'adv', 'beforehand', 'Je moet vooraf reserveren.', 'You have to book beforehand.');
  w('tot nu toe', 'adv', 'so far', 'Tot nu toe gaat alles goed.', 'So far everything is going well.');
  w('toevallig', 'adv', 'by chance', 'Ik kwam haar toevallig tegen.', 'I ran into her by chance.');
  w('expres', 'adv', 'on purpose', 'Ik deed het niet expres.', 'I did not do it on purpose.');
  w('blijkbaar', 'adv', 'apparently', 'Blijkbaar is de winkel dicht.', 'Apparently the shop is closed.');
  w('hopelijk', 'adv', 'hopefully', 'Hopelijk tot snel!', 'Hopefully see you soon!');
  w('tamelijk', 'adv', 'fairly', 'Het is tamelijk koud vandaag.', 'It is fairly cold today.');
  w('nogal', 'adv', 'rather', 'Dat is nogal duur.', 'That is rather expensive.');
  w('steeds', 'adv', 'all the time / increasingly', 'Het wordt steeds drukker.', 'It is getting busier and busier.');
})();
