/* Stage 3 (B1) — Unit 5: Milieu · Unit 6: Geld en bureaucratie · Unit 7: Vergaderingen en e-mails · Unit 8: Nederlandse cultuur en geschiedenis
   Two full lessons per unit; further lessons are listed in content/TODO.md */
(function () {
  'use strict';
  const NL = window.NL, A = NL.contentApi;
  const { N, VB, W, PH, h, p, tip, warn, table, ex, list, mc, fill, tr, build, conj, art, plural, dict, listen, speak, free, match, read, fix, write, auto, lesson, unit } = A;
  const units = (NL.content._s3units = NL.content._s3units || []);

  /* ---------------- Unit 5: Milieu ---------------- */
  N('milieu', 'het', null, 'environment', 'Fietsen is beter voor het milieu.', 'Cycling is better for the environment.', { theme: 'environment', stage: 3 });
  N('klimaat', 'het', 'klimaten', 'climate', 'Het klimaat verandert sneller dan verwacht.', 'The climate is changing faster than expected.', { theme: 'environment', stage: 3 });
  N('klimaatverandering', 'de', null, 'climate change', 'Klimaatverandering is een wereldwijd probleem.', 'Climate change is a worldwide problem.', { theme: 'environment', stage: 3 });
  N('zeespiegel', 'de', null, 'sea level', 'De zeespiegel stijgt.', 'The sea level is rising.', { theme: 'environment', stage: 3 });
  N('dijk', 'de', 'dijken', 'dyke', 'De dijken werden na 1953 versterkt.', 'The dykes were reinforced after 1953.', { theme: 'environment', stage: 3 });
  N('overstroming', 'de', 'overstromingen', 'flood', 'Bij de overstroming van 1953 kwamen veel mensen om.', 'Many people died in the flood of 1953.', { theme: 'environment', stage: 3 });
  N('uitstoot', 'de', null, 'emissions', 'De uitstoot van CO2 moet omlaag.', 'CO2 emissions must come down.', { theme: 'environment', stage: 3 });
  N('energie', 'de', null, 'energy', 'We gebruiken te veel energie.', 'We use too much energy.', { theme: 'environment', stage: 3 });
  N('windmolen', 'de', 'windmolens', 'wind turbine / windmill', 'Op zee worden nieuwe windmolens gebouwd.', 'New wind turbines are being built at sea.', { theme: 'environment', stage: 3 });
  N('zonnepaneel', 'het', 'zonnepanelen', 'solar panel', 'Er zijn zonnepanelen op ons dak gelegd.', 'Solar panels have been put on our roof.', { theme: 'environment', stage: 3 });
  N('gas', 'het', null, 'gas', 'Nederland wil van het gas af.', 'The Netherlands wants to get off gas.', { theme: 'environment', stage: 3 });
  VB('verminderen', 'to reduce', 'verminder|vermindert|verminderen', 'verminderde|verminderden', 'verminderd', 'hebben', 'De uitstoot moet worden verminderd.', 'Emissions must be reduced.', { theme: 'environment', stage: 3 });
  VB('besparen', 'to save (energy, money)', 'bespaar|bespaart|besparen', 'bespaarde|bespaarden', 'bespaard', 'hebben', 'Met isolatie bespaar je energie.', 'With insulation you save energy.', { theme: 'environment', stage: 3 });
  VB('isoleren', 'to insulate', 'isoleer|isoleert|isoleren', 'isoleerde|isoleerden', 'geïsoleerd', 'hebben', 'Ons huis is vorig jaar geïsoleerd.', 'Our house was insulated last year.', { theme: 'environment', stage: 3 });
  VB('versterken', 'to reinforce', 'versterk|versterkt|versterken', 'versterkte|versterkten', 'versterkt', 'hebben', 'De dijk wordt versterkt.', 'The dyke is being reinforced.', { theme: 'environment', stage: 3 });
  VB('beschermen', 'to protect', 'bescherm|beschermt|beschermen', 'beschermde|beschermden', 'beschermd', 'hebben', 'De duinen beschermen het land tegen de zee.', 'The dunes protect the land against the sea.', { theme: 'environment', stage: 3 });
  VB('opwekken', 'to generate', 'wek op|wekt op|wekken op', 'wekte op|wekten op', 'opgewekt', 'hebben', 'De stroom wordt opgewekt door windmolens.', 'The electricity is generated by wind turbines.', { theme: 'environment', stage: 3 });
  W('duurzaam', 'sustainable', 'adj', 'We willen duurzamer leven.', 'We want to live more sustainably.', { theme: 'environment', stage: 3 });
  W('schadelijk', 'harmful', 'adj', 'Plastic is schadelijk voor de zee.', 'Plastic is harmful to the sea.', { theme: 'environment', stage: 3 });
  W('wereldwijd', 'worldwide', 'adj', 'Het is een wereldwijd probleem.', 'It is a worldwide problem.', { theme: 'environment', stage: 3 });

  N('afval', 'het', null, 'waste / rubbish', 'In Amsterdam wordt afval gescheiden.', 'In Amsterdam waste is separated.', { theme: 'environment', stage: 3 });
  N('afvalscheiding', 'de', null, 'waste separation', 'Afvalscheiding is in veel gemeenten verplicht.', 'Waste separation is compulsory in many municipalities.', { theme: 'environment', stage: 3 });
  N('vuilniszak', 'de', 'vuilniszakken', 'rubbish bag', 'De vuilniszak moet voor zes uur buiten staan.', 'The rubbish bag has to be outside before six.', { theme: 'environment', stage: 3 });
  N('glasbak', 'de', 'glasbakken', 'bottle bank', 'De glasbak staat op de hoek.', 'The bottle bank is on the corner.', { theme: 'environment', stage: 3 });
  N('statiegeld', 'het', null, 'deposit (on bottles)', 'Op blikjes zit statiegeld.', 'There is a deposit on cans.', { theme: 'environment', stage: 3 });
  N('verpakking', 'de', 'verpakkingen', 'packaging', 'Deze verpakking is herbruikbaar.', 'This packaging is reusable.', { theme: 'environment', stage: 3 });
  N('kringloopwinkel', 'de', 'kringloopwinkels', 'second-hand shop', 'Ik koop mijn meubels bij de kringloopwinkel.', 'I buy my furniture at the second-hand shop.', { theme: 'environment', stage: 3 });
  W('tweedehands', 'second-hand', 'adj', 'Ik heb een tweedehands fiets gekocht.', 'I bought a second-hand bike.', { theme: 'environment', stage: 3, note: 'Does not take an -e ending.' });
  N('luchtvervuiling', 'de', null, 'air pollution', 'Luchtvervuiling is slecht voor je gezondheid.', 'Air pollution is bad for your health.', { theme: 'environment', stage: 3 });
  N('duurzaamheid', 'de', null, 'sustainability', 'Duurzaamheid is een belangrijk thema.', 'Sustainability is an important theme.', { theme: 'environment', stage: 3 });
  VB('scheiden', 'to separate', 'scheid|scheidt|scheiden', 'scheidde|scheidden', 'gescheiden', 'hebben', 'Scheid je je afval?', 'Do you separate your waste?', { theme: 'environment', stage: 3 });
  VB('weggooien', 'to throw away', 'gooi weg|gooit weg|gooien weg', 'gooide weg|gooiden weg', 'weggegooid', 'hebben', 'Gooi dat niet weg, het is nog goed.', 'Do not throw that away, it is still good.', { theme: 'environment', stage: 3 });
  VB('hergebruiken', 'to reuse', 'hergebruik|hergebruikt|hergebruiken', 'hergebruikte|hergebruikten', 'hergebruikt', 'hebben', 'We hergebruiken glazen potten.', 'We reuse glass jars.', { theme: 'environment', stage: 3 });
  VB('recyclen', 'to recycle', 'recycle|recyclet|recyclen', 'recyclede|recycleden', 'gerecycled', 'hebben', 'Papier wordt gerecycled.', 'Paper is recycled.', { theme: 'environment', stage: 3 });
  W('herbruikbaar', 'reusable', 'adj', 'Neem een herbruikbare tas mee.', 'Bring a reusable bag.', { theme: 'environment', stage: 3 });
  W('afbreekbaar', 'degradable', 'adj', 'Dit plastic is niet afbreekbaar.', 'This plastic is not degradable.', { theme: 'environment', stage: 3 });
  N('verspilling', 'de', null, 'waste (squandering)', 'Voedselverspilling is een groot probleem.', 'Food waste is a big problem.', { theme: 'environment', stage: 3 });
  W('onnodig', 'unnecessary', 'adj', 'Onnodige verpakkingen zijn schadelijk.', 'Unnecessary packaging is harmful.', { theme: 'environment', stage: 3 });
  W('milieuvriendelijk', 'environmentally friendly', 'adj', 'De trein is milieuvriendelijker dan het vliegtuig.', 'The train is more environmentally friendly than the plane.', { theme: 'environment', stage: 3 });

  const u5 = [];
  u5.push(lesson('s3u5l1', 'Water, energy and climate: the passive in every tense', 'You can read and talk about climate and energy in the Netherlands, using the passive in the present, past, perfect and with modals.', [
    h('The passive in every tense'),
    table(['tense', 'example'], [['present', '*De dijk wordt versterkt.'], ['past', '*De dijken werden na 1953 versterkt.'], ['perfect', '*Ons huis is vorig jaar geïsoleerd.'], ['pluperfect', '*De polder was al in de zeventiende eeuw drooggelegd.'], ['future', '*Er zullen nieuwe windmolens gebouwd worden.'], ['modal', '*De uitstoot moet verminderd worden.'], ['impersonal', '*Er wordt veel over het klimaat gesproken.']]),
    p('With two or three verbs at the end the order is flexible: `moet verminderd worden` / `moet worden verminderd`. Both are correct.'),
    h('The Netherlands and water'),
    p('About a quarter of the country lies below sea level. After the flood of 1953 (`de watersnoodramp`) the `Deltawerken` were built. Today the debate is about the rising `zeespiegel`, getting off `gas`, and energy from `windmolens` and `zonnepanelen`.'),
    ex(['Na de overstroming van 1953 werden de dijken versterkt en werden de Deltawerken gebouwd.', 'After the flood of 1953 the dykes were reinforced and the Delta Works were built.'], ['Er worden steeds meer zonnepanelen op daken gelegd.', 'More and more solar panels are being put on roofs.'], ['De uitstoot moet voor 2030 met de helft verminderd worden.', 'Emissions must be reduced by half before 2030.'], ['Ons huis is geïsoleerd, waardoor we veel energie besparen.', 'Our house has been insulated, which means we save a lot of energy.']),
    tip('`is geïsoleerd` = it has been done (result). `wordt geïsoleerd` = it is being done now. `werd geïsoleerd` = it was done then (story).'),
  ], ['g3-passive'], ['milieu', 'klimaat', 'klimaatverandering', 'zeespiegel', 'dijk', 'overstroming', 'uitstoot', 'energie', 'windmolen', 'zonnepaneel', 'gas', 'verminderen', 'besparen', 'isoleren', 'versterken', 'beschermen', 'opwekken', 'duurzaam', 'schadelijk', 'wereldwijd'], [
    mc('De dijken ___ na 1953 versterkt.', ['worden', 'werden', 'zijn geworden'], 1, 'Past: werden.'),
    mc('Ons huis ___ vorig jaar geïsoleerd.', ['is', 'wordt', 'heeft'], 0, 'Perfect passive: is.'),
    mc('De uitstoot moet ___.', ['verminderen worden', 'verminderd worden', 'wordt verminderd'], 1, 'modal + participle + worden.'),
    mc('Er ___ veel over het klimaat gesproken.', ['wordt', 'is geworden', 'heeft'], 0, 'Impersonal: er wordt.'),
    art('milieu', 'het', 'het milieu.'),
    art('klimaat', 'het', 'het klimaat.'),
    art('dijk', 'de', 'de dijk.'),
    fill('Er ___ nieuwe windmolens op zee gebouwd. (present)', ['worden'], 'New wind turbines are being built at sea.', 'plural subject → worden.'),
    fill('De stroom wordt ___ windmolens opgewekt.', ['door'], 'The electricity is generated by wind turbines.', 'door = by.'),
    fill('De zeespiegel ___ sneller dan verwacht. (stijgen)', ['stijgt'], 'The sea level is rising faster than expected.', 'stijgt.'),
    build('The dykes were reinforced after the flood.', 'De dijken werden na de overstroming versterkt.', ['zijn', 'versterken'], 'werden … versterkt.'),
    build('Emissions must be reduced before 2030.', 'De uitstoot moet voor 2030 verminderd worden.', ['verminderen', 'wordt'], 'moet … verminderd worden.'),
    build('Solar panels have been put on our roof.', 'Er zijn zonnepanelen op ons dak gelegd.', ['hebben', 'leggen'], 'er zijn … gelegd.'),
    tr('en-nl', 'The train is better for the environment than the plane.', ['De trein is beter voor het milieu dan het vliegtuig.'], 'beter voor het milieu dan.'),
    tr('nl-en', 'De duinen en dijken beschermen het land tegen de zee.', ['The dunes and dykes protect the land against the sea.', 'The dunes and dykes protect the country from the sea.'], 'beschermen tegen.'),
    fix('De dijk is versterkt geworden.', ['De dijk is versterkt.'], 'No geworden.'),
    dict('Er worden steeds meer zonnepanelen op daken gelegd.', 'More and more solar panels are being put on roofs.', 'er worden … gelegd.'),
    listen('Een kwart van Nederland ligt onder de zeespiegel en wordt door dijken beschermd.', ['A quarter of the Netherlands lies below sea level and is protected by dykes.', 'A quarter of the Netherlands was flooded last year.', 'The dykes are a quarter of the country.'], 0, 'onder de zeespiegel; wordt … beschermd.'),
    speak('Na de overstroming van 1953 werden de dijken versterkt en werden de Deltawerken gebouwd.', 'After the flood of 1953 the dykes were reinforced and the Delta Works were built.'),
    read('Nederland en het water. Ongeveer een kwart van Nederland ligt onder de zeespiegel. Eeuwenlang werd het land beschermd door dijken en werden meren drooggelegd om nieuw land te maken. In 1953 braken bij een zware storm veel dijken door; bijna tweeduizend mensen kwamen om. Daarna werden de Deltawerken gebouwd. Nu de zeespiegel stijgt, worden de dijken opnieuw versterkt. Tegelijk wordt er geïnvesteerd in windmolens op zee, zodat er minder gas gebruikt hoeft te worden.', [
      { q: 'What happened in 1953?', options: ['the Delta Works were finished', 'many dykes broke in a storm', 'a lake was drained'], answer: 1, explain: '"braken bij een zware storm veel dijken door".' },
      { q: 'Why are the dykes being reinforced again?', options: ['because the sea level is rising', 'because they are too old', 'because of wind turbines'], answer: 0, explain: '"Nu de zeespiegel stijgt".' },
      { q: 'What is the purpose of investing in wind turbines?', options: ['to protect the dykes', 'so that less gas needs to be used', 'to drain more lakes'], answer: 1, explain: '"zodat er minder gas gebruikt hoeft te worden".' },
    ], { en: 'The Netherlands and water. About a quarter of the Netherlands lies below sea level. For centuries the land was protected by dykes and lakes were drained to make new land. In 1953 many dykes broke in a heavy storm; almost two thousand people died. After that the Delta Works were built. Now that the sea level is rising, the dykes are being reinforced again. At the same time there is investment in wind turbines at sea, so that less gas needs to be used.' }),
    free('Explain in three or four sentences what is being done about climate or energy where you live. Use at least two passives.', 'In mijn buurt worden veel huizen geïsoleerd. Er zijn vorig jaar zonnepanelen op onze flat gelegd. De gemeente wil dat er minder gas gebruikt wordt. Ik vind dat er nog meer gedaan moet worden.', 'In my neighbourhood many houses are being insulated. Last year solar panels were put on our block. The municipality wants less gas to be used. I think even more needs to be done.', { hints: ['Er worden …', '… is / zijn … ge…', '… moet … worden'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('De polder ___ in 1930 drooggelegd.', ['wordt', 'werd'], 1, 'Past: werd.'),
    fill('Het huis ___ vorig jaar geïsoleerd.', ['is', 'werd'], 'The house was insulated last year.', 'is / werd.'),
    fill('De uitstoot moet verminderd ___.', ['worden'], 'Emissions must be reduced.', 'worden.'),
    build('The electricity is generated by wind turbines.', 'De stroom wordt door windmolens opgewekt.', ['is', 'wekt op'], 'wordt … opgewekt.'),
    tr('en-nl', 'The sea level is rising.', ['De zeespiegel stijgt.'], 'stijgen.'),
    speak('Er wordt veel geïnvesteerd in duurzame energie, maar er moet nog meer gedaan worden.', 'A lot is being invested in sustainable energy, but more still needs to be done.'),
  ]));

  u5.push(lesson('s3u5l2', 'Waste and reuse: building words', 'You can talk about waste, recycling and sustainable choices, and decode and build Dutch words with compounds, -heid, -ing, -baar, -loos, on- and her-.', [
    h('Compounds: read from the right'),
    p('`afval + scheiding = afvalscheiding`, `kring + loop + winkel = kringloopwinkel`, `lucht + vervuiling = luchtvervuiling`. The **last** part is the core and sets the gender: **de** winkel → **de** kringloopwinkel. Always one word.'),
    h('Productive endings'),
    table(['affix', 'example', 'meaning'], [['-baar', '*herbruikbaar, *afbreekbaar, *betaalbaar', 'can be …ed'], ['-heid', '*duurzaamheid, *gezondheid', 'the quality of being'], ['-ing', '*verpakking, *vervuiling, *verspilling', 'the act or result'], ['-loos', '*zinloos, *draadloos', 'without'], ['on-', '*onnodig, *ongezond, *onmogelijk', 'not'], ['her-', '*hergebruiken, *herhalen', 'again'], ['-vriendelijk', '*milieuvriendelijk, *kindvriendelijk', 'friendly to']]),
    h('Living with Dutch waste rules'),
    p('`afval scheiden`: glas in de `glasbak`, papier, plastic, gft (groente, fruit en tuinafval) en restafval. Op flessen en blikjes zit `statiegeld`. De `kringloopwinkel` verkoopt `tweedehands` spullen. `Gooi het niet weg` is a national value.'),
    ex(['Deze verpakking is herbruikbaar, maar niet afbreekbaar.', 'This packaging is reusable, but not degradable.'], ['Voedselverspilling is onnodig en slecht voor het milieu.', 'Food waste is unnecessary and bad for the environment.'], ['Ik heb mijn bank bij de kringloopwinkel gekocht; dat is goedkoper en milieuvriendelijker.', 'I bought my sofa at the second-hand shop; that is cheaper and more environmentally friendly.'], ['Vergeet niet het statiegeld van de flessen terug te vragen.', 'Do not forget to reclaim the deposit on the bottles.']),
    tip('Unknown long word? Cut it from the right: `luchtvervuiling` = vervuiling (pollution) of lucht (air).'),
  ], ['g3-word-formation'], ['afval', 'afvalscheiding', 'vuilniszak', 'glasbak', 'statiegeld', 'verpakking', 'kringloopwinkel', 'tweedehands', 'luchtvervuiling', 'duurzaamheid', 'scheiden', 'weggooien', 'hergebruiken', 'recyclen', 'herbruikbaar', 'afbreekbaar', 'verspilling', 'onnodig', 'milieuvriendelijk'], [
    mc('"kringloopwinkel": which article?', ['de', 'het'], 0, 'Last part: de winkel.'),
    mc('"herbruikbaar" means', ['cannot be used', 'can be used again', 'used once'], 1, 'her- (again) + bruik + -baar (able).'),
    mc('The opposite of "nodig":', ['onnodig', 'nodigloos', 'nietnodig'], 0, 'on-.'),
    mc('"gezond" → noun:', ['gezonding', 'gezondheid', 'gezondschap'], 1, '-heid.'),
    mc('Which spelling is correct?', ['afval scheiding', 'afvalscheiding', 'afval-scheiding'], 1, 'Compounds are one word.'),
    art('statiegeld', 'het', 'het geld → het statiegeld.'),
    art('verpakking', 'de', '-ing → de.'),
    art('duurzaamheid', 'de', '-heid → de.'),
    fill('Dit plastic is niet ___. (degradable)', ['afbreekbaar'], 'This plastic is not degradable.', 'afbreken + baar.'),
    fill('De trein is ___ dan de auto. (milieuvriendelijk)', ['milieuvriendelijker'], 'The train is more environmentally friendly than the car.', '-er.'),
    fill('Gooi dat niet ___, het is nog goed.', ['weg'], 'Do not throw that away, it is still good.', 'weggooien.'),
    fill('Op deze fles zit ___.', ['statiegeld'], 'There is a deposit on this bottle.', 'statiegeld.'),
    build('Do you separate your waste?', 'Scheid je je afval?', ['scheidt', 'jouw'], 'scheid je (no t after inversion).'),
    build('This packaging is reusable.', 'Deze verpakking is herbruikbaar.', ['dit', 'hergebruiken'], 'deze verpakking (de-word).'),
    build('I bought a second-hand bike at the second-hand shop.', 'Ik heb een tweedehands fiets bij de kringloopwinkel gekocht.', ['tweedehandse', 'kocht'], 'tweedehands does not inflect.'),
    tr('en-nl', 'Food waste is unnecessary.', ['Voedselverspilling is onnodig.'], 'voedsel + verspilling.'),
    tr('nl-en', 'Glas gaat in de glasbak en papier wordt apart opgehaald.', ['Glass goes in the bottle bank and paper is collected separately.'], 'glasbak; wordt opgehaald.'),
    fix('Ik breng het glas naar de glas bak.', ['Ik breng het glas naar de glasbak.'], 'One word.'),
    dict('Afvalscheiding is verplicht, dus we hergebruiken zo veel mogelijk.', 'Waste separation is compulsory, so we reuse as much as possible.', 'afvalscheiding; hergebruiken.'),
    listen('De vuilniszakken worden op dinsdag opgehaald en moeten voor zes uur buiten staan.', ['The rubbish bags are collected on Tuesdays and must be outside before six.', 'The rubbish bags are collected at six on Tuesdays.', 'You may put rubbish outside only after six.'], 0, 'worden opgehaald; voor zes uur.'),
    speak('Ik probeer duurzamer te leven: ik scheid mijn afval en ik koop veel tweedehands.', 'I try to live more sustainably: I separate my waste and I buy a lot second-hand.'),
    free('Describe three things you do (or could do) to live more sustainably. Use at least two words ending in -baar, -heid or -ing.', 'Ik scheid mijn afval en ik gebruik een herbruikbare tas. Ik koop kleding bij de kringloopwinkel. Ik vind duurzaamheid belangrijk, dus ik probeer verspilling te vermijden.', 'I separate my waste and I use a reusable bag. I buy clothes at the second-hand shop. I find sustainability important, so I try to avoid waste.', { hints: ['Ik scheid …', 'herbruikbaar', 'duurzaamheid', 'verspilling'] }),
    match([['het afval', 'waste'], ['de glasbak', 'bottle bank'], ['het statiegeld', 'deposit'], ['herbruikbaar', 'reusable'], ['onnodig', 'unnecessary'], ['weggooien', 'to throw away']]),
  ], [
    mc('"werkloos" means', ['hard-working', 'unemployed', 'workable'], 1, '-loos = without.'),
    art('kringloopwinkel', 'de', 'de winkel.'),
    fill('mogelijk → ___ (noun)', ['mogelijkheid'], 'possible → possibility', '-heid.'),
    build('Paper is recycled.', 'Papier wordt gerecycled.', ['is', 'recyclen'], 'wordt gerecycled.'),
    tr('en-nl', 'Bring a reusable bag.', ['Neem een herbruikbare tas mee.'], 'herbruikbare (de-word); neem … mee.'),
    speak('Deze verpakking is herbruikbaar, dus gooi haar niet weg.', 'This packaging is reusable, so do not throw it away.'),
  ]));

  units.push(unit('s3u5', 'Milieu', 'environment', u5, [
    mc('De dijken ___ versterkt. (present)', ['worden', 'werden'], 0, 'worden.'),
    mc('"herbruikbaar" means', ['reusable', 'useless'], 0, 'her + bruik + baar.'),
    fill('Het huis ___ vorig jaar geïsoleerd.', ['is', 'werd'], 'The house was insulated last year.', 'is / werd.'),
    fill('Compounds are written as ___ word. (number, in Dutch)', ['één', 'een'], 'Compounds are written as one word.', 'één woord.'),
    art('afval', 'het', 'het afval.'),
    build('More wind turbines must be built.', 'Er moeten meer windmolens gebouwd worden.', ['bouwen', 'wordt'], 'er moeten … gebouwd worden.'),
    build('We try to avoid waste.', 'We proberen verspilling te vermijden.', ['vermijden te', 'vermijdt'], 'proberen … te vermijden.'),
    fix('De fles is weg gegooid.', ['De fles is weggegooid.'], 'One word.'),
    tr('en-nl', 'Climate change is a worldwide problem.', ['Klimaatverandering is een wereldwijd probleem.'], 'wereldwijd probleem (het-word with een).'),
    listen('Er wordt steeds meer afval gescheiden, maar er wordt nog te veel weggegooid.', ['More and more waste is separated, but too much is still thrown away.', 'Less waste is separated than before.', 'Nothing is thrown away any more.'], 0, 'wordt gescheiden; wordt weggegooid.'),
    speak('De zeespiegel stijgt, dus de dijken worden versterkt en er wordt geïnvesteerd in duurzame energie.', 'The sea level is rising, so the dykes are being reinforced and there is investment in sustainable energy.'),
  ]));

  /* ---------------- Unit 6: Geld en bureaucratie ---------------- */
  N('bankrekening', 'de', 'bankrekeningen', 'bank account', 'De rekening waarop mijn salaris komt, is bij ING.', 'The account my salary goes into is with ING.', { theme: 'money', stage: 3 });
  N('spaarrekening', 'de', 'spaarrekeningen', 'savings account', 'Ik zet elke maand geld op mijn spaarrekening.', 'I put money into my savings account every month.', { theme: 'money', stage: 3 });
  N('rente', 'de', null, 'interest', 'De rente is laag.', 'The interest rate is low.', { theme: 'money', stage: 3 });
  N('hypotheek', 'de', 'hypotheken', 'mortgage', 'We hebben een hypotheek afgesloten.', 'We took out a mortgage.', { theme: 'money', stage: 3 });
  N('lening', 'de', 'leningen', 'loan', 'Een lening kost geld.', 'A loan costs money.', { theme: 'money', stage: 3 });
  N('schuld', 'de', 'schulden', 'debt', 'Hij heeft schulden bij de Belastingdienst.', 'He has debts with the tax office.', { theme: 'money', stage: 3 });
  N('inkomen', 'het', 'inkomens', 'income', 'De toeslag hangt af van je inkomen.', 'The allowance depends on your income.', { theme: 'money', stage: 3 });
  N('uitgave', 'de', 'uitgaven', 'expense', 'Mijn uitgaven zijn hoger dan mijn inkomen.', 'My expenses are higher than my income.', { theme: 'money', stage: 3 });
  N('toeslag', 'de', 'toeslagen', 'allowance / benefit', 'Je kunt huurtoeslag aanvragen.', 'You can apply for rent allowance.', { theme: 'money', stage: 3 });
  N('belastingaangifte', 'de', 'belastingaangiftes', 'tax return', 'De belastingaangifte moet voor 1 mei binnen zijn.', 'The tax return has to be in before 1 May.', { theme: 'money', stage: 3 });
  N('Belastingdienst', 'de', null, 'tax office', 'De brief die ik van de Belastingdienst kreeg, was onduidelijk.', 'The letter I got from the tax office was unclear.', { theme: 'money', stage: 3 });
  N('verzekering', 'de', 'verzekeringen', 'insurance', 'De verzekering waarover ik belde, is te duur.', 'The insurance I called about is too expensive.', { theme: 'money', stage: 3 });
  N('adviseur', 'de', 'adviseurs', 'adviser', 'De adviseur met wie ik sprak, was heel duidelijk.', 'The adviser I spoke to was very clear.', { theme: 'money', stage: 3 });
  VB('sparen', 'to save (money)', 'spaar|spaart|sparen', 'spaarde|spaarden', 'gespaard', 'hebben', 'We sparen voor een huis.', 'We are saving for a house.', { theme: 'money', stage: 3 });
  VB('lenen', 'to borrow / lend', 'leen|leent|lenen', 'leende|leenden', 'geleend', 'hebben', 'Geld lenen kost geld.', 'Borrowing money costs money.', { theme: 'money', stage: 3 });
  VB('overmaken', 'to transfer (money)', 'maak over|maakt over|maken over', 'maakte over|maakten over', 'overgemaakt', 'hebben', 'Ik heb de huur overgemaakt.', 'I transferred the rent.', { theme: 'money', stage: 3 });
  VB('afsluiten', 'to take out (insurance, mortgage)', 'sluit af|sluit af|sluiten af', 'sloot af|sloten af', 'afgesloten', 'hebben', 'Ik heb een verzekering afgesloten.', 'I took out insurance.', { theme: 'money', stage: 3 });
  VB('afhangen van', 'to depend on', 'hang af van|hangt af van|hangen af van', 'hing af van|hingen af van', 'afgehangen van', 'hebben', 'Dat hangt af van je inkomen.', 'That depends on your income.', { theme: 'basics', stage: 3, id: 'afhangen-van' });
  VB('recht hebben op', 'to be entitled to', 'heb recht op|heeft recht op|hebben recht op', 'had recht op|hadden recht op', 'recht gehad op', 'hebben', 'Je hebt recht op zorgtoeslag.', 'You are entitled to healthcare allowance.', { theme: 'money', stage: 3, id: 'recht-hebben-op' });
  W('onduidelijk', 'unclear', 'adj', 'De brief was onduidelijk.', 'The letter was unclear.', { theme: 'basics', stage: 3 });

  N('aanvraagformulier', 'het', 'aanvraagformulieren', 'application form', 'Het aanvraagformulier dient volledig te worden ingevuld.', 'The application form must be filled in completely.', { theme: 'bureaucracy', stage: 3 });
  N('gegevens', 'de', 'gegevens', 'data / details', 'Controleer uw gegevens.', 'Check your details.', { theme: 'bureaucracy', stage: 3, note: 'Plural only.' });
  N('wijziging', 'de', 'wijzigingen', 'change / amendment', 'Geef wijzigingen binnen vier weken door.', 'Report changes within four weeks.', { theme: 'bureaucracy', stage: 3 });
  N('besluit', 'het', 'besluiten', 'decision', 'Tegen dit besluit kunt u bezwaar maken.', 'You can object to this decision.', { theme: 'bureaucracy', stage: 3 });
  N('betalingsregeling', 'de', 'betalingsregelingen', 'payment arrangement', 'U kunt een betalingsregeling aanvragen.', 'You can apply for a payment arrangement.', { theme: 'bureaucracy', stage: 3 });
  N('herinnering', 'de', 'herinneringen', 'reminder', 'Ik heb een herinnering ontvangen.', 'I received a reminder.', { theme: 'bureaucracy', stage: 3 });
  N('bedrag', 'het', 'bedragen', 'amount', 'Het bedrag dient binnen 14 dagen te worden betaald.', 'The amount must be paid within 14 days.', { theme: 'money', stage: 3 });
  VB('dienen te', 'must (formal)', 'dien te|dient te|dienen te', 'diende te|dienden te', 'gediend te', 'hebben', 'U dient het formulier te ondertekenen.', 'You must sign the form.', { theme: 'formal', stage: 3, id: 'dienen-te' });
  VB('verzoeken', 'to request (formal)', 'verzoek|verzoekt|verzoeken', 'verzocht|verzochten', 'verzocht', 'hebben', 'Wij verzoeken u het bedrag over te maken.', 'We request you to transfer the amount.', { theme: 'formal', stage: 3 });
  VB('doorgeven', 'to pass on / report', 'geef door|geeft door|geven door', 'gaf door|gaven door', 'doorgegeven', 'hebben', 'Geef uw verhuizing door aan de gemeente.', 'Report your move to the municipality.', { theme: 'bureaucracy', stage: 3 });
  VB('voldoen aan', 'to meet (requirements)', 'voldoe aan|voldoet aan|voldoen aan', 'voldeed aan|voldeden aan', 'voldaan aan', 'hebben', 'U voldoet niet aan de voorwaarden.', 'You do not meet the conditions.', { theme: 'formal', stage: 3, id: 'voldoen-aan' });
  N('voorwaarde', 'de', 'voorwaarden', 'condition', 'Lees de voorwaarden goed.', 'Read the conditions carefully.', { theme: 'formal', stage: 3 });
  W('in verband met', 'in connection with / because of', 'prep', 'In verband met drukte is de wachttijd langer.', 'Because of high demand the waiting time is longer.', { theme: 'formal', stage: 3, id: 'in-verband-met' });
  W('betreffende', 'regarding', 'prep', 'Een brief betreffende uw toeslag.', 'A letter regarding your allowance.', { theme: 'formal', stage: 3 });
  W('tevens', 'also (formal)', 'adv', 'Tevens verzoeken wij u een kopie mee te sturen.', 'We also request you to enclose a copy.', { theme: 'formal', stage: 3 });
  W('echter', 'however', 'adv', 'Uw aanvraag is echter niet compleet.', 'Your application is, however, not complete.', { theme: 'formal', stage: 3 });
  W('indien', 'if (formal)', 'conj', 'Indien u vragen heeft, kunt u bellen.', 'If you have questions, you can call.', { theme: 'formal', stage: 3 });
  W('volledig', 'complete(ly)', 'adj', 'Vul het formulier volledig in.', 'Fill in the form completely.', { theme: 'formal', stage: 3 });
  W('desgewenst', 'if desired (formal)', 'adv', 'U kunt desgewenst een afspraak maken.', 'If desired you can make an appointment.', { theme: 'formal', stage: 3 });

  const u6 = [];
  u6.push(lesson('s3u6l1', 'Banks, tax and allowances: waar + preposition and met wie', 'You can talk about accounts, tax and allowances and build relative clauses with prepositions: de rekening waarop, de adviseur met wie.', [
    h('Relative clauses with a preposition'),
    table(['antecedent', 'form', 'example'], [['thing', 'waar + preposition', '*De rekening waarop mijn salaris komt.'], ['thing (split, spoken)', 'waar … preposition', '*De verzekering waar ik over belde.'], ['person', 'preposition + wie', '*De adviseur met wie ik sprak.'], ['place', 'waar', '*De bank waar ik klant ben.'], ['whole clause', 'wat', '*De rente is laag, wat sparen minder aantrekkelijk maakt.']]),
    p('The preposition belongs to the verb: `bellen **over**` → `waarover`, `recht hebben **op**` → `waarop`, `afhangen **van**` → `waarvan`, `spreken **met**` → `met wie` / `waarmee`.'),
    h('The money system in short'),
    p('Your `inkomen` decides whether you have `recht op` a `toeslag` (`huurtoeslag`, `zorgtoeslag`, `kinderopvangtoeslag`), applied for at the `Belastingdienst` with DigiD. The `belastingaangifte` is due before 1 May. Changes in income must be reported, or you pay back later.'),
    ex(['De toeslag waarop je recht hebt, hangt af van je inkomen.', 'The allowance you are entitled to depends on your income.'], ['De adviseur met wie ik gisteren sprak, raadde me aan te sparen.', 'The adviser I spoke to yesterday advised me to save.'], ['Dat is precies het probleem waar ik bang voor was.', 'That is exactly the problem I was afraid of.'], ['De brief die ik van de Belastingdienst kreeg, was onduidelijk, wat me zorgen baart.', 'The letter I got from the tax office was unclear, which worries me.']),
    tip('In writing keep `waarop` together. In speech split it: `waar ik recht **op** heb`.'),
  ], ['g3-relative', 'g3-pronominal-adverbs'], ['bankrekening', 'spaarrekening', 'rente', 'hypotheek', 'lening', 'schuld', 'inkomen', 'uitgave', 'toeslag', 'belastingaangifte', 'belastingdienst', 'verzekering', 'adviseur', 'sparen', 'lenen', 'overmaken', 'afsluiten', 'afhangen-van', 'recht-hebben-op', 'onduidelijk'], [
    mc('De rekening ___ mijn salaris komt.', ['waarop', 'op die', 'dat op'], 0, 'Thing + op → waarop.'),
    mc('De adviseur ___ ik sprak, was duidelijk.', ['waarmee', 'met wie', 'die met'], 1, 'Person → met wie.'),
    mc('De toeslag ___ je recht hebt.', ['waarop', 'waarvan', 'met wie'], 0, 'recht hebben op → waarop.'),
    mc('De rente is laag, ___ sparen minder aantrekkelijk maakt.', ['dat', 'wat', 'die'], 1, 'Whole clause → wat.'),
    fill('Dat hangt af ___ je inkomen.', ['van'], 'That depends on your income.', 'afhangen van.'),
    fill('De verzekering waar ik ___ belde, is te duur.', ['over'], 'The insurance I called about is too expensive.', 'bellen over; split form.'),
    fill('Ik heb de huur gisteren ___. (overmaken)', ['overgemaakt'], 'I transferred the rent yesterday.', 'over + ge + maakt.'),
    fill('Je hebt recht ___ zorgtoeslag.', ['op'], 'You are entitled to healthcare allowance.', 'recht hebben op.'),
    build('The allowance you are entitled to depends on your income.', 'De toeslag waarop je recht hebt, hangt af van je inkomen.', ['waarvan', 'heb je'], 'waarop … hebt; hangt af van.'),
    build('The colleague I work with comes from Ghent.', 'De collega met wie ik werk, komt uit Gent.', ['waarmee', 'werk ik'], 'met wie … werk.'),
    build('We took out a mortgage last year.', 'We hebben vorig jaar een hypotheek afgesloten.', ['sluiten af', 'afsloten'], 'afgesloten at the end.'),
    tr('en-nl', 'We are saving for a house.', ['We sparen voor een huis.', 'Wij sparen voor een huis.'], 'sparen voor.'),
    tr('nl-en', 'De belastingaangifte moet voor 1 mei binnen zijn.', ['The tax return has to be in before 1 May.', 'The tax return must be submitted before 1 May.'], 'belastingaangifte.'),
    fix('De man waarmee ik sprak was de adviseur.', ['De man met wie ik sprak, was de adviseur.', 'De man met wie ik sprak was de adviseur.'], 'Person → met wie (waarmee is heard, but not in careful Dutch).'),
    fix('De brief dat ik kreeg was onduidelijk.', ['De brief die ik kreeg, was onduidelijk.', 'De brief die ik kreeg was onduidelijk.'], 'de brief → die.'),
    dict('De toeslag waarop je recht hebt, hangt af van je inkomen.', 'The allowance you are entitled to depends on your income.', 'waarop; hangt af van.'),
    listen('Ik heb de adviseur gesproken over de hypotheek waarover we twijfelden.', ['I spoke to the adviser about the mortgage we were doubting.', 'The adviser doubts our mortgage.', 'We took out the mortgage yesterday.'], 0, 'waarover … twijfelden.'),
    speak('De adviseur met wie ik sprak, zei dat ik recht heb op huurtoeslag.', 'The adviser I spoke to said that I am entitled to rent allowance.'),
    free('Explain one money matter you dealt with in the Netherlands (bank account, allowance, tax). Use one relative clause with a preposition.', 'Vorig jaar heb ik zorgtoeslag aangevraagd. De toeslag waarop ik recht heb, hangt af van mijn inkomen. De medewerker met wie ik belde, legde alles goed uit.', 'Last year I applied for healthcare allowance. The allowance I am entitled to depends on my income. The employee I phoned explained everything well.', { hints: ['De … waarop / waarover …', 'De … met wie …', 'hangt af van'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('Het probleem ___ we spraken.', ['waarover', 'over wie'], 0, 'Thing → waarover.'),
    mc('De vrouw ___ ik het gaf.', ['waaraan', 'aan wie'], 1, 'Person → aan wie.'),
    fill('Dat hangt ___ van de rente.', ['af'], 'That depends on the interest rate.', 'afhangen van.'),
    build('That is the account I save in.', 'Dat is de rekening waarop ik spaar.', ['die', 'spaar ik'], 'waarop … spaar.'),
    tr('en-nl', 'I transferred the money.', ['Ik heb het geld overgemaakt.'], 'overmaken.'),
    speak('De lening waarover ik je vertelde, heb ik uiteindelijk niet afgesloten.', 'In the end I did not take out the loan I told you about.'),
  ]));

  u6.push(lesson('s3u6l2', 'Official language: reading and writing formal Dutch', 'You can decode formal letters and forms (dient te, indien, tevens, echter, in verband met) and write a formal request yourself.', [
    h('Formal words and their everyday twins'),
    table(['formal', 'everyday', 'English'], [['*u dient te', '*u moet', 'you must'], ['*indien', '*als', 'if'], ['*tevens', '*ook', 'also'], ['*echter', '*maar', 'however'], ['*in verband met', '*vanwege, door', 'because of'], ['*betreffende', '*over', 'regarding'], ['*verzoeken', '*vragen', 'to request'], ['*ontvangen', '*krijgen', 'to receive'], ['*desgewenst', '*als u wilt', 'if desired'], ['*volledig', '*helemaal', 'completely']]),
    p('`echter` never starts a sentence in careful Dutch; it sits after the first element: `Uw aanvraag is **echter** niet compleet.` Formal letters favour the passive and `dienen te worden`: `Het formulier dient volledig te worden ingevuld.`'),
    h('Writing a formal request'),
    list('`Geachte heer, mevrouw,`', '`Betreft: …` (one line)', '`Naar aanleiding van uw brief van 3 mei …` (following your letter of 3 May)', '`Ik verzoek u vriendelijk …` / `Zou u mij kunnen laten weten …`', '`In de bijlage vindt u …`', '`Bij voorbaat dank voor uw reactie.`', '`Met vriendelijke groet,`'),
    ex(['Indien u niet aan de voorwaarden voldoet, wordt uw aanvraag afgewezen.', 'If you do not meet the conditions, your application will be rejected.'], ['In verband met een wijziging in uw inkomen dient u een nieuwe aanvraag in te dienen.', 'Because of a change in your income you must submit a new application.'], ['Wij verzoeken u het bedrag binnen 14 dagen over te maken. Desgewenst kunt u een betalingsregeling aanvragen.', 'We request you to transfer the amount within 14 days. If desired you can apply for a payment arrangement.'], ['Naar aanleiding van uw herinnering verzoek ik u vriendelijk om uitstel van betaling.', 'Following your reminder I kindly request a postponement of payment.']),
    tip('Translate a formal letter into everyday Dutch in your head (dient te → moet, indien → als). The message is usually three lines: what, by when, or else what.'),
  ], ['g3-register', 'g3-passive'], ['aanvraagformulier', 'gegevens', 'wijziging', 'besluit', 'betalingsregeling', 'herinnering', 'bedrag', 'dienen-te', 'verzoeken', 'doorgeven', 'voldoen-aan', 'voorwaarde', 'in-verband-met', 'betreffende', 'tevens', 'echter', 'indien', 'volledig', 'desgewenst'], [
    mc('"U dient te" in everyday Dutch:', ['u mag', 'u moet', 'u kunt'], 1, 'dienen te = moeten.'),
    mc('"Indien" means', ['because', 'if', 'although'], 1, 'indien = als.'),
    mc('"Tevens" means', ['however', 'also', 'therefore'], 1, 'tevens = ook.'),
    mc('Which is correct formal Dutch?', ['Echter uw aanvraag is niet compleet.', 'Uw aanvraag is echter niet compleet.', 'Uw aanvraag echter is niet compleet niet.'], 1, 'echter after the first element or the verb.'),
    fill('Het formulier ___ volledig te worden ingevuld.', ['dient'], 'The form must be filled in completely.', 'dient te.'),
    fill('___ u vragen heeft, kunt u bellen met 14 020. (if, formal)', ['Indien'], 'If you have questions, you can call 14 020.', 'indien.'),
    fill('In ___ met drukte is de wachttijd langer.', ['verband'], 'Because of high demand the waiting time is longer.', 'in verband met.'),
    fill('U voldoet niet ___ de voorwaarden.', ['aan'], 'You do not meet the conditions.', 'voldoen aan.'),
    build('We request you to transfer the amount within 14 days.', 'Wij verzoeken u het bedrag binnen 14 dagen over te maken.', ['overmaken te', 'vragen'], 'over te maken.'),
    build('You can object to this decision.', 'Tegen dit besluit kunt u bezwaar maken.', ['u kunt', 'deze'], 'Fronted phrase + inversion; dit besluit.'),
    build('Report changes within four weeks.', 'Geef wijzigingen binnen vier weken door.', ['doorgeef', 'geeft'], 'geef … door.'),
    build('I kindly request a payment arrangement.', 'Ik verzoek u vriendelijk om een betalingsregeling.', ['vraag', 'jou'], 'verzoek u vriendelijk om.'),
    tr('en-nl', 'Check your details.', ['Controleer uw gegevens.', 'Controleer je gegevens.'], 'gegevens.'),
    tr('nl-en', 'Indien u het niet eens bent met dit besluit, kunt u binnen zes weken bezwaar maken.', ['If you do not agree with this decision, you can object within six weeks.', 'If you disagree with this decision you may lodge an objection within six weeks.'], 'indien; bezwaar maken.'),
    fix('Echter is uw aanvraag niet compleet.', ['Uw aanvraag is echter niet compleet.'], 'echter does not open the sentence.'),
    dict('Het bedrag dient binnen veertien dagen te worden betaald.', 'The amount must be paid within fourteen days.', 'dient … te worden betaald.'),
    listen('In verband met een wijziging in uw inkomen ontvangt u een nieuw besluit.', ['Because of a change in your income you will receive a new decision.', 'Your income has not changed, so nothing happens.', 'You must send a new decision about your income.'], 0, 'in verband met; ontvangt … besluit.'),
    speak('Naar aanleiding van uw brief verzoek ik u vriendelijk om een betalingsregeling.', 'Following your letter I kindly request a payment arrangement.'),
    read('Belastingdienst. Betreft: herinnering betaling. Geachte heer Taylor, Uit onze administratie blijkt dat het bedrag van € 312 nog niet is ontvangen. Wij verzoeken u dit bedrag binnen 14 dagen over te maken. Indien u niet op tijd betaalt, worden extra kosten in rekening gebracht. Kunt u het bedrag niet in één keer betalen? Dan kunt u desgewenst een betalingsregeling aanvragen via Mijn Belastingdienst. Heeft u inmiddels betaald? Dan kunt u deze brief als niet verzonden beschouwen. Hoogachtend, de Belastingdienst', [
      { q: 'What is this letter?', options: ['a refund notice', 'a payment reminder', 'a request for documents'], answer: 1, explain: '"herinnering betaling".' },
      { q: 'What happens if Mr Taylor does not pay on time?', options: ['nothing', 'extra costs are charged', 'his account is closed'], answer: 1, explain: '"worden extra kosten in rekening gebracht".' },
      { q: 'What can he do if he cannot pay at once?', options: ['apply for a payment arrangement', 'lodge an objection', 'call 14 020'], answer: 0, explain: '"een betalingsregeling aanvragen".' },
      { q: 'What if he has already paid?', options: ['he must send proof', 'he can ignore the letter', 'he gets a refund'], answer: 1, explain: '"deze brief als niet verzonden beschouwen".' },
    ], { en: 'Tax office. Re: payment reminder. Dear Mr Taylor, Our records show that the amount of € 312 has not yet been received. We request you to transfer this amount within 14 days. If you do not pay on time, extra costs will be charged. Can you not pay the amount in one go? Then you can, if desired, apply for a payment arrangement via Mijn Belastingdienst. Have you paid in the meantime? Then you can regard this letter as not sent. Yours faithfully, the tax office' }),
    write('Reply formally to the reminder above (5 to 7 sentences): refer to the letter, explain briefly why you have not paid, request a payment arrangement, and close correctly.', ['Geachte heer, mevrouw, + Betreft-line', 'Naar aanleiding van uw brief van …', 'Reason in one sentence (in verband met …)', 'Ik verzoek u vriendelijk om …', 'Uses u throughout and one formal connector (echter, tevens, indien)', 'Bij voorbaat dank + Met vriendelijke groet,'], 'Geachte heer, mevrouw, Betreft: herinnering betaling € 312. Naar aanleiding van uw brief van 4 juni bericht ik u het volgende. In verband met een wijziging in mijn inkomen kan ik het bedrag niet in één keer betalen. Ik verzoek u daarom vriendelijk om een betalingsregeling van drie maanden. Indien u aanvullende gegevens nodig heeft, stuur ik die graag op. Bij voorbaat dank voor uw reactie. Met vriendelijke groet, Sam Taylor'),
  ], [
    mc('"Echter" means', ['however', 'also'], 0, 'echter = however.'),
    fill('U ___ het formulier te ondertekenen. (must, formal)', ['dient'], 'You must sign the form.', 'dient te.'),
    fill('Bij ___ dank voor uw reactie.', ['voorbaat'], 'Thank you in advance for your response.', 'bij voorbaat dank.'),
    build('If you have questions, you can call.', 'Indien u vragen heeft, kunt u bellen.', ['u kunt', 'heeft u'], 'indien … heeft; kunt u.'),
    tr('en-nl', 'Read the conditions carefully.', ['Lees de voorwaarden goed.', 'Lees de voorwaarden zorgvuldig.'], 'voorwaarden.'),
    speak('In verband met mijn verhuizing verzoek ik u mijn gegevens te wijzigen.', 'Because of my move I request you to change my details.'),
  ]));

  units.push(unit('s3u6', 'Geld en bureaucratie', 'money and bureaucracy', u6, [
    mc('De rekening ___ ik spaar.', ['waarop', 'op wie'], 0, 'waarop.'),
    mc('"Indien" =', ['als', 'maar'], 0, 'als.'),
    fill('De adviseur met ___ ik sprak.', ['wie'], 'The adviser I spoke to.', 'met wie.'),
    fill('Dat hangt af ___ uw inkomen.', ['van'], 'That depends on your income.', 'afhangen van.'),
    fill('Het bedrag ___ binnen 14 dagen te worden betaald.', ['dient'], 'The amount must be paid within 14 days.', 'dient te.'),
    build('You are entitled to rent allowance.', 'U heeft recht op huurtoeslag.', ['aan', 'bent'], 'recht hebben op.'),
    build('Your application is, however, not complete.', 'Uw aanvraag is echter niet compleet.', ['Echter uw', 'maar'], 'echter in the middle.'),
    fix('De toeslag waarvan je recht hebt.', ['De toeslag waarop je recht hebt.'], 'recht hebben op → waarop.'),
    tr('en-nl', 'I transferred the amount yesterday.', ['Ik heb het bedrag gisteren overgemaakt.'], 'overgemaakt.'),
    listen('Indien u niet aan de voorwaarden voldoet, wordt uw aanvraag afgewezen.', ['If you do not meet the conditions, your application will be rejected.', 'You meet the conditions, so your application is granted.', 'The conditions have changed.'], 0, 'voldoen aan; wordt afgewezen.'),
    speak('De toeslag waarop ik recht heb, hangt af van mijn inkomen en dient elk jaar opnieuw te worden aangevraagd.', 'The allowance I am entitled to depends on my income and must be applied for again every year.'),
  ]));

  /* ---------------- Unit 7: Vergaderingen en e-mails ---------------- */
  N('agendapunt', 'het', 'agendapunten', 'agenda item', 'Het eerste agendapunt is de begroting.', 'The first agenda item is the budget.', { theme: 'meetings', stage: 3 });
  N('notulen', 'de', 'notulen', 'minutes', 'Wie maakt de notulen?', 'Who is taking the minutes?', { theme: 'meetings', stage: 3, note: 'Plural only.' });
  N('voorzitter', 'de', 'voorzitters', 'chair', 'De voorzitter opent de vergadering.', 'The chair opens the meeting.', { theme: 'meetings', stage: 3 });
  N('voorstel', 'het', 'voorstellen', 'proposal', 'Ik heb een voorstel.', 'I have a proposal.', { theme: 'meetings', stage: 3 });
  N('actiepunt', 'het', 'actiepunten', 'action point', 'Laten we de actiepunten doornemen.', 'Let us go through the action points.', { theme: 'meetings', stage: 3 });
  N('begroting', 'de', 'begrotingen', 'budget', 'De begroting is te krap.', 'The budget is too tight.', { theme: 'meetings', stage: 3 });
  N('kwartaal', 'het', 'kwartalen', 'quarter', 'Volgend kwartaal starten we.', 'We start next quarter.', { theme: 'meetings', stage: 3 });
  N('doelstelling', 'de', 'doelstellingen', 'objective', 'Onze doelstelling is duidelijk.', 'Our objective is clear.', { theme: 'meetings', stage: 3 });
  VB('voorstellen', 'to propose / suggest', 'stel voor|stelt voor|stellen voor', 'stelde voor|stelden voor', 'voorgesteld', 'hebben', 'Ik stel voor dat we dit uitstellen.', 'I propose that we postpone this.', { theme: 'meetings', stage: 3 });
  VB('bespreken', 'to discuss', 'bespreek|bespreekt|bespreken', 'besprak|bespraken', 'besproken', 'hebben', 'Dat bespreken we volgende week.', 'We will discuss that next week.', { theme: 'meetings', stage: 3 });
  VB('samenvatten', 'to summarise', 'vat samen|vat samen|vatten samen', 'vatte samen|vatten samen', 'samengevat', 'hebben', 'Zal ik het even samenvatten?', 'Shall I summarise it?', { theme: 'meetings', stage: 3 });
  VB('afronden', 'to wrap up', 'rond af|rondt af|ronden af', 'rondde af|rondden af', 'afgerond', 'hebben', 'Laten we afronden.', 'Let us wrap up.', { theme: 'meetings', stage: 3 });
  VB('aansluiten', 'to join', 'sluit aan|sluit aan|sluiten aan', 'sloot aan|sloten aan', 'aangesloten', 'zijn', 'Tom sluit later aan.', 'Tom will join later.', { theme: 'meetings', stage: 3 });
  VB('terugkomen op', 'to come back to', 'kom terug op|komt terug op|komen terug op', 'kwam terug op|kwamen terug op', 'teruggekomen op', 'zijn', 'Daar kom ik zo op terug.', 'I will come back to that in a moment.', { theme: 'meetings', stage: 3, id: 'terugkomen-op' });
  PH('Mag ik daar even op reageren?', 'May I respond to that?', 'Mag ik daar even op reageren? Ik zie het anders.', 'May I respond to that? I see it differently.', { theme: 'meetings', stage: 3, id: 'ph-mag-ik-reageren' });
  PH('Wat mij betreft', 'As far as I am concerned', 'Wat mij betreft beginnen we maandag.', 'As far as I am concerned we start on Monday.', { theme: 'meetings', stage: 3, id: 'ph-wat-mij-betreft' });
  PH('Zijn we het daarover eens?', 'Are we agreed on that?', 'Dus we stellen de lancering uit. Zijn we het daarover eens?', 'So we postpone the launch. Are we agreed on that?', { theme: 'meetings', stage: 3, id: 'ph-eens-daarover' });
  W('concreet', 'concrete / specific', 'adj', 'Kun je iets concreter zijn?', 'Can you be a bit more specific?', { theme: 'meetings', stage: 3 });
  W('haalbaar', 'feasible', 'adj', 'Is die deadline haalbaar?', 'Is that deadline feasible?', { theme: 'meetings', stage: 3 });

  N('offerte', 'de', 'offertes', 'quotation', 'Kunt u mij een offerte sturen?', 'Could you send me a quotation?', { theme: 'email', stage: 3 });
  N('factuur', 'de', 'facturen', 'invoice', 'De factuur is nog niet betaald.', 'The invoice has not been paid yet.', { theme: 'email', stage: 3 });
  N('opdracht', 'de', 'opdrachten', 'assignment / order', 'We hebben de opdracht gekregen.', 'We won the assignment.', { theme: 'email', stage: 3 });
  N('reactie', 'de', 'reacties', 'response', 'Ik zie uw reactie graag tegemoet.', 'I look forward to your response.', { theme: 'email', stage: 3 });
  N('excuses', 'de', 'excuses', 'apologies', 'Mijn excuses voor de late reactie.', 'My apologies for the late response.', { theme: 'email', stage: 3, note: 'Plural.' });
  N('ongemak', 'het', null, 'inconvenience', 'Excuses voor het ongemak.', 'Apologies for the inconvenience.', { theme: 'email', stage: 3 });
  VB('bijsluiten', 'to enclose', 'sluit bij|sluit bij|sluiten bij', 'sloot bij|sloten bij', 'bijgesloten', 'hebben', 'De offerte is bijgesloten.', 'The quotation is enclosed.', { theme: 'email', stage: 3 });
  VB('toelichten', 'to explain / clarify', 'licht toe|licht toe|lichten toe', 'lichtte toe|lichtten toe', 'toegelicht', 'hebben', 'Ik licht het graag telefonisch toe.', 'I would be happy to explain it by phone.', { theme: 'email', stage: 3 });
  VB('inplannen', 'to schedule', 'plan in|plant in|plannen in', 'plande in|planden in', 'ingepland', 'hebben', 'Zal ik een afspraak inplannen?', 'Shall I schedule an appointment?', { theme: 'email', stage: 3 });
  VB('terugkoppelen', 'to report back', 'koppel terug|koppelt terug|koppelen terug', 'koppelde terug|koppelden terug', 'teruggekoppeld', 'hebben', 'Ik koppel het morgen terug.', 'I will report back tomorrow.', { theme: 'email', stage: 3 });
  PH('Naar aanleiding van', 'Further to / following', 'Naar aanleiding van ons gesprek stuur ik u de offerte.', 'Further to our conversation I am sending you the quotation.', { theme: 'email', stage: 3, id: 'ph-naar-aanleiding-van' });
  PH('Ik zie uw reactie graag tegemoet.', 'I look forward to your response.', 'Ik zie uw reactie graag tegemoet.', 'I look forward to your response.', { theme: 'email', stage: 3, id: 'ph-reactie-tegemoet' });
  PH('Mocht u vragen hebben', 'Should you have any questions', 'Mocht u vragen hebben, dan hoor ik het graag.', 'Should you have any questions, please let me know.', { theme: 'email', stage: 3, id: 'ph-mocht-u' });
  PH('Bij voorbaat dank.', 'Thank you in advance.', 'Bij voorbaat dank voor uw medewerking.', 'Thank you in advance for your cooperation.', { theme: 'email', stage: 3, id: 'ph-bij-voorbaat-dank' });
  W('uiterlijk', 'at the latest', 'adv', 'Graag uiterlijk vrijdag reageren.', 'Please respond by Friday at the latest.', { theme: 'email', stage: 3 });
  W('graag', 'please / gladly', 'adv', 'Graag uw reactie voor vrijdag.', 'Your response before Friday, please.', { theme: 'email', stage: 3 });
  W('zo spoedig mogelijk', 'as soon as possible (formal)', 'adv', 'Wij nemen zo spoedig mogelijk contact met u op.', 'We will contact you as soon as possible.', { theme: 'email', stage: 3, id: 'zo-spoedig-mogelijk' });

  const u7 = [];
  u7.push(lesson('s3u7l1', 'In the meeting: word order for emphasis', 'You can take part in a Dutch meeting: propose, respond, summarise, and use word order (fronting, time-manner-place) to say exactly what you mean.', [
    h('Meeting language'),
    table(['function', 'Dutch'], [['open', '*Zullen we beginnen? Het eerste agendapunt is …'], ['propose', '*Ik stel voor dat we … / Wat mij betreft …'], ['respond', '*Mag ik daar even op reageren? / Daar ben ik het (niet) mee eens.'], ['ask for detail', '*Kun je dat concreter maken? / Is dat haalbaar?'], ['park it', '*Daar kom ik zo op terug. / Dat bespreken we volgende keer.'], ['summarise', '*Even samenvatten: … / Zijn we het daarover eens?'], ['close', '*Laten we afronden. Wie doet wat?']]),
    h('Fronting: put first what matters'),
    p('Anything can stand in first position; the verb stays second and the subject follows it. Use it to link to what was just said or to contrast: `**Dat voorstel** vind ik goed, **het andere** niet.` `**Volgend kwartaal** is dat haalbaar, **dit kwartaal** niet.` `**Daar** kom ik zo op terug.`'),
    h('The middle field: time, manner, place'),
    p('`We bespreken dat **morgen** **uitgebreid** **in de vergadering**.` Pronouns go early: `Ik stuur **het je** morgen.` Definite objects before time, indefinite after: `Ik heb **de notulen** gisteren verstuurd` / `Ik heb gisteren **een voorstel** verstuurd`.'),
    ex(['Wat mij betreft stellen we de lancering een kwartaal uit.', 'As far as I am concerned we postpone the launch by a quarter.'], ['Die deadline vind ik eerlijk gezegd niet haalbaar.', 'Honestly, I do not find that deadline feasible.'], ['Mag ik daar even op reageren? Over de begroting hebben we het nog niet gehad.', 'May I respond to that? We have not talked about the budget yet.'], ['Even samenvatten: Anna maakt de planning, Tom vraagt de offerte aan. Zijn we het daarover eens?', 'To summarise: Anna makes the planning, Tom requests the quotation. Are we agreed?']),
    tip('Start your turn with what the previous speaker said: `Dat punt over de planning …`, `Daarover wil ik nog iets zeggen.` It sounds connected and buys you thinking time.'),
  ], ['g3-word-order', 'g3-pronominal-adverbs'], ['agendapunt', 'notulen', 'voorzitter', 'voorstel', 'besluit', 'actiepunt', 'begroting', 'kwartaal', 'doelstelling', 'voorstellen', 'bespreken', 'samenvatten', 'afronden', 'aansluiten', 'terugkomen-op', 'ph-mag-ik-reageren', 'ph-wat-mij-betreft', 'ph-eens-daarover', 'concreet', 'haalbaar'], [
    mc('Which is correct?', ['Dat voorstel ik vind goed.', 'Dat voorstel vind ik goed.', 'Dat voorstel goed vind ik.'], 1, 'Fronted object, verb second, then subject.'),
    mc('Natural order:', ['We bespreken dat in de vergadering morgen uitgebreid.', 'We bespreken dat morgen uitgebreid in de vergadering.', 'We bespreken uitgebreid morgen dat in de vergadering.'], 1, 'Time, manner, place.'),
    mc('Which is correct?', ['Ik heb gisteren de notulen verstuurd.', 'Ik heb de notulen gisteren verstuurd.', 'Both are fine, the second is more neutral.'], 2, 'Definite objects usually come before time; after is possible for emphasis.'),
    mc('"I will come back to that":', ['Daar kom ik op terug.', 'Dat kom ik terug op.', 'Ik kom terug op het.'], 0, 'daar … op terug.'),
    fill('Wat ___ betreft beginnen we maandag.', ['mij'], 'As far as I am concerned we start on Monday.', 'wat mij betreft.'),
    fill('Ik stel ___ dat we dit volgende week bespreken. (voorstellen)', ['voor'], 'I propose that we discuss this next week.', 'stel … voor.'),
    fill('Is die deadline ___? (feasible)', ['haalbaar'], 'Is that deadline feasible?', 'halen + baar.'),
    fill('Zal ik het even ___? (summarise)', ['samenvatten'], 'Shall I summarise it?', 'samenvatten.'),
    build('That deadline I do not find feasible.', 'Die deadline vind ik niet haalbaar.', ['ik vind', 'dat'], 'Fronted object + vind ik.'),
    build('May I respond to that?', 'Mag ik daar even op reageren?', ['over', 'dat'], 'daar … op reageren.'),
    build('We have to take a decision today.', 'We moeten vandaag een besluit nemen.', ['maken', 'nemen een besluit'], 'een besluit nemen.'),
    build('Tom will join later.', 'Tom sluit later aan.', ['aansluit', 'komt'], 'sluit … aan.'),
    tr('en-nl', 'Let us wrap up. Who does what?', ['Laten we afronden. Wie doet wat?'], 'afronden.'),
    tr('nl-en', 'Over de begroting hebben we het nog niet gehad.', ['We have not talked about the budget yet.', 'We have not discussed the budget yet.'], 'het hebben over = to talk about.'),
    fix('Volgend kwartaal wij starten het project.', ['Volgend kwartaal starten we het project.', 'Volgend kwartaal starten wij het project.'], 'Inversion after a fronted time.'),
    fix('Ik stuur morgen het je.', ['Ik stuur het je morgen.'], 'Pronouns before time.'),
    dict('Wat mij betreft stellen we de lancering een kwartaal uit.', 'As far as I am concerned we postpone the launch by a quarter.', 'wat mij betreft + inversion; stellen … uit.'),
    listen('Even samenvatten: Anna maakt de planning en Tom koppelt vrijdag terug.', ['To summarise: Anna makes the planning and Tom reports back on Friday.', 'Anna reports back and Tom makes the planning.', 'The planning is postponed until Friday.'], 0, 'samenvatten; koppelt terug.'),
    speak('Mag ik daar even op reageren? Die deadline vind ik eerlijk gezegd niet haalbaar.', 'May I respond to that? Honestly, I do not find that deadline feasible.'),
    free('You are in a meeting about moving the office. Make a proposal, give one reason, and ask whether everyone agrees.', 'Ik stel voor dat we in het derde kwartaal verhuizen. Dit kwartaal is dat niet haalbaar, want de begroting is te krap. Zijn we het daarover eens?', 'I propose that we move in the third quarter. This quarter that is not feasible, because the budget is too tight. Are we agreed on that?', { hints: ['Ik stel voor dat …', '… is (niet) haalbaar, want …', 'Zijn we het daarover eens?'] }),
    auto(3, ['tr-nl-en', 'article']),
  ], [
    mc('Which is correct?', ['Morgen ik bel je.', 'Morgen bel ik je.'], 1, 'Inversion.'),
    fill('Daar kom ik zo ___ terug.', ['op'], 'I will come back to that in a moment.', 'terugkomen op.'),
    fill('We moeten een besluit ___.', ['nemen'], 'We have to take a decision.', 'een besluit nemen.'),
    build('That we will discuss next week.', 'Dat bespreken we volgende week.', ['we bespreken', 'over'], 'Fronted dat + inversion.'),
    tr('en-nl', 'Can you be more specific?', ['Kun je concreter zijn?', 'Kun je dat concreter maken?', 'Kunt u concreter zijn?'], 'concreter.'),
    speak('Wat mij betreft ronden we nu af en bespreken we de begroting volgende week.', 'As far as I am concerned we wrap up now and discuss the budget next week.'),
  ]));

  u7.push(lesson('s3u7l2', 'Professional email: formal requests, apologies and follow-ups', 'You can write a professional Dutch email to a client or organisation: refer, request with zou, apologise, attach, set a deadline and close.', [
    h('Building blocks'),
    table(['function', 'Dutch'], [['refer', '*Naar aanleiding van ons gesprek van dinsdag …'], ['purpose', '*Hierbij stuur ik u … / Ik schrijf u in verband met …'], ['polite request', '*Zou u mij de offerte kunnen toesturen? / Graag ontvang ik …'], ['apologise', '*Mijn excuses voor de late reactie. / Excuses voor het ongemak.'], ['attach', '*De factuur is bijgesloten. / In de bijlage vindt u …'], ['deadline', '*Graag uiterlijk vrijdag. / zo spoedig mogelijk'], ['offer', '*Ik licht het graag telefonisch toe. / Zal ik een afspraak inplannen?'], ['close', '*Mocht u vragen hebben, dan hoor ik het graag. / Ik zie uw reactie graag tegemoet. / Bij voorbaat dank.']]),
    p('`Graag` at the start is a compact polite imperative: `Graag uw reactie voor vrijdag.` (= Please respond before Friday.) `Mocht u …` is the formal "should you …": `Mocht u vragen hebben, dan …`'),
    h('Register ladder'),
    p('Colleague: `Hoi Tom, kun je …? Groet, Sam`. Known client: `Beste mevrouw Jansen, zou u … kunnen …? Met vriendelijke groet,`. Unknown organisation: `Geachte heer, mevrouw, … Hoogachtend,` or `Met vriendelijke groet,`.'),
    ex(['Naar aanleiding van ons telefoongesprek stuur ik u hierbij de offerte.', 'Further to our phone call I am hereby sending you the quotation.'], ['Mijn excuses voor de late reactie; ik was vorige week afwezig.', 'My apologies for the late response; I was away last week.'], ['Zou u de factuur uiterlijk vrijdag kunnen voldoen?', 'Could you settle the invoice by Friday at the latest?'], ['Mocht u nog vragen hebben, dan licht ik het graag telefonisch toe.', 'Should you have any further questions, I would be happy to explain by phone.']),
    tip('One email, one request. Put the request in its own short paragraph and the deadline in the same sentence.'),
  ], ['g3-register', 'g3-conditional'], ['offerte', 'factuur', 'opdracht', 'reactie', 'excuses', 'ongemak', 'bijsluiten', 'toelichten', 'inplannen', 'terugkoppelen', 'ph-naar-aanleiding-van', 'ph-reactie-tegemoet', 'ph-mocht-u', 'ph-bij-voorbaat-dank', 'uiterlijk', 'graag', 'zo-spoedig-mogelijk'], [
    mc('Most polite request to a client:', ['Stuur de offerte.', 'Kun je de offerte sturen?', 'Zou u mij de offerte kunnen toesturen?'], 2, 'zou u … kunnen.'),
    mc('"Mocht u vragen hebben" means', ['you may have questions', 'should you have questions', 'you must have questions'], 1, 'Formal conditional.'),
    mc('"Graag uiterlijk vrijdag" means', ['gladly after Friday', 'by Friday at the latest, please', 'on Friday evening'], 1, 'graag + uiterlijk.'),
    mc('Opening for an unknown organisation:', ['Hoi,', 'Geachte heer, mevrouw,', 'Beste allemaal,'], 1, 'Geachte heer, mevrouw,'),
    fill('Naar ___ van ons gesprek stuur ik u de offerte.', ['aanleiding'], 'Further to our conversation I am sending you the quotation.', 'naar aanleiding van.'),
    fill('Mijn ___ voor de late reactie.', ['excuses'], 'My apologies for the late response.', 'excuses.'),
    fill('De factuur is ___. (bijsluiten, participle)', ['bijgesloten'], 'The invoice is enclosed.', 'bij + gesloten.'),
    fill('Ik zie uw reactie graag ___.', ['tegemoet'], 'I look forward to your response.', 'tegemoet zien.'),
    build('Could you send me the quotation by Friday at the latest?', 'Zou u mij de offerte uiterlijk vrijdag kunnen sturen?', ['Kan', 'stuurt'], 'zou u … kunnen sturen.'),
    build('Should you have questions, please let me know.', 'Mocht u vragen hebben, dan hoor ik het graag.', ['ik hoor', 'Als'], 'mocht u … hebben, dan hoor ik.'),
    build('I will report back tomorrow.', 'Ik koppel het morgen terug.', ['terugkoppel', 'morgen het'], 'koppel … terug; pronoun before time.'),
    build('We will contact you as soon as possible.', 'Wij nemen zo spoedig mogelijk contact met u op.', ['opnemen', 'jou'], 'nemen … contact met u op.'),
    tr('en-nl', 'Apologies for the inconvenience.', ['Excuses voor het ongemak.', 'Mijn excuses voor het ongemak.'], 'ongemak.'),
    tr('nl-en', 'Ik licht het voorstel graag telefonisch toe.', ['I would be happy to explain the proposal by phone.', 'I will gladly clarify the proposal by phone.'], 'toelichten.'),
    fix('Geachte mevrouw Jansen, kun je de factuur betalen? Groetjes, Sam', ['Geachte mevrouw Jansen, zou u de factuur kunnen voldoen? Met vriendelijke groet, Sam', 'Beste mevrouw Jansen, zou u de factuur kunnen betalen? Met vriendelijke groet, Sam'], 'Formal opening needs u, zou and a formal closing.'),
    dict('Mocht u nog vragen hebben, dan hoor ik het graag.', 'Should you have any further questions, please let me know.', 'mocht u … hebben, dan.'),
    listen('Naar aanleiding van uw mail van gisteren stuur ik u hierbij de aangepaste offerte.', ['Further to your email of yesterday I am hereby sending you the revised quotation.', 'I did not receive your email of yesterday.', 'The quotation will follow tomorrow.'], 0, 'naar aanleiding van; aangepaste offerte.'),
    speak('Mijn excuses voor de late reactie. Zou u mij de factuur opnieuw kunnen toesturen?', 'My apologies for the late response. Could you send me the invoice again?'),
    read('Beste heer De Boer, Naar aanleiding van ons gesprek van dinsdag stuur ik u hierbij de offerte voor de verbouwing van uw kantoor. De werkzaamheden kunnen in week 38 starten en duren ongeveer drie weken. De prijs is inclusief materiaal, maar exclusief btw. Zou u mij uiterlijk 1 september kunnen laten weten of u akkoord gaat? Dan plannen wij de werkzaamheden in. Mocht u vragen hebben, dan licht ik de offerte graag telefonisch toe. Met vriendelijke groet, Anna Visser', [
      { q: 'When can the work start?', options: ['on 1 September', 'in week 38', 'in three weeks'], answer: 1, explain: '"in week 38 starten".' },
      { q: 'What is not included in the price?', options: ['materials', 'VAT', 'labour'], answer: 1, explain: '"exclusief btw".' },
      { q: 'What does Anna ask Mr De Boer to do?', options: ['call her', 'say by 1 September whether he agrees', 'pay in advance'], answer: 1, explain: '"uiterlijk 1 september … of u akkoord gaat".' },
    ], { en: 'Dear Mr De Boer, Further to our conversation on Tuesday I am hereby sending you the quotation for the renovation of your office. The work can start in week 38 and takes about three weeks. The price includes materials, but excludes VAT. Could you let me know by 1 September at the latest whether you agree? Then we will schedule the work. Should you have questions, I would be happy to explain the quotation by phone. Kind regards, Anna Visser' }),
    write('Write a professional email (6 to 8 sentences) to a company: refer to earlier contact, apologise for a delay, make one request with zou, give a deadline and close formally.', ['Correct opening for the relationship', 'Naar aanleiding van …', 'Excuses for something', 'One request with Zou u … kunnen …?', 'Deadline with uiterlijk or zo spoedig mogelijk', 'Mocht u vragen hebben … + Met vriendelijke groet,'], 'Beste mevrouw Jansen, Naar aanleiding van uw mail van maandag stuur ik u hierbij de gevraagde gegevens. Mijn excuses voor de late reactie; ik was vorige week afwezig. In de bijlage vindt u de getekende opdracht. Zou u mij uiterlijk vrijdag een bevestiging kunnen sturen? Dan plan ik de eerste afspraak in. Mocht u vragen hebben, dan hoor ik het graag. Met vriendelijke groet, Sam Taylor'),
  ], [
    mc('"Bij voorbaat dank" means', ['thanks afterwards', 'thank you in advance'], 1, 'bij voorbaat.'),
    fill('___ u vragen hebben, dan hoor ik het graag.', ['Mocht'], 'Should you have questions, please let me know.', 'mocht u.'),
    fill('Zou u mij de offerte ___ sturen? (can)', ['kunnen'], 'Could you send me the quotation?', 'zou … kunnen.'),
    build('The invoice has not been paid yet.', 'De factuur is nog niet betaald.', ['heeft', 'niet nog'], 'is nog niet betaald.'),
    tr('en-nl', 'I look forward to your response.', ['Ik zie uw reactie graag tegemoet.', 'Ik kijk uit naar uw reactie.'], 'tegemoet zien.'),
    speak('Naar aanleiding van ons gesprek stuur ik u hierbij de offerte. Ik zie uw reactie graag tegemoet.', 'Further to our conversation I am hereby sending you the quotation. I look forward to your response.'),
  ]));

  units.push(unit('s3u7', 'Vergaderingen en e-mails', 'work meetings and emails', u7, [
    mc('Which is correct?', ['Dat ik vind goed.', 'Dat vind ik goed.'], 1, 'Verb second.'),
    mc('Most formal:', ['Kun je …?', 'Zou u … kunnen …?'], 1, 'zou u.'),
    fill('Wat mij ___ beginnen we nu.', ['betreft'], 'As far as I am concerned we start now.', 'wat mij betreft.'),
    fill('Naar aanleiding ___ uw mail …', ['van'], 'Further to your email …', 'naar aanleiding van.'),
    fill('Daar kom ik zo op ___.', ['terug'], 'I will come back to that in a moment.', 'terugkomen op.'),
    build('We discuss that tomorrow in the meeting.', 'We bespreken dat morgen in de vergadering.', ['in de vergadering morgen', 'over'], 'Time before place.'),
    build('Should you have questions, I will explain it by phone.', 'Mocht u vragen hebben, dan licht ik het telefonisch toe.', ['ik licht', 'toelicht'], 'dan licht ik … toe.'),
    fix('Ik stuur morgen het je.', ['Ik stuur het je morgen.'], 'Pronouns first.'),
    tr('en-nl', 'I propose that we postpone this.', ['Ik stel voor dat we dit uitstellen.', 'Ik stel voor om dit uit te stellen.'], 'voorstellen dat.'),
    listen('Zijn we het daarover eens? Dan ronden we af en stuur ik vanmiddag de notulen.', ['Are we agreed on that? Then we wrap up and I will send the minutes this afternoon.', 'We do not agree, so there are no minutes.', 'The minutes were sent this morning.'], 0, 'daarover eens; afronden; notulen.'),
    speak('Wat mij betreft is dat haalbaar. Ik koppel het vrijdag terug en stuur de offerte uiterlijk maandag.', 'As far as I am concerned that is feasible. I will report back on Friday and send the quotation by Monday at the latest.'),
  ]));

  /* ---------------- Unit 8: Nederlandse cultuur en geschiedenis ---------------- */
  N('gezelligheid', 'de', null, 'cosiness / conviviality', 'Gezelligheid is moeilijk te vertalen.', 'Gezelligheid is hard to translate.', { theme: 'culture', stage: 3 });
  N('Koningsdag', 'de', null, 'King’s Day (27 April)', 'Op Koningsdag is de hele stad oranje.', 'On King’s Day the whole city is orange.', { theme: 'culture', stage: 3 });
  N('vrijmarkt', 'de', 'vrijmarkten', 'free market (street sale on King’s Day)', 'Op de vrijmarkt verkopen kinderen hun oude speelgoed.', 'At the free market children sell their old toys.', { theme: 'culture', stage: 3 });
  N('Sinterklaas', 'de', null, 'Saint Nicholas (5 December)', 'Met Sinterklaas schrijven we gedichten voor elkaar.', 'At Sinterklaas we write poems for each other.', { theme: 'culture', stage: 3 });
  N('gedicht', 'het', 'gedichten', 'poem', 'Bij elk cadeau hoort een gedicht.', 'Every present comes with a poem.', { theme: 'culture', stage: 3 });
  N('traditie', 'de', 'tradities', 'tradition', 'Dat is een oude traditie.', 'That is an old tradition.', { theme: 'culture', stage: 3 });
  N('feestdag', 'de', 'feestdagen', 'public holiday', 'Op feestdagen zijn de winkels vaak dicht.', 'On public holidays the shops are often closed.', { theme: 'culture', stage: 3 });
  N('verjaardagskalender', 'de', 'verjaardagskalenders', 'birthday calendar', 'De verjaardagskalender hangt op de wc.', 'The birthday calendar hangs in the toilet.', { theme: 'culture', stage: 3 });
  N('directheid', 'de', null, 'directness', 'Nederlanders staan bekend om hun directheid.', 'The Dutch are known for their directness.', { theme: 'culture', stage: 3 });
  VB('vieren', 'to celebrate', 'vier|viert|vieren', 'vierde|vierden', 'gevierd', 'hebben', 'We vieren Sinterklaas op 5 december.', 'We celebrate Sinterklaas on 5 December.', { theme: 'culture', stage: 3 });
  VB('feliciteren', 'to congratulate', 'feliciteer|feliciteert|feliciteren', 'feliciteerde|feliciteerden', 'gefeliciteerd', 'hebben', 'Je feliciteert ook de familie van de jarige.', 'You also congratulate the family of the birthday person.', { theme: 'culture', stage: 3 });
  VB('trakteren', 'to treat', 'trakteer|trakteert|trakteren', 'trakteerde|trakteerden', 'getrakteerd', 'hebben', 'Als je jarig bent, trakteer je zelf op taart.', 'When it is your birthday, you treat others to cake yourself.', { theme: 'culture', stage: 3 });
  W('nuchter', 'down-to-earth / sober', 'adj', 'Nederlanders zijn nuchter.', 'The Dutch are down-to-earth.', { theme: 'culture', stage: 3 });
  W('zuinig', 'thrifty', 'adj', 'Hij is zuinig, niet gierig.', 'He is thrifty, not stingy.', { theme: 'culture', stage: 3 });
  PH('Het valt wel mee.', 'It is not so bad.', 'Hoe was het weer? — Het viel wel mee.', 'How was the weather? — Not so bad.', { theme: 'idioms', stage: 3, id: 'id-valt-mee' });
  PH('met de deur in huis vallen', 'to get straight to the point', 'Ik val maar met de deur in huis: we moeten bezuinigen.', 'I will get straight to the point: we have to cut costs.', { theme: 'idioms', stage: 3, id: 'id-deur-in-huis' });
  PH('de kat uit de boom kijken', 'to wait and see', 'Hij kijkt eerst de kat uit de boom.', 'He waits and sees first.', { theme: 'idioms', stage: 3, id: 'id-kat-uit-de-boom' });
  PH('iemand op de hoogte houden', 'to keep someone informed', 'Ik hou je op de hoogte.', 'I will keep you informed.', { theme: 'idioms', stage: 3, id: 'id-op-de-hoogte' });
  PH('Doe maar gewoon, dan doe je al gek genoeg.', 'Just act normal, that is crazy enough.', 'Doe maar gewoon, dan doe je al gek genoeg, zei mijn oma altijd.', 'Just act normal, that is crazy enough, my grandma always said.', { theme: 'idioms', stage: 3, id: 'id-doe-maar-gewoon' });
  PH('Het regent pijpenstelen.', 'It is pouring.', 'Neem een jas mee, het regent pijpenstelen.', 'Take a coat, it is pouring.', { theme: 'idioms', stage: 3, id: 'id-pijpenstelen' });
  PH('Dat slaat nergens op.', 'That makes no sense.', 'Die regel slaat nergens op.', 'That rule makes no sense.', { theme: 'idioms', stage: 3, id: 'id-slaat-nergens-op' });

  N('eeuw', 'de', 'eeuwen', 'century', 'In de zeventiende eeuw was Amsterdam een wereldstad.', 'In the seventeenth century Amsterdam was a world city.', { theme: 'history', stage: 3 });
  N('Gouden Eeuw', 'de', null, 'Golden Age (17th century)', 'In de Gouden Eeuw werden de grachten gegraven.', 'In the Golden Age the canals were dug.', { theme: 'history', stage: 3, id: 'gouden-eeuw' });
  N('gracht', 'de', 'grachten', 'canal (in a city)', 'De grachten werden in de zeventiende eeuw aangelegd.', 'The canals were laid out in the seventeenth century.', { theme: 'history', stage: 3 });
  N('handel', 'de', null, 'trade', 'De stad werd rijk door de handel.', 'The city became rich through trade.', { theme: 'history', stage: 3 });
  N('kolonie', 'de', 'koloniën', 'colony', 'Indonesië was een Nederlandse kolonie.', 'Indonesia was a Dutch colony.', { theme: 'history', stage: 3 });
  N('slavernij', 'de', null, 'slavery', 'De slavernij werd in 1863 afgeschaft.', 'Slavery was abolished in 1863.', { theme: 'history', stage: 3 });
  N('oorlog', 'de', 'oorlogen', 'war', 'Tijdens de oorlog was Nederland bezet.', 'During the war the Netherlands was occupied.', { theme: 'history', stage: 3 });
  N('bezetting', 'de', null, 'occupation', 'De bezetting duurde vijf jaar.', 'The occupation lasted five years.', { theme: 'history', stage: 3 });
  N('bevrijding', 'de', null, 'liberation', 'Op 5 mei vieren we de bevrijding.', 'On 5 May we celebrate the liberation.', { theme: 'history', stage: 3 });
  N('herdenking', 'de', 'herdenkingen', 'commemoration', 'Op 4 mei is de Dodenherdenking.', 'On 4 May is the Remembrance of the Dead.', { theme: 'history', stage: 3 });
  N('koninkrijk', 'het', 'koninkrijken', 'kingdom', 'Nederland is sinds 1815 een koninkrijk.', 'The Netherlands has been a kingdom since 1815.', { theme: 'history', stage: 3 });
  N('grondwet', 'de', 'grondwetten', 'constitution', 'De grondwet van 1848 werd door Thorbecke geschreven.', 'The constitution of 1848 was written by Thorbecke.', { theme: 'history', stage: 3 });
  N('polder', 'de', 'polders', 'polder (reclaimed land)', 'Flevoland is een polder uit de twintigste eeuw.', 'Flevoland is a polder from the twentieth century.', { theme: 'history', stage: 3 });
  VB('stichten', 'to found', 'sticht|sticht|stichten', 'stichtte|stichtten', 'gesticht', 'hebben', 'De VOC werd in 1602 gesticht.', 'The VOC was founded in 1602.', { theme: 'history', stage: 3 });
  VB('afschaffen', 'to abolish', 'schaf af|schaft af|schaffen af', 'schafte af|schaften af', 'afgeschaft', 'hebben', 'De slavernij werd in 1863 afgeschaft.', 'Slavery was abolished in 1863.', { theme: 'history', stage: 3 });
  VB('bezetten', 'to occupy', 'bezet|bezet|bezetten', 'bezette|bezetten', 'bezet', 'hebben', 'Nederland werd in 1940 bezet.', 'The Netherlands was occupied in 1940.', { theme: 'history', stage: 3 });
  VB('bevrijden', 'to liberate', 'bevrijd|bevrijdt|bevrijden', 'bevrijdde|bevrijdden', 'bevrijd', 'hebben', 'Het land werd in mei 1945 bevrijd.', 'The country was liberated in May 1945.', { theme: 'history', stage: 3 });
  VB('herdenken', 'to commemorate', 'herdenk|herdenkt|herdenken', 'herdacht|herdachten', 'herdacht', 'hebben', 'Op 4 mei worden de doden herdacht.', 'On 4 May the dead are commemorated.', { theme: 'history', stage: 3 });
  VB('droogleggen', 'to drain (reclaim land)', 'leg droog|legt droog|leggen droog', 'legde droog|legden droog', 'drooggelegd', 'hebben', 'De Beemster werd in 1612 drooggelegd.', 'The Beemster was drained in 1612.', { theme: 'history', stage: 3 });
  W('tijdens', 'during', 'prep', 'Tijdens de oorlog was er honger.', 'During the war there was hunger.', { theme: 'history', stage: 3 });

  const u8 = [];
  u8.push(lesson('s3u8l1', 'Dutch habits and idioms: what people really say', 'You can explain typical Dutch customs and use a first set of everyday idioms naturally: het valt wel mee, ik hou je op de hoogte, met de deur in huis vallen.', [
    h('Customs worth knowing'),
    list('**Verjaardag**: you congratulate everyone in the room (`Gefeliciteerd met je broer!`), sit in a circle, and the birthday person **trakteert** (brings cake to work).', '**Koningsdag** (27 April): orange clothes and the `vrijmarkt`, where anyone may sell second-hand things on the street.', '**Sinterklaas** (5 December): presents with a `gedicht` that gently teases the receiver.', '**Afspraak**: you do not drop by unannounced; you make an appointment, even with friends, often weeks ahead.', '**Directheid**: saying what you think is seen as honest, not rude. `Doe maar gewoon` is the national motto.'),
    h('Idioms you will hear every week'),
    table(['idiom', 'meaning', 'use it when'], [['*Het valt wel mee.', 'it is not so bad', 'someone expects the worst'], ['*Ik hou je op de hoogte.', 'I will keep you posted', 'ending a call or email'], ['*met de deur in huis vallen', 'get straight to the point', 'opening a difficult topic'], ['*de kat uit de boom kijken', 'wait and see', 'someone is cautious in a new group'], ['*Dat slaat nergens op.', 'that makes no sense', 'mild protest'], ['*Het regent pijpenstelen.', 'it is pouring', 'any autumn day'], ['*Doe maar gewoon.', 'just act normal', 'someone shows off']]),
    ex(['Ik val maar met de deur in huis: ik heb een andere baan.', 'I will get straight to the point: I have another job.'], ['Hoe was de verhuizing? — Ach, het viel wel mee.', 'How was the move? — Oh, it was not so bad.'], ['In een nieuwe groep kijk ik eerst de kat uit de boom.', 'In a new group I wait and see first.'], ['Ik weet het morgen. Ik hou je op de hoogte!', 'I will know tomorrow. I will keep you posted!']),
    tip('Idioms are fixed: do not change the words. `de kat uit de boom kijken` never becomes "de hond".'),
  ], ['g3-idioms', 'g3-particles'], ['gezelligheid', 'koningsdag', 'vrijmarkt', 'sinterklaas', 'gedicht', 'traditie', 'feestdag', 'verjaardagskalender', 'directheid', 'vieren', 'feliciteren', 'trakteren', 'nuchter', 'zuinig', 'id-valt-mee', 'id-deur-in-huis', 'id-kat-uit-de-boom', 'id-op-de-hoogte', 'id-doe-maar-gewoon', 'id-pijpenstelen', 'id-slaat-nergens-op'], [
    mc('"Het valt wel mee" means', ['it fell down', 'it is not so bad', 'it fits well'], 1, 'meevallen.'),
    mc('"Met de deur in huis vallen" means', ['to break the door', 'to get straight to the point', 'to arrive late'], 1, 'Straight to the point.'),
    mc('"De kat uit de boom kijken" means', ['to rescue a cat', 'to wait and see', 'to look for trouble'], 1, 'Wait and see.'),
    mc('On a Dutch birthday, who brings the cake to work?', ['the colleagues', 'the birthday person', 'the boss'], 1, 'De jarige trakteert.'),
    mc('"Ik hou je op de hoogte" means', ['I will hold you up', 'I will keep you posted', 'I am taller than you'], 1, 'Keep informed.'),
    fill('Het regent ___. (it is pouring)', ['pijpenstelen'], 'It is pouring.', 'pijpenstelen.'),
    fill('Dat slaat ___ op. (makes no sense)', ['nergens'], 'That makes no sense.', 'nergens op slaan.'),
    fill('___ met je verjaardag!', ['Gefeliciteerd'], 'Happy birthday!', 'gefeliciteerd met.'),
    fill('Op Koningsdag is er overal een ___. (street market)', ['vrijmarkt'], 'On King’s Day there is a free market everywhere.', 'vrijmarkt.'),
    build('I will get straight to the point.', 'Ik val maar met de deur in huis.', ['huis in', 'de deur met'], 'Fixed idiom.'),
    build('I will keep you posted.', 'Ik hou je op de hoogte.', ['hoog', 'in'], 'op de hoogte houden.'),
    build('When it is your birthday, you treat others yourself.', 'Als je jarig bent, trakteer je zelf.', ['je trakteert', 'bent jarig'], 'als … bent; trakteer je.'),
    tr('en-nl', 'The Dutch are known for their directness.', ['Nederlanders staan bekend om hun directheid.'], 'bekendstaan om.'),
    tr('nl-en', 'Doe maar gewoon, dan doe je al gek genoeg.', ['Just act normal, that is crazy enough.', 'Just be normal, that is already crazy enough.'], 'The Dutch motto.'),
    fix('Hij kijkt de hond uit de boom.', ['Hij kijkt de kat uit de boom.'], 'Idioms are fixed: kat.'),
    dict('Hoe was het examen? Ach, het viel wel mee.', 'How was the exam? Oh, it was not so bad.', 'viel wel mee.'),
    listen('Ik val maar met de deur in huis: we moeten het feest verzetten, want het regent pijpenstelen.', ['I will get straight to the point: we have to move the party, because it is pouring.', 'The door is broken, so the party is cancelled.', 'The party goes ahead despite the rain.'], 0, 'Two idioms.'),
    speak('Met Sinterklaas schrijven we gedichten voor elkaar, en op Koningsdag is de hele stad oranje.', 'At Sinterklaas we write poems for each other, and on King’s Day the whole city is orange.'),
    free('Describe one Dutch custom that surprised you, and use one idiom from this lesson.', 'Ik was verbaasd dat je op je verjaardag zelf moet trakteren. In het begin vond ik de directheid ook moeilijk, maar het valt wel mee. Nu vind ik het juist prettig.', 'I was surprised that on your birthday you have to bring the treats yourself. At first I also found the directness hard, but it is not so bad. Now I actually like it.', { hints: ['Ik was verbaasd dat …', 'het valt wel mee', 'Nederlanders zijn …'] }),
    match([['het valt wel mee', 'it is not so bad'], ['op de hoogte houden', 'keep informed'], ['met de deur in huis vallen', 'get to the point'], ['de kat uit de boom kijken', 'wait and see'], ['dat slaat nergens op', 'that makes no sense'], ['trakteren', 'to treat']]),
  ], [
    mc('"Dat slaat nergens op" means', ['that hits hard', 'that makes no sense'], 1, 'Makes no sense.'),
    fill('Ik hou je op de ___.', ['hoogte'], 'I will keep you posted.', 'hoogte.'),
    fill('Het viel wel ___.', ['mee'], 'It was not so bad.', 'mee.'),
    build('We celebrate Sinterklaas on 5 December.', 'We vieren Sinterklaas op 5 december.', ['feesten', 'in'], 'vieren; op + date.'),
    tr('en-nl', 'Happy birthday!', ['Gefeliciteerd met je verjaardag!', 'Gefeliciteerd!'], 'gefeliciteerd.'),
    speak('Ik kijk eerst de kat uit de boom, maar ik hou je op de hoogte.', 'I will wait and see first, but I will keep you posted.'),
  ]));

  u8.push(lesson('s3u8l2', 'A short history of the Netherlands', 'You can read and retell key moments in Dutch history, using the past passive (werd gesticht, werden aangelegd) and time expressions with eeuw, tijdens and sinds.', [
    h('History in eight lines'),
    list('**1568–1648**: the revolt against Spain; the Republic is born.', '**17th century, de Gouden Eeuw**: trade (`de VOC werd in 1602 gesticht`), science, painting (Rembrandt, Vermeer); the Amsterdam `grachten` are dug. Wealth also came from `koloniën` and `slavernij`.', '**1815**: the `koninkrijk` is founded. **1848**: Thorbecke’s `grondwet` limits the king’s power.', '**1863**: slavery is abolished in Suriname and the Antilles.', '**1940–1945**: German `bezetting`; most Dutch Jews were murdered. **4 mei**: `Dodenherdenking`, **5 mei**: `Bevrijdingsdag`.', '**1945–1949**: Indonesia becomes independent after a colonial war.', '**1953**: the flood; the Deltawerken follow.', '**20th century**: new `polders` (Flevoland), the welfare state, and a society of many cultures.'),
    h('The language of history'),
    p('History texts use the **simple past** and the **past passive**: `werd gesticht`, `werden aangelegd`, `werd afgeschaft`, `werd bezet`, `werd bevrijd`. Centuries: `in de zeventiende eeuw` (1600s). `tijdens` = during; `sinds` = since; `eeuwenlang` = for centuries.'),
    ex(['De grachtengordel werd in de zeventiende eeuw aangelegd.', 'The canal ring was laid out in the seventeenth century.'], ['Tijdens de bezetting werden meer dan honderdduizend Joden weggevoerd.', 'During the occupation more than a hundred thousand Jews were deported.'], ['De slavernij werd in 1863 afgeschaft, maar wordt pas sinds kort officieel herdacht.', 'Slavery was abolished in 1863, but has only recently been officially commemorated.'], ['Op 4 mei om acht uur is het twee minuten stil.', 'On 4 May at eight o’clock there are two minutes of silence.']),
    warn('On 4 May at 20:00 the whole country falls silent for two minutes. Stop walking, stop talking; trams stop too.'),
  ], ['g3-passive', 'g3-word-formation'], ['eeuw', 'gouden-eeuw', 'gracht', 'handel', 'kolonie', 'slavernij', 'oorlog', 'bezetting', 'bevrijding', 'herdenking', 'koninkrijk', 'grondwet', 'polder', 'stichten', 'afschaffen', 'bezetten', 'bevrijden', 'herdenken', 'droogleggen', 'tijdens'], [
    mc('"De zeventiende eeuw" is', ['the 1600s', 'the 1700s', 'the 1500s'], 0, 'zeventiende eeuw = 1600–1699.'),
    mc('De VOC ___ in 1602 gesticht.', ['wordt', 'werd', 'is geworden'], 1, 'Past passive: werd.'),
    mc('What happens on 4 May at 20:00?', ['fireworks', 'two minutes of silence', 'a parade'], 1, 'Dodenherdenking.'),
    mc('What is celebrated on 5 May?', ['the king’s birthday', 'the liberation', 'Sinterklaas'], 1, 'Bevrijdingsdag.'),
    art('koninkrijk', 'het', 'het rijk → het koninkrijk.'),
    art('grondwet', 'de', 'de wet → de grondwet.'),
    art('eeuw', 'de', 'de eeuw.'),
    fill('De grachten ___ in de zeventiende eeuw aangelegd.', ['werden'], 'The canals were laid out in the seventeenth century.', 'Plural past passive: werden.'),
    fill('De slavernij werd in 1863 ___. (afschaffen)', ['afgeschaft'], 'Slavery was abolished in 1863.', 'af + ge + schaft.'),
    fill('___ de oorlog was Nederland bezet.', ['Tijdens'], 'During the war the Netherlands was occupied.', 'tijdens = during.'),
    fill('Nederland is ___ 1815 een koninkrijk.', ['sinds'], 'The Netherlands has been a kingdom since 1815.', 'sinds + present.'),
    build('The country was liberated in May 1945.', 'Het land werd in mei 1945 bevrijd.', ['is', 'bevrijdde'], 'werd … bevrijd.'),
    build('The constitution was written by Thorbecke.', 'De grondwet werd door Thorbecke geschreven.', ['van', 'schreef'], 'werd door … geschreven.'),
    build('On 4 May the dead are commemorated.', 'Op 4 mei worden de doden herdacht.', ['de doden worden', 'herdenken'], 'Inversion: worden de doden; herdacht.'),
    tr('en-nl', 'The city became rich through trade.', ['De stad werd rijk door de handel.', 'De stad is rijk geworden door de handel.'], 'werd rijk (worden = become here).'),
    tr('nl-en', 'Flevoland is een polder die in de twintigste eeuw werd drooggelegd.', ['Flevoland is a polder that was drained in the twentieth century.', 'Flevoland is a polder which was reclaimed in the twentieth century.'], 'die … werd drooggelegd.'),
    fix('De VOC is in 1602 gesticht geworden.', ['De VOC is in 1602 gesticht.', 'De VOC werd in 1602 gesticht.'], 'No geworden.'),
    dict('Tijdens de Gouden Eeuw werden de grachten van Amsterdam gegraven.', 'During the Golden Age the canals of Amsterdam were dug.', 'werden … gegraven.'),
    listen('Op 4 mei herdenken we de doden en op 5 mei vieren we de bevrijding.', ['On 4 May we commemorate the dead and on 5 May we celebrate the liberation.', 'On 5 May we commemorate the dead.', 'On 4 May we celebrate the king.'], 0, 'herdenken; vieren.'),
    speak('De grachten werden in de zeventiende eeuw aangelegd, toen Amsterdam rijk werd door de handel.', 'The canals were laid out in the seventeenth century, when Amsterdam became rich through trade.'),
    read('Amsterdam in de Gouden Eeuw. In de zeventiende eeuw groeide Amsterdam van een kleine havenstad uit tot een van de rijkste steden ter wereld. In 1602 werd de VOC gesticht, een handelsbedrijf dat schepen naar Azië stuurde. Met het geld dat werd verdiend, werd de grachtengordel aangelegd en werden honderden koopmanshuizen gebouwd. De stad trok schilders, wetenschappers en vluchtelingen uit heel Europa aan. Die rijkdom had echter ook een donkere kant: er werd veel geld verdiend aan slavernij en koloniale handel. Pas sinds kort wordt daaraan in musea en op school meer aandacht besteed.', [
      { q: 'What was the VOC?', options: ['a city council', 'a trading company that sent ships to Asia', 'a group of painters'], answer: 1, explain: '"een handelsbedrijf dat schepen naar Azië stuurde".' },
      { q: 'What was built with the money?', options: ['the canal ring and merchant houses', 'the dykes', 'the Delta Works'], answer: 0, explain: '"werd de grachtengordel aangelegd en werden … koopmanshuizen gebouwd".' },
      { q: 'What is the "dark side" the text mentions?', options: ['floods', 'money made from slavery and colonial trade', 'the war with Spain'], answer: 1, explain: '"verdiend aan slavernij en koloniale handel".' },
      { q: 'What has changed recently?', options: ['more attention is paid to that history', 'the museums were closed', 'the canals were rebuilt'], answer: 0, explain: '"Pas sinds kort wordt daaraan … meer aandacht besteed".' },
    ], { en: 'Amsterdam in the Golden Age. In the seventeenth century Amsterdam grew from a small port town into one of the richest cities in the world. In 1602 the VOC was founded, a trading company that sent ships to Asia. With the money that was earned, the canal ring was laid out and hundreds of merchant houses were built. The city attracted painters, scientists and refugees from all over Europe. That wealth, however, also had a dark side: a lot of money was made from slavery and colonial trade. Only recently has more attention been paid to this in museums and at school.' }),
    free('Retell one event from Dutch history (or the history of your own country) in four sentences, with at least two past passives.', 'In 1940 werd Nederland door Duitsland bezet. Tijdens de bezetting werden veel mensen weggevoerd. In mei 1945 werd het land bevrijd. Sindsdien worden de doden elk jaar op 4 mei herdacht.', 'In 1940 the Netherlands was occupied by Germany. During the occupation many people were deported. In May 1945 the country was liberated. Since then the dead have been commemorated every year on 4 May.', { hints: ['In … werd …', 'Tijdens … werden …', 'Sindsdien wordt / worden …'] }),
    auto(3, ['article', 'tr-nl-en']),
  ], [
    mc('Nederland ___ in 1940 bezet.', ['wordt', 'werd'], 1, 'werd.'),
    fill('In de ___ eeuw (1600s) was Amsterdam een wereldstad.', ['zeventiende'], 'In the seventeenth century Amsterdam was a world city.', 'zeventiende.'),
    fill('Op 5 mei vieren we de ___.', ['bevrijding'], 'On 5 May we celebrate the liberation.', 'bevrijding.'),
    build('Slavery was abolished in 1863.', 'De slavernij werd in 1863 afgeschaft.', ['is geworden', 'schafte af'], 'werd … afgeschaft.'),
    tr('en-nl', 'The Netherlands has been a kingdom since 1815.', ['Nederland is sinds 1815 een koninkrijk.'], 'sinds + present.'),
    speak('Tijdens de Gouden Eeuw werd Amsterdam rijk door de handel, maar die rijkdom had ook een donkere kant.', 'During the Golden Age Amsterdam became rich through trade, but that wealth also had a dark side.'),
  ]));

  units.push(unit('s3u8', 'Nederlandse cultuur en geschiedenis', 'Dutch culture and history', u8, [
    mc('"Het valt wel mee" means', ['it is not so bad', 'it is terrible'], 0, 'meevallen.'),
    mc('De VOC ___ in 1602 gesticht.', ['werd', 'wordt'], 0, 'werd.'),
    fill('Ik hou je op de ___.', ['hoogte'], 'I will keep you posted.', 'hoogte.'),
    fill('De grachten ___ in de zeventiende eeuw aangelegd.', ['werden'], 'The canals were laid out in the seventeenth century.', 'werden.'),
    fill('___ de bezetting was er honger.', ['Tijdens'], 'During the occupation there was hunger.', 'tijdens.'),
    build('I will get straight to the point.', 'Ik val met de deur in huis.', ['huis in', 'door'], 'Idiom.'),
    build('On 4 May the dead are commemorated.', 'Op 4 mei worden de doden herdacht.', ['de doden worden', 'herdenkt'], 'worden … herdacht.'),
    fix('Het regent pijpen stelen.', ['Het regent pijpenstelen.'], 'One word.'),
    tr('en-nl', 'On King’s Day the whole city is orange.', ['Op Koningsdag is de hele stad oranje.'], 'op Koningsdag + inversion.'),
    listen('Als je jarig bent, trakteer je zelf op taart en feliciteert iedereen ook je familie.', ['When it is your birthday, you bring the cake yourself and everyone also congratulates your family.', 'On your birthday your colleagues buy you cake.', 'Nobody celebrates birthdays in the Netherlands.'], 0, 'trakteer je zelf; feliciteert … familie.'),
    speak('Nederland werd in 1945 bevrijd; daarom herdenken we op 4 mei en vieren we op 5 mei.', 'The Netherlands was liberated in 1945; that is why we commemorate on 4 May and celebrate on 5 May.'),
  ]));

  A.stage('s3', '3', 'B1', 'Intermediate', 'Independent Dutch: relative clauses, the passive, zou and hypotheticals, reported speech, infinitive constructions, deep word order, particles and register, across news, opinions, education, health, environment, money, work and Dutch culture.', units, []);
})();
