/* Stage 5 — vocabulary bank, part 2: household, tools, school subjects, countries, religion, press, banking, medical, traffic, farming, verbs, abstract nouns.
   Same helpers as stage5-bank.js. Words that already exist keep their first definition (the registry merges). */
(function () {
  'use strict';
  const NL = window.NL, A = NL.contentApi;
  let O = { theme: 'misc', stage: 5 };
  const theme = (t, stage) => { O = { theme: t, stage: stage || 5, bank: true }; };
  const n = (nl, g, pl, en, a, b) => A.N(nl, g, pl, en, a, b, Object.assign({}, O));
  const v = (nl, en, pres, past, part, aux, a, b) => A.VB(nl, en, pres, past, part, aux, a, b, Object.assign({}, O));
  const w = (nl, pos, en, a, b) => A.W(nl, en, pos, a, b, Object.assign({}, O));

  theme('home', 2);
  n('huishouden', 'het', 'huishoudens', 'household / housework', 'We verdelen het huishouden.', 'We share the housework.');
  n('was', 'de', null, 'laundry', 'De was hangt buiten.', 'The laundry is hanging outside.');
  n('wasmiddel', 'het', 'wasmiddelen', 'detergent', 'Het wasmiddel is op.', 'The detergent has run out.');
  n('droger', 'de', 'drogers', 'tumble dryer', 'Ik heb geen droger, ik hang alles op.', 'I have no dryer, I hang everything up.');
  n('strijkijzer', 'het', 'strijkijzers', 'iron', 'Het strijkijzer is te heet.', 'The iron is too hot.');
  n('bezem', 'de', 'bezems', 'broom', 'Pak de bezem even.', 'Grab the broom.');
  n('dweil', 'de', 'dweilen', 'mop / floor cloth', 'Er ligt een dweil in de kast.', 'There is a mop in the cupboard.');
  n('emmer', 'de', 'emmers', 'bucket', 'Vul de emmer met warm water.', 'Fill the bucket with warm water.');
  n('spons', 'de', 'sponzen', 'sponge', 'Neem een nieuwe spons.', 'Take a new sponge.');
  n('afwasmiddel', 'het', null, 'washing-up liquid', 'Een beetje afwasmiddel is genoeg.', 'A little washing-up liquid is enough.');
  n('stof', 'het', null, 'dust', 'Er ligt stof op de kast.', 'There is dust on the cupboard.');
  n('vlek', 'de', 'vlekken', 'stain', 'Die vlek gaat er niet uit.', 'That stain will not come out.');
  n('schoonmaakmiddel', 'het', 'schoonmaakmiddelen', 'cleaning product', 'Gebruik geen agressief schoonmaakmiddel.', 'Do not use an aggressive cleaning product.');
  n('lakens', 'de', 'lakens', 'sheets', 'Ik verschoon de lakens op zaterdag.', 'I change the sheets on Saturdays.');
  n('dekbed', 'het', 'dekbedden', 'duvet', 'In de zomer gebruik ik een dun dekbed.', 'In summer I use a thin duvet.');
  n('klusje', 'het', 'klusjes', 'small job / chore', 'Er zijn nog een paar klusjes in huis.', 'There are still a few chores in the house.');
  v('stofzuigen', 'to vacuum', 'stofzuig|stofzuigt|stofzuigen', 'stofzuigde|stofzuigden', 'gestofzuigd', 'hebben', 'Ik stofzuig elke zaterdag.', 'I vacuum every Saturday.');
  v('dweilen', 'to mop', 'dweil|dweilt|dweilen', 'dweilde|dweilden', 'gedweild', 'hebben', 'De keukenvloer moet gedweild worden.', 'The kitchen floor needs mopping.');
  v('strijken', 'to iron', 'strijk|strijkt|strijken', 'streek|streken', 'gestreken', 'hebben', 'Ik strijk alleen overhemden.', 'I only iron shirts.');
  v('opvouwen', 'to fold', 'vouw op|vouwt op|vouwen op', 'vouwde op|vouwden op', 'opgevouwen', 'hebben', 'Vouw de was op en leg hem in de kast.', 'Fold the laundry and put it in the wardrobe.');
  v('ophangen', 'to hang up', 'hang op|hangt op|hangen op', 'hing op|hingen op', 'opgehangen', 'hebben', 'Ik hang de was buiten op.', 'I hang the laundry up outside.');
  v('afstoffen', 'to dust', 'stof af|stoft af|stoffen af', 'stofte af|stoften af', 'afgestoft', 'hebben', 'Ik heb de planken afgestoft.', 'I have dusted the shelves.');
  v('opruimen', 'to tidy up', 'ruim op|ruimt op|ruimen op', 'ruimde op|ruimden op', 'opgeruimd', 'hebben', 'Ruim je kamer op.', 'Tidy your room.');
  v('verschonen', 'to change (bedding, a nappy)', 'verschoon|verschoont|verschonen', 'verschoonde|verschoonden', 'verschoond', 'hebben', 'Ik verschoon het bed.', 'I am changing the bed.');
  v('boenen', 'to scrub', 'boen|boent|boenen', 'boende|boenden', 'geboend', 'hebben', 'Ze boende de vloer schoon.', 'She scrubbed the floor clean.');
  v('ontdooien', 'to defrost', 'ontdooi|ontdooit|ontdooien', 'ontdooide|ontdooiden', 'ontdooid', 'hebben', 'De vriezer moet ontdooid worden.', 'The freezer needs defrosting.');

  theme('home', 3);
  n('gereedschap', 'het', null, 'tools', 'Heb je gereedschap in huis?', 'Do you have tools at home?');
  n('hamer', 'de', 'hamers', 'hammer', 'Geef me de hamer even.', 'Pass me the hammer.');
  n('schroevendraaier', 'de', 'schroevendraaiers', 'screwdriver', 'Ik zoek een kleine schroevendraaier.', 'I am looking for a small screwdriver.');
  n('schroef', 'de', 'schroeven', 'screw', 'Er zit een schroef los.', 'A screw is loose.');
  n('spijker', 'de', 'spijkers', 'nail', 'Sla de spijker recht in de muur.', 'Hammer the nail straight into the wall.');
  n('boor', 'de', 'boren', 'drill', 'Mag ik je boor lenen?', 'May I borrow your drill?');
  n('boormachine', 'de', 'boormachines', 'power drill', 'De boormachine is te zwaar voor deze muur.', 'The power drill is too heavy for this wall.');
  n('tang', 'de', 'tangen', 'pliers', 'Met een tang krijg je de spijker eruit.', 'With pliers you can get the nail out.');
  n('zaag', 'de', 'zagen', 'saw', 'De zaag is bot.', 'The saw is blunt.');
  n('ladder', 'de', 'ladders', 'ladder', 'Zet de ladder tegen de muur.', 'Put the ladder against the wall.');
  n('meetlint', 'het', 'meetlinten', 'tape measure', 'Meet het eerst op met het meetlint.', 'Measure it first with the tape measure.');
  n('verf', 'de', null, 'paint', 'We hebben witte verf nodig.', 'We need white paint.');
  n('kwast', 'de', 'kwasten', 'paintbrush', 'Was de kwast na gebruik uit.', 'Wash out the brush after use.');
  n('behang', 'het', null, 'wallpaper', 'Het oude behang moet eraf.', 'The old wallpaper has to come off.');
  n('lijm', 'de', null, 'glue', 'Laat de lijm een uur drogen.', 'Let the glue dry for an hour.');
  n('plank', 'de', 'planken', 'plank / shelf', 'Ik zaag de plank op maat.', 'I am sawing the plank to size.');
  n('bouwmarkt', 'de', 'bouwmarkten', 'DIY store', 'Ik ga naar de bouwmarkt voor schroeven.', 'I am going to the DIY store for screws.');
  n('klusser', 'de', 'klussers', 'handyman', 'Ik ben geen handige klusser.', 'I am not a handy person.');
  n('stopcontact', 'het', 'stopcontacten', 'socket', 'Het stopcontact is kapot.', 'The socket is broken.');
  n('zekering', 'de', 'zekeringen', 'fuse', 'De zekering is doorgeslagen.', 'The fuse has blown.');
  n('meterkast', 'de', 'meterkasten', 'meter cupboard', 'De meterkast zit bij de voordeur.', 'The meter cupboard is by the front door.');
  n('lekkage', 'de', 'lekkages', 'leak', 'Er is een lekkage in de badkamer.', 'There is a leak in the bathroom.');
  v('klussen', 'to do DIY', 'klus|klust|klussen', 'kluste|klusten', 'geklust', 'hebben', 'We klussen het hele weekend.', 'We are doing DIY all weekend.');
  v('boren', 'to drill', 'boor|boort|boren', 'boorde|boorden', 'geboord', 'hebben', 'Boor niet in een leiding.', 'Do not drill into a pipe.');
  v('schroeven', 'to screw', 'schroef|schroeft|schroeven', 'schroefde|schroefden', 'geschroefd', 'hebben', 'Schroef de plank aan de muur.', 'Screw the shelf to the wall.');
  v('zagen', 'to saw', 'zaag|zaagt|zagen', 'zaagde|zaagden', 'gezaagd', 'hebben', 'Zaag het hout op maat.', 'Saw the wood to size.');
  v('verven', 'to paint (walls)', 'verf|verft|verven', 'verfde|verfden', 'geverfd', 'hebben', 'We hebben de muren geverfd.', 'We have painted the walls.');
  v('behangen', 'to wallpaper', 'behang|behangt|behangen', 'behing|behingen', 'behangen', 'hebben', 'De slaapkamer is opnieuw behangen.', 'The bedroom has been re-wallpapered.');
  v('meten', 'to measure', 'meet|meet|meten', 'mat|maten', 'gemeten', 'hebben', 'Meet twee keer, zaag één keer.', 'Measure twice, cut once.');
  v('in elkaar zetten', 'to assemble', 'zet in elkaar|zet in elkaar|zetten in elkaar', 'zette in elkaar|zetten in elkaar', 'in elkaar gezet', 'hebben', 'We hebben de kast in elkaar gezet.', 'We assembled the cupboard.');
  v('lekken', 'to leak', 'lek|lekt|lekken', 'lekte|lekten', 'gelekt', 'hebben', 'De kraan lekt al dagen.', 'The tap has been leaking for days.');

  theme('study', 2);
  n('wiskunde', 'de', null, 'mathematics', 'Wiskunde was mijn beste vak.', 'Maths was my best subject.');
  n('natuurkunde', 'de', null, 'physics', 'Natuurkunde gaat over krachten en energie.', 'Physics is about forces and energy.');
  n('scheikunde', 'de', null, 'chemistry', 'Bij scheikunde doen we proeven.', 'In chemistry we do experiments.');
  n('biologie', 'de', null, 'biology', 'Biologie vond ik het leukst.', 'I liked biology most.');
  n('aardrijkskunde', 'de', null, 'geography', 'Bij aardrijkskunde leer je over landen en klimaat.', 'In geography you learn about countries and climate.');
  n('geschiedenis', 'de', null, 'history', 'Geschiedenis is een verplicht vak.', 'History is a compulsory subject.');
  n('maatschappijleer', 'de', null, 'social studies', 'Maatschappijleer gaat over politiek en samenleving.', 'Social studies is about politics and society.');
  n('economie', 'de', null, 'economics', 'Ze kiest economie in de bovenbouw.', 'She is choosing economics in the upper years.');
  n('lichamelijke opvoeding', 'de', null, 'physical education', 'Lichamelijke opvoeding heet op school gewoon gym.', 'Physical education is simply called gym at school.');
  n('handvaardigheid', 'de', null, 'crafts', 'Bij handvaardigheid maken we dingen van hout.', 'In crafts we make things from wood.');
  n('tekenen', 'het', null, 'art (drawing)', 'Tekenen is een keuzevak.', 'Art is an optional subject.');
  n('informatica', 'de', null, 'computer science', 'Informatica wordt steeds populairder.', 'Computer science is getting more popular.');
  n('profiel', 'het', 'profielen', 'subject cluster (upper secondary)', 'Welk profiel heb je gekozen?', 'Which subject cluster did you choose?');
  n('keuzevak', 'het', 'keuzevakken', 'optional subject', 'Spaans is een keuzevak.', 'Spanish is an optional subject.');
  n('proefwerk', 'het', 'proefwerken', 'test (school)', 'Morgen heb ik een proefwerk Frans.', 'Tomorrow I have a French test.');
  n('toets', 'de', 'toetsen', 'test / quiz', 'De toets telt mee voor het rapport.', 'The test counts towards the report.');
  n('eindexamen', 'het', 'eindexamens', 'final exam', 'Het eindexamen begint in mei.', 'The final exams start in May.');
  n('mentor', 'de', 'mentoren', 'form tutor', 'De mentor belt de ouders.', 'The form tutor phones the parents.');
  n('rooster', 'het', 'roosters', 'timetable', 'Het rooster staat online.', 'The timetable is online.');
  n('pauze', 'de', 'pauzes', 'break', 'In de pauze eten we buiten.', 'In the break we eat outside.');
  n('spijbelen', 'het', null, 'truancy', 'Spijbelen wordt gemeld bij de leerplichtambtenaar.', 'Truancy is reported to the attendance officer.');
  v('overgaan', 'to move up a year', 'ga over|gaat over|gaan over', 'ging over|gingen over', 'overgegaan', 'zijn', 'Hij is overgegaan naar de vierde.', 'He has moved up to year four.');
  v('blijven zitten', 'to repeat a year', 'blijf zitten|blijft zitten|blijven zitten', 'bleef zitten|bleven zitten', 'blijven zitten', 'zijn', 'Ze is één keer blijven zitten.', 'She repeated a year once.');
  v('spijbelen', 'to play truant', 'spijbel|spijbelt|spijbelen', 'spijbelde|spijbelden', 'gespijbeld', 'hebben', 'Hij spijbelt vaak op vrijdag.', 'He often skips school on Fridays.');
  v('nakijken', 'to mark', 'kijk na|kijkt na|kijken na', 'keek na|keken na', 'nagekeken', 'hebben', 'De docent kijkt de toetsen na.', 'The teacher marks the tests.');

  theme('countries', 1);
  n('België', 'het', null, 'Belgium', 'België ligt ten zuiden van Nederland.', 'Belgium lies south of the Netherlands.');
  n('Frankrijk', 'het', null, 'France', 'We gaan op vakantie naar Frankrijk.', 'We are going on holiday to France.');
  n('Spanje', 'het', null, 'Spain', 'In Spanje is het warmer.', 'In Spain it is warmer.');
  n('Italië', 'het', null, 'Italy', 'Italië is beroemd om zijn eten.', 'Italy is famous for its food.');
  n('Griekenland', 'het', null, 'Greece', 'Griekenland heeft veel eilanden.', 'Greece has many islands.');
  n('Portugal', 'het', null, 'Portugal', 'Lissabon is de hoofdstad van Portugal.', 'Lisbon is the capital of Portugal.');
  n('Polen', 'het', null, 'Poland', 'Veel arbeidsmigranten komen uit Polen.', 'Many labour migrants come from Poland.');
  n('Turkije', 'het', null, 'Turkey', 'Mijn buren komen uit Turkije.', 'My neighbours come from Turkey.');
  n('Marokko', 'het', null, 'Morocco', 'Ze gaat elke zomer naar Marokko.', 'She goes to Morocco every summer.');
  n('Suriname', 'het', null, 'Suriname', 'Suriname was tot 1975 een Nederlandse kolonie.', 'Suriname was a Dutch colony until 1975.');
  n('Indonesië', 'het', null, 'Indonesia', 'Indonesië werd in 1949 onafhankelijk.', 'Indonesia became independent in 1949.');
  n('Verenigde Staten', 'de', null, 'United States', 'Hij werkt in de Verenigde Staten.', 'He works in the United States.');
  n('Verenigd Koninkrijk', 'het', null, 'United Kingdom', 'Het Verenigd Koninkrijk is geen EU-lid meer.', 'The United Kingdom is no longer an EU member.');
  n('China', 'het', null, 'China', 'China is een grote handelspartner.', 'China is a big trading partner.');
  n('nationaliteit', 'de', 'nationaliteiten', 'nationality', 'Welke nationaliteit heeft u?', 'What nationality are you?');
  n('hoofdstad', 'de', 'hoofdsteden', 'capital', 'Amsterdam is de hoofdstad, Den Haag de regeringszetel.', 'Amsterdam is the capital, The Hague the seat of government.');
  n('buitenlander', 'de', 'buitenlanders', 'foreigner', 'Als buitenlander mag je bij de gemeenteraad stemmen.', 'As a foreigner you may vote for the municipal council.');
  w('Belgisch', 'adj', 'Belgian', 'Belgische frieten zijn beroemd.', 'Belgian chips are famous.');
  w('Frans', 'adj', 'French', 'Ze spreekt vloeiend Frans.', 'She speaks fluent French.');
  w('Spaans', 'adj', 'Spanish', 'Spaans is een keuzevak.', 'Spanish is an optional subject.');
  w('Italiaans', 'adj', 'Italian', 'We eten vanavond Italiaans.', 'We are eating Italian tonight.');
  w('Grieks', 'adj', 'Greek', 'Grieks eten is heel lekker.', 'Greek food is delicious.');
  w('Pools', 'adj', 'Polish', 'Mijn collega is Pools.', 'My colleague is Polish.');
  w('Turks', 'adj', 'Turkish', 'De Turkse bakker verkoopt verse pide.', 'The Turkish baker sells fresh pide.');
  w('Marokkaans', 'adj', 'Moroccan', 'De Marokkaanse keuken gebruikt veel kruiden.', 'Moroccan cuisine uses many spices.');
  w('Surinaams', 'adj', 'Surinamese', 'Surinaamse roti is een Amsterdams gerecht geworden.', 'Surinamese roti has become an Amsterdam dish.');
  w('Indonesisch', 'adj', 'Indonesian', 'Een Indonesische rijsttafel is een feest.', 'An Indonesian rijsttafel is a feast.');
  w('Amerikaans', 'adj', 'American', 'Hij heeft een Amerikaans accent.', 'He has an American accent.');
  w('Brits', 'adj', 'British', 'De Britse ambassade staat in Den Haag.', 'The British embassy is in The Hague.');
  w('Chinees', 'adj', 'Chinese', 'We halen Chinees vanavond.', 'We are getting Chinese takeaway tonight.');
  w('Europees', 'adj', 'European', 'De Europese verkiezingen zijn om de vijf jaar.', 'The European elections are every five years.');
  w('buitenlands', 'adj', 'foreign', 'Buitenlandse studenten betalen meer collegegeld.', 'Foreign students pay more tuition.');

  theme('society', 3);
  n('geloof', 'het', 'geloven', 'faith / belief', 'Geloof is in Nederland een privézaak.', 'Faith is a private matter in the Netherlands.');
  n('godsdienst', 'de', 'godsdiensten', 'religion', 'Vrijheid van godsdienst staat in de grondwet.', 'Freedom of religion is in the constitution.');
  n('christendom', 'het', null, 'Christianity', 'Het christendom was eeuwenlang dominant.', 'Christianity was dominant for centuries.');
  n('islam', 'de', null, 'Islam', 'De islam is de tweede godsdienst van het land.', 'Islam is the second religion of the country.');
  n('jodendom', 'het', null, 'Judaism', 'Amsterdam had een grote Joodse gemeenschap.', 'Amsterdam had a large Jewish community.');
  n('katholiek', 'de', 'katholieken', 'Catholic', 'Het zuiden was van oudsher katholiek.', 'The south was traditionally Catholic.');
  n('protestant', 'de', 'protestanten', 'Protestant', 'Het noorden was overwegend protestant.', 'The north was predominantly Protestant.');
  n('moslim', 'de', 'moslims', 'Muslim', 'Veel moslims vasten tijdens de ramadan.', 'Many Muslims fast during Ramadan.');
  n('gelovige', 'de', 'gelovigen', 'believer', 'Het aantal gelovigen daalt.', 'The number of believers is falling.');
  n('ongelovige', 'de', 'ongelovigen', 'non-believer', 'De meeste Nederlanders noemen zich ongelovig.', 'Most Dutch people call themselves non-believers.');
  n('verzuiling', 'de', null, 'pillarisation', 'De verzuiling verdeelde het land in zuilen.', 'Pillarisation divided the country into pillars.');
  n('kerkdienst', 'de', 'kerkdiensten', 'church service', 'De kerkdienst begint om tien uur.', 'The church service starts at ten.');
  n('gebed', 'het', 'gebeden', 'prayer', 'Het gebed duurt een kwartier.', 'The prayer lasts a quarter of an hour.');
  n('ramadan', 'de', null, 'Ramadan', 'Tijdens de ramadan eten we na zonsondergang.', 'During Ramadan we eat after sunset.');
  n('gemeenschap', 'de', 'gemeenschappen', 'community', 'De Surinaamse gemeenschap viert Keti Koti.', 'The Surinamese community celebrates Keti Koti.');
  n('tolerantie', 'de', null, 'tolerance', 'Nederland is trots op zijn tolerantie.', 'The Netherlands is proud of its tolerance.');
  n('discriminatie', 'de', null, 'discrimination', 'Discriminatie is verboden.', 'Discrimination is forbidden.');
  w('gelovig', 'adj', 'religious', 'Mijn oma was heel gelovig.', 'My grandma was very religious.');
  w('seculier', 'adj', 'secular', 'Nederland is een seculier land geworden.', 'The Netherlands has become a secular country.');
  v('geloven in', 'to believe in', 'geloof in|gelooft in|geloven in', 'geloofde in|geloofden in', 'geloofd in', 'hebben', 'Ik geloof niet in toeval.', 'I do not believe in coincidence.');
  v('bidden', 'to pray', 'bid|bidt|bidden', 'bad|baden', 'gebeden', 'hebben', 'Ze bidt voor het eten.', 'She prays before the meal.');
  v('vasten', 'to fast', 'vast|vast|vasten', 'vastte|vastten', 'gevast', 'hebben', 'Hij vast een maand per jaar.', 'He fasts one month a year.');

  theme('media', 3);
  n('pers', 'de', null, 'the press', 'De pers wachtte buiten.', 'The press was waiting outside.');
  n('persconferentie', 'de', 'persconferenties', 'press conference', 'De premier gaf een persconferentie.', 'The prime minister gave a press conference.');
  n('hoofdredacteur', 'de', 'hoofdredacteuren', 'editor-in-chief', 'De hoofdredacteur is opgestapt.', 'The editor-in-chief has stepped down.');
  n('redactie', 'de', 'redacties', 'editorial team', 'De redactie besluit wat op de voorpagina komt.', 'The editorial team decides what goes on the front page.');
  n('voorpagina', 'de', "voorpagina's", 'front page', 'Het stond op de voorpagina.', 'It was on the front page.');
  n('column', 'de', 'columns', 'column', 'Ze schrijft elke week een column.', 'She writes a column every week.');
  n('abonnement', 'het', 'abonnementen', 'subscription', 'Ik heb een digitaal abonnement op de krant.', 'I have a digital subscription to the newspaper.');
  n('bron', 'de', 'bronnen', 'source', 'De journalist beschermt zijn bronnen.', 'The journalist protects his sources.');
  n('primeur', 'de', 'primeurs', 'scoop', 'De krant had de primeur.', 'The newspaper had the scoop.');
  n('rectificatie', 'de', 'rectificaties', 'correction', 'De krant plaatste een rectificatie.', 'The newspaper printed a correction.');
  n('talkshow', 'de', 'talkshows', 'talk show', 'Elke avond is er een talkshow.', 'Every evening there is a talk show.');
  n('kijkcijfer', 'het', 'kijkcijfers', 'viewing figure', 'De kijkcijfers vielen tegen.', 'The viewing figures were disappointing.');
  n('podcast', 'de', 'podcasts', 'podcast', 'Ik luister naar een Nederlandse podcast.', 'I listen to a Dutch podcast.');
  n('roddel', 'de', 'roddels', 'gossip', 'Dat is een roddel, geen nieuws.', 'That is gossip, not news.');
  n('censuur', 'de', null, 'censorship', 'In Nederland is er geen censuur.', 'There is no censorship in the Netherlands.');
  n('persvrijheid', 'de', null, 'press freedom', 'Persvrijheid is een grondrecht.', 'Press freedom is a fundamental right.');
  v('berichten over', 'to report on', 'bericht over|bericht over|berichten over', 'berichtte over|berichtten over', 'bericht over', 'hebben', 'De media berichtten uitgebreid over de storm.', 'The media reported extensively on the storm.');
  v('interviewen', 'to interview', 'interview|interviewt|interviewen', 'interviewde|interviewden', 'geïnterviewd', 'hebben', 'Ze werd geïnterviewd voor het journaal.', 'She was interviewed for the news.');
  v('uitzenden', 'to broadcast', 'zend uit|zendt uit|zenden uit', 'zond uit|zonden uit', 'uitgezonden', 'hebben', 'Het debat wordt live uitgezonden.', 'The debate is broadcast live.');
  v('abonneren', 'to subscribe', 'abonneer|abonneert|abonneren', 'abonneerde|abonneerden', 'geabonneerd', 'hebben', 'Ik heb me geabonneerd op de nieuwsbrief.', 'I have subscribed to the newsletter.');
  w('onafhankelijk', 'adj', 'independent', 'Een onafhankelijke pers is onmisbaar.', 'An independent press is indispensable.');
  w('objectief', 'adj', 'objective', 'Geen enkele krant is volledig objectief.', 'No newspaper is completely objective.');

  theme('money', 2);
  n('pinpas', 'de', 'pinpassen', 'debit card', 'Ik ben mijn pinpas kwijt.', 'I have lost my debit card.');
  n('creditcard', 'de', 'creditcards', 'credit card', 'Niet elke winkel accepteert creditcards.', 'Not every shop accepts credit cards.');
  n('pincode', 'de', 'pincodes', 'PIN', 'Ik ben mijn pincode vergeten.', 'I have forgotten my PIN.');
  n('rekeningnummer', 'het', 'rekeningnummers', 'account number', 'Wat is uw rekeningnummer?', 'What is your account number?');
  n('overschrijving', 'de', 'overschrijvingen', 'bank transfer', 'De overschrijving duurt één werkdag.', 'The transfer takes one working day.');
  n('saldo', 'het', "saldo's", 'balance', 'Mijn saldo is bijna nul.', 'My balance is almost zero.');
  n('afschrift', 'het', 'afschriften', 'bank statement', 'Bewaar je afschriften een jaar.', 'Keep your statements for a year.');
  n('incasso', 'de', "incasso's", 'direct debit', 'De huur gaat via automatische incasso.', 'The rent goes by direct debit.');
  n('rood staan', 'het', null, 'overdraft', 'Rood staan kost rente.', 'Being overdrawn costs interest.');
  n('spaargeld', 'het', null, 'savings', 'Ik heb weinig spaargeld.', 'I have little in savings.');
  n('valuta', 'de', "valuta's", 'currency', 'De euro is onze valuta.', 'The euro is our currency.');
  n('wisselkoers', 'de', 'wisselkoersen', 'exchange rate', 'De wisselkoers is ongunstig.', 'The exchange rate is unfavourable.');
  n('geldautomaat', 'de', 'geldautomaten', 'cash machine', 'De geldautomaat is buiten gebruik.', 'The cash machine is out of order.');
  n('contant geld', 'het', null, 'cash', 'Steeds minder winkels nemen contant geld aan.', 'Fewer and fewer shops accept cash.');
  n('fooi', 'de', 'fooien', 'tip', 'In Nederland is een fooi niet verplicht.', 'In the Netherlands a tip is not compulsory.');
  n('korting', 'de', 'kortingen', 'discount', 'Studenten krijgen korting.', 'Students get a discount.');
  n('btw', 'de', null, 'VAT', 'De prijs is inclusief btw.', 'The price includes VAT.');
  v('pinnen', 'to pay by card / withdraw cash', 'pin|pint|pinnen', 'pinde|pinden', 'gepind', 'hebben', 'Kan ik hier pinnen?', 'Can I pay by card here?');
  v('overmaken', 'to transfer', 'maak over|maakt over|maken over', 'maakte over|maakten over', 'overgemaakt', 'hebben', 'Ik maak het vanavond over.', 'I will transfer it tonight.');
  v('opnemen', 'to withdraw', 'neem op|neemt op|nemen op', 'nam op|namen op', 'opgenomen', 'hebben', 'Ik wil honderd euro opnemen.', 'I want to withdraw a hundred euros.');
  v('storten', 'to deposit', 'stort|stort|storten', 'stortte|stortten', 'gestort', 'hebben', 'Het salaris wordt op de 25e gestort.', 'The salary is deposited on the 25th.');
  v('blokkeren', 'to block', 'blokkeer|blokkeert|blokkeren', 'blokkeerde|blokkeerden', 'geblokkeerd', 'hebben', 'Laat je pas meteen blokkeren.', 'Have your card blocked immediately.');
  v('afschrijven', 'to debit', 'schrijf af|schrijft af|schrijven af', 'schreef af|schreven af', 'afgeschreven', 'hebben', 'Het bedrag wordt maandelijks afgeschreven.', 'The amount is debited monthly.');
  v('tikkie sturen', 'to send a payment request', 'stuur een tikkie|stuurt een tikkie|sturen een tikkie', 'stuurde een tikkie|stuurden een tikkie', 'een tikkie gestuurd', 'hebben', 'Ik stuur je wel een tikkie.', 'I will send you a payment request.');

  theme('health', 3);
  n('huisartsenpost', 'de', 'huisartsenposten', 'out-of-hours GP service', '’s Nachts bel je de huisartsenpost.', 'At night you call the out-of-hours service.');
  n('verwijsbrief', 'de', 'verwijsbrieven', 'referral letter', 'Zonder verwijsbrief kun je niet naar de specialist.', 'Without a referral letter you cannot see the specialist.');
  n('fysiotherapeut', 'de', 'fysiotherapeuten', 'physiotherapist', 'De fysiotherapeut geeft oefeningen.', 'The physiotherapist gives exercises.');
  n('tandartscontrole', 'de', 'tandartscontroles', 'dental check-up', 'Twee keer per jaar heb ik tandartscontrole.', 'Twice a year I have a dental check-up.');
  n('vaccinatie', 'de', 'vaccinaties', 'vaccination', 'Kinderen krijgen vaccinaties via het consultatiebureau.', 'Children get vaccinations via the child health clinic.');
  n('consultatiebureau', 'het', 'consultatiebureaus', 'child health clinic', 'Het consultatiebureau volgt de groei van baby’s.', 'The child health clinic monitors babies’ growth.');
  n('zwangerschap', 'de', 'zwangerschappen', 'pregnancy', 'De zwangerschap verliep goed.', 'The pregnancy went well.');
  n('verloskundige', 'de', 'verloskundigen', 'midwife', 'In Nederland begeleidt een verloskundige de zwangerschap.', 'In the Netherlands a midwife supervises the pregnancy.');
  n('bevalling', 'de', 'bevallingen', 'birth / delivery', 'De bevalling was thuis.', 'The birth was at home.');
  n('kraamzorg', 'de', null, 'maternity care at home', 'Kraamzorg is typisch Nederlands.', 'Maternity home care is typically Dutch.');
  n('bloeddruk', 'de', null, 'blood pressure', 'Mijn bloeddruk is te hoog.', 'My blood pressure is too high.');
  n('suikerziekte', 'de', null, 'diabetes', 'Suikerziekte komt steeds vaker voor.', 'Diabetes is becoming more common.');
  n('hartaanval', 'de', 'hartaanvallen', 'heart attack', 'Hij kreeg een hartaanval.', 'He had a heart attack.');
  n('beroerte', 'de', 'beroertes', 'stroke', 'Na de beroerte kon ze niet praten.', 'After the stroke she could not speak.');
  n('kanker', 'de', null, 'cancer', 'Kanker is de belangrijkste doodsoorzaak.', 'Cancer is the main cause of death.');
  n('griepprik', 'de', 'griepprikken', 'flu jab', 'Ouderen krijgen een gratis griepprik.', 'The elderly get a free flu jab.');
  n('antibiotica', 'de', 'antibiotica', 'antibiotics', 'Nederlandse artsen zijn zuinig met antibiotica.', 'Dutch doctors are sparing with antibiotics.');
  n('pijnstiller', 'de', 'pijnstillers', 'painkiller', 'Neem een pijnstiller als het nodig is.', 'Take a painkiller if necessary.');
  n('bijsluiter', 'de', 'bijsluiters', 'package leaflet', 'Lees eerst de bijsluiter.', 'Read the leaflet first.');
  n('dosering', 'de', 'doseringen', 'dosage', 'Houd je aan de dosering.', 'Stick to the dosage.');
  n('bloedonderzoek', 'het', 'bloedonderzoeken', 'blood test', 'Het bloedonderzoek was in orde.', 'The blood test was fine.');
  n('geheugenverlies', 'het', null, 'memory loss', 'Geheugenverlies kan een teken van dementie zijn.', 'Memory loss can be a sign of dementia.');
  n('rolstoel', 'de', 'rolstoelen', 'wheelchair', 'De ingang is toegankelijk voor rolstoelen.', 'The entrance is accessible for wheelchairs.');
  n('mantelzorg', 'de', null, 'informal care (by family)', 'Veel ouderen zijn afhankelijk van mantelzorg.', 'Many elderly people depend on informal care.');
  v('vaccineren', 'to vaccinate', 'vaccineer|vaccineert|vaccineren', 'vaccineerde|vaccineerden', 'gevaccineerd', 'hebben', 'Ben je gevaccineerd?', 'Have you been vaccinated?');
  v('bevallen', 'to give birth', 'beval|bevalt|bevallen', 'beviel|bevielen', 'bevallen', 'zijn', 'Ze is gisteren bevallen van een zoon.', 'She gave birth to a son yesterday.');
  v('genezen', 'to heal / cure', 'genees|geneest|genezen', 'genas|genazen', 'genezen', 'zijn', 'De wond is goed genezen.', 'The wound has healed well.');
  v('flauwvallen', 'to faint', 'val flauw|valt flauw|vallen flauw', 'viel flauw|vielen flauw', 'flauwgevallen', 'zijn', 'Ze viel flauw van de hitte.', 'She fainted from the heat.');
  v('overgeven', 'to vomit', 'geef over|geeft over|geven over', 'gaf over|gaven over', 'overgegeven', 'hebben', 'Het kind heeft twee keer overgegeven.', 'The child has vomited twice.');

  theme('transport', 2);
  n('rijbewijs', 'het', 'rijbewijzen', 'driving licence', 'Mijn rijbewijs is verlopen.', 'My driving licence has expired.');
  n('rijles', 'de', 'rijlessen', 'driving lesson', 'Rijlessen zijn duur.', 'Driving lessons are expensive.');
  n('rijexamen', 'het', 'rijexamens', 'driving test', 'Ik ben in één keer geslaagd voor mijn rijexamen.', 'I passed my driving test first time.');
  n('kenteken', 'het', 'kentekens', 'number plate', 'Noteer het kenteken.', 'Note down the number plate.');
  n('apk', 'de', "apk's", 'annual vehicle inspection', 'De auto moet naar de apk.', 'The car has to go for its inspection.');
  n('benzine', 'de', null, 'petrol', 'Benzine is weer duurder geworden.', 'Petrol has become more expensive again.');
  n('tankstation', 'het', 'tankstations', 'petrol station', 'Het tankstation is 24 uur open.', 'The petrol station is open 24 hours.');
  n('band', 'de', 'banden', 'tyre', 'Ik heb een lekke band.', 'I have a flat tyre.');
  n('stuur', 'het', 'sturen', 'steering wheel / handlebars', 'Houd het stuur met twee handen vast.', 'Hold the steering wheel with both hands.');
  n('rem', 'de', 'remmen', 'brake', 'De remmen zijn versleten.', 'The brakes are worn.');
  n('gordel', 'de', 'gordels', 'seatbelt', 'Doe je gordel om.', 'Put on your seatbelt.');
  n('richtingaanwijzer', 'de', 'richtingaanwijzers', 'indicator', 'Gebruik je richtingaanwijzer.', 'Use your indicator.');
  n('verkeersbord', 'het', 'verkeersborden', 'traffic sign', 'Dat verkeersbord betekent verboden in te rijden.', 'That traffic sign means no entry.');
  n('snelheidscontrole', 'de', 'snelheidscontroles', 'speed check', 'Er staat een snelheidscontrole op de A2.', 'There is a speed check on the A2.');
  n('flitspaal', 'de', 'flitspalen', 'speed camera', 'Ik ben geflitst door een flitspaal.', 'I was caught by a speed camera.');
  n('bekeuring', 'de', 'bekeuringen', 'ticket / fine', 'Ik kreeg een bekeuring voor fout parkeren.', 'I got a ticket for wrong parking.');
  n('aanrijding', 'de', 'aanrijdingen', 'collision', 'Bij de aanrijding raakte niemand gewond.', 'Nobody was injured in the collision.');
  n('schadeformulier', 'het', 'schadeformulieren', 'accident report form', 'Vul samen het schadeformulier in.', 'Fill in the accident form together.');
  n('wegenwacht', 'de', null, 'roadside assistance', 'Bel de wegenwacht bij pech.', 'Call roadside assistance when you break down.');
  n('pech', 'de', null, 'breakdown', 'We hadden pech op de snelweg.', 'We broke down on the motorway.');
  n('bromfiets', 'de', 'bromfietsen', 'moped', 'Voor een bromfiets heb je een rijbewijs nodig.', 'For a moped you need a licence.');
  n('scooter', 'de', 'scooters', 'scooter', 'Scooters mogen niet op het fietspad.', 'Scooters are not allowed on the cycle path.');
  v('tanken', 'to fill up', 'tank|tankt|tanken', 'tankte|tankten', 'getankt', 'hebben', 'Ik moet nog tanken.', 'I still have to fill up.');
  v('remmen', 'to brake', 'rem|remt|remmen', 'remde|remden', 'geremd', 'hebben', 'Ze remde hard.', 'She braked hard.');
  v('inhalen', 'to overtake', 'haal in|haalt in|halen in', 'haalde in|haalden in', 'ingehaald', 'hebben', 'Hier mag je niet inhalen.', 'You may not overtake here.');
  v('voorrang verlenen', 'to give way', 'verleen voorrang|verleent voorrang|verlenen voorrang', 'verleende voorrang|verleenden voorrang', 'voorrang verleend', 'hebben', 'Je moet fietsers voorrang verlenen.', 'You must give way to cyclists.');
  v('botsen', 'to collide', 'bots|botst|botsen', 'botste|botsten', 'gebotst', 'zijn', 'Twee auto’s zijn op elkaar gebotst.', 'Two cars collided.');
  v('slippen', 'to skid', 'slip|slipt|slippen', 'slipte|slipten', 'geslipt', 'zijn', 'De auto slipte op het ijs.', 'The car skidded on the ice.');
  v('keren', 'to turn around', 'keer|keert|keren', 'keerde|keerden', 'gekeerd', 'zijn', 'Hier mag je niet keren.', 'You may not turn around here.');

  theme('nature', 3);
  n('boer', 'de', 'boeren', 'farmer', 'De boer melkt de koeien om zes uur.', 'The farmer milks the cows at six.');
  n('boerderij', 'de', 'boerderijen', 'farm', 'We logeren op een boerderij.', 'We are staying on a farm.');
  n('akker', 'de', 'akkers', 'field (arable)', 'Op de akker groeit tarwe.', 'Wheat grows in the field.');
  n('oogst', 'de', 'oogsten', 'harvest', 'De oogst was dit jaar slecht.', 'The harvest was poor this year.');
  n('kas', 'de', 'kassen', 'greenhouse', 'In het Westland staan duizenden kassen.', 'In the Westland there are thousands of greenhouses.');
  n('tuinbouw', 'de', null, 'horticulture', 'De tuinbouw exporteert bloemen over de hele wereld.', 'Horticulture exports flowers all over the world.');
  n('veeteelt', 'de', null, 'livestock farming', 'De veeteelt veroorzaakt stikstofuitstoot.', 'Livestock farming causes nitrogen emissions.');
  n('stikstof', 'de', null, 'nitrogen', 'De stikstofcrisis raakt de boeren hard.', 'The nitrogen crisis hits farmers hard.');
  n('mest', 'de', null, 'manure', 'Te veel mest vervuilt het grondwater.', 'Too much manure pollutes the groundwater.');
  n('tarwe', 'de', null, 'wheat', 'Van tarwe wordt brood gemaakt.', 'Bread is made from wheat.');
  n('aardappel', 'de', 'aardappelen', 'potato', 'Nederland exporteert veel aardappelen.', 'The Netherlands exports many potatoes.');
  n('bol', 'de', 'bollen', 'bulb', 'Plant de bollen in oktober.', 'Plant the bulbs in October.');
  n('tulp', 'de', 'tulpen', 'tulip', 'De tulp komt oorspronkelijk uit Turkije.', 'The tulip originally comes from Turkey.');
  n('zaad', 'het', 'zaden', 'seed', 'Ik zaai het zaad in maart.', 'I sow the seed in March.');
  n('stal', 'de', 'stallen', 'stable / shed', 'De koeien staan ’s winters op stal.', 'The cows are in the shed in winter.');
  n('weide', 'de', 'weiden', 'pasture', 'De koeien lopen in de weide.', 'The cows are in the pasture.');
  n('trekker', 'de', 'trekkers', 'tractor', 'Boeren protesteerden met trekkers.', 'Farmers protested with tractors.');
  n('biologisch', 'het', null, 'organic (farming)', 'Biologisch is duurder maar beter voor het milieu.', 'Organic is more expensive but better for the environment.');
  v('zaaien', 'to sow', 'zaai|zaait|zaaien', 'zaaide|zaaiden', 'gezaaid', 'hebben', 'In het voorjaar zaaien we.', 'In spring we sow.');
  v('oogsten', 'to harvest', 'oogst|oogst|oogsten', 'oogstte|oogstten', 'geoogst', 'hebben', 'De aardappelen worden in september geoogst.', 'The potatoes are harvested in September.');
  v('melken', 'to milk', 'melk|melkt|melken', 'molk|molken', 'gemolken', 'hebben', 'De koeien worden twee keer per dag gemolken.', 'The cows are milked twice a day.');
  v('planten', 'to plant', 'plant|plant|planten', 'plantte|plantten', 'geplant', 'hebben', 'We hebben een boom geplant.', 'We planted a tree.');
  v('snoeien', 'to prune', 'snoei|snoeit|snoeien', 'snoeide|snoeiden', 'gesnoeid', 'hebben', 'De heg moet gesnoeid worden.', 'The hedge needs pruning.');
  v('water geven', 'to water', 'geef water|geeft water|geven water', 'gaf water|gaven water', 'water gegeven', 'hebben', 'Geef de planten elke dag water.', 'Water the plants every day.');
  w('vruchtbaar', 'adj', 'fertile', 'De grond in de polder is vruchtbaar.', 'The soil in the polder is fertile.');
  w('droog', 'adj', 'dry', 'Het was een droge zomer.', 'It was a dry summer.');

  theme('verbs', 4);
  v('aanpassen', 'to adapt / adjust', 'pas aan|past aan|passen aan', 'paste aan|pasten aan', 'aangepast', 'hebben', 'Het plan is aangepast.', 'The plan has been adjusted.');
  v('afhandelen', 'to deal with / settle', 'handel af|handelt af|handelen af', 'handelde af|handelden af', 'afgehandeld', 'hebben', 'Uw klacht wordt binnen een week afgehandeld.', 'Your complaint will be dealt with within a week.');
  v('bereiken', 'to achieve / reach', 'bereik|bereikt|bereiken', 'bereikte|bereikten', 'bereikt', 'hebben', 'We hebben ons doel bereikt.', 'We have achieved our goal.');
  v('beschouwen als', 'to regard as', 'beschouw als|beschouwt als|beschouwen als', 'beschouwde als|beschouwden als', 'beschouwd als', 'hebben', 'Ik beschouw Amsterdam als mijn thuis.', 'I regard Amsterdam as my home.');
  v('betreffen', 'to concern', 'betref|betreft|betreffen', 'betrof|betroffen', 'betroffen', 'hebben', 'Wat mij betreft is het duidelijk.', 'As far as I am concerned it is clear.');
  v('bevorderen', 'to promote / further', 'bevorder|bevordert|bevorderen', 'bevorderde|bevorderden', 'bevorderd', 'hebben', 'Sport bevordert de gezondheid.', 'Sport promotes health.');
  v('erkennen', 'to acknowledge / recognise', 'erken|erkent|erkennen', 'erkende|erkenden', 'erkend', 'hebben', 'De minister erkende de fout.', 'The minister acknowledged the mistake.');
  v('garanderen', 'to guarantee', 'garandeer|garandeert|garanderen', 'garandeerde|garandeerden', 'gegarandeerd', 'hebben', 'Niemand kan dat garanderen.', 'Nobody can guarantee that.');
  v('hanteren', 'to apply / use', 'hanteer|hanteert|hanteren', 'hanteerde|hanteerden', 'gehanteerd', 'hebben', 'De bank hanteert strenge regels.', 'The bank applies strict rules.');
  v('inschatten', 'to estimate / assess', 'schat in|schat in|schatten in', 'schatte in|schatten in', 'ingeschat', 'hebben', 'Ik had de tijd verkeerd ingeschat.', 'I had misjudged the time.');
  v('leveren', 'to deliver / supply', 'lever|levert|leveren', 'leverde|leverden', 'geleverd', 'hebben', 'Wij leveren binnen twee dagen.', 'We deliver within two days.');
  v('nastreven', 'to pursue', 'streef na|streeft na|streven na', 'streefde na|streefden na', 'nagestreefd', 'hebben', 'De gemeente streeft een autovrij centrum na.', 'The municipality is pursuing a car-free centre.');
  v('omgaan met', 'to deal with / handle', 'ga om met|gaat om met|gaan om met', 'ging om met|gingen om met', 'omgegaan met', 'zijn', 'Hij kan goed met kritiek omgaan.', 'He handles criticism well.');
  v('opleveren', 'to yield / produce', 'lever op|levert op|leveren op', 'leverde op|leverden op', 'opgeleverd', 'hebben', 'De actie leverde tienduizend euro op.', 'The campaign raised ten thousand euros.');
  v('optreden', 'to act / perform / occur', 'treed op|treedt op|treden op', 'trad op|traden op', 'opgetreden', 'zijn', 'De politie trad hard op.', 'The police acted firmly.');
  v('plaatsvinden', 'to take place', 'vind plaats|vindt plaats|vinden plaats', 'vond plaats|vonden plaats', 'plaatsgevonden', 'hebben', 'Het overleg vindt maandag plaats.', 'The meeting takes place on Monday.');
  v('realiseren', 'to realise / bring about', 'realiseer|realiseert|realiseren', 'realiseerde|realiseerden', 'gerealiseerd', 'hebben', 'Het plan is nooit gerealiseerd.', 'The plan was never realised.');
  v('zich realiseren', 'to realise (become aware)', 'realiseer me|realiseert zich|realiseren ons', 'realiseerde me|realiseerden ons', 'gerealiseerd', 'hebben', 'Ik realiseerde me te laat dat de winkel dicht was.', 'I realised too late that the shop was closed.');
  v('schatten', 'to estimate', 'schat|schat|schatten', 'schatte|schatten', 'geschat', 'hebben', 'Ik schat de kosten op duizend euro.', 'I estimate the costs at a thousand euros.');
  v('toepassen', 'to apply', 'pas toe|past toe|passen toe', 'paste toe|pasten toe', 'toegepast', 'hebben', 'De regel wordt streng toegepast.', 'The rule is strictly applied.');
  v('uitbreiden', 'to expand', 'breid uit|breidt uit|breiden uit', 'breidde uit|breidden uit', 'uitgebreid', 'hebben', 'Het bedrijf breidt uit naar België.', 'The company is expanding to Belgium.');
  v('vaststellen', 'to determine / establish', 'stel vast|stelt vast|stellen vast', 'stelde vast|stelden vast', 'vastgesteld', 'hebben', 'De oorzaak is nog niet vastgesteld.', 'The cause has not yet been established.');
  v('verlopen', 'to proceed / expire', 'verloop|verloopt|verlopen', 'verliep|verliepen', 'verlopen', 'zijn', 'Het gesprek verliep goed.', 'The conversation went well.');
  v('vermelden', 'to mention / state', 'vermeld|vermeldt|vermelden', 'vermeldde|vermeldden', 'vermeld', 'hebben', 'Vermeld uw klantnummer.', 'State your customer number.');
  v('vervullen', 'to fulfil', 'vervul|vervult|vervullen', 'vervulde|vervulden', 'vervuld', 'hebben', 'De vacature is vervuld.', 'The vacancy has been filled.');
  v('voorzien in', 'to provide for', 'voorzie in|voorziet in|voorzien in', 'voorzag in|voorzagen in', 'voorzien in', 'hebben', 'De regeling voorziet in een vergoeding.', 'The scheme provides for compensation.');
  v('waarborgen', 'to safeguard', 'waarborg|waarborgt|waarborgen', 'waarborgde|waarborgden', 'gewaarborgd', 'hebben', 'De privacy moet gewaarborgd worden.', 'Privacy must be safeguarded.');
  v('wijzigen', 'to change / amend', 'wijzig|wijzigt|wijzigen', 'wijzigde|wijzigden', 'gewijzigd', 'hebben', 'De openingstijden zijn gewijzigd.', 'The opening hours have changed.');
  v('zich bezighouden met', 'to be engaged in', 'houd me bezig met|houdt zich bezig met|houden ons bezig met', 'hield me bezig met|hielden ons bezig met', 'beziggehouden met', 'hebben', 'Ze houdt zich bezig met onderzoek.', 'She is engaged in research.');
  v('zich verdiepen in', 'to study in depth', 'verdiep me in|verdiept zich in|verdiepen ons in', 'verdiepte me in|verdiepten ons in', 'verdiept in', 'hebben', 'Ik heb me verdiept in de geschiedenis van de stad.', 'I have studied the city’s history in depth.');
  v('zich voordoen', 'to occur / arise', 'doe me voor|doet zich voor|doen zich voor', 'deed zich voor|deden zich voor', 'voorgedaan', 'hebben', 'Er deed zich een probleem voor.', 'A problem arose.');
  v('zich afvragen', 'to wonder', 'vraag me af|vraagt zich af|vragen ons af', 'vroeg me af|vroegen ons af', 'afgevraagd', 'hebben', 'Ik vraag me af of dat klopt.', 'I wonder whether that is right.');

  theme('abstract', 4);
  n('aanleiding', 'de', 'aanleidingen', 'occasion / immediate cause', 'De aanleiding was een klacht.', 'The immediate cause was a complaint.');
  n('achtergrond', 'de', 'achtergronden', 'background', 'Wat is de achtergrond van dit besluit?', 'What is the background to this decision?');
  n('benadering', 'de', 'benaderingen', 'approach', 'Een praktische benadering werkt hier beter.', 'A practical approach works better here.');
  n('bewustzijn', 'het', null, 'awareness', 'Het bewustzijn over privacy groeit.', 'Awareness of privacy is growing.');
  n('doelmatigheid', 'de', null, 'effectiveness / efficiency', 'De doelmatigheid van de maatregel is twijfelachtig.', 'The effectiveness of the measure is doubtful.');
  n('eigenschap', 'de', 'eigenschappen', 'characteristic / property', 'Geduld is een nuttige eigenschap.', 'Patience is a useful characteristic.');
  n('gelegenheid', 'de', 'gelegenheden', 'opportunity / occasion', 'Ik kreeg de gelegenheid om te reageren.', 'I got the opportunity to respond.');
  n('houding', 'de', 'houdingen', 'attitude', 'Zijn houding tegenover verandering is positief.', 'His attitude towards change is positive.');
  n('inzicht', 'het', 'inzichten', 'insight', 'Het onderzoek geeft nieuw inzicht.', 'The research gives new insight.');
  n('maatstaf', 'de', 'maatstaven', 'standard / yardstick', 'Naar Nederlandse maatstaven is dat duur.', 'By Dutch standards that is expensive.');
  n('noodzaak', 'de', null, 'necessity', 'De noodzaak van de maatregel is duidelijk.', 'The necessity of the measure is clear.');
  n('omstandigheid', 'de', 'omstandigheden', 'circumstance', 'Onder deze omstandigheden is dat begrijpelijk.', 'Under these circumstances that is understandable.');
  n('opvatting', 'de', 'opvattingen', 'view / opinion', 'Die opvatting is achterhaald.', 'That view is outdated.');
  n('overweging', 'de', 'overwegingen', 'consideration', 'Een belangrijke overweging is de prijs.', 'An important consideration is the price.');
  n('uitgangspunt', 'het', 'uitgangspunten', 'starting point / premise', 'Het uitgangspunt is dat iedereen meedoet.', 'The premise is that everyone takes part.');
  n('verantwoording', 'de', null, 'accountability / justification', 'De directie moet verantwoording afleggen.', 'The management must be held to account.');
  n('vertrouwen', 'het', null, 'trust / confidence', 'Het vertrouwen in de politiek is laag.', 'Trust in politics is low.');
  n('voorwaarde', 'de', 'voorwaarden', 'condition', 'Onder één voorwaarde: op tijd.', 'On one condition: on time.');
  n('vooruitgang', 'de', null, 'progress', 'Ik zie duidelijke vooruitgang.', 'I see clear progress.');
  n('wezen', 'het', null, 'essence', 'In wezen is het probleem simpel.', 'In essence the problem is simple.');
  n('zeggenschap', 'de', null, 'say / control', 'Huurders hebben weinig zeggenschap.', 'Tenants have little say.');
  n('zorgvuldigheid', 'de', null, 'care / diligence', 'Zorgvuldigheid gaat boven snelheid.', 'Diligence comes before speed.');
  w('aanzienlijk', 'adj', 'considerable', 'Het verschil is aanzienlijk.', 'The difference is considerable.');
  w('betrekkelijk', 'adj', 'relative', 'Alles is betrekkelijk.', 'Everything is relative.');
  w('daadwerkelijk', 'adj', 'actual(ly)', 'Is het plan daadwerkelijk uitgevoerd?', 'Was the plan actually carried out?');
  w('geleidelijk', 'adj', 'gradual(ly)', 'De situatie verbetert geleidelijk.', 'The situation is gradually improving.');
  w('ingrijpend', 'adj', 'far-reaching / drastic', 'Het is een ingrijpende beslissing.', 'It is a far-reaching decision.');
  w('nadrukkelijk', 'adj', 'explicit(ly) / emphatic', 'Ze heeft dat nadrukkelijk ontkend.', 'She has explicitly denied that.');
  w('oorspronkelijk', 'adj', 'original(ly)', 'Oorspronkelijk kom ik uit Leeds.', 'Originally I come from Leeds.');
  w('toenemend', 'adj', 'increasing', 'Er is toenemende kritiek.', 'There is increasing criticism.');
  w('uitgebreid', 'adj', 'extensive', 'Er is uitgebreid onderzoek gedaan.', 'Extensive research has been done.');
  w('vergelijkbaar', 'adj', 'comparable', 'De situatie is vergelijkbaar met die in Denemarken.', 'The situation is comparable to that in Denmark.');
  w('wezenlijk', 'adj', 'essential / fundamental', 'Dat is een wezenlijk verschil.', 'That is a fundamental difference.');
  w('zodanig', 'adj', 'such / in such a way', 'De regels zijn zodanig veranderd dat niemand ze begrijpt.', 'The rules have changed in such a way that nobody understands them.');
})();
